// Masq word/role data — Locations, Biomes, Historical Eras, and Movies catalogs.
// Loaded as a plain script (not a dc-runtime file) so it can sit in its own
// file; exposes everything on window.MASQ_LOCATIONS_DATA for
// "index.html" to read at render time.
// All catalog keys and their role/word lists are sorted alphabetically.
(function () {
  var biomeCatalog = {
    'Alpine Mountains': ['Bighorn Sheep', 'Condor', 'Eagle', 'Ibex', 'Marmot', 'Mountain Goat', 'Snow Leopard', 'Yak'],
    'Antarctic Ice Sheet (Frozen Ocean)': ['Albatross', 'Antarctic Krill', 'Beluga Whale', 'Emperor Penguin', 'Leopard Seal', 'Orca', 'Seal', 'Snow Petrel'],
    'Arctic Tundra': ['Arctic Fox', 'Arctic Hare', 'Lemming', 'Musk Ox', 'Polar Bear', 'Reindeer', 'Snowy Owl', 'Walrus'],
    'Australian Outback': ['Dingo', 'Emu', 'Kangaroo', 'Koala', 'Platypus', 'Tasmanian Devil', 'Thorny Devil', 'Wombat'],
    'Beach': ['Hermit Crab', 'Mussel', 'Pelican', 'Sand Dollar', 'Sandpiper', 'Sea Lion', 'Seagull', 'Starfish'],
    'Cave System': ['Bat', 'Blind Fish', 'Cricket', 'Rat', 'Salamander', 'Silverfish', 'Spider', 'Troglodyte Beetle'],
    'Chaparral (Shrubland)': ['Bobcat', 'California Quail', 'Coyote', 'Gecko', 'Jackrabbit', 'Kangaroo Rat', 'Rattlesnake', 'Roadrunner'],
    'Coral Reef': ['Clownfish', 'Manta Ray', 'Moray Eel', 'Octopus', 'Parrotfish', 'Reef Shark', 'Sea Turtle', 'Seahorse'],
    'Deep Ocean': ['Anglerfish', 'Deep Sea Jellyfish', 'Dumbo Octopus', 'Fangtooth Fish', 'Giant Squid', 'Gulper Eel', 'Sperm Whale', 'Vampire Squid'],
    'Desert': ['Camel', 'Fennec Fox', 'Gila Monster', 'Meerkat', 'Rattlesnake', 'Sand Cat', 'Scorpion', 'Vulture'],
    'Freshwater River': ['Beaver', 'Catfish', 'Heron', 'Hippopotamus', 'Otter', 'Piranha', 'River Dolphin', 'Salmon'],
    'House': ['Cat', 'Dog', 'Goldfish', 'Rabbit', 'Rat', 'Snake', 'Spider', 'Turtle'],
    'Jurassic Park': ['Ankylosaurus', 'Brachiosaurus', 'Pterodactyl', 'Spinosaurus', 'Stegosaurus', 'Triceratops', 'Tyrannosaurus Rex', 'Velociraptor'],
    'Mangrove Forest': ['Bengal Tiger', 'Cuckoo', 'Fiddler Crab', 'Frog', 'Mudskipper', 'Proboscis Monkey', 'Saltwater Crocodile', 'Tarsier'],
    'Prairie': ['Antelope', 'Badger', 'Bison', 'Coyote', 'Ferret', 'Prairie Dog', 'Rattlesnake', 'Red-Tailed Hawk'],
    'Savanna': ['Cheetah', 'Elephant', 'Giraffe', 'Hyena', 'Lion', 'Rhino', 'Wildebeest', 'Zebra'],
    'Swamp': ['Alligator', 'Beaver', 'Bullfrog', 'Heron', 'River Otter', 'Snapping Turtle', 'Toad', 'Water Moccasin'],
    'Taiga (Boreal Forest)': ['Black Bear', 'Gray Owl', 'Gray Wolf', 'Lynx', 'Moose', 'Red Squirrel', 'Snowshoe Hare', 'Wolverine'],
    'Temperate Forest': ['Black Bear', 'Deer', 'Owl', 'Raccoon', 'Red Fox', 'Squirrel', 'Wild Boar', 'Woodpecker'],
    'Tropical Rainforest': ['Anaconda', 'Gorilla', 'Harpy Eagle', 'Howler Monkey', 'Jaguar', 'Poison Dart Frog', 'Sloth', 'Toucan'],
    'Urban Environment (City)': ['Cockroach', 'Opossum', 'Pigeon', 'Raccoon', 'Rat', 'Sparrow', 'Squirrel', 'Stray Cat'],
    'Volcanic Island': ['Fire Salamander', 'Galápagos Iguana', 'Hawaiian Hoary Bat', 'Lava Lizard', 'Peregrine Falcon', 'Vampire Ground Finch', 'Volcanic Mouse', 'Volcano Rabbit'],
  };

  var fakeBiomeRoleCatalog = {
    'Alpine Mountains': ['Antelope', 'Gila Monster', 'Water Moccasin'],
    'Antarctic Ice Sheet (Frozen Ocean)': ['Bullfrog', 'Cheetah', 'Spider'],
    'Arctic Tundra': ['Hermit Crab', 'Jaguar', 'Toucan'],
    'Australian Outback': ['Moose', 'Piranha', 'Reindeer'],
    'Beach': ['Bat', 'Prairie Dog', 'Snow Leopard'],
    'Cave System': ['Heron', 'Koala', 'Vampire Squid'],
    'Chaparral (Shrubland)': ['Catfish', 'Moray Eel', 'Zebra'],
    'Coral Reef': ['Marmot', 'Snow Petrel', 'Volcanic Mouse'],
    'Deep Ocean': ['Bullfrog', 'Hippopotamus', 'Otter'],
    'Desert': ['Bat', 'Beaver', 'Kangaroo Rat'],
    'Freshwater River': ['Condor', 'Emu', 'Mountain Goat'],
    'House': ['Anaconda', 'Meerkat', 'Pelican'],
    'Jurassic Park': ['Camel', 'Koala', 'Octopus'],
    'Mangrove Forest': ['Beaver', 'Clownfish', 'Squirrel'],
    'Prairie': ['Antarctic Krill', 'Hawaiian Hoary Bat', 'Rat'],
    'Savanna': ['Fire Salamander', 'Harpy Eagle', 'Leopard Seal'],
    'Swamp': ['Poison Dart Frog', 'Troglodyte Beetle', 'Walrus'],
    'Taiga (Boreal Forest)': ['Red-Tailed Hawk', 'Stray Cat', 'Water Moccasin'],
    'Temperate Forest': ['Beaver', 'Bison', 'Troglodyte Beetle'],
    'Tropical Rainforest': ['Cockroach', 'Reindeer', 'Troglodyte Beetle'],
    'Urban Environment (City)': ['Beaver', 'Deep Sea Jellyfish', 'Manta Ray'],
    'Volcanic Island': ['Harpy Eagle', 'Sparrow', 'Zebra'],
  };

  var locationCatalog = {
    'Airplane': ['Air Marshal', 'Bartender', 'Crying Baby', 'Flight Attendant', 'Flight Engineer', 'Passenger', 'Pilot', 'Stowaway'],
    'Airport': ['Crew Member', 'Customs Officer', 'Gate Agent', 'Passenger', 'Pilot', 'Ramp Agent', 'Security Officer', 'Tourist'],
    'Bank': ['Account Holder', 'Armored Car Driver', 'Auditor', 'Branch Manager', 'Loan Officer', 'Robber', 'Security Guard', 'Teller'],
    'Beach': ['Ice Cream Vendor', 'Lifeguard', 'Photographer', 'Sandcastle Builder', 'Sunbather', 'Surfer', 'Tourist', 'Volleyball Player'],
    'Campground': ['Bear', 'Biker', 'Camper', 'Campfire Cook', 'Eagle Scout', 'Hiker', 'Park Ranger', 'Wildlife Photographer'],
    'Casino': ['Bartender', 'Bouncer', 'Cardsharp', 'Dealer', 'Drunkard', 'Gambler', 'Head of Security', 'Pit Boss'],
    'Circus Tent': ['Acrobat', 'Animal Tamer', 'Circus-Goer', 'Clown', 'Juggler', 'Knife Thrower', 'Magician', 'Ringmaster'],
    'Convenience Store': ['Alcoholic', 'Cashier', 'Delivery Driver', 'Food Roller Operator', 'Late Night Customer', 'Manager', 'Regular', 'Shoplifter'],
    'Corporate Party': ['Accountant', 'Administrative Assistant', 'CEO', 'Courier', 'Emcee', 'Intern', 'Manager', 'Party Crasher'],
    'Cruise Ship': ['Attendant', 'Bartender', 'Captain', 'Cook', 'Musician', 'Passenger', 'Radio Operator', 'Stowaway'],
    'Crusader Army': ['Archer', 'Bishop', 'Captive', 'Knight', 'Monk', 'Saracen', 'Servant', 'Squire'],
    'Day Spa': ['Beautician', 'Customer', 'Dermatologist', 'Makeup Specialist', 'Masseur', 'Nail Specialist', 'Receptionist', 'Stylist'],
    'Elementary School': ['Janitor', 'Librarian', 'Lunch Lady', 'Nurse', 'Principal', 'Student', 'Substitute Teacher', 'Teacher'],
    'Embassy': ['Ambassador', 'Bureaucrat', 'Diplomat', 'Interpreter', 'Refugee', 'Secretary', 'Security Guard', 'Tourist'],
    'Fast Food Restaurant': ['Cashier', 'Customer', 'Delivery Driver', 'Disgruntled Teenager Working Their First Job', 'Drive-Thru Worker', 'Fry Cook', 'Health Inspector', 'Manager'],
    'Fire Station': ['Arson Investigator', 'Captain', 'Dispatcher', 'Firefighter', 'Paramedic', 'Rescue Dog', 'Rookie', 'Station Cook'],
    'Gym': ['Athlete', 'Front Desk Worker', "New Year's Resolution Member", 'Personal Trainer', 'Runner', 'Swimmer', 'Weightlifter', 'Yoga Instructor'],
    'Hospital': ['EMT', 'Janitor', 'Nurse', 'Paramedic', 'Patient', 'Receptionist', 'Surgeon', 'Therapist'],
    'Hotel': ['Bellhop', 'Concierge', 'Front Desk Clerk', 'Guest', 'Housekeeper', 'Manager', 'Room Service Worker', 'Valet Parking Attendant'],
    'Military Base': ['Colonel', 'Deserter', 'Drill Instructor', 'Drone Operator', 'Medic', 'Non-Commissioned Officer', 'Private', 'Sentry'],
    'Movie Studio': ['Actor', 'Cameraman', 'Costume Designer', 'Director', 'Extra', 'Producer', 'Sound Engineer', 'Stuntman'],
    'Movie Theater': ['Concession Worker', 'Couple', 'Film Critic', 'Manager', 'Projectionist', 'Teenager', 'Ticket Seller', 'Usher'],
    'Night Club': ['Bartender', 'Bottle Service Waitress', 'Bouncer', 'Dancer', 'DJ', 'Model', 'Pick-Up Artist', 'Regular'],
    'Pirate Ship': ['Cabin Boy', 'Cook', 'First Mate', 'Gunner', 'Parrot', 'Seaman', 'Shackled Prisoner', 'Swashbuckling Captain'],
    'Polar Station': ['Biologist', 'Expedition Leader', 'Geoscientist', 'Hydrologist', 'Medic', 'Meteorologist', 'Photographer', 'Radio Operator'],
    'Police Station': ['Attorney', 'Cop', 'Detective', 'Forensic Scientist', 'Journalist', 'Lieutenant', 'Patrol Officer', 'Suspect'],
    'Restaurant': ['Annoying Karen', 'Dishwasher', 'Food Critic', 'Head Chef', 'Host', 'Manager', 'Sommelier', 'Waiter'],
    'Service Station': ['Biker', 'Car Washer', 'Driver', 'Electrical Technician', 'Manager', 'Service Receptionist', 'Tire Technician', 'Tow Truck Driver'],
    'Space Station': ['Aerospace Engineer', 'Alien', 'Astronaut', 'Doctor', 'Mission Commander', 'Pilot', 'Research Engineer', 'Wealthy Tourist'],
    'Sports Stadium': ['Coach', 'Commentator', 'Concession Worker', 'Mascot', 'Player', 'Referee', 'Security Guard', 'Superfan'],
    'Submarine': ['Commander', 'Cook', 'Electrical Officer', 'Navigator', 'New Recruit', 'Radio Operator', 'Sailor', 'Sonar Operator'],
    'Supermarket': ['Butcher', 'Cart Wrangler', 'Cashier', 'Custodian', 'Delivery Man', 'Manager', 'Shopper', 'Stock Worker'],
    'Theatre': ['Actor', 'Audience Member', 'Coatroom Attendant', 'Director', 'Prompter', 'Stage Hand', 'Understudy', 'Usher'],
    'Theme Park / Amusement Park': ['Character Performer', 'Clown', 'Food Vendor', 'Kid', 'Merchandise Vendor', 'Parent', 'Ride Operator', 'Visitor'],
    'Train': ['Backpacker', 'Conductor', 'Dining Car Cook', 'Passenger', 'Passenger Car Attendant', 'Stoker', 'Ticket Taker', 'Vendor'],
    'University': ['Campus Security', 'Dean', 'Frat Member', 'Freshman', 'Graduate Student', 'Professor', 'Resident Advisor', 'Tour Guide'],
    'Zoo': ['Caretaker', 'General Manager', 'Guide', 'Janitor', 'Vendor', 'Veterinarian', 'Visitor', 'Zookeeper'],
  };

  var fakeLocationRoleCatalog = {
    'Airplane': ['Lifeguard', 'Nail Specialist', 'Security Officer'],
    'Airport': ['Bellhop', 'Coach', 'Shackled Prisoner'],
    'Bank': ['Dancer', 'Film Critic', 'Pick-Up Artist'],
    'Beach': ['Astronaut', 'Housekeeper', 'Librarian'],
    'Campground': ['Concierge', 'Security Guard', 'Usher'],
    'Casino': ['Dancer', 'Drive-Thru Worker', 'Manager'],
    'Circus Tent': ['Actor', 'Biologist', 'Geoscientist'],
    'Convenience Store': ['Backpacker', 'Campus Security', 'Dean'],
    'Corporate Party': ['Cameraman', 'Campus Security', 'Flight Attendant'],
    'Cruise Ship': ['Administrative Assistant', 'Usher', 'Zookeeper'],
    'Crusader Army': ['Cabin Boy', 'Dispatcher', 'Teller'],
    'Day Spa': ['Detective', 'Visitor', 'Zookeeper'],
    'Elementary School': ['Auditor', 'Cardsharp', 'Cashier'],
    'Embassy': ['Ice Cream Vendor', 'Masseur', 'Wildlife Photographer'],
    'Fast Food Restaurant': ['Interpreter', 'Journalist', 'Magician'],
    'Fire Station': ['Bartender', 'Coach', 'Radio Operator'],
    'Gym': ['Archer', 'Auditor', 'Cardsharp'],
    'Hospital': ['Archer', 'Delivery Man', 'Stage Hand'],
    'Hotel': ['CEO', "New Year's Resolution Member", 'Sunbather'],
    'Military Base': ['Audience Member', 'Musician', 'Zookeeper'],
    'Movie Studio': ['Astronaut', 'Attendant', 'Receptionist'],
    'Movie Theater': ['Coatroom Attendant', 'Cop', 'Teller'],
    'Night Club': ['Cashier', 'Sommelier', 'Vendor'],
    'Pirate Ship': ['Campus Security', 'Dancer', 'Personal Trainer'],
    'Polar Station': ['Prompter', 'Waiter', 'Wealthy Tourist'],
    'Police Station': ['Audience Member', 'Non-Commissioned Officer', 'Shoplifter'],
    'Restaurant': ['First Mate', 'Pick-Up Artist', 'Usher'],
    'Service Station': ['Bartender', 'Ringmaster', 'Weightlifter'],
    'Space Station': ['Disgruntled Teenager Working Their First Job', 'Ice Cream Vendor', 'Janitor'],
    'Sports Stadium': ['Acrobat', 'Ambassador', 'Parrot'],
    'Submarine': ['Butcher', 'Flight Engineer', 'Tourist'],
    'Supermarket': ['Runner', 'Service Receptionist', 'Usher'],
    'Theatre': ['Auditor', 'Shopper', 'Yoga Instructor'],
    'Theme Park / Amusement Park': ['Campus Security', 'Captive', 'Sommelier'],
    'Train': ['Bottle Service Waitress', 'Circus-Goer', 'Guest'],
    'University': ['Bartender', 'Pilot', 'Tourist'],
    'Zoo': ['Delivery Driver', 'Front Desk Clerk', 'Pick-Up Artist'],
  };

  var historicalErasCatalog = {
    'Age of Exploration': ['Caravel Captain', 'Conquistador', 'Indigenous Interpreter', 'Missionary Priest', 'New World Cartographer', 'Scurvy-Stricken Sailor', 'Ship\'s Navigator', 'Spice Trade Merchant'],
    'American Revolution': ['British Redcoat', 'Colonial Town Crier', 'Continental Army Surgeon', 'Founding Father', 'Loyalist Tory', 'Minuteman Militiaman', 'Pamphlet Printer', 'Tea Party Raider'],
    'Ancient China (Dynastic Era)': ['Confucian Scholar-Official', 'Court Eunuch', 'Dynastic Emperor', 'Great Wall Laborer', 'Gunpowder Alchemist', 'Imperial Calligrapher', 'Silk Road Merchant', 'Terracotta Army Sculptor'],
    'Ancient Egypt': ['Hieroglyph Scribe', 'Mummification Embalmer', 'Nile Flood Surveyor', 'Pharaoh', 'Priest of Ra', 'Pyramid Stonecutter', 'Royal Vizier', 'Tomb Robber'],
    'Ancient Greece': ['Athenian Philosopher', 'Homeric Bard', 'Marble Temple Sculptor', 'Olympic Wrestler', 'Oracle of Delphi', 'Spartan Hoplite', 'Tragedy Playwright', 'Trireme Rower'],
    'Ancient Rome': ['Aqueduct Engineer', 'Chariot Racer', 'Colosseum Gladiator', 'Forum Senator', 'Legion Centurion', 'Praetorian Guard', 'Toga-Clad Emperor', 'Vestal Virgin'],
    'Aztec Empire': ['Chinampa Garden Farmer', 'Eagle Warrior', 'Featherwork Artisan', 'Jaguar Warrior', 'Pochteca Long-Distance Trader', 'Sacrificial Captive', 'Sacrificial Temple Priest', 'Tlatoani Ruler'],
    'Cold War Era': ['Berlin Wall Guard', 'CIA Agent', 'Duck-and-Cover Schoolteacher', 'Fallout Shelter Builder', 'Iron Curtain Defector', 'KGB Spy', 'Missile Silo Officer', 'Propaganda Radio Broadcaster'],
    'Feudal Japan': ['Daimyo Lord', 'Geisha', 'Katana Swordsmith', 'Masterless Ronin', 'Ninja Assassin', 'Samurai', 'Shogun', 'Zen Temple Monk'],
    'Great Depression': ['Boxcar-Hopping Hobo', 'Breadline Regular', 'Dance Marathon Contestant', 'Dust Bowl Farmer', 'Hooverville Resident', 'Soup Kitchen Volunteer', 'Wiped-Out Stockbroker', 'WPA Road Crew Worker'],
    'Industrial Revolution': ['Chimney Sweep Boy', 'Coal Miner', 'Factory Foreman', 'Luddite Machine-Breaker', 'Mill Owner', 'Steam Engine Mechanic', 'Steam Locomotive Engineer', 'Textile Mill Child Laborer'],
    'Medieval Europe': ['Armored Knight', 'Cathedral Stonemason', 'Court Jester', 'Crusader', 'Feudal King', 'Manor Serf', 'Manuscript-Illuminating Monk', 'Plague Doctor'],
    'Prehistoric/Stone Age': ['Bone Flute Carver', 'Cave Painter', 'Clan Elder', 'Fire Keeper', 'Flint Toolmaker', 'Mammoth Hunter', 'Root and Berry Forager', 'Tribal Shaman'],
    'Renaissance': ['Flying Machine Inventor', 'Forbidden Anatomist', 'Fresco Painter', 'Heretical Astronomer', 'Humanist Scholar', 'Medici Banker', 'Patron of the Arts', 'Printing Press Operator'],
    'Viking Age': ['Berserker', 'Jarl Chieftain', 'Longship Raider', 'Longship Shipwright', 'Rune Carver', 'Shield Maiden', 'Skald Storyteller', 'Völva Seer'],
    'Wild West': ['Bounty Hunter', 'Cattle Drive Cowboy', 'Frontier Sheriff', 'Gold Rush Prospector', 'Pony Express Rider', 'Saloon Keeper', 'Stagecoach Driver', 'Train-Robbing Outlaw'],
    'World War II': ['Air Raid Warden', 'Bomber Crew Gunner', 'D-Day Paratrooper', 'Enigma Codebreaker', 'French Resistance Fighter', 'Radar Operator', 'Riveting Factory Worker', 'Spitfire Pilot'],
  };

  var fakeHistoricalErasRoleCatalog = {
    'Age of Exploration': ['Enigma Codebreaker', 'Fresco Painter', 'Pharaoh'],
    'American Revolution': ['Cattle Drive Cowboy', 'Great Wall Laborer', 'Oracle of Delphi'],
    'Ancient China (Dynastic Era)': ['Gold Rush Prospector', 'Hieroglyph Scribe', 'Zen Temple Monk'],
    'Ancient Egypt': ['Crusader', 'Terracotta Army Sculptor', 'Wiped-Out Stockbroker'],
    'Ancient Greece': ['Longship Raider', 'Radar Operator', 'Vestal Virgin'],
    'Ancient Rome': ['Katana Swordsmith', 'KGB Spy', 'Spartan Hoplite'],
    'Aztec Empire': ['Bounty Hunter', 'Conquistador', 'Priest of Ra'],
    'Cold War Era': ['Court Jester', 'Enigma Codebreaker', 'Spitfire Pilot'],
    'Feudal Japan': ['Armored Knight', 'Confucian Scholar-Official', 'Riveting Factory Worker'],
    'Great Depression': ['Coal Miner', 'Riveting Factory Worker', 'Vestal Virgin'],
    'Industrial Revolution': ['Gold Rush Prospector', 'Hooverville Resident', 'Ninja Assassin'],
    'Medieval Europe': ['Jaguar Warrior', 'Samurai', 'Steam Locomotive Engineer'],
    'Prehistoric/Stone Age': ['Pyramid Stonecutter', 'Völva Seer', 'Wiped-Out Stockbroker'],
    'Renaissance': ['Cathedral Stonemason', 'Cave Painter', 'New World Cartographer'],
    'Viking Age': ['Crusader', 'Legion Centurion', 'Pony Express Rider'],
    'Wild West': ['Boxcar-Hopping Hobo', 'Court Eunuch', 'Steam Locomotive Engineer'],
    'World War II': ['Berlin Wall Guard', 'Court Jester', 'Dust Bowl Farmer'],
  };

  var movieCatalog = {
    'Action': ['Die Hard', 'Fast and Furious', 'John Wick', 'Mad Max', 'Mission Impossible', 'Speed', 'Terminator', 'The Avengers'],
    'Animated': ['Coco', 'Finding Nemo', 'Frozen', 'Shrek', 'Spider-Man: Into the Spider-Verse', 'The Lion King', 'Toy Story', 'Up'],
    'Comedy': ['Anchorman', 'Bridesmaids', 'Dumb and Dumber', 'Ghostbusters', 'Home Alone', 'Mean Girls', 'Superbad', 'The Hangover'],
    'Crime': ['Casino', 'Goodfellas', 'Heat', 'Pulp Fiction', 'Scarface', 'The Dark Knight', 'The Departed', 'The Godfather'],
    'Fantasy': ['Aladdin', 'Harry Potter', 'Pirates of the Caribbean', 'Shrek', 'The Chronicles of Narnia', 'The Lord of the Rings', 'The Princess Bride', 'Willow'],
    'Horror': ['A Nightmare on Elm Street', 'Get Out', 'Halloween', 'It', 'Scream', 'The Conjuring', 'The Exorcist', 'The Shining'],
    'Musical': ['Chicago', 'Grease', 'Hairspray', 'La La Land', 'Mamma Mia', 'Moulin Rouge', 'The Greatest Showman', 'West Side Story'],
    'Romance': ['(500) Days of Summer', 'Crazy Rich Asians', 'La La Land', 'Notting Hill', 'The Notebook', 'The Princess Bride', 'Titanic', 'Twilight'],
    'Sci-Fi': ['Avatar', 'Back to the Future', 'E.T.', 'Inception', 'Interstellar', 'Jurassic Park', 'Star Wars', 'The Matrix'],
    'Thriller': ['Fight Club', 'Gone Girl', 'Inception', 'Jaws', 'Parasite', 'Se7en', 'Shutter Island', 'The Silence of the Lambs'],
    'War': ['1917', 'American Sniper', 'Apocalypse Now', 'Black Hawk Down', 'Dunkirk', 'Hacksaw Ridge', 'Pearl Harbor', 'Saving Private Ryan'],
    'Western': ['3:10 to Yuma', 'Butch Cassidy and the Sundance Kid', 'Django Unchained', 'No Country for Old Men', 'The Good, the Bad and the Ugly', 'Tombstone', 'True Grit', 'Unforgiven'],
  };

  var fakeMovieRoleCatalog = {
    'Action': ['Frozen', 'The Exorcist', 'The Notebook'],
    'Animated': ['Mad Max', 'The Conjuring', 'Titanic'],
    'Comedy': ['Jaws', 'John Wick', 'Titanic'],
    'Crime': ['Bridesmaids', 'Interstellar', 'Speed'],
    'Fantasy': ['Dunkirk', 'Scarface', 'Se7en'],
    'Horror': ['Die Hard', 'Grease', 'Toy Story'],
    'Musical': ['Coco', 'Terminator', 'The Shining'],
    'Romance': ['Die Hard', 'Goodfellas', 'Halloween'],
    'Sci-Fi': ['Grease', 'Home Alone', 'The Godfather'],
    'Thriller': ['Aladdin', 'Ghostbusters', 'Pearl Harbor'],
    'War': ['It', 'Notting Hill', 'The Hangover'],
    'Western': ['Avatar', 'Fight Club', 'Mean Girls'],
  };

  var wordOnlyCatalog = {
    'Animals': [
      'Alpaca', 'Ant', 'Antelope', 'Baboon', 'Bat', 'Bear', 'Beaver', 'Bee', 'Bison', 'Buffalo',
      'Butterfly', 'Camel', 'Chameleon', 'Cheetah', 'Chicken', 'Chimpanzee', 'Cow', 'Crab', 'Crocodile', 'Deer',
      'Dolphin', 'Donkey', 'Duck', 'Eagle', 'Elephant', 'Elk', 'Falcon', 'Flamingo', 'Fox', 'Frog',
      'Gazelle', 'Giraffe', 'Goat', 'Gorilla', 'Guinea Pig', 'Hamster', 'Hawk', 'Hedgehog', 'Hippo', 'Horse',
      'Hyena', 'Jaguar', 'Jellyfish', 'Kangaroo', 'Koala', 'Lemur', 'Leopard', 'Lion', 'Lizard', 'Llama',
      'Lobster', 'Meerkat', 'Moose', 'Mouse', 'Octopus', 'Orangutan', 'Orca', 'Otter', 'Owl', 'Panda',
      'Panther', 'Parrot', 'Peacock', 'Penguin', 'Pig', 'Platypus', 'Polar Bear', 'Rabbit', 'Raccoon', 'Rat',
      'Red Panda', 'Rhino', 'Scorpion', 'Seal', 'Shark', 'Sheep', 'Shrimp', 'Skunk', 'Sloth', 'Snail',
      'Snake', 'Spider', 'Squirrel', 'Starfish', 'Stingray', 'Swan', 'Tiger', 'Toad', 'Tortoise', 'Toucan',
      'Turkey', 'Turtle', 'Vulture', 'Walrus', 'Warthog', 'Whale', 'Wildebeest', 'Wolf', 'Wombat', 'Zebra'],
    'Food': [
      'Apple', 'Avocado', 'Bacon', 'Bagel', 'Baked Potato', 'Banana', 'Bao', 'Barbecue', 'Biscuit', 'BLT',
      'Brownie', 'Burger', 'Burrito', 'Cereal', 'Cheese', 'Cheesecake', 'Chicken Wings', 'Chocolate', 'Chocolate Cake', 'Club Sandwich',
      'Coconut', 'Coffee', 'Coleslaw', 'Cookies', 'Corn on the Cob', 'Croissant', 'Cupcake', 'Curry', 'Deviled Eggs', 'Dim Sum',
      'Donut', 'Dumplings', 'Enchiladas', 'Falafel', 'French Fries', 'French Toast', 'Fried Chicken', 'Fried Rice', 'Gnocchi', 'Goulash',
      'Grapes', 'Grilled Cheese', 'Guacamole', 'Gyro', 'Honey', 'Hot Dog', 'Hummus', 'Ice Cream', 'Jelly', 'Kebab',
      'Lasagna', 'Lemonade', 'Macaroni and Cheese', 'Mango', 'Maple Syrup', 'Mashed Potatoes', 'Meatballs', 'Meatloaf', 'Milkshake', 'Muffin',
      'Nachos', 'Oatmeal', 'Omelette', 'Orange', 'Pad Thai', 'Paella', 'Pancakes', 'Pasta', 'Peanut Butter', 'Pho',
      'Pie', 'Pierogi', 'Pineapple', 'Pizza', 'Popcorn', 'Potato Salad', 'Pretzel', 'Quesadilla', 'Ramen', 'Ravioli',
      'Ribs', 'Risotto', 'Salad', 'Salsa', 'Sandwich', 'Scrambled Eggs', 'Shawarma', 'Smoothie', 'Soup', 'Spaghetti',
      'Spring Rolls', 'Steak', 'Strawberry', 'Sushi', 'Sweet Potato', 'Tacos', 'Tiramisu', 'Toast', 'Waffles', 'Watermelon'],
    'Movies': [
      '10 Things I Hate About You', '12 Angry Men', '1917', '2001: A Space Odyssey', 'About Time', 'Aladdin', 'Alien', 'Amélie', 'American Beauty', 'American Psycho',
      'Anatomy of a Fall', 'Anyone But You', 'Avatar', 'Baby Driver', 'Back to the Future', 'Barbie', 'Batman', 'Beautiful Boy', 'Beauty and the Beast', 'Before Sunrise',
      'Black Panther', 'Black Swan', 'Blade Runner', 'Bottoms', 'Bourne', 'Braveheart', 'Brokeback Mountain', 'Call Me by Your Name', 'Casino', 'Cast Away',
      'Catch Me If You Can', 'Cinderella', 'Clueless', 'Coco', 'Conclave', 'Coraline', 'Dead Poets Society', 'Deadpool', 'Despicable Me', 'Die Hard',
      'Django Unchained', 'Don\'t Look Up', 'Donnie Darko', 'Drive', 'E.T.', 'Edward Scissorhands', 'Eternal Sunshine of the Spotless Mind', 'Eyes Wide Shut', 'Fantastic Four', 'Fantastic Mr. Fox',
      'Fast and Furious', 'Fight Club', 'Finding Nemo', 'Forrest Gump', 'Frozen', 'Get Out', 'Ghostbusters', 'Girl, Interrupted', 'Gladiator', 'Glass Onion',
      'Gone Girl', 'Good Will Hunting', 'Goodfellas', 'Gravity', 'Guardians of the Galaxy', 'Hamnet', 'Harry Potter', 'Heat', 'Her', 'Home Alone',
      'How to Train Your Dragon', 'Howl\'s Moving Castle', 'Inception', 'Indiana Jones', 'Inglourious Basterds', 'Inside Out', 'Interstellar', 'Iron Man', 'James Bond', 'Jaws',
      'Jennifer\'s Body', 'John Wick', 'Jojo Rabbit', 'Joker', 'Jumanji', 'Jurassic Park', 'Kill Bill', 'Knives Out', 'KPop Demon Hunters', 'Kung Fu Panda',
      'La La Land', 'Lady Bird', 'Legally Blonde', 'Little Miss Sunshine', 'Little Women', 'Logan', 'Love Actually', 'Mad Max', 'Mamma Mia', 'Memento',
      'Men in Black', 'Mickey 17', 'Midsommar', 'Mission Impossible', 'Moana', 'Monsters, Inc.', 'Moonlight', 'Mulholland Drive', 'My Neighbor Totoro', 'National Treasure',
      'Nightcrawler', 'Nope', 'Nosferatu', 'Ocean\'s Eleven', 'Oldboy', 'Once Upon a Time in Hollywood', 'Oppenheimer', 'Parasite', 'Perfect Blue', 'Pirates of the Caribbean',
      'Poor Things', 'Portrait of a Lady on Fire', 'Pride and Prejudice', 'Princess Mononoke', 'Pulp Fiction', 'Puss in Boots', 'Ratatouille', 'Requiem for a Dream', 'Rocky', 'Saltburn',
      'Saving Private Ryan', 'Saw', 'Scarface', 'Schindler\'s List', 'Scott Pilgrim vs. the World', 'Scream', 'Se7en', 'Shrek', 'Shutter Island', 'Signs',
      'Sinners', 'Sleeping Beauty', 'Snow White', 'Soul', 'Speed', 'Spider-Man', 'Spirited Away', 'Star Trek', 'Star Wars', 'Superbad',
      'Taxi Driver', 'Terminator', 'The Avengers', 'The Breakfast Club', 'The Dark Knight', 'The Departed', 'The Devil Wears Prada', 'The Fabelmans', 'The Godfather', 'The Grand Budapest Hotel',
      'The Green Mile', 'The Hobbit', 'The Holdovers', 'The Hunger Games', 'The Incredibles', 'The Lighthouse', 'The Lion King', 'The Little Mermaid', 'The Lord of the Rings', 'The Martian',
      'The Matrix', 'The Menu', 'The Neverending Story', 'The Nightmare Before Christmas', 'The Notebook', 'The Perks of Being a Wallflower', 'The Prestige', 'The Princess Bride', 'The Shawshank Redemption', 'The Shining',
      'The Silence of the Lambs', 'The Sixth Sense', 'The Social Network', 'The Substance', 'The Truman Show', 'The Virgin Suicides', 'The Wolf of Wall Street', 'Thor: Ragnarok', 'Thunderbolts', 'Titanic',
      'Toy Story', 'Transformers', 'Twilight', 'Uncut Gems', 'Up', 'Us', 'WALL-E', 'Whiplash', 'Wicked', 'Willow',
      'Wonder Woman', 'X-Men', 'Zodiac', 'Zootopia'],
    'Objects': [
      'Backpack', 'Bag', 'Basket', 'Battery', 'Bed', 'Belt', 'Binoculars', 'Blanket', 'Book', 'Bookshelf',
      'Bottle', 'Bowl', 'Box', 'Bracelet', 'Broom', 'Bucket', 'Calculator', 'Camera', 'Candle', 'Chain',
      'Chair', 'Charger', 'Clock', 'Comb', 'Compass', 'Computer', 'Couch', 'Cup', 'Curtain', 'Desk',
      'Door', 'Envelope', 'Eraser', 'Fan', 'Flashlight', 'Fork', 'Globe', 'Gloves', 'Guitar', 'Hammer',
      'Hat', 'Headphones', 'Jar', 'Key', 'Keyboard', 'Knife', 'Ladder', 'Lamp', 'Laptop', 'Lock',
      'Map', 'Microphone', 'Mirror', 'Mouse', 'Mug', 'Nail', 'Necklace', 'Newspaper', 'Notebook', 'Painting',
      'Passport', 'Pen', 'Pencil', 'Phone', 'Picture Frame', 'Pillow', 'Plate', 'Refrigerator', 'Remote Control', 'Ring',
      'Rope', 'Rug', 'Ruler', 'Scarf', 'Scissors', 'Screw', 'Screwdriver', 'Shoes', 'Soap', 'Socks',
      'Speaker', 'Sponge', 'Spoon', 'Stamp', 'Stove', 'Suitcase', 'Sunglasses', 'Table', 'Telescope', 'Television',
      'Toaster', 'Toothbrush', 'Towel', 'Umbrella', 'Vacuum', 'Vase', 'Wallet', 'Watch', 'Window', 'Wrench'],
  };

  window.MASQ_LOCATIONS_DATA = {
    'biomeCatalog': biomeCatalog,
    'locationCatalog': locationCatalog,
    'fakeLocationRoleCatalog': fakeLocationRoleCatalog,
    'fakeBiomeRoleCatalog': fakeBiomeRoleCatalog,
    'historicalErasCatalog': historicalErasCatalog,
    'fakeHistoricalErasRoleCatalog': fakeHistoricalErasRoleCatalog,
    'movieCatalog': movieCatalog,
    'fakeMovieRoleCatalog': fakeMovieRoleCatalog,
    'wordOnlyCatalog': wordOnlyCatalog,
  };
})();