// GENERATED by tools/fetch-animals.js — do not edit by hand.
// Maps a Biomes-catalog animal to its Wikipedia lead photo, as a finished
// URL — unlike the album art, there is no size to append. Each trailing
// comment is the article the photo came from.
(function () {
  window.MASQ_ANIMALS = {
    "Albatross": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Short_tailed_Albatross1.jpg/500px-Short_tailed_Albatross1.jpg",  // Albatross
    "Alligator": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Chinese%2Bamerican_alligators.png/500px-Chinese%2Bamerican_alligators.png",  // Alligator
    "Anaconda": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Eunectes_murinus2.jpg/500px-Eunectes_murinus2.jpg",  // Anaconda
    "Anglerfish": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Humpback_anglerfish.png/500px-Humpback_anglerfish.png",  // Humpback anglerfish
    "Ankylosaurus": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Ankylosaur_head_-_cast_-_Custer_County_Montana_-_Museum_of_the_Rockies_-_2013-07-08.jpg/500px-Ankylosaur_head_-_cast_-_Custer_County_Montana_-_Museum_of_the_Rockies_-_2013-07-08.jpg",  // Ankylosaurus
    "Antarctic Krill": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Antarctic_krill_%28Euphausia_superba%29.jpg/500px-Antarctic_krill_%28Euphausia_superba%29.jpg",  // Antarctic krill
    "Antelope": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Blackbuck_male_female.jpg/500px-Blackbuck_male_female.jpg",  // Antelope
    "Arctic Fox": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Vulpes_lagopus_in_Iceland_%28cropped_3%29.jpg/500px-Vulpes_lagopus_in_Iceland_%28cropped_3%29.jpg",  // Arctic fox
    "Arctic Hare": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Arctic_Hare_1.jpg/500px-Arctic_Hare_1.jpg",  // Arctic hare
    "Badger": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/European_badger_%28Meles_meles_taxus%29_Drenthe.jpg/500px-European_badger_%28Meles_meles_taxus%29_Drenthe.jpg",  // Badger
    "Bat": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Big-eared-townsend-fledermaus.jpg/500px-Big-eared-townsend-fledermaus.jpg",  // Bat
    "Beaver": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/American_Beaver.jpg/500px-American_Beaver.jpg",  // Beaver
    "Beluga Whale": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Oceanogr%C3%A0fic_29102004.jpg/500px-Oceanogr%C3%A0fic_29102004.jpg",  // Beluga whale
    "Bengal Tiger": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Bengal_tiger_in_Sanjay_Dubri_Tiger_Reserve_December_2024_by_Tisha_Mukherjee_11.jpg/500px-Bengal_tiger_in_Sanjay_Dubri_Tiger_Reserve_December_2024_by_Tisha_Mukherjee_11.jpg",  // Bengal tiger
    "Bighorn Sheep": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/New_Mexico_Bighorn_Sheep.JPG/500px-New_Mexico_Bighorn_Sheep.JPG",  // Bighorn sheep
    "Bison": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/American_bison_k5680-1.jpg/500px-American_bison_k5680-1.jpg",  // Bison
    "Black Bear": "https://upload.wikimedia.org/wikipedia/commons/0/08/01_Schwarzb%C3%A4r.jpg",  // American black bear
    "Blind Fish": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Mexican_Tetra_%28Astyanax_mexicanus%29_%282687270083%29.jpg/500px-Mexican_Tetra_%28Astyanax_mexicanus%29_%282687270083%29.jpg",  // Mexican tetra
    "Bobcat": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Bobcat_at_Columbus_Zoo_Boo.jpg/500px-Bobcat_at_Columbus_Zoo_Boo.jpg",  // Bobcat
    "Brachiosaurus": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Brachiosaurus_mount.jpg/500px-Brachiosaurus_mount.jpg",  // Brachiosaurus
    "Bullfrog": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/North-American-bullfrog1.jpg/500px-North-American-bullfrog1.jpg",  // Bullfrog
    "California Quail": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/California_quail_%28Callipepla_californica%29_male_Tricao.jpg/500px-California_quail_%28Callipepla_californica%29_male_Tricao.jpg",  // California quail
    "Camel": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/07._Camel_Profile%2C_near_Silverton%2C_NSW%2C_07.07.2007.jpg/500px-07._Camel_Profile%2C_near_Silverton%2C_NSW%2C_07.07.2007.jpg",  // Camel
    "Cat": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Cat_August_2010-4.jpg/500px-Cat_August_2010-4.jpg",  // Cat
    "Catfish": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Silurus_glanis_02.jpg/500px-Silurus_glanis_02.jpg",  // Wels catfish
    "Cheetah": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Male_cheetah_facing_left_in_South_Africa.jpg/500px-Male_cheetah_facing_left_in_South_Africa.jpg",  // Cheetah
    "Clownfish": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Amphiprion_ocellaris_%28Clown_anemonefish%29_by_Nick_Hobgood.jpg/500px-Amphiprion_ocellaris_%28Clown_anemonefish%29_by_Nick_Hobgood.jpg",  // Clownfish
    "Cockroach": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Snodgrass_common_household_roaches.png/500px-Snodgrass_common_household_roaches.png",  // Cockroach
    "Condor": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/AndeanCondorMale.jpg/500px-AndeanCondorMale.jpg",  // Condor
    "Coyote": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/2009-Coyote-Yosemite.jpg/500px-2009-Coyote-Yosemite.jpg",  // Coyote
    "Cricket": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Gryllus_campestris_MHNT.jpg/500px-Gryllus_campestris_MHNT.jpg",  // Cricket (insect)
    "Cuckoo": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Cacomantis_flabelliformis.jpg/500px-Cacomantis_flabelliformis.jpg",  // Cuckoo
    "Deep Sea Jellyfish": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Atolla_wyvillei_%28Operation_Deep_Scope_2004%29.jpg/500px-Atolla_wyvillei_%28Operation_Deep_Scope_2004%29.jpg",  // Atolla jellyfish
    "Deer": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/White-tailed_deer.jpg/500px-White-tailed_deer.jpg",  // White-tailed deer
    "Dingo": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Dingo_%28Canis_lupus_dingo%29_Kakadu_2.jpg/500px-Dingo_%28Canis_lupus_dingo%29_Kakadu_2.jpg",  // Dingo
    "Dog": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Huskiesatrest.jpg/500px-Huskiesatrest.jpg",  // Dog
    "Dumbo Octopus": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Dumbo-hires_%28cropped%29.jpg/500px-Dumbo-hires_%28cropped%29.jpg",  // Grimpoteuthis
    "Eagle": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Eagles_together.jpg/500px-Eagles_together.jpg",  // Eagle
    "Elephant": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/178_Male_African_bush_elephant_in_Etosha_National_Park_Photo_by_Giles_Laurent.jpg/500px-178_Male_African_bush_elephant_in_Etosha_National_Park_Photo_by_Giles_Laurent.jpg",  // African bush elephant
    "Emperor Penguin": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Aptenodytes_forsteri_-Snow_Hill_Island%2C_Antarctica_-adults_and_juvenile-8.jpg/500px-Aptenodytes_forsteri_-Snow_Hill_Island%2C_Antarctica_-adults_and_juvenile-8.jpg",  // Emperor penguin
    "Emu": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Emu_1_-_Tidbinbilla.jpg/500px-Emu_1_-_Tidbinbilla.jpg",  // Emu
    "Fangtooth Fish": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Anoplogaster_cornuta_2012.jpg/500px-Anoplogaster_cornuta_2012.jpg",  // Fangtooth
    "Fennec Fox": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Fennec_Fox_Vulpes_zerda.jpg/500px-Fennec_Fox_Vulpes_zerda.jpg",  // Fennec fox
    "Ferret": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Ferret_2008.png/500px-Ferret_2008.png",  // Ferret
    "Fiddler Crab": "https://upload.wikimedia.org/wikipedia/commons/0/0b/Fiddler_crab.jpg",  // Fiddler crab
    "Fire Salamander": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Salamandra_salamandra_MHNT_1.jpg/500px-Salamandra_salamandra_MHNT_1.jpg",  // Fire salamander
    "Frog": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Red-eyed_Leaf_Frog_%2849661076226%29.jpg/500px-Red-eyed_Leaf_Frog_%2849661076226%29.jpg",  // Frog
    "Galápagos Iguana": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Galapagos_Land_Iguana_%2815341919654%29.jpg/500px-Galapagos_Land_Iguana_%2815341919654%29.jpg",  // Conolophus
    "Gecko": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Phelsuma_l._laticauda.jpg/500px-Phelsuma_l._laticauda.jpg",  // Gecko
    "Giant Squid": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Giant_squid_Ranheim.jpg/500px-Giant_squid_Ranheim.jpg",  // Giant squid
    "Gila Monster": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Gila_monster2.JPG/500px-Gila_monster2.JPG",  // Gila monster
    "Giraffe": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Rothschild%27s_giraffe_%28Giraffa_camelopardalis_rothschildi%29_-_Murchison_Falls_National_Park.jpg/500px-Rothschild%27s_giraffe_%28Giraffa_camelopardalis_rothschildi%29_-_Murchison_Falls_National_Park.jpg",  // Northern giraffe
    "Goldfish": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Gold_fish1.jpg/500px-Gold_fish1.jpg",  // Goldfish
    "Gorilla": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Gorille_des_plaines_de_l%27ouest_%C3%A0_l%27Espace_Zoologique.jpg/500px-Gorille_des_plaines_de_l%27ouest_%C3%A0_l%27Espace_Zoologique.jpg",  // Gorilla
    "Gray Owl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/%D0%91%D0%BE%D1%80%D0%BE%D0%B4%D0%B0%D1%82%D0%B0%D1%8F_%D0%BD%D0%B5%D1%8F%D1%81%D1%8B%D1%82%D1%8C_%28Strix_nebulosa%2C_m%29%2C_%D0%91%D0%BE%D1%82%D0%B0%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D1%81%D0%B0%D0%B4.jpg/500px-%D0%91%D0%BE%D1%80%D0%BE%D0%B4%D0%B0%D1%82%D0%B0%D1%8F_%D0%BD%D0%B5%D1%8F%D1%81%D1%8B%D1%82%D1%8C_%28Strix_nebulosa%2C_m%29%2C_%D0%91%D0%BE%D1%82%D0%B0%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D1%81%D0%B0%D0%B4.jpg",  // Great grey owl
    "Gray Wolf": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Eurasian_wolf_2.jpg/500px-Eurasian_wolf_2.jpg",  // Wolf
    "Gulper Eel": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Eurypharynx_pelecanoides.jpg/500px-Eurypharynx_pelecanoides.jpg",  // Pelican eel
    "Harpy Eagle": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Harpia_harpyja_001_800.jpg/500px-Harpia_harpyja_001_800.jpg",  // Harpy eagle
    "Hawaiian Hoary Bat": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Hawaiian_hoary_bat_Lasiurus_cinereus_semotus.jpg/500px-Hawaiian_hoary_bat_Lasiurus_cinereus_semotus.jpg",  // Hawaiian hoary bat
    "Hermit Crab": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Calliactis_and_Dardanus_001.JPG/500px-Calliactis_and_Dardanus_001.JPG",  // Hermit crab
    "Heron": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Ardeidae-01.jpg/500px-Ardeidae-01.jpg",  // Heron
    "Hippopotamus": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Portrait_Hippopotamus_in_the_water.jpg/500px-Portrait_Hippopotamus_in_the_water.jpg",  // Hippopotamus
    "Howler Monkey": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Mantled_howler_monkey_and_baby_%2881337%292.jpg/500px-Mantled_howler_monkey_and_baby_%2881337%292.jpg",  // Howler monkey
    "Hyena": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Hyaenidae_Diversity.jpg/500px-Hyaenidae_Diversity.jpg",  // Hyena
    "Ibex": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Capra_ibex_ibex.jpg/500px-Capra_ibex_ibex.jpg",  // Ibex
    "Jackrabbit": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Scrub_Hare_%28Lepus_saxatilis%29_close-up_%2830544290256%29_%282%29.jpg/500px-Scrub_Hare_%28Lepus_saxatilis%29_close-up_%2830544290256%29_%282%29.jpg",  // Hare
    "Jaguar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Standing_jaguar.jpg/500px-Standing_jaguar.jpg",  // Jaguar
    "Kangaroo": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Forester_kangaroo_%28Macropus_giganteus_tasmaniensis%29_juvenile_hopping_Esk_Valley.jpg/500px-Forester_kangaroo_%28Macropus_giganteus_tasmaniensis%29_juvenile_hopping_Esk_Valley.jpg",  // Kangaroo
    "Kangaroo Rat": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Kangaroo-rat.jpg/500px-Kangaroo-rat.jpg",  // Kangaroo rat
    "Koala": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Koala_climbing_tree.jpg/500px-Koala_climbing_tree.jpg",  // Koala
    "Lava Lizard": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Microlophus_peruvianus_447780594.jpg/500px-Microlophus_peruvianus_447780594.jpg",  // Microlophus
    "Lemming": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Tunturisopuli_Lemmus_Lemmus.jpg/500px-Tunturisopuli_Lemmus_Lemmus.jpg",  // Lemming
    "Leopard Seal": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Antarctic_Sound-2016-Brown_Bluff%E2%80%93Leopard_seal_%28Hydrurga_leptonyx%29_04.jpg/500px-Antarctic_Sound-2016-Brown_Bluff%E2%80%93Leopard_seal_%28Hydrurga_leptonyx%29_04.jpg",  // Leopard seal
    "Lion": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/020_The_lion_king_Snyggve_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg/500px-020_The_lion_king_Snyggve_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg",  // Lion
    "Lynx": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Lynx_Nationalpark_Bayerischer_Wald_01.jpg/500px-Lynx_Nationalpark_Bayerischer_Wald_01.jpg",  // Eurasian lynx
    "Manta Ray": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Dharavandhoo_Thila_-_Manata_Black_Pearl.JPG/500px-Dharavandhoo_Thila_-_Manata_Black_Pearl.JPG",  // Manta ray
    "Marmot": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/071_Wild_marmot_at_Grand_Muveran_Nature_Reserve_Photo_by_Giles_Laurent.jpg/500px-071_Wild_marmot_at_Grand_Muveran_Nature_Reserve_Photo_by_Giles_Laurent.jpg",  // Marmot
    "Meerkat": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Meerkat_%28Suricata_suricatta%29_Tswalu.jpg/500px-Meerkat_%28Suricata_suricatta%29_Tswalu.jpg",  // Meerkat
    "Moose": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Alaska_moose.jpg/500px-Alaska_moose.jpg",  // Moose
    "Moray Eel": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Moray_eel.jpg/500px-Moray_eel.jpg",  // Moray eel
    "Mountain Goat": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Mountain_Goat%2C_Enchantments_Basin.jpg/500px-Mountain_Goat%2C_Enchantments_Basin.jpg",  // Mountain goat
    "Mudskipper": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/GambianMudskippers.jpg/500px-GambianMudskippers.jpg",  // Mudskipper
    "Musk Ox": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Muskox_%28Ovibos_moschatus%29_male_Dovrefjell_4.jpg/500px-Muskox_%28Ovibos_moschatus%29_male_Dovrefjell_4.jpg",  // Muskox
    "Mussel": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/CornishMussels.JPG/500px-CornishMussels.JPG",  // Mussel
    "Octopus": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Octopus2.jpg/500px-Octopus2.jpg",  // Octopus
    "Opossum": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Didelphis_virginiana_with_young.JPG/500px-Didelphis_virginiana_with_young.JPG",  // Opossum
    "Orca": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Killerwhales_jumping.jpg/500px-Killerwhales_jumping.jpg",  // Orca
    "Otter": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Fischotter%2C_Lutra_Lutra.JPG/500px-Fischotter%2C_Lutra_Lutra.JPG",  // Otter
    "Owl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Bubo_bubo_sibiricus_-_01.JPG/500px-Bubo_bubo_sibiricus_-_01.JPG",  // Owl
    "Parrotfish": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Scarus_frenatus_by_Ewa_Barska.jpg/500px-Scarus_frenatus_by_Ewa_Barska.jpg",  // Parrotfish
    "Pelican": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Pelikan_Walvis_Bay.jpg/500px-Pelikan_Walvis_Bay.jpg",  // Pelican
    "Peregrine Falcon": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Falco_peregrinus_m_Humber_Bay_Park_Toronto.jpg/500px-Falco_peregrinus_m_Humber_Bay_Park_Toronto.jpg",  // Peregrine falcon
    "Pigeon": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Treron_vernans_male_-_Kent_Ridge_Park.jpg/500px-Treron_vernans_male_-_Kent_Ridge_Park.jpg",  // Columbidae
    "Piranha": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Pygocentrus_nattereri_-_Karlsruhe_Zoo_01.jpg/500px-Pygocentrus_nattereri_-_Karlsruhe_Zoo_01.jpg",  // Piranha
    "Platypus": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Duck-billed_platypus_%28Ornithorhynchus_anatinus%29_Scottsdale.jpg/500px-Duck-billed_platypus_%28Ornithorhynchus_anatinus%29_Scottsdale.jpg",  // Platypus
    "Poison Dart Frog": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Dendrobates_tinctorius_-_Karlsruhe_Zoo_05.jpg/500px-Dendrobates_tinctorius_-_Karlsruhe_Zoo_05.jpg",  // Dyeing poison dart frog
    "Polar Bear": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Polar_Bear_-_Alaska_%28cropped%29.jpg/500px-Polar_Bear_-_Alaska_%28cropped%29.jpg",  // Polar bear
    "Prairie Dog": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Black-Tailed_Prairie_Dog.jpg/500px-Black-Tailed_Prairie_Dog.jpg",  // Prairie dog
    "Proboscis Monkey": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Proboscis_Monkey_in_Borneo.jpg/500px-Proboscis_Monkey_in_Borneo.jpg",  // Proboscis monkey
    "Pterodactyl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Pteranodon_amnh_martyniuk.jpg/500px-Pteranodon_amnh_martyniuk.jpg",  // Pterosaur
    "Rabbit": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Oryctolagus_cuniculus_Rcdo.jpg/500px-Oryctolagus_cuniculus_Rcdo.jpg",  // Rabbit
    "Raccoon": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Raccoon_in_Central_Park_%2835264%29.jpg/500px-Raccoon_in_Central_Park_%2835264%29.jpg",  // Raccoon
    "Rat": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Brown_Rat_%28Rattus_norvegicus%29.jpg/500px-Brown_Rat_%28Rattus_norvegicus%29.jpg",  // Rat
    "Rattlesnake": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Crotalus_cerastes_mesquite_springs_CA-2.jpg/500px-Crotalus_cerastes_mesquite_springs_CA-2.jpg",  // Rattlesnake
    "Red Fox": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Portrait_of_a_red_fox_in_Rautas_fj%C3%A4llurskog_%28cropped%29.jpg/500px-Portrait_of_a_red_fox_in_Rautas_fj%C3%A4llurskog_%28cropped%29.jpg",  // Red fox
    "Red Squirrel": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Squirrel_posing.jpg/500px-Squirrel_posing.jpg",  // Red squirrel
    "Red-Tailed Hawk": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Red-tailed_Hawk_%2845812546121%29.jpg/500px-Red-tailed_Hawk_%2845812546121%29.jpg",  // Red-tailed hawk
    "Reef Shark": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Caribbean_reef_shark.jpg/500px-Caribbean_reef_shark.jpg",  // Reef shark
    "Reindeer": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Reinbukken_p%C3%A5_frisk_gr%C3%B8nt_beite._-_panoramio.jpg/500px-Reinbukken_p%C3%A5_frisk_gr%C3%B8nt_beite._-_panoramio.jpg",  // Reindeer
    "Rhino": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/081_White_rhinoceros_%28male%29_in_the_Kalahari_Desert_of_Namibia_Photo_by_Giles_Laurent.jpg/500px-081_White_rhinoceros_%28male%29_in_the_Kalahari_Desert_of_Namibia_Photo_by_Giles_Laurent.jpg",  // Rhinoceros
    "River Dolphin": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Amazonas-Flussdelfin_Orinoko3.jpg/500px-Amazonas-Flussdelfin_Orinoko3.jpg",  // Amazon river dolphin
    "River Otter": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Northern_River_Otter_on_Seedskadee_NWR_%2822802102984%29.jpg/500px-Northern_River_Otter_on_Seedskadee_NWR_%2822802102984%29.jpg",  // North American river otter
    "Roadrunner": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/20140322-0062_La_Quinta_CA.JPG/500px-20140322-0062_La_Quinta_CA.JPG",  // Roadrunner
    "Salamander": "https://upload.wikimedia.org/wikipedia/commons/b/b2/SpottedSalamander.jpg",  // Salamander
    "Salmon": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Sockeye_salmon_swimming_right.jpg/500px-Sockeye_salmon_swimming_right.jpg",  // Sockeye salmon
    "Saltwater Crocodile": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/SaltwaterCrocodile%28%27Maximo%27%29.jpg/500px-SaltwaterCrocodile%28%27Maximo%27%29.jpg",  // Saltwater crocodile
    "Sand Cat": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Persian_sand_CAT.jpg/500px-Persian_sand_CAT.jpg",  // Sand cat
    "Sand Dollar": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Clypeaster_reticulatus.jpg/500px-Clypeaster_reticulatus.jpg",  // Sand dollar
    "Sandpiper": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Eurasian_Woodcock_Scolopax_rusticola%2C_Keski-Karjala%2C_Finland_365403651.jpg/500px-Eurasian_Woodcock_Scolopax_rusticola%2C_Keski-Karjala%2C_Finland_365403651.jpg",  // Sandpiper
    "Scorpion": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Scorpion_Photograph_By_Shantanu_Kuveskar.jpg/500px-Scorpion_Photograph_By_Shantanu_Kuveskar.jpg",  // Scorpion
    "Sea Lion": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/South_American_bull_sea_lion_%28Otaria_flavescens%29.jpg/500px-South_American_bull_sea_lion_%28Otaria_flavescens%29.jpg",  // Sea lion
    "Sea Turtle": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Chelonia_mydas_is_going_for_the_air_edit.jpg/500px-Chelonia_mydas_is_going_for_the_air_edit.jpg",  // Sea turtle
    "Seagull": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Herring_Gull_%28Larus_argentatus%29%2C_Brighton%2C_England.JPG/500px-Herring_Gull_%28Larus_argentatus%29%2C_Brighton%2C_England.JPG",  // Gull
    "Seahorse": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Hippocampus_hippocampus_%28on_Ascophyllum_nodosum%29.jpg/500px-Hippocampus_hippocampus_%28on_Ascophyllum_nodosum%29.jpg",  // Seahorse
    "Seal": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Common_seal_%28Phoca_vitulina%29_2.jpg/500px-Common_seal_%28Phoca_vitulina%29_2.jpg",  // Harbor seal
    "Silverfish": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/LepismaSaccharina.jpg/500px-LepismaSaccharina.jpg",  // Silverfish
    "Sloth": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Bicho-pregui%C3%A7a_3.jpg/500px-Bicho-pregui%C3%A7a_3.jpg",  // Sloth
    "Snake": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Trimeresurus_sabahi_fucatus%2C_Banded_pit_viper_-_Takua_Pa_District%2C_Phang-nga_Province_%2846710893582%29.jpg/500px-Trimeresurus_sabahi_fucatus%2C_Banded_pit_viper_-_Takua_Pa_District%2C_Phang-nga_Province_%2846710893582%29.jpg",  // Snake
    "Snapping Turtle": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Common_Snapping_Turtle_%2852259285400%29.jpg/500px-Common_Snapping_Turtle_%2852259285400%29.jpg",  // Chelydridae
    "Snow Leopard": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Irbis4.JPG/500px-Irbis4.JPG",  // Snow leopard
    "Snow Petrel": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/P%C3%A9trel_des_neiges_-_Snow_Petrel.jpg/500px-P%C3%A9trel_des_neiges_-_Snow_Petrel.jpg",  // Snow petrel
    "Snowshoe Hare": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Lepus_americanus_5459_cropped.jpg/500px-Lepus_americanus_5459_cropped.jpg",  // Snowshoe hare
    "Snowy Owl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/SnowyOwlAmericanBlackDuck.jpg/500px-SnowyOwlAmericanBlackDuck.jpg",  // Snowy owl
    "Sparrow": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/House_sparrow_male_in_Prospect_Park_%2853532%29.jpg/500px-House_sparrow_male_in_Prospect_Park_%2853532%29.jpg",  // House sparrow
    "Sperm Whale": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Mother_and_baby_sperm_whale.jpg/500px-Mother_and_baby_sperm_whale.jpg",  // Sperm whale
    "Spider": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Araneus_diadematus_%28Clerck%2C_1757%29.JPG/500px-Araneus_diadematus_%28Clerck%2C_1757%29.JPG",  // Spider
    "Spinosaurus": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Spinosaurus_Skeleton_Cast_at_the_National_Geographic_Museum.jpg/500px-Spinosaurus_Skeleton_Cast_at_the_National_Geographic_Museum.jpg",  // Spinosaurus Skeleton Cast at the National Geographic Museum.jpg
    "Squirrel": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/EasternGraySquirrel_GAm.jpg/500px-EasternGraySquirrel_GAm.jpg",  // Eastern gray squirrel
    "Starfish": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Asterias_rubens.jpg/500px-Asterias_rubens.jpg",  // Common starfish
    "Stegosaurus": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Journal.pone.0138352.g001A.jpg/500px-Journal.pone.0138352.g001A.jpg",  // Stegosaurus
    "Stray Cat": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Feral_cat_1.JPG/500px-Feral_cat_1.JPG",  // Feral cat
    "Tarsier": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Philippine_tarsier_%28Carlito_syrichta_fraterculus%29_Bohol_2.jpg/500px-Philippine_tarsier_%28Carlito_syrichta_fraterculus%29_Bohol_2.jpg",  // Tarsier
    "Tasmanian Devil": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Sarcophilus_harrisii_taranna.jpg/500px-Sarcophilus_harrisii_taranna.jpg",  // Tasmanian devil
    "Thorny Devil": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Thornydevil.jpg/500px-Thornydevil.jpg",  // Thorny devil
    "Toad": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Bombina_bombina_1_%28Marek_Szczepanek%29.jpg/500px-Bombina_bombina_1_%28Marek_Szczepanek%29.jpg",  // Toad
    "Toucan": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/006_Toco_toucan_in_Encontro_das_%C3%81guas_State_Park_Photo_by_Giles_Laurent.jpg/500px-006_Toco_toucan_in_Encontro_das_%C3%81guas_State_Park_Photo_by_Giles_Laurent.jpg",  // Toco toucan
    "Triceratops": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/LA-Triceratops_mount-2.jpg/500px-LA-Triceratops_mount-2.jpg",  // Triceratops
    "Troglodyte Beetle": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Leptodirus_hochenwartii.jpg/500px-Leptodirus_hochenwartii.jpg",  // Leptodirus
    "Turtle": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Turtle_diversity.jpg/500px-Turtle_diversity.jpg",  // Turtle
    "Tyrannosaurus Rex": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Tyrannosaurus_Rex_Holotype.jpg/500px-Tyrannosaurus_Rex_Holotype.jpg",  // Tyrannosaurus
    "Vampire Ground Finch": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Vampire_finch_%284229090408%29.jpg/500px-Vampire_finch_%284229090408%29.jpg",  // Vampire ground finch
    "Vampire Squid": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Vampyroteuthis_illustration.jpg/500px-Vampyroteuthis_illustration.jpg",  // Vampire squid
    "Velociraptor": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Velociraptor_skeleton_white_background.jpg/500px-Velociraptor_skeleton_white_background.jpg",  // Velociraptor
    "Volcanic Mouse": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Mexican_volcano_mouse_imported_from_iNaturalist_photo_70082694_on_18_April_2022.jpg/500px-Mexican_volcano_mouse_imported_from_iNaturalist_photo_70082694_on_18_April_2022.jpg",  // Mexican volcano mouse
    "Volcano Rabbit": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Romerolagus_diazi_-_Zoologico_de_Chapultepec%2C_Ciudad_de_M%C3%A9xico_-_Cropped2xAlt.png/500px-Romerolagus_diazi_-_Zoologico_de_Chapultepec%2C_Ciudad_de_M%C3%A9xico_-_Cropped2xAlt.png",  // Volcano rabbit
    "Vulture": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Gyps_rueppellii_-Nairobi_National_Park%2C_Kenya-8-4c.jpg/500px-Gyps_rueppellii_-Nairobi_National_Park%2C_Kenya-8-4c.jpg",  // Vulture
    "Walrus": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Walrus_in_the_Russian_Arctic_National_Park%2C_Novaya_Zemlya_2015-2.jpg/500px-Walrus_in_the_Russian_Arctic_National_Park%2C_Novaya_Zemlya_2015-2.jpg",  // Walrus
    "Water Moccasin": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Florida_Water_Moccasin_056.jpg/500px-Florida_Water_Moccasin_056.jpg",  // Florida Water Moccasin 056.jpg
    "Wild Boar": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Wildschwein%2C_N%C3%A4he_Pulverstampftor_%28cropped%29.jpg/500px-Wildschwein%2C_N%C3%A4he_Pulverstampftor_%28cropped%29.jpg",  // Wild boar
    "Wildebeest": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Blue_wildebeest_%28Connochaetes_taurinus_taurinus%29%2C_male.jpg/500px-Blue_wildebeest_%28Connochaetes_taurinus_taurinus%29%2C_male.jpg",  // Blue wildebeest (Connochaetes taurinus taurinus), male.jpg
    "Wolverine": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/J%C3%A4rv1.jpg/500px-J%C3%A4rv1.jpg",  // Wolverine
    "Wombat": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Vombatus_ursinus_-Maria_Island_National_Park.jpg/500px-Vombatus_ursinus_-Maria_Island_National_Park.jpg",  // Wombat
    "Woodpecker": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/PileatedWoodpeckerFeedingonTree%2C_crop.jpg/500px-PileatedWoodpeckerFeedingonTree%2C_crop.jpg",  // Woodpecker
    "Yak": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Sarlyk_Yak2.jpg/500px-Sarlyk_Yak2.jpg",  // Yak
    "Zebra": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Equus_quagga_burchellii_-_Etosha%2C_2014.jpg/500px-Equus_quagga_burchellii_-_Etosha%2C_2014.jpg",  // Plains zebra
  };

  // Photographer and licence for each photo above — what most of those
  // licences ask in return. Read by the Credits screen. An empty name is a
  // public-domain photo with no author on record, so there is nobody owed.
  window.MASQ_ANIMAL_CREDITS = [
    ["Albatross", "Jlfutari", "CC BY 2.5"],
    ["Alligator", "C. J. Cornish et al", "Public domain"],
    ["Anaconda", "LA Dawson", "CC BY-SA 2.5"],
    ["Anglerfish", "", "Public domain"],
    ["Ankylosaurus", "Tim Evanson", "CC BY-SA 2.0"],
    ["Antarctic Krill", "Uwe Kils", "CC BY-SA 3.0"],
    ["Antelope", "Mr Raja Purohit", "CC BY-SA 2.5"],
    ["Arctic Fox", "Jonathen Pie", "CC0"],
    ["Arctic Hare", "Steve Sayles", "CC BY-SA 2.0"],
    ["Badger", "Charles J. Sharp", "CC BY-SA 4.0"],
    ["Bat", "", "Public domain"],
    ["Beaver", "Steve from Washington, DC, USA", "CC BY-SA 2.0"],
    ["Beluga Whale", "Javier Yaya Tur / CIUDAD DE LAS ARTES Y LAS CIENCIAS", "CC BY 2.0"],
    ["Bengal Tiger", "Tisha Mukherjee", "CC BY-SA 4.0"],
    ["Bighorn Sheep", "Jwanamaker", "CC BY-SA 3.0"],
    ["Bison", "Jack Dykinga", "Public domain"],
    ["Black Bear", "Diginatur", "CC BY-SA 3.0"],
    ["Blind Fish", "Clinton & Charles Robertson", "CC BY 2.0"],
    ["Bobcat", "Becker1999 (Paul and Cathy)", "CC BY 2.0"],
    ["Brachiosaurus", "Matt Wedel", "CC BY 3.0"],
    ["Bullfrog", "Carl D. Howe", "CC BY-SA 2.5"],
    ["California Quail", "Charles J. Sharp", "CC BY-SA 4.0"],
    ["Camel", "Jjron", "CC BY-SA 3.0"],
    ["Cat", "Alvesgaspar", "CC BY-SA 3.0"],
    ["Catfish", "Dieter Florian", "CC BY-SA 3.0 de"],
    ["Cheetah", "AfricanConservation", "CC BY-SA 4.0"],
    ["Clownfish", "Nick Hobgood", "CC BY-SA 3.0"],
    ["Cockroach", "", "Public domain"],
    ["Condor", "Greg Hume", "CC BY-SA 3.0"],
    ["Coyote", "Yathin S Krishnappa", "CC BY-SA 3.0"],
    ["Cricket", "Didier Descouens", "CC BY-SA 4.0"],
    ["Cuckoo", "JJ Harrison", "CC BY-SA 3.0"],
    ["Deep Sea Jellyfish", "NOAA Ocean Explorer", "CC BY-SA 2.0"],
    ["Deer", "USDA photo by Scott Bauer", "Public domain"],
    ["Dingo", "Charles J. Sharp", "CC BY-SA 4.0"],
    ["Dog", "M. Rehemtulla", "CC BY 2.0"],
    ["Dumbo Octopus", "NOAA Okeanos Explorer", "Public domain"],
    ["Eagle", "Punetor i Rregullt5", "CC BY-SA 4.0"],
    ["Elephant", "Giles Laurent", "CC BY-SA 4.0"],
    ["Emperor Penguin", "Ian Duffy", "CC BY 2.0"],
    ["Emu", "JJ Harrison", "CC BY-SA 4.0"],
    ["Fangtooth Fish", "Citron", "CC BY-SA 3.0"],
    ["Fennec Fox", "Drew Avery", "CC BY 2.0"],
    ["Ferret", "Alfredo Gutiérrez", "CC BY-SA 4.0"],
    ["Fiddler Crab", "NOAA", "Public domain"],
    ["Fire Salamander", "Didier Descouens", "CC BY-SA 4.0"],
    ["Frog", "Charlie Jackson", "CC BY 2.0"],
    ["Galápagos Iguana", "Andy Morffew", "CC BY 2.0"],
    ["Gecko", "Jurriaan Schulman", "CC BY-SA 3.0"],
    ["Giant Squid", "NTNU Vitenskapsmuseet", "CC BY 2.0"],
    ["Gila Monster", "Blueag9", "CC BY-SA 3.0"],
    ["Giraffe", "Thomas Fuhrmann", "CC BY-SA 4.0"],
    ["Goldfish", "לינה אבוגוש", "CC BY-SA 3.0"],
    ["Gorilla", "Thurundir", "CC BY-SA 4.0"],
    ["Gray Owl", "Dion Art", "CC BY-SA 4.0"],
    ["Gray Wolf", "Mas3cf", "CC BY-SA 4.0"],
    ["Gulper Eel", "", "Public domain"],
    ["Harpy Eagle", "Tom Friedel (birdphotos.com)", "CC BY 3.0"],
    ["Hawaiian Hoary Bat", "Frank Bonaccorso, USGS", "Public domain"],
    ["Hermit Crab", "H. Zell", "CC BY-SA 3.0"],
    ["Heron", "MathKnight", "CC BY-SA 4.0"],
    ["Hippopotamus", "Muhammad Mahdi Karim", "CC BY-SA 4.0"],
    ["Howler Monkey", "Rhododendrites", "CC BY-SA 4.0"],
    ["Hyena", "Termininja", "CC BY-SA 4.0"],
    ["Ibex", "T.Voekler", "CC BY-SA 3.0"],
    ["Jackrabbit", "Bernard DUPONT", "CC BY-SA 2.0"],
    ["Jaguar", "USFWS", "Public domain"],
    ["Kangaroo", "Charles J. Sharp", "CC BY-SA 4.0"],
    ["Kangaroo Rat", "", "Public domain"],
    ["Koala", "Diliff", "CC BY-SA 3.0"],
    ["Lava Lizard", "David F. Belmonte", "CC BY 4.0"],
    ["Lemming", "Argus fin", "Public domain"],
    ["Leopard Seal", "Godot13", "CC BY-SA 4.0"],
    ["Lion", "Giles Laurent", "CC BY-SA 4.0"],
    ["Lynx", "Aconcagua", "CC BY-SA 3.0"],
    ["Manta Ray", "Shiyam ElkCloner", "CC BY-SA 3.0"],
    ["Marmot", "Giles Laurent", "CC BY-SA 4.0"],
    ["Meerkat", "Charles J. Sharp", "CC BY-SA 4.0"],
    ["Moose", "Paxson Woelber", "CC BY-SA 4.0"],
    ["Moray Eel", "Mstroeck", "CC BY-SA 3.0"],
    ["Mountain Goat", "Adam Schneider", "CC BY-SA 4.0"],
    ["Mudskipper", "Bjørn Christian Tørrissen", "CC BY-SA 4.0"],
    ["Musk Ox", "Charles J. Sharp", "CC BY-SA 4.0"],
    ["Mussel", "Wilson44691", "Public domain"],
    ["Octopus", "albert kok", "CC BY-SA 3.0"],
    ["Opossum", "Specialjake", "CC BY-SA 3.0"],
    ["Orca", "Robert Pittman", "Public domain"],
    ["Otter", "Bernard Landgraf", "CC BY-SA 3.0"],
    ["Owl", "Carlos Delgado", "CC BY-SA 4.0"],
    ["Parrotfish", "Ewa Barska", "CC BY-SA 3.0"],
    ["Pelican", "Rui Ornelas", "CC BY 2.0"],
    ["Peregrine Falcon", "Mykola Swarnyk", "CC BY-SA 3.0"],
    ["Pigeon", "JJ Harrison", "CC BY-SA 4.0"],
    ["Piranha", "H. Zell", "CC BY-SA 3.0"],
    ["Platypus", "Charles J. Sharp", "CC BY-SA 4.0"],
    ["Poison Dart Frog", "H. Zell", "CC BY-SA 3.0"],
    ["Polar Bear", "Alan Wilson", "CC BY-SA 3.0"],
    ["Prairie Dog", "Joe Ravi", "CC BY-SA 3.0"],
    ["Proboscis Monkey", "David Dennis", "CC BY-SA 2.0"],
    ["Pterodactyl", "Matt Martyniuk", "CC BY 3.0"],
    ["Rabbit", "JM Ligero Loarte", "CC BY 3.0"],
    ["Raccoon", "Rhododendrites", "CC BY-SA 4.0"],
    ["Rat", "Dunpharlain", "CC BY-SA 4.0"],
    ["Rattlesnake", "Tigerhawkvok (edited by Victorrocha)", "CC BY-SA 3.0"],
    ["Red Fox", "ClaudiaTen", "CC BY-SA 4.0"],
    ["Red Squirrel", "Peter Trimming", "CC BY 2.0"],
    ["Red-Tailed Hawk", "Becky Matsubara", "CC BY 2.0"],
    ["Reef Shark", "Albert kok", "CC BY-SA 3.0"],
    ["Reindeer", "Are G Nilsen", "CC BY-SA 3.0"],
    ["Rhino", "Giles Laurent", "CC BY-SA 4.0"],
    ["River Dolphin", "Oceancetaceen", "CC BY-SA 2.0 de"],
    ["River Otter", "USFWS Mountain-Prairie", "Public domain"],
    ["Roadrunner", "Nandaro", "CC BY-SA 4.0"],
    ["Salamander", "Scott Camazine", "CC BY-SA 3.0"],
    ["Salmon", "Milton Love, Marine Science Institute, UCSB", "Public domain"],
    ["Saltwater Crocodile", "Molly Ebersold, St. Augustine Alligator Farm", "Public domain"],
    ["Sand Cat", "Payman sazesh", "CC BY-SA 3.0"],
    ["Sand Dollar", "Frédéric Ducarme", "CC BY-SA 4.0"],
    ["Sandpiper", "lindalotjonen", "CC BY 4.0"],
    ["Scorpion", "Shantanu Kuveskar", "CC BY-SA 4.0"],
    ["Sea Lion", "Atsme", "CC BY-SA 4.0"],
    ["Sea Turtle", "Brocken Inaglory", "CC BY-SA 3.0"],
    ["Seagull", "Beata May", "CC BY-SA 3.0"],
    ["Seahorse", "Hans Hillewaert", "CC BY-SA 4.0"],
    ["Seal", "Charles J. Sharp", "CC BY-SA 4.0"],
    ["Silverfish", "Christian Fischer", "CC BY-SA 3.0"],
    ["Sloth", "Daniella Maraschiello", "CC BY-SA 4.0"],
    ["Snake", "Rushenb", "CC BY-SA 2.0"],
    ["Snapping Turtle", "USFWS Mountain Prairie", "Public domain"],
    ["Snow Leopard", "Irbis1983", "Public domain"],
    ["Snow Petrel", "Samuel Blanc", "CC BY-SA 3.0"],
    ["Snowshoe Hare", "Walter Siegmund", "CC BY-SA 3.0"],
    ["Snowy Owl", "Chuck Homler d/b/a Focus On Wildlife", "CC BY-SA 3.0"],
    ["Sparrow", "Rhododendrites", "CC BY-SA 4.0"],
    ["Sperm Whale", "Gabriel Barathieu", "CC BY-SA 2.0"],
    ["Spider", "Michael Gäbler", "CC BY-SA 3.0"],
    ["Spinosaurus", "Ryan Somma", "CC BY 2.0"],
    ["Squirrel", "JeffreyGammon", "CC BY-SA 4.0"],
    ["Starfish", "Hans Hillewaert", "CC BY-SA 4.0"],
    ["Stegosaurus", "Susannah Maidment et al. & Natural History Museum, London", "CC BY 4.0"],
    ["Stray Cat", "Brocken Inaglory", "CC BY-SA 3.0"],
    ["Tarsier", "Charles J. Sharp", "CC BY-SA 4.0"],
    ["Tasmanian Devil", "JJ Harrison", "CC BY-SA 3.0"],
    ["Thorny Devil", "Bäras", "CC BY-SA 3.0"],
    ["Toad", "Marek Szczepanek", "CC BY-SA 3.0"],
    ["Toucan", "Giles Laurent", "CC BY-SA 4.0"],
    ["Triceratops", "Allie Caulfield (edited by MathKnight)", "CC BY-SA 3.0"],
    ["Troglodyte Beetle", "Yerpo", "CC BY-SA 3.0"],
    ["Turtle", "Petra Karstedt, CLpramod, Matthew Field, Hoffryan", "CC BY-SA 4.0"],
    ["Tyrannosaurus Rex", "ScottRobertAnselmo", "CC BY-SA 3.0"],
    ["Vampire Ground Finch", "Peter Wilton", "CC BY 2.0"],
    ["Vampire Squid", "Carl Chun", "Public domain"],
    ["Velociraptor", "Eduard Solà Vázquez", "CC BY 3.0"],
    ["Volcanic Mouse", "Juan Cruzado Cortés", "CC BY-SA 4.0"],
    ["Volcano Rabbit", "ProtoplasmaKid", "CC BY-SA 4.0"],
    ["Vulture", "Jorge Láscar (edited by Snowmanradio)", "CC BY-SA 2.0"],
    ["Walrus", "Nixette", "CC BY-SA 4.0"],
    ["Water Moccasin", "Ltshears", "CC BY-SA 3.0"],
    ["Wild Boar", "Valentin Panzirsch", "CC BY-SA 3.0 at"],
    ["Wildebeest", "Charles J. Sharp", "CC BY-SA 4.0"],
    ["Wolverine", "Esquilo", "CC BY-SA 3.0"],
    ["Wombat", "JJ Harrison", "CC BY-SA 3.0"],
    ["Woodpecker", "Joshlaymon", "CC BY-SA 3.0"],
    ["Yak", "Alexandr frolov", "CC BY-SA 4.0"],
    ["Zebra", "Yathin S Krishnappa", "CC BY-SA 3.0"],
  ];
})();
