// GENERATED by tools/fetch-cuisines.js — do not edit by hand.
// Maps a food — a Cuisines role, or a word from the Food category — to its
// Wikipedia lead photo, as a finished URL; unlike the album art, there is
// no size to append. Each trailing comment is the article it came from.
(function () {
  window.MASQ_FOOD = {
    "Acai Bowl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/A%C3%A7a%C3%AD_do_Par%C3%A1.jpg/500px-A%C3%A7a%C3%AD_do_Par%C3%A1.jpg",  // Açai bowl
    "Acaraje": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Beans_Ball-Akara.jpg/500px-Beans_Ball-Akara.jpg",  // Akara
    "Adobo": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Lomo_en_adobo-2009.jpg/500px-Lomo_en_adobo-2009.jpg",  // Adobo
    "Aji de Gallina": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Aj%C3%AD_de_gallina.jpg/500px-Aj%C3%AD_de_gallina.jpg",  // Ají de gallina
    "Almonds": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Almonds_-_in_shell%2C_shell_cracked_open%2C_shelled%2C_blanched.jpg/500px-Almonds_-_in_shell%2C_shell_cracked_open%2C_shelled%2C_blanched.jpg",  // Almond
    "Anticuchos": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Anticuchos_-_Grilled_Beef_Heart_skewers.jpg/500px-Anticuchos_-_Grilled_Beef_Heart_skewers.jpg",  // Anticucho
    "Apple": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Honeycrisp-Apple.jpg/500px-Honeycrisp-Apple.jpg",  // Honeycrisp
    "Apple Pie": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Lattice_apple_pie.png/500px-Lattice_apple_pie.png",  // Apple pie
    "Avocado": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Avocado_Hass_-_single_and_halved.jpg/500px-Avocado_Hass_-_single_and_halved.jpg",  // Avocado Hass - single and halved.jpg
    "BLT": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Mmm..._BLT_for_me%21_%285487341380%29.jpg/500px-Mmm..._BLT_for_me%21_%285487341380%29.jpg",  // BLT
    "Baba Ghanoush": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Baba_Ganoush_05of05_%288735238183%29.jpg/500px-Baba_Ganoush_05of05_%288735238183%29.jpg",  // Baba ghanoush
    "Bacon": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Made20bacon.png/500px-Made20bacon.png",  // Bacon
    "Bagel": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Bagel_with_sesame_3.jpg/500px-Bagel_with_sesame_3.jpg",  // Bagel
    "Baghrir": "https://upload.wikimedia.org/wikipedia/commons/d/d2/%D8%A8%D8%BA%D8%B1%D9%8A%D8%B1.jpg",  // Baghrir
    "Baguette": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Baguettes%2C_Paris%2C_France_-_panoramio.jpg/500px-Baguettes%2C_Paris%2C_France_-_panoramio.jpg",  // Baguette
    "Baked Potato": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/BakedPotatoWithButter.jpg/500px-BakedPotatoWithButter.jpg",  // Baked potato
    "Baklava": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Baklava%281%29.png/500px-Baklava%281%29.png",  // Baklava
    "Banana": "https://upload.wikimedia.org/wikipedia/commons/d/de/Bananavarieties.jpg",  // Banana
    "Banana Bread": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Banana_bread_slices.jpg/500px-Banana_bread_slices.jpg",  // Banana bread
    "Banchan": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Banchan.jpg/500px-Banchan.jpg",  // Banchan
    "Bangers and Mash": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Sausage_and_mash_with_peas.jpg/500px-Sausage_and_mash_with_peas.jpg",  // Bangers and mash
    "Banh Mi": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/B%C3%A1nh_m%C3%AC_th%E1%BB%8Bt_n%C6%B0%E1%BB%9Bng.png/500px-B%C3%A1nh_m%C3%AC_th%E1%BB%8Bt_n%C6%B0%E1%BB%9Bng.png",  // Bánh mì
    "Banh Xeo": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Banh_Xeo_with_fish_sauce_and_vegetables.jpg/500px-Banh_Xeo_with_fish_sauce_and_vegetables.jpg",  // Bánh xèo
    "Bastilla": "https://upload.wikimedia.org/wikipedia/commons/e/ed/Bisteeya.jpg",  // Pastilla
    "Beef": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Beef_fillet_steak_with_mushrooms.jpg/500px-Beef_fillet_steak_with_mushrooms.jpg",  // Steak
    "Beef Stew": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Lamb-stew.jpg/500px-Lamb-stew.jpg",  // Stew
    "Beef Wellington": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Beef_Wellington_2019.jpg/500px-Beef_Wellington_2019.jpg",  // Beef Wellington
    "Beyaynetu": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Beyaynetu.JPG/500px-Beyaynetu.JPG",  // Beyaynetu
    "Bibimbap": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Dolsot-bibimbap.jpg/500px-Dolsot-bibimbap.jpg",  // Bibimbap
    "Bibingka": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/02545jfPlaza_Publika_de_Baliuag_Bulacanfvf_03.jpg/500px-02545jfPlaza_Publika_de_Baliuag_Bulacanfvf_03.jpg",  // Bibingka
    "Bicol Express": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Bicol_Express.jpg/500px-Bicol_Express.jpg",  // Bicol express
    "Birria": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Plato_de_birria.jpg/500px-Plato_de_birria.jpg",  // Birria
    "Biryani": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/%22Hyderabadi_Dum_Biryani%22.jpg/500px-%22Hyderabadi_Dum_Biryani%22.jpg",  // Biryani
    "Biscuit": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Loveless_Cafe_Biscuits.jpg/500px-Loveless_Cafe_Biscuits.jpg",  // Biscuit (bread)
    "Black Pudding": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Stornoway_Black_Pudding.jpg/500px-Stornoway_Black_Pudding.jpg",  // Black pudding
    "Blueberries": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Blueberries-In-Pack.jpg/500px-Blueberries-In-Pack.jpg",  // Blueberries-In-Pack.jpg
    "Boba Milk Tea": "https://upload.wikimedia.org/wikipedia/commons/a/a2/Bubble_Tea.png",  // Bubble tea
    "Bouillabaisse": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Bullabessa.jpg/500px-Bullabessa.jpg",  // Bouillabaisse
    "Bratwurst": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/German_Bratw%C3%BCrste.jpg/500px-German_Bratw%C3%BCrste.jpg",  // Bratwurst
    "Bread": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Korb_mit_Br%C3%B6tchen.JPG/500px-Korb_mit_Br%C3%B6tchen.JPG",  // Bread
    "Brigadeiro": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Brigadeiro.jpg/500px-Brigadeiro.jpg",  // Brigadeiro
    "Briouat": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Moroccan_food-02.jpg/500px-Moroccan_food-02.jpg",  // Briouat
    "Broccoli": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Basket_of_broccoli_in_Singapore_market.jpg/500px-Basket_of_broccoli_in_Singapore_market.jpg",  // Basket of broccoli in Singapore market.jpg
    "Brownie": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Chocolatebrownie.JPG/500px-Chocolatebrownie.JPG",  // Chocolate brownie
    "Bruschetta": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/2014_Bruschetta_The_Larder_Chiang_Mai.jpg/500px-2014_Bruschetta_The_Larder_Chiang_Mai.jpg",  // Bruschetta
    "Buffalo Wings": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Buffalo_wings-01.jpg/500px-Buffalo_wings-01.jpg",  // Buffalo wing
    "Bulgogi": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Bulgogi_2.jpg/500px-Bulgogi_2.jpg",  // Bulgogi
    "Bun Bo Hue": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/B%C3%BAn_b%C3%B2_Hu%E1%BA%BF_-_Ch%E1%BB%A3_%C4%90%C3%B4ng_Ba_%282024%29_-_img_02.jpg/500px-B%C3%BAn_b%C3%B2_Hu%E1%BA%BF_-_Ch%E1%BB%A3_%C4%90%C3%B4ng_Ba_%282024%29_-_img_02.jpg",  // Bún bò Huế
    "Bun Cha": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/B%C3%BAn_ch%E1%BA%A3_Vietnamese_food.jpg/500px-B%C3%BAn_ch%E1%BA%A3_Vietnamese_food.jpg",  // Bun cha
    "Bun Rieu": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/B%C3%BAn_ri%C3%AAu_%C4%91%E1%BA%B7c_bi%E1%BB%87t.jpg/500px-B%C3%BAn_ri%C3%AAu_%C4%91%E1%BA%B7c_bi%E1%BB%87t.jpg",  // Bún riêu
    "Burger": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/RedDot_Burger.jpg/500px-RedDot_Burger.jpg",  // Hamburger
    "Burrito": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Burrito.JPG/500px-Burrito.JPG",  // Burrito
    "Butter Chicken": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Butter_Chicken_%26_Butter_Naan_-_Home_-_Chandigarh_-_India_-_0006.jpg/500px-Butter_Chicken_%26_Butter_Naan_-_Home_-_Chandigarh_-_India_-_0006.jpg",  // Butter chicken
    "Calzone": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Wikimania_2016_Deryck_day_0_-_07_calzone.jpg/500px-Wikimania_2016_Deryck_day_0_-_07_calzone.jpg",  // Calzone
    "Cantaloupe": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Cucumis_melo_var._reticulatus_%28photo_by_Scott_Bauer%29.jpg/500px-Cucumis_melo_var._reticulatus_%28photo_by_Scott_Bauer%29.jpg",  // Cucumis melo var. reticulatus (photo by Scott Bauer).jpg
    "Cao Lau": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Cao_l%E1%BA%A7u_H%E1%BB%99i_An_%282024%29.jpg/500px-Cao_l%E1%BA%A7u_H%E1%BB%99i_An_%282024%29.jpg",  // Cao lầu
    "Carbonara": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Espaguetis_carbonara.jpg/500px-Espaguetis_carbonara.jpg",  // Carbonara
    "Carrot Cake": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Carrot_cake_at_America_Graffiti_%28cropped%29.jpg/500px-Carrot_cake_at_America_Graffiti_%28cropped%29.jpg",  // Carrot cake
    "Carrots": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Vegetable-Carrot-Bundle-wStalks.jpg/500px-Vegetable-Carrot-Bundle-wStalks.jpg",  // Carrot
    "Cassoulet": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Bowl_of_cassoulet.JPG/500px-Bowl_of_cassoulet.JPG",  // Cassoulet
    "Causa": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Causa_Rellena.jpg/500px-Causa_Rellena.jpg",  // Causa limeña
    "Cereal": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/NCI_Visuals_Food_Meal_Breakfast.jpg/500px-NCI_Visuals_Food_Meal_Breakfast.jpg",  // Breakfast cereal
    "Ceviche": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Cebiche_de_corvina.JPG/500px-Cebiche_de_corvina.JPG",  // Ceviche
    "Cha Ca": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Ch%E1%BA%A3_c%C3%A1_L%C3%A3_V%E1%BB%8Dng_H%C3%A0_N%E1%BB%99i.jpg/500px-Ch%E1%BA%A3_c%C3%A1_L%C3%A3_V%E1%BB%8Dng_H%C3%A0_N%E1%BB%99i.jpg",  // Chả cá Lã Vọng
    "Chaat": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Dahi_puri%2C_Doi_phuchka.jpg/500px-Dahi_puri%2C_Doi_phuchka.jpg",  // Chaat
    "Chai": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Chai_In_Sakora.jpg/500px-Chai_In_Sakora.jpg",  // Masala chai
    "Char Siu": "https://upload.wikimedia.org/wikipedia/commons/9/95/Charsiu.jpg",  // Char siu
    "Chawanmushi": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Chawan-mushi.JPG/500px-Chawan-mushi.JPG",  // Chawanmushi
    "Chebakia": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Chebakia.jpg/500px-Chebakia.jpg",  // Shebakia
    "Cheese": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Cheese_platter.jpg/500px-Cheese_platter.jpg",  // Cheese
    "Cheeseburger": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Cheeseburger.jpg/500px-Cheeseburger.jpg",  // Cheeseburger
    "Cheesecake": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Baked_cheesecake_with_raspberries_and_blueberries.jpg/500px-Baked_cheesecake_with_raspberries_and_blueberries.jpg",  // Cheesecake
    "Cherries": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Cherry_season_%2848216568227%29.jpg/500px-Cherry_season_%2848216568227%29.jpg",  // Cherry
    "Chicharron": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/El_Coyote_Market_%26_Deli_-_February_2023_-_Sarah_Stierch_02.jpg/500px-El_Coyote_Market_%26_Deli_-_February_2023_-_Sarah_Stierch_02.jpg",  // Chicharrón
    "Chicken": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Max%27s_Roasted_Chicken_-_Evan_Swigart.jpg/500px-Max%27s_Roasted_Chicken_-_Evan_Swigart.jpg",  // Roast chicken
    "Chicken Fried Steak": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Chicken_Fried_Steak.jpg/500px-Chicken_Fried_Steak.jpg",  // Chicken-fried steak
    "Chicken Noodle Soup": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Chicken_Noodle_Soup.jpg/500px-Chicken_Noodle_Soup.jpg",  // Chicken soup
    "Chicken Nuggets": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Chicken_Nuggets.jpg/500px-Chicken_Nuggets.jpg",  // Chicken nugget
    "Chicken Tikka Masala": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Chicken_tikka_masala_%28cropped%29.jpg/500px-Chicken_tikka_masala_%28cropped%29.jpg",  // Chicken tikka masala
    "Chicken Wings": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Buffalo_wings-01.jpg/500px-Buffalo_wings-01.jpg",  // Buffalo wing
    "Chilaquiles": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Chilaquiles_at_the_Grand_Cantina%2C_Windsor%2C_Ontario%2C_2025-09-01_04.jpg/500px-Chilaquiles_at_the_Grand_Cantina%2C_Windsor%2C_Ontario%2C_2025-09-01_04.jpg",  // Chilaquiles
    "Chili": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Bowl_of_chili.jpg/500px-Bowl_of_chili.jpg",  // Chili con carne
    "Chocolate": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Three_Bars_%281%29.jpg/500px-Three_Bars_%281%29.jpg",  // Chocolate
    "Chocolate Cake": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Chocolate_fudge_cake.jpg/500px-Chocolate_fudge_cake.jpg",  // Chocolate cake
    "Chole Bhature": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Chole_Bhature_from_Nagpur.JPG/500px-Chole_Bhature_from_Nagpur.JPG",  // Chole bhature
    "Chow Mein": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Homemade_Chow_mein_with_shrimps_and_meat_with_a_choy_and_Choung.jpg/500px-Homemade_Chow_mein_with_shrimps_and_meat_with_a_choy_and_Choung.jpg",  // Chow mein
    "Churros": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Chocolate_con_churros_%2827343655726%29.jpg/500px-Chocolate_con_churros_%2827343655726%29.jpg",  // Churro
    "Cinnamon Roll": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Cinnamon_roll_in_Stockholm.jpg/500px-Cinnamon_roll_in_Stockholm.jpg",  // Cinnamon roll
    "Clam Chowder": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Quail_07_bg_041506.jpg/500px-Quail_07_bg_041506.jpg",  // Clam chowder
    "Cobb Salad": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Cobb_salad%2C_15_October_2010.jpg/500px-Cobb_salad%2C_15_October_2010.jpg",  // Cobb salad
    "Coconut": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Young_Coconut_Drink.jpg/500px-Young_Coconut_Drink.jpg",  // Coconut water
    "Coffee": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Latte_and_dark_coffee.jpg/500px-Latte_and_dark_coffee.jpg",  // Coffee
    "Coleslaw": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/2015-12-20_Spitzkohlsalat_mit_M%C3%B6hren_anagoria.JPG/500px-2015-12-20_Spitzkohlsalat_mit_M%C3%B6hren_anagoria.JPG",  // Coleslaw
    "Com Tam": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/C%C6%A1m_T%E1%BA%A5m%2C_Da_Nang%2C_Vietnam.jpg/500px-C%C6%A1m_T%E1%BA%A5m%2C_Da_Nang%2C_Vietnam.jpg",  // Cơm tấm
    "Congee": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Chinese_rice_congee.jpg/500px-Chinese_rice_congee.jpg",  // Congee
    "Cookies": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Choco_chip_cookie.png/500px-Choco_chip_cookie.png",  // Cookie
    "Coq au Vin": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Gourmet_coq_au_vin.jpg/500px-Gourmet_coq_au_vin.jpg",  // Coq au vin
    "Corn Dog": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Corn_dog_001.jpg/500px-Corn_dog_001.jpg",  // Corn dog 001.jpg
    "Corn on the Cob": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/CookedCornOnTheCob.JPG/500px-CookedCornOnTheCob.JPG",  // Corn on the cob
    "Cornish Pasty": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Cornish_Pasty_%28cropped%29.jpeg/500px-Cornish_Pasty_%28cropped%29.jpeg",  // Pasty
    "Cotton Candy": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Cotton_candy_%CE%9C%CE%B1%CE%BB%CE%BB%CE%AF_%CF%84%CE%B7%CF%82_%CE%B3%CF%81%CE%B9%CE%AC%CF%82.JPG/500px-Cotton_candy_%CE%9C%CE%B1%CE%BB%CE%BB%CE%AF_%CF%84%CE%B7%CF%82_%CE%B3%CF%81%CE%B9%CE%AC%CF%82.JPG",  // Cotton candy
    "Couscous": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Moroccan_cuscus%2C_from_Casablanca%2C_September_2018.jpg/500px-Moroccan_cuscus%2C_from_Casablanca%2C_September_2018.jpg",  // Couscous
    "Coxinha": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/%282014-11-22%29_La_Donosti_-_Agudos_-_Coxinha_de_Leitoa_Romerito_Pontes_%2815870107515%29.jpg/500px-%282014-11-22%29_La_Donosti_-_Agudos_-_Coxinha_de_Leitoa_Romerito_Pontes_%2815870107515%29.jpg",  // Coxinha
    "Crab": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Ristet_br%C3%B8d_med_krabbekl%C3%B8er_%284898535215%29.jpg/500px-Ristet_br%C3%B8d_med_krabbekl%C3%B8er_%284898535215%29.jpg",  // Crab meat
    "Crackers": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Crackers_with_herring_and_garlic_sauce.jpg/500px-Crackers_with_herring_and_garlic_sauce.jpg",  // Cracker (food)
    "Creme Brulee": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/2014_0531_Cr%C3%A8me_br%C3%BBl%C3%A9e_Doi_Mae_Salong_%28cropped%29.jpg/500px-2014_0531_Cr%C3%A8me_br%C3%BBl%C3%A9e_Doi_Mae_Salong_%28cropped%29.jpg",  // Crème brûlée
    "Crepes": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Crepes_dsc07085.jpg/500px-Crepes_dsc07085.jpg",  // Crêpe
    "Croissant": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Croissant-Petr_Kratochvil.jpg/500px-Croissant-Petr_Kratochvil.jpg",  // Croissant
    "Croque Monsieur": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Croque_monsieur.jpg/500px-Croque_monsieur.jpg",  // Croque monsieur
    "Croquetas": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Croquetas_Caseras_%287068664101%29.jpg/500px-Croquetas_Caseras_%287068664101%29.jpg",  // Croquette
    "Crème Brûlée": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/2014_0531_Cr%C3%A8me_br%C3%BBl%C3%A9e_Doi_Mae_Salong_%28cropped%29.jpg/500px-2014_0531_Cr%C3%A8me_br%C3%BBl%C3%A9e_Doi_Mae_Salong_%28cropped%29.jpg",  // Crème brûlée
    "Cucumber": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Board%2C_knife_and_cucumbers.JPG/500px-Board%2C_knife_and_cucumbers.JPG",  // Board, knife and cucumbers.JPG
    "Cupcake": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Cupcakes%2C_chocolate_and_strawberry_flavour.jpg/500px-Cupcakes%2C_chocolate_and_strawberry_flavour.jpg",  // Cupcake
    "Curry": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Taj_Mahal_-_Lamb_Curry_Madras.jpg/500px-Taj_Mahal_-_Lamb_Curry_Madras.jpg",  // Curry
    "Currywurst": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/20220430_currywurst.jpg/500px-20220430_currywurst.jpg",  // Currywurst
    "Dabo Kolo": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/ASC_Leiden_-_Dabo_kolo_-_%22Elsa_kolo_Yegbes_Kolo_Belewez%22_-_A_bowl_of_bread_chunks_with_packaging%2C_Leiden_2022.jpg/500px-ASC_Leiden_-_Dabo_kolo_-_%22Elsa_kolo_Yegbes_Kolo_Belewez%22_-_A_bowl_of_bread_chunks_with_packaging%2C_Leiden_2022.jpg",  // Dabo kolo
    "Dan Dan Noodles": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Dan-dan_noodles%2C_Shanghai.jpg/500px-Dan-dan_noodles%2C_Shanghai.jpg",  // Dandan noodles
    "Dim Sum": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Chinese_DimSum_%289023590541%29.jpg/500px-Chinese_DimSum_%289023590541%29.jpg",  // Dim sum
    "Dolmades": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Speca_te_mbushura_me_mish.JPG/500px-Speca_te_mbushura_me_mish.JPG",  // Dolma
    "Donut": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Glazed-Donut.jpg/500px-Glazed-Donut.jpg",  // Doughnut
    "Doro Wat": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Ethiopian_wat.jpg/500px-Ethiopian_wat.jpg",  // Wat (food)
    "Dosa": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Dosa_at_Sri_Ganesha_Restauran%2C_Bangkok_%2844570742744%29.jpg/500px-Dosa_at_Sri_Ganesha_Restauran%2C_Bangkok_%2844570742744%29.jpg",  // Dosa (food)
    "Duck": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/And_%2824559569447%29.jpg/500px-And_%2824559569447%29.jpg",  // Duck as food
    "Duck Confit": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Confitdecanard.jpg/500px-Confitdecanard.jpg",  // Duck confit
    "Dumplings": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/HK_SYP_%E8%A5%BF%E7%87%9F%E7%9B%A4_Sai_Ying_Pun_Kwan_Yick_Building_%E5%90%8D%E6%98%9F%E6%B5%B7%E9%AE%AE%E9%85%92%E5%AE%B6_Star_Seafood_Restaurant_food_%E5%90%9E%E9%BA%B5_Wonton_dim_sum_October_2020_SS2_01.jpg/500px-HK_SYP_%E8%A5%BF%E7%87%9F%E7%9B%A4_Sai_Ying_Pun_Kwan_Yick_Building_%E5%90%8D%E6%98%9F%E6%B5%B7%E9%AE%AE%E9%85%92%E5%AE%B6_Star_Seafood_Restaurant_food_%E5%90%9E%E9%BA%B5_Wonton_dim_sum_October_2020_SS2_01.jpg",  // Dumpling
    "Egg Rolls": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/CookbookEggrollTongs.jpg/500px-CookbookEggrollTongs.jpg",  // Egg roll
    "Elote": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/CookedCornOnTheCob.JPG/500px-CookedCornOnTheCob.JPG",  // Corn on the cob
    "Enchiladas": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Enchilada_Rice_Beans.jpg/500px-Enchilada_Rice_Beans.jpg",  // Enchilada
    "Escargot": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Caracoles-del-restaurante-granero.jpg/500px-Caracoles-del-restaurante-granero.jpg",  // Snails as food
    "Espresso": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Tazzina_di_caff%C3%A8_a_Ventimiglia.jpg/500px-Tazzina_di_caff%C3%A8_a_Ventimiglia.jpg",  // Espresso
    "Esquites": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Esquites_%281%29.jpg/500px-Esquites_%281%29.jpg",  // Esquites
    "Eton Mess": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Eton_Mess_2025-2.jpg/500px-Eton_Mess_2025-2.jpg",  // Eton mess
    "Fabada": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Fabada_en_cazuela_de_barro.jpg/500px-Fabada_en_cazuela_de_barro.jpg",  // Fabada asturiana
    "Fajitas": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Chicken_fajita_platter%2C_Lone_Star_Texas_Grill%2C_Windsor%2C_Ontario%2C_2025-06-14_03.jpg/500px-Chicken_fajita_platter%2C_Lone_Star_Texas_Grill%2C_Windsor%2C_Ontario%2C_2025-06-14_03.jpg",  // Fajita
    "Falafel": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Falafels_2.jpg/500px-Falafels_2.jpg",  // Falafel
    "Farofa": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Farofa_brazil.jpg/500px-Farofa_brazil.jpg",  // Farofa
    "Fattoush": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Fattoush_mixed-salad.jpg/500px-Fattoush_mixed-salad.jpg",  // Fattoush
    "Feijoada": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Feijoada_%C3%A0_transmontada.jpg/500px-Feijoada_%C3%A0_transmontada.jpg",  // Feijoada
    "Fettuccine Alfredo": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/The_Only_Original_Alfredo_Sauce_with_Butter_and_Parmesano-Reggiano_Cheese.png/500px-The_Only_Original_Alfredo_Sauce_with_Butter_and_Parmesano-Reggiano_Cheese.png",  // Fettuccine Alfredo
    "Fir Fir": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Taita_fit-fit.jpg/500px-Taita_fit-fit.jpg",  // Fit-fit
    "Fish and Chips": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Fish_and_chips_blackpool.jpg/500px-Fish_and_chips_blackpool.jpg",  // Fish and chips
    "Flan": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Cremecaramel.jpg/500px-Cremecaramel.jpg",  // Crème caramel
    "Focaccia": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Focaccia_with_Crumb.jpg/500px-Focaccia_with_Crumb.jpg",  // Focaccia
    "French Fries": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/French_Fries.JPG/500px-French_Fries.JPG",  // French fries
    "French Toast": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/FrenchToast.JPG/500px-FrenchToast.JPG",  // French toast
    "Fried Chicken": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Fried-Chicken-Set.jpg/500px-Fried-Chicken-Set.jpg",  // Fried chicken
    "Fried Rice": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Koh_Mak%2C_Thailand%2C_Fried_rice_with_seafood%2C_Thai_fried_rice.jpg/500px-Koh_Mak%2C_Thailand%2C_Fried_rice_with_seafood%2C_Thai_fried_rice.jpg",  // Fried rice
    "Full English Breakfast": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Full_English_breakfast_%28cropped%29.jpg/500px-Full_English_breakfast_%28cropped%29.jpg",  // Full breakfast
    "Gambas al Ajillo": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Gambas_al_ajillo_en_madrid.jpg/500px-Gambas_al_ajillo_en_madrid.jpg",  // Al ajillo
    "Garlic Bread": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Garlicbread.jpg/500px-Garlicbread.jpg",  // Garlic bread
    "Gazpacho": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Gazpacho_Malague%C3%B1o_con_su_%E2%80%9Cpica%C3%ADto%E2%80%9D_-_Moreno%2C_Playa_Burriana_%28cropped%29.jpg/500px-Gazpacho_Malague%C3%B1o_con_su_%E2%80%9Cpica%C3%ADto%E2%80%9D_-_Moreno%2C_Playa_Burriana_%28cropped%29.jpg",  // Gazpacho
    "Genfo": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Ga%27at_food.jpg/500px-Ga%27at_food.jpg",  // Genfo
    "Gimbap": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Gimbap_%28pixabay%29.jpg/500px-Gimbap_%28pixabay%29.jpg",  // Gimbap
    "Gnocchi": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Gnocchi_di_ricotta_burro_e_salvia.jpg/500px-Gnocchi_di_ricotta_burro_e_salvia.jpg",  // Gnocchi
    "Goi Cuon": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Homemade_spring_rolls_%287010969349%29.jpg/500px-Homemade_spring_rolls_%287010969349%29.jpg",  // Gỏi cuốn
    "Gored Gored": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Gored_gored_plate%2C_July_2019.jpg/500px-Gored_gored_plate%2C_July_2019.jpg",  // Gored gored
    "Granola": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Granola%2C_yogurt%2C_fruit._%2816696981528%29.jpg/500px-Granola%2C_yogurt%2C_fruit._%2816696981528%29.jpg",  // Granola
    "Grapes": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Grapes%2C_Rostov-on-Don%2C_Russia.jpg/500px-Grapes%2C_Rostov-on-Don%2C_Russia.jpg",  // Grape
    "Green Beans": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Green_beans_169clue.jpg/500px-Green_beans_169clue.jpg",  // Green beans 169clue.jpg
    "Green Curry": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Thai_green_chicken_curry_and_roti.jpg/500px-Thai_green_chicken_curry_and_roti.jpg",  // Green curry
    "Grilled Cheese": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Classic_Grilled_Cheese_Sandwich_%2825791331763%29_%28cropped%29.jpg/500px-Classic_Grilled_Cheese_Sandwich_%2825791331763%29_%28cropped%29.jpg",  // Grilled cheese
    "Guacamole": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Guacamole_IMGP1271.jpg/500px-Guacamole_IMGP1271.jpg",  // Guacamole
    "Gyro": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Pita_giros.JPG/500px-Pita_giros.JPG",  // Gyros
    "Halo-Halo": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Halo-Halo.jpg/500px-Halo-Halo.jpg",  // Halo-halo
    "Harcha": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Ary-7ercha.JPG/500px-Ary-7ercha.JPG",  // Harcha
    "Harira": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Harira.png/500px-Harira.png",  // Harira
    "Hash Browns": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Mmm..._sliders_and_deep_fried_hash_browns_%287958927842%29.jpg/500px-Mmm..._sliders_and_deep_fried_hash_browns_%287958927842%29.jpg",  // Hash browns
    "Himbasha": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Himbasha.jpg/500px-Himbasha.jpg",  // Himbasha
    "Honey": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Runny_hunny.jpg/500px-Runny_hunny.jpg",  // Honey
    "Horiatiki Salad": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Greece_Food_Horiatiki.JPG/500px-Greece_Food_Horiatiki.JPG",  // Greek salad
    "Hot Chocolate": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/After_The_St._Patrick%27s_Parade_Late_Lunch_%40_Lemon%2C_Dawson_Street%2C_Dublin%2C_Rep._Of_Ireland_A_Fine_Tradition%21_%286992614913%29.jpg/500px-After_The_St._Patrick%27s_Parade_Late_Lunch_%40_Lemon%2C_Dawson_Street%2C_Dublin%2C_Rep._Of_Ireland_A_Fine_Tradition%21_%286992614913%29.jpg",  // Hot chocolate
    "Hot Dog": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Hot_dog_with_mustard.png/500px-Hot_dog_with_mustard.png",  // Hot dog
    "Hot Pot": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Hot_Pot.jpg/500px-Hot_Pot.jpg",  // Hot pot
    "Hu Tieu": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Hu_Tieu_Nam_Vang.jpg/500px-Hu_Tieu_Nam_Vang.jpg",  // Hủ tiếu
    "Hummus": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Lebanese_style_hummus.jpg/500px-Lebanese_style_hummus.jpg",  // Hummus
    "Ice Cream": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Ice_cream_with_whipped_cream%2C_chocolate_syrup%2C_and_a_wafer_%28cropped%29.jpg/500px-Ice_cream_with_whipped_cream%2C_chocolate_syrup%2C_and_a_wafer_%28cropped%29.jpg",  // Ice cream
    "Iced Tea": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Iced_Tea_from_flickr.jpg/500px-Iced_Tea_from_flickr.jpg",  // Iced tea
    "Idli": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Idli_Sambar.JPG/500px-Idli_Sambar.JPG",  // Idli
    "Injera": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Injera_with_eight_kinds_of_stew.jpg/500px-Injera_with_eight_kinds_of_stew.jpg",  // Injera
    "Jam": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Fruits_jam_variants.jpg/500px-Fruits_jam_variants.jpg",  // Fruit preserves
    "Jamon Iberico": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Jamon_iberico_de_bellota_2_%28cinco_jotas%29.jpg/500px-Jamon_iberico_de_bellota_2_%28cinco_jotas%29.jpg",  // Jamón ibérico
    "Japchae": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Polish_Korean_Cuisine_and_Culture_Exchanges_Gradmother%E2%80%99s_Recipes_05.jpg/500px-Polish_Korean_Cuisine_and_Culture_Exchanges_Gradmother%E2%80%99s_Recipes_05.jpg",  // Japchae
    "Jello": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/2019-10-10_22_15_43_Gelatin_from_a_single_opened_cup_of_Jell-O_strawberry_gelatin_snack_being_lifted_by_a_spoon_in_the_Franklin_Farm_section_of_Oak_Hill%2C_Fairfax_County%2C_Virginia.jpg/500px-thumbnail.jpg",  // Jell-O
    "Jjajangmyeon": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Jajangmyeon.jpg/500px-Jajangmyeon.jpg",  // Jajangmyeon
    "Kafta": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Koofteh_tabrizi.jpg/500px-Koofteh_tabrizi.jpg",  // Kofta
    "Kare-Kare": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Mac_MG_5939.jpg/500px-Mac_MG_5939.jpg",  // Kare-kare
    "Kasespatzle": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Berggasthof_Haldenhof_-_K%C3%A4skn%C3%B6pfle_%281%29.jpg/500px-Berggasthof_Haldenhof_-_K%C3%A4skn%C3%B6pfle_%281%29.jpg",  // Käsespätzle
    "Katsu Curry": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/%E3%81%A8%E3%82%93%E3%81%8B%E3%82%89%E4%BA%AD_%E6%AD%A6%E8%94%B5%E9%87%8E%E3%83%96%E3%83%A9%E3%83%83%E3%82%AF%E3%81%8B%E3%81%A4%E3%82%AB%E3%83%AC%E3%83%BC_-_1.jpg/500px-%E3%81%A8%E3%82%93%E3%81%8B%E3%82%89%E4%BA%AD_%E6%AD%A6%E8%94%B5%E9%87%8E%E3%83%96%E3%83%A9%E3%83%83%E3%82%AF%E3%81%8B%E3%81%A4%E3%82%AB%E3%83%AC%E3%83%BC_-_1.jpg",  // Katsu curry
    "Kebab": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Lula_kebab_2.jpg/500px-Lula_kebab_2.jpg",  // Kebab
    "Key Lime Pie": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Slice_of_Key_Lime_Pie.jpg/500px-Slice_of_Key_Lime_Pie.jpg",  // Key lime pie
    "Khao Soi": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Khao_Soi_Northern_Thai_food_%E0%B8%82%E0%B9%89%E0%B8%B2%E0%B8%A7%E0%B8%8B%E0%B8%AD%E0%B8%A2_%E0%B8%9C%E0%B8%B1%E0%B8%81%E0%B8%94%E0%B8%AD%E0%B8%87.jpg/500px-Khao_Soi_Northern_Thai_food_%E0%B8%82%E0%B9%89%E0%B8%B2%E0%B8%A7%E0%B8%8B%E0%B8%AD%E0%B8%A2_%E0%B8%9C%E0%B8%B1%E0%B8%81%E0%B8%94%E0%B8%AD%E0%B8%87.jpg",  // Khao soi
    "Kibbeh": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Kibbeh3.jpg/500px-Kibbeh3.jpg",  // Kibbeh
    "Kimchi": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Korean_Gimchi01.jpg/500px-Korean_Gimchi01.jpg",  // Baechu-kimchi
    "Kimchi Jjigae": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Korean_stew_dish_-_Kimchi-jjigae_Kimchi_Stew_2019_%2801%29.jpg/500px-Korean_stew_dish_-_Kimchi-jjigae_Kimchi_Stew_2019_%2801%29.jpg",  // Kimchi-jjigae
    "Kitfo": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Kitfo_with_Ayibe..JPG/500px-Kitfo_with_Ayibe..JPG",  // Kitfo
    "Kiwi": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Kiwi_%28Actinidia_chinensis%29_1_Luc_Viatour.jpg/500px-Kiwi_%28Actinidia_chinensis%29_1_Luc_Viatour.jpg",  // Kiwi (Actinidia chinensis) 1 Luc Viatour.jpg
    "Kleftiko": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Kleftiko.JPG/500px-Kleftiko.JPG",  // Kleftiko
    "Knafeh": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/K%C3%BCnefe.jpg/500px-K%C3%BCnefe.jpg",  // Knafeh
    "Kocho": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Chefuye_in_meskel.jpg/500px-Chefuye_in_meskel.jpg",  // Kocho (food)
    "Kung Pao Chicken": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Kung-pao-shanghai.jpg/500px-Kung-pao-shanghai.jpg",  // Kung Pao chicken
    "Lamb": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Kleftiko_-_Brunswick_Centre_-_London_2026-06-04.jpg/500px-Kleftiko_-_Brunswick_Centre_-_London_2026-06-04.jpg",  // Kleftiko - Brunswick Centre - London 2026-06-04.jpg
    "Larb": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/LaoFood_LarbNeua.JPG/500px-LaoFood_LarbNeua.JPG",  // Larb
    "Lasagna": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Lasagne_-_stonesoup.jpg/500px-Lasagne_-_stonesoup.jpg",  // Lasagna
    "Leberkase": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Leberk%C3%A4se-1.jpg/500px-Leberk%C3%A4se-1.jpg",  // Leberkäse
    "Lechon": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Cochinillos-Mercado_de_la_Cebada.jpg/500px-Cochinillos-Mercado_de_la_Cebada.jpg",  // Suckling pig
    "Lemon": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Lemon-Whole-Split.jpg/500px-Lemon-Whole-Split.jpg",  // Lemon-Whole-Split.jpg
    "Lemonade": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Lemonade_-_27682817724.jpg/500px-Lemonade_-_27682817724.jpg",  // Lemonade
    "Lime": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Lime-Whole-Split.jpg/500px-Lime-Whole-Split.jpg",  // Lime-Whole-Split.jpg
    "Lobster": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Lobster_Thermidor_entree.jpg/500px-Lobster_Thermidor_entree.jpg",  // Lobster Thermidor
    "Lollipop": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Farbenfrohe_Lollipops%2C_Austria.jpg/500px-Farbenfrohe_Lollipops%2C_Austria.jpg",  // Lollipop
    "Lomo Saltado": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Lomo_Saltado_-_Lima%2C_Peru_Miraflores_%28Tiendecita_Blanca%29.jpg/500px-Lomo_Saltado_-_Lima%2C_Peru_Miraflores_%28Tiendecita_Blanca%29.jpg",  // Lomo saltado
    "Lumpia": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Loenpia_Semarang.JPG/500px-Loenpia_Semarang.JPG",  // Lumpia
    "Mac and Cheese": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Original_Mac_n_Cheese_.jpg/500px-Original_Mac_n_Cheese_.jpg",  // Macaroni and cheese
    "Macaron": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/VanillaMacaron.jpg/500px-VanillaMacaron.jpg",  // Macaron
    "Macaroni and Cheese": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Original_Mac_n_Cheese_.jpg/500px-Original_Mac_n_Cheese_.jpg",  // Macaroni and cheese
    "Manakish": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Zaatar_Mankousheh.jpg/500px-Zaatar_Mankousheh.jpg",  // Manakish
    "Mandu": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/%EB%A7%8C%EB%91%90.jpg/500px-%EB%A7%8C%EB%91%90.jpg",  // Mandu (food)
    "Mango": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Mangos_-_single_and_halved.jpg/500px-Mangos_-_single_and_halved.jpg",  // Mango
    "Mango Sticky Rice": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Mango_sticy_rice_%283859549574%29.jpg/500px-Mango_sticy_rice_%283859549574%29.jpg",  // Mango sticky rice
    "Mapo Tofu": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Chen_Mapo_Tofu.jpg/500px-Chen_Mapo_Tofu.jpg",  // Mapo tofu
    "Marshmallow": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/White_Marshmallows.jpg/500px-White_Marshmallows.jpg",  // Marshmallow
    "Mashed Potatoes": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Sous_vide_mashed_potatoes.jpg/500px-Sous_vide_mashed_potatoes.jpg",  // Mashed potato
    "Massaman Curry": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Kaeng_matsaman_kai.JPG/500px-Kaeng_matsaman_kai.JPG",  // Massaman curry
    "Matcha": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Matcha_Scoop.jpg/500px-Matcha_Scoop.jpg",  // Matcha
    "Maultaschen": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Maultaschensuppe.jpg/500px-Maultaschensuppe.jpg",  // Maultasche
    "Meatballs": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Soup_with_meatballs-01.jpg/500px-Soup_with_meatballs-01.jpg",  // Meatball
    "Meatloaf": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/MeatloafWithSauce.jpg/500px-MeatloafWithSauce.jpg",  // Meatloaf
    "Mechoui": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Mechoui.jpg/500px-Mechoui.jpg",  // Méchoui
    "Mi Quang": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/M%C3%AC_Qu%E1%BA%A3ng%2C_Da_Nang%2C_Vietnam.jpg/500px-M%C3%AC_Qu%E1%BA%A3ng%2C_Da_Nang%2C_Vietnam.jpg",  // Mì Quảng
    "Milk": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Glass_of_Milk_%2833657535532%29.jpg/500px-Glass_of_Milk_%2833657535532%29.jpg",  // Milk
    "Milkshake": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Strawberry_milk_shake_%28cropped%29.jpg/500px-Strawberry_milk_shake_%28cropped%29.jpg",  // Milkshake
    "Minestrone": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Minestrone_soup_%285%29.jpg/500px-Minestrone_soup_%285%29.jpg",  // Minestrone
    "Miso Soup": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Miso_Soup_001.jpg/500px-Miso_Soup_001.jpg",  // Miso soup
    "Mochi": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Daifuku_1.jpg/500px-Daifuku_1.jpg",  // Daifuku
    "Mole Poblano": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/ChickRedMole.JPG/500px-ChickRedMole.JPG",  // Mole (sauce)
    "Moqueca": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Moqueca.jpg/500px-Moqueca.jpg",  // Moqueca
    "Moussaka": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/MussakasMeMelitsanesKePatates01.JPG/500px-MussakasMeMelitsanesKePatates01.JPG",  // Moussaka
    "Mozzarella Sticks": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Fried_Mozzarella_Sticks_at_Millers_Pub_%28301456962%29.jpg/500px-Fried_Mozzarella_Sticks_at_Millers_Pub_%28301456962%29.jpg",  // Mozzarella sticks
    "Msemen": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/%D9%85%D8%B3%D9%85%D9%86.jpg/500px-%D9%85%D8%B3%D9%85%D9%86.jpg",  // Msemmen
    "Muffin": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/%28301-365%29_Muffin_%286100678703%29.jpg/500px-%28301-365%29_Muffin_%286100678703%29.jpg",  // (301-365) Muffin (6100678703).jpg
    "Mujadara": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Mujaddara.jpg/500px-Mujaddara.jpg",  // Mujaddara
    "Mushrooms": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Edible_fungi_in_basket_2009_G1_%28cropped%29.jpg/500px-Edible_fungi_in_basket_2009_G1_%28cropped%29.jpg",  // Edible mushroom
    "Naan": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Annapurna_Naan.jpg/500px-Annapurna_Naan.jpg",  // Naan
    "Nachos": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Nachos-cheese.jpg/500px-Nachos-cheese.jpg",  // Nachos
    "Oatmeal": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Oatmeal_%281%29.jpg/500px-Oatmeal_%281%29.jpg",  // Porridge
    "Okonomiyaki": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Okonomiyaki_001.jpg/500px-Okonomiyaki_001.jpg",  // Okonomiyaki
    "Olives": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Gr%C3%BCne_Oliven.jpg/500px-Gr%C3%BCne_Oliven.jpg",  // Grüne Oliven.jpg
    "Omelette": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Gorgonzola_%2B_Bacon_Omelette_%40_Omelegg_%40_Amsterdam_%2816600947041%29.jpg/500px-Gorgonzola_%2B_Bacon_Omelette_%40_Omelegg_%40_Amsterdam_%2816600947041%29.jpg",  // Omelette
    "Onigiri": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/%E5%B0%8F%E6%96%99%E7%90%86%E3%83%90%E3%83%AB%E3%81%95%E3%81%8F%E3%82%89_%E7%89%B9%E8%A3%BD%E3%81%8A%E3%81%AB%E3%81%8E%E3%82%8A.jpg/500px-%E5%B0%8F%E6%96%99%E7%90%86%E3%83%90%E3%83%AB%E3%81%95%E3%81%8F%E3%82%89_%E7%89%B9%E8%A3%BD%E3%81%8A%E3%81%AB%E3%81%8E%E3%82%8A.jpg",  // Onigiri
    "Onion": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Mixed_onions.jpg/500px-Mixed_onions.jpg",  // Onion
    "Onion Rings": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/OnionRings.JPG/500px-OnionRings.JPG",  // Onion ring
    "Orange": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Oranges_-_whole-halved-segment.jpg/500px-Oranges_-_whole-halved-segment.jpg",  // Orange (fruit)
    "Orange Chicken": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Flickr_preppybyday_4786746354--Orange_chicken.jpg/500px-Flickr_preppybyday_4786746354--Orange_chicken.jpg",  // Orange chicken
    "Orange Juice": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Orangejuice.jpg/500px-Orangejuice.jpg",  // Orange juice
    "Osso Buco": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Ossobuco.jpg/500px-Ossobuco.jpg",  // Ossobuco
    "Pad Kra Pao": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Basil_fried_crispy_pork_with_rice_-_Chiang_Mai_-_2017-07-11_%28002%29.jpg/500px-Basil_fried_crispy_pork_with_rice_-_Chiang_Mai_-_2017-07-11_%28002%29.jpg",  // Phat kaphrao
    "Pad See Ew": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Pad_see_ew.jpg/500px-Pad_see_ew.jpg",  // Pad see ew
    "Pad Thai": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Phat_Thai_kung_Chang_Khien_street_stall.jpg/500px-Phat_Thai_kung_Chang_Khien_street_stall.jpg",  // Pad thai
    "Paella": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/01_Paella_Valenciana_original.jpg/500px-01_Paella_Valenciana_original.jpg",  // Paella
    "Palak Paneer": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Palakpaneer_Rayagada_Odisha_0009.jpg/500px-Palakpaneer_Rayagada_Odisha_0009.jpg",  // Palak paneer
    "Pancakes": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Foodiesfeed.com_pouring-honey-on-pancakes-with-walnuts.jpg/500px-Foodiesfeed.com_pouring-honey-on-pancakes-with-walnuts.jpg",  // Pancake
    "Pancit": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Pancit_Ilonggo_Style_-_12110747826.jpg/500px-Pancit_Ilonggo_Style_-_12110747826.jpg",  // Pancit
    "Panini": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Panini_%28Mozzarella%2C_Pesto_%26_Tomato%29_-_Dyke_Road_Park_Cafe.jpg/500px-Panini_%28Mozzarella%2C_Pesto_%26_Tomato%29_-_Dyke_Road_Park_Cafe.jpg",  // Panini (Mozzarella, Pesto & Tomato) - Dyke Road Park Cafe.jpg
    "Panna Cotta": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Panna_Cotta_with_cream_and_garnish.jpg/500px-Panna_Cotta_with_cream_and_garnish.jpg",  // Panna cotta
    "Pao de Queijo": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Cheesebread.jpg/500px-Cheesebread.jpg",  // Pão de queijo
    "Papa a la Huancaina": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Papa_a_la_huancaina.jpg/500px-Papa_a_la_huancaina.jpg",  // Papa a la huancaína
    "Pasta": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/%28Pasta%29_by_David_Adam_Kess_%28pic.2%29.jpg/500px-%28Pasta%29_by_David_Adam_Kess_%28pic.2%29.jpg",  // Pasta
    "Pastel": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Brazilian_pastel.jpg/500px-Brazilian_pastel.jpg",  // Pastel (Brazilian food)
    "Pastitsio": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Pastitsio_homemade.jpg/500px-Pastitsio_homemade.jpg",  // Pastitsio
    "Patatas Bravas": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Patatas_bravas_madrid.jpg/500px-Patatas_bravas_madrid.jpg",  // Patatas bravas
    "Peach": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/White-Peaches-Bunch.jpg/500px-White-Peaches-Bunch.jpg",  // White-Peaches-Bunch.jpg
    "Peanut Butter": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/2020-03-24_20_57_22_An_open_jar_of_Skippy_Creamy_Peanut_Butter_in_the_Dulles_section_of_Sterling%2C_Loudoun_County%2C_Virginia.jpg/500px-2020-03-24_20_57_22_An_open_jar_of_Skippy_Creamy_Peanut_Butter_in_the_Dulles_section_of_Sterling%2C_Loudoun_County%2C_Virginia.jpg",  // Peanut butter
    "Peanuts": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Roasted_Peanuts_with_shell.jpg/500px-Roasted_Peanuts_with_shell.jpg",  // Roasted Peanuts with shell.jpg
    "Pear": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Assortment_of_pears.jpg/500px-Assortment_of_pears.jpg",  // Assortment of pears.jpg
    "Pecan Pie": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Pecan_pie%2C_November_2010.jpg/500px-Pecan_pie%2C_November_2010.jpg",  // Pecan pie
    "Peking Duck": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Peking_Duck%2C_2014_%2802%29.jpg/500px-Peking_Duck%2C_2014_%2802%29.jpg",  // Peking duck
    "Pesto Pasta": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Pasta_with_pesto.jpg/500px-Pasta_with_pesto.jpg",  // Pasta with pesto.jpg
    "Philly Cheesesteak": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Cheesesteak_%2819386149993%29.jpg/500px-Cheesesteak_%2819386149993%29.jpg",  // Cheesesteak (19386149993).jpg
    "Pho": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Bowl_of_Meatball_pho.jpg/500px-Bowl_of_Meatball_pho.jpg",  // Pho
    "Picanha": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Picanha3.jpg/500px-Picanha3.jpg",  // Picanha
    "Picarones": "https://upload.wikimedia.org/wikipedia/commons/e/ea/Picarones.jpg",  // Picarones
    "Pickles": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Glasses_of_pickled_cucumbers.jpg/500px-Glasses_of_pickled_cucumbers.jpg",  // Glasses of pickled cucumbers.jpg
    "Pineapple": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Ananas_comosus_Victoria_P1190459.jpg/500px-Ananas_comosus_Victoria_P1190459.jpg",  // Ananas comosus Victoria P1190459.jpg
    "Pisto": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Pisto.jpg/500px-Pisto.jpg",  // Pisto
    "Pita": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Pita_Bread.jpg/500px-Pita_Bread.jpg",  // Pita
    "Pizza": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Pizza-3007395.jpg/500px-Pizza-3007395.jpg",  // Pizza
    "Plum": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Plums_African_Rose_-_whole%2C_halved_and_slice.jpg/500px-Plums_African_Rose_-_whole%2C_halved_and_slice.jpg",  // Plum
    "Poke": "https://upload.wikimedia.org/wikipedia/commons/5/5d/Shoyu_and_onion_poke.jpg",  // Poke (dish)
    "Pollo a la Brasa": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Un_cuarto_de_Pollo_a_la_Brasa.JPG/500px-Un_cuarto_de_Pollo_a_la_Brasa.JPG",  // Pollo a la brasa
    "Pomegranate": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Pomegranate_Juice_%282019%29.jpg/500px-Pomegranate_Juice_%282019%29.jpg",  // Pomegranate
    "Popcorn": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Bowl_of_Popcorn_%28Unsplash%29.jpg/500px-Bowl_of_Popcorn_%28Unsplash%29.jpg",  // Bowl of Popcorn (Unsplash).jpg
    "Popsicle": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Cucumber%2C_elderflower_and_mint_ice_pop_from_Nicepops_%2818159920902%29.jpg/500px-Cucumber%2C_elderflower_and_mint_ice_pop_from_Nicepops_%2818159920902%29.jpg",  // Ice pop
    "Pork": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Ribs_from_the_pit.jpg/500px-Ribs_from_the_pit.jpg",  // List of pork dishes
    "Potato Chips": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Potato-Chips.jpg/500px-Potato-Chips.jpg",  // Potato chips
    "Potato Salad": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Potato_salad_%281%29.jpg/500px-Potato_salad_%281%29.jpg",  // Potato salad
    "Pozole": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Green_pozole%2C_dressed_%2829161841908%29_%28cropped%29.jpg/500px-Green_pozole%2C_dressed_%2829161841908%29_%28cropped%29.jpg",  // Pozole
    "Pretzel": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/BrezelnSalz02_%28cropped%29.JPG/500px-BrezelnSalz02_%28cropped%29.JPG",  // Pretzel
    "Pudding": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/2020-03-08_23_43_19_Jell-O_chocolate_pudding_in_the_Dulles_section_of_Sterling%2C_Loudoun_County%2C_Virginia.jpg/500px-2020-03-08_23_43_19_Jell-O_chocolate_pudding_in_the_Dulles_section_of_Sterling%2C_Loudoun_County%2C_Virginia.jpg",  // Chocolate pudding
    "Pulled Pork": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Pulled_pork_while_pulling.JPG/500px-Pulled_pork_while_pulling.JPG",  // Pulled pork
    "Pulpo a la Gallega": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Polbo_a_feira.jpg/500px-Polbo_a_feira.jpg",  // Polbo á feira
    "Pumpkin Pie": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Pumpkin-Pie-Whole-Slice.jpg/500px-Pumpkin-Pie-Whole-Slice.jpg",  // Pumpkin pie
    "Quesadilla": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Empanada_flor_de_Calabaza.jpg/500px-Empanada_flor_de_Calabaza.jpg",  // Quesadilla
    "Quiche Lorraine": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Quiche_de_Lorraine.jpg/500px-Quiche_de_Lorraine.jpg",  // Quiche Lorraine
    "Quindim": "https://upload.wikimedia.org/wikipedia/commons/4/44/Quindim.jpg",  // Quindim
    "Ramen": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Shoyu_Ramen%EF%BC%88Tokyo_Ramen%EF%BC%89_-_01.jpg/500px-Shoyu_Ramen%EF%BC%88Tokyo_Ramen%EF%BC%89_-_01.jpg",  // Ramen
    "Raspberries": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Raspberries-1426859_960_720.jpg/500px-Raspberries-1426859_960_720.jpg",  // Raspberries-1426859 960 720.jpg
    "Ratatouille": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Ratatouille_home_cooked.jpg/500px-Ratatouille_home_cooked.jpg",  // Ratatouille
    "Ravioli": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Flickr_-_cyclonebill_-_Ravioli_med_skinke_og_asparges_i_mascarponecreme.jpg/500px-Flickr_-_cyclonebill_-_Ravioli_med_skinke_og_asparges_i_mascarponecreme.jpg",  // Ravioli
    "Red Velvet Cake": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Red_Velvet_Cake_Waldorf_Astoria.jpg/500px-Red_Velvet_Cake_Waldorf_Astoria.jpg",  // Red velvet cake
    "Rfissa": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Rfissa_marocaine.jpg/500px-Rfissa_marocaine.jpg",  // Rfissa
    "Ribs": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Balinese_Roasted_Pork_Ribs_-_Iga_Babi_Panggang_Bali.JPG/500px-Balinese_Roasted_Pork_Ribs_-_Iga_Babi_Panggang_Bali.JPG",  // Pork ribs
    "Rice": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Meshi_001.jpg/500px-Meshi_001.jpg",  // Cooked rice
    "Risotto": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Risotto_with_speck_and_goat_cheese_%286101067436%29.jpg/500px-Risotto_with_speck_and_goat_cheese_%286101067436%29.jpg",  // Risotto
    "Rocoto Relleno": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Rocoto_relleno.jpg/500px-Rocoto_relleno.jpg",  // Rocoto relleno
    "Rogan Josh": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Rogan_Josh_Kashmiri.jpg/500px-Rogan_Josh_Kashmiri.jpg",  // Rogan josh
    "Rouladen": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Rinderroulade-zutaten-02.JPG/500px-Rinderroulade-zutaten-02.JPG",  // Rinderroulade
    "Salad": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Mixed_Green_Salad_%2815977106804%29.jpg/500px-Mixed_Green_Salad_%2815977106804%29.jpg",  // Mixed Green Salad (15977106804).jpg
    "Salmon": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Sashimi_-_Maguro_Restaurant%2C_Bangna%2C_Bangkok_%2844856596864%29.jpg/500px-Sashimi_-_Maguro_Restaurant%2C_Bangna%2C_Bangkok_%2844856596864%29.jpg",  // Salmon as food
    "Salmorejo": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Salmorejo_cordouan.JPG/500px-Salmorejo_cordouan.JPG",  // Salmorejo
    "Salsa": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Various_salsas.jpg/500px-Various_salsas.jpg",  // Salsa (food)
    "Saltimbocca": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Saltimbocca_01.jpg/500px-Saltimbocca_01.jpg",  // Saltimbocca
    "Samgyeopsal": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Samgyeopsal-gui.jpg/500px-Samgyeopsal-gui.jpg",  // Samgyeopsal
    "Samosa": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Samosas%2C_snack_food_at_Wikipedia%27s_16th_Birthday_celebration_in_Chittagong_%2801%29.jpg/500px-Samosas%2C_snack_food_at_Wikipedia%27s_16th_Birthday_celebration_in_Chittagong_%2801%29.jpg",  // Samosa
    "Sandwich": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Bacon%2C_lettuce%2C_tomato%2C_and_avocado.jpg/500px-Bacon%2C_lettuce%2C_tomato%2C_and_avocado.jpg",  // Sandwich
    "Satay": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Sate_Udang.JPG/500px-Sate_Udang.JPG",  // Satay
    "Sauerbraten": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Heldrunger_Sauerbraten_2.JPG/500px-Heldrunger_Sauerbraten_2.JPG",  // Sauerbraten
    "Sausage": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/German_Bratw%C3%BCrste.jpg/500px-German_Bratw%C3%BCrste.jpg",  // Bratwurst
    "Schwarzwalder Kirschtorte": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Black_Forest_gateau.jpg/500px-Black_Forest_gateau.jpg",  // Black Forest gateau
    "Scone": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Scone_varieties.jpg/500px-Scone_varieties.jpg",  // Scone
    "Scotch Egg": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/One_scotch_egg_%28No_jar_of_Marmite%29.jpg/500px-One_scotch_egg_%28No_jar_of_Marmite%29.jpg",  // Scotch egg
    "Scrambled Eggs": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Scrambed_eggs.jpg/500px-Scrambed_eggs.jpg",  // Scrambled eggs
    "Sfiha": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Sfiha2.jpg/500px-Sfiha2.jpg",  // Sfiha
    "Shawarma": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Shawarma_2.jpg/500px-Shawarma_2.jpg",  // Shawarma
    "Shepherd's Pie": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Homerton_College_-_Shepherd%27s_pie_%28cropped%29.jpg/500px-Homerton_College_-_Shepherd%27s_pie_%28cropped%29.jpg",  // Shepherd's pie
    "Shiro": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Taita_and_shiro.jpg/500px-Taita_and_shiro.jpg",  // Shiro (food)
    "Shrimp": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Spicy_fried_King_Prawns.jpg/500px-Spicy_fried_King_Prawns.jpg",  // Shrimp and prawn as food
    "Sinigang": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/The_Best_Sinigang_Cuisine.jpg/500px-The_Best_Sinigang_Cuisine.jpg",  // Sinigang
    "Sisig": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Authentic_Kapampangan_Sisig.jpg/500px-Authentic_Kapampangan_Sisig.jpg",  // Sisig
    "Sloppy Joe": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Sloppy_Joe_%22homemade%22.jpg/500px-Sloppy_Joe_%22homemade%22.jpg",  // Sloppy joe
    "Smoothie": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Kiwi_Smoothie.jpg/500px-Kiwi_Smoothie.jpg",  // Smoothie
    "Soba": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Dried_soba_noodles_by_FotoosVanRobin.jpg/500px-Dried_soba_noodles_by_FotoosVanRobin.jpg",  // Soba
    "Soda": "https://upload.wikimedia.org/wikipedia/commons/c/cf/Tumbler_of_cola_with_ice.jpg",  // Soft drink
    "Som Tam": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/2013_Tam_Lao.jpg/500px-2013_Tam_Lao.jpg",  // Green papaya salad
    "Soup": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Asparagus_soup_%28spargelsuppe%29.jpg/500px-Asparagus_soup_%28spargelsuppe%29.jpg",  // Soup
    "Souvlaki": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/%CE%95%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CF%8C_%CE%A3%CE%BF%CF%85%CE%B2%CE%BB%CE%AC%CE%BA%CE%B9_-_panoramio.jpg/500px-%CE%95%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CF%8C_%CE%A3%CE%BF%CF%85%CE%B2%CE%BB%CE%AC%CE%BA%CE%B9_-_panoramio.jpg",  // Souvlaki
    "Spaghetti": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Spaghetti_di_Gragnano_e_colatura_di_alici.jpg/500px-Spaghetti_di_Gragnano_e_colatura_di_alici.jpg",  // Spaghetti di Gragnano e colatura di alici.jpg
    "Spanakopita": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Spanakopita.jpg/500px-Spanakopita.jpg",  // Savory spinach pie
    "Spatzle": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Sp%C3%A4tzle-02.jpg/500px-Sp%C3%A4tzle-02.jpg",  // Spätzle
    "Spring Rolls": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Spring_Rolls_%283357696061%29.jpg/500px-Spring_Rolls_%283357696061%29.jpg",  // Spring roll
    "Sticky Toffee Pudding": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Sticky_toffee_pudding_at_the_Black_Swan_-_Stierch.jpg/500px-Sticky_toffee_pudding_at_the_Black_Swan_-_Stierch.jpg",  // Sticky toffee pudding
    "Stollen": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Stollen-Dresdner_Christstollen.jpg/500px-Stollen-Dresdner_Christstollen.jpg",  // Stollen
    "Strawberry": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Garden_strawberry_%28Fragaria_%C3%97_ananassa%29_single2.jpg/500px-Garden_strawberry_%28Fragaria_%C3%97_ananassa%29_single2.jpg",  // Strawberry
    "Sub Sandwich": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Submarine_sandwich_with_toppings_and_dijon_mustard.jpg/500px-Submarine_sandwich_with_toppings_and_dijon_mustard.jpg",  // Submarine sandwich
    "Sundubu Jjigae": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Sundubu-jjigae.jpg/500px-Sundubu-jjigae.jpg",  // Sundubu-jjigae
    "Sushi": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Sushi_platter.jpg/500px-Sushi_platter.jpg",  // Sushi
    "Sweet Potato": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Ipomoea_batatas_006.JPG/500px-Ipomoea_batatas_006.JPG",  // Sweet potato
    "Sweet and Sour Pork": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Sweet_and_sour_pork.jpg/500px-Sweet_and_sour_pork.jpg",  // Sweet and sour pork
    "Tabbouleh": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Tabouleh_1.JPG/500px-Tabouleh_1.JPG",  // Tabbouleh
    "Tacos": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/001_Tacos_de_carnitas%2C_carne_asada_y_al_pastor.jpg/500px-001_Tacos_de_carnitas%2C_carne_asada_y_al_pastor.jpg",  // Taco
    "Tacos al Pastor": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Tacos-al-Pastor.jpg/500px-Tacos-al-Pastor.jpg",  // Al pastor
    "Tacu Tacu": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Tacu_Tacu.jpg/500px-Tacu_Tacu.jpg",  // Tacu-tacu
    "Tagine": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Tajine-marocain-un-plat-varie-et-sain_%28cropped%29.jpg/500px-Tajine-marocain-un-plat-varie-et-sain_%28cropped%29.jpg",  // Tagine
    "Taho": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Taho2.jpg/500px-Taho2.jpg",  // Taho
    "Takoyaki": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/%E3%82%BD%E3%83%BC%E3%82%B9%E3%81%A8%E3%83%9D%E3%83%B3%E9%85%A2%E3%81%AE%E3%81%9F%E3%81%93%E7%84%BC%E3%81%8D.jpg/500px-%E3%82%BD%E3%83%BC%E3%82%B9%E3%81%A8%E3%83%9D%E3%83%B3%E9%85%A2%E3%81%AE%E3%81%9F%E3%81%93%E7%84%BC%E3%81%8D.jpg",  // Takoyaki
    "Tamales": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Tamale_Oaxaque%C3%B1o.jpg/500px-Tamale_Oaxaque%C3%B1o.jpg",  // Tamale
    "Tandoori Chicken": "https://upload.wikimedia.org/wikipedia/commons/e/e1/Chickentandoori.jpg",  // Tandoori chicken
    "Taramasalata": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Taramosalata01.jpg/500px-Taramosalata01.jpg",  // Taramasalata
    "Tea": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Cup_of_black_tea.JPG/500px-Cup_of_black_tea.JPG",  // Black tea
    "Tempura": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Tempura_01.jpg/500px-Tempura_01.jpg",  // Tempura
    "Tihlo": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Eating_Traditional_Tihlo%2C_Ethiopia.jpg/500px-Eating_Traditional_Tihlo%2C_Ethiopia.jpg",  // Tihlo
    "Tinola": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Chicken_tinola.jpg/500px-Chicken_tinola.jpg",  // Tinola
    "Tiradito": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Tiradito.jpg/500px-Tiradito.jpg",  // Tiradito
    "Tiramisu": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Tiramisu_-_Raffaele_Diomede.jpg/500px-Tiramisu_-_Raffaele_Diomede.jpg",  // Tiramisu
    "Tlayuda": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Tlayuda12-05oaxaca013x.jpg/500px-Tlayuda12-05oaxaca013x.jpg",  // Tlayuda
    "Toad in the Hole": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Toad_in_the_hole.jpg/500px-Toad_in_the_hole.jpg",  // Toad in the hole
    "Toast": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Toast-3.jpg/500px-Toast-3.jpg",  // Toast (food)
    "Tofu": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Japanese_SilkyTofu_%28Kinugoshi_Tofu%29.JPG/500px-Japanese_SilkyTofu_%28Kinugoshi_Tofu%29.JPG",  // Tofu
    "Tom Kha Gai": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Flickr_preppybyday_4711943668--Tom_kha_gai.jpg/500px-Flickr_preppybyday_4711943668--Tom_kha_gai.jpg",  // Tom kha kai
    "Tom Yum": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Tom_yam_kung_maenam.jpg/500px-Tom_yam_kung_maenam.jpg",  // Tom yum
    "Tomato": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Tomato_je.jpg/500px-Tomato_je.jpg",  // Tomato
    "Tomato Soup": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Tomato_soup%2C_plant-based_%2844040252791%29.jpg/500px-Tomato_soup%2C_plant-based_%2844040252791%29.jpg",  // Tomato soup
    "Tonkatsu": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/%22Amai-Yuwaku%22_Special_Loin_Pork_Cutlet1.jpg/500px-%22Amai-Yuwaku%22_Special_Loin_Pork_Cutlet1.jpg",  // Tonkatsu
    "Torta": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Torta_Cence%C3%B1a_%28Roda%29.jpg/500px-Torta_Cence%C3%B1a_%28Roda%29.jpg",  // Torta
    "Tortilla Espanola": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Tortilla_de_patata_-_San_Sebasti%C3%A1n.jpg/500px-Tortilla_de_patata_-_San_Sebasti%C3%A1n.jpg",  // Spanish omelette
    "Tteokbokki": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Tteokbokki.JPG/500px-Tteokbokki.JPG",  // Tteokbokki
    "Tuna": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Seared_Ahi_Tuna_Steak.jpg/500px-Seared_Ahi_Tuna_Steak.jpg",  // Seared Ahi Tuna Steak.jpg
    "Turkey": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Thanksgiving_Turkey.jpg/500px-Thanksgiving_Turkey.jpg",  // Turkey as food
    "Tzatziki": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Cacik-1.jpg/500px-Cacik-1.jpg",  // Tzatziki
    "Udon": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/%E9%B6%8F%E5%A4%A9%E3%81%AE%E3%81%86%E3%81%A9%E3%82%93.jpg/500px-%E9%B6%8F%E5%A4%A9%E3%81%AE%E3%81%86%E3%81%A9%E3%82%93.jpg",  // Udon
    "Vada Pav": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Vada_Pav-Indian_street_food.JPG/500px-Vada_Pav-Indian_street_food.JPG",  // Vada pav
    "Vatapa": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Vatap%C3%A1.jpg/500px-Vatap%C3%A1.jpg",  // Vatapá
    "Veggie Burger": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/%D7%94%D7%9E%D7%91%D7%95%D7%A8%D7%92%D7%A8_%D7%98%D7%91%D7%A2%D7%95%D7%A0%D7%99.jpg/500px-%D7%94%D7%9E%D7%91%D7%95%D7%A8%D7%92%D7%A8_%D7%98%D7%91%D7%A2%D7%95%D7%A0%D7%99.jpg",  // Veggie burger
    "Vindaloo": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Beef_Vindaloo_-_Chilli_Mama%2C_Chadstone_%283014236693%29.jpg/500px-Beef_Vindaloo_-_Chilli_Mama%2C_Chadstone_%283014236693%29.jpg",  // Vindaloo
    "Vitello Tonnato": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Vitello_tonnato.jpg/500px-Vitello_tonnato.jpg",  // Vitello tonnato
    "Waffles": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Waffles_with_Strawberries.jpg/500px-Waffles_with_Strawberries.jpg",  // Waffle
    "Watermelon": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Divided_Water_Melon.jpg/500px-Divided_Water_Melon.jpg",  // Divided Water Melon.jpg
    "Wiener Schnitzel": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Wiener-Schnitzel02.jpg/500px-Wiener-Schnitzel02.jpg",  // Wiener schnitzel
    "Wonton Soup": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Pork_Steamed_Wontons.jpg/500px-Pork_Steamed_Wontons.jpg",  // Wonton
    "Wontons": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Pork_Steamed_Wontons.jpg/500px-Pork_Steamed_Wontons.jpg",  // Wonton
    "Xiao Long Bao": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/A_Xiaolongbao_from_The_Modern_Shanghai.jpg/500px-A_Xiaolongbao_from_The_Modern_Shanghai.jpg",  // Xiaolongbao
    "Yakitori": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Cooking_yakitori.jpg/500px-Cooking_yakitori.jpg",  // Yakitori
    "Yangnyeom Chicken": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Yangnyeom-chikin_bhcChicken_1.jpg/500px-Yangnyeom-chikin_bhcChicken_1.jpg",  // Yangnyeom chicken
    "Yogurt": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Joghurt.jpg/500px-Joghurt.jpg",  // Yogurt
    "Yorkshire Pudding": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Yorkshire_Puddings_on_plate.jpg/500px-Yorkshire_Puddings_on_plate.jpg",  // Yorkshire pudding
    "Youvetsi": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Giouvetsi.JPG/500px-Giouvetsi.JPG",  // Giouvetsi
    "Zaalouk": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Zaalouk-01.JPG/500px-Zaalouk-01.JPG",  // Zaalouk
    "Zhajiangmian": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Billyzhajiang1.jpg/500px-Billyzhajiang1.jpg",  // Zhajiangmian
  };

  // Photographer and licence for each photo above — what most of those
  // licences ask in return. Read by the Credits screen. An empty name is a
  // public-domain photo with no author on record, so there is nobody owed.
  window.MASQ_FOOD_CREDITS = [
    ["Acai Bowl", "Túllio F", "CC BY-SA 4.0"],
    ["Acaraje", "AkinkuotuFunmi", "CC BY-SA 4.0"],
    ["Adobo", "Tamorlan", "CC BY 3.0"],
    ["Aji de Gallina", "Feralbt", "CC BY-SA 3.0"],
    ["Almonds", "Ivar Leidus", "CC BY-SA 4.0"],
    ["Anticuchos", "Carly & Art", "CC BY-SA 2.0"],
    ["Apple", "Evan-Amos", "CC0"],
    ["Apple Pie", "The-Wuje", "CC BY-SA 4.0"],
    ["Avocado", "Ivar Leidus", "CC BY-SA 4.0"],
    ["BLT", "jeffreyw", "CC BY 2.0"],
    ["Baba Ghanoush", "Breville USA", "CC BY 2.0"],
    ["Bacon", "Made20rder555", "Public domain"],
    ["Bagel", "Shisma", "CC BY 4.0"],
    ["Baghrir", "فاطمة الزهراء", "CC BY-SA 4.0"],
    ["Baguette", "Nick Thweatt", "CC BY-SA 3.0"],
    ["Baked Potato", "Renee Comet", "Public domain"],
    ["Baklava", "Sakaman", "CC BY-SA 4.0"],
    ["Banana", "TimothyPilgrim", "CC BY-SA 3.0"],
    ["Banana Bread", "Shisma", "CC BY 4.0"],
    ["Banchan", "국립국어원", "CC BY-SA 2.0 kr"],
    ["Bangers and Mash", "anokarina", "CC BY-SA 2.0"],
    ["Banh Mi", "Nsaum75", "CC BY-SA 3.0"],
    ["Banh Xeo", "HungryHuy", "CC BY 2.0"],
    ["Bastilla", "Krista", "CC BY 2.0"],
    ["Beef", "Archie MacDonald52", "CC BY-SA 3.0"],
    ["Beef Stew", "FiveRings", "CC BY 3.0"],
    ["Beef Wellington", "Snielsen1112", "CC BY-SA 4.0"],
    ["Beyaynetu", "Dawityirga", "CC BY-SA 4.0"],
    ["Bibimbap", "Sous Chef", "CC BY 2.0"],
    ["Bibingka", "Judgefloro", "CC0"],
    ["Bicol Express", "Raymund Macaalay", "CC BY-SA 3.0"],
    ["Birria", "Equipo 9mkt", "CC BY-SA 3.0"],
    ["Biryani", "Mahi Tatavarty", "CC BY-SA 4.0"],
    ["Biscuit", "Dale Cruse", "CC BY 2.0"],
    ["Black Pudding", "Alexbrn", "CC BY-SA 3.0"],
    ["Blueberries", "Evan-Amos", "CC0"],
    ["Boba Milk Tea", "Howief", "CC BY-SA 3.0"],
    ["Bouillabaisse", "Slastic", "CC BY 3.0"],
    ["Bratwurst", "Gerbis", "CC BY-SA 3.0"],
    ["Bread", "3268zauber", "CC BY-SA 3.0"],
    ["Brigadeiro", "Mayra (Maych)", "CC BY-SA 2.0"],
    ["Briouat", "Christian Muise", "CC BY-SA 2.0"],
    ["Broccoli", "David", "Public domain"],
    ["Brownie", "Ɱ", "CC BY-SA 3.0"],
    ["Bruschetta", "Takeaway", "CC BY-SA 4.0"],
    ["Buffalo Wings", "Clotee Pridgen Allochuku", "CC BY 2.0"],
    ["Bulgogi", "국립국어원", "CC BY-SA 2.0 kr"],
    ["Bun Bo Hue", "Chainwit.", "CC BY 4.0"],
    ["Bun Cha", "stuart spivack", "CC BY 2.0"],
    ["Bun Rieu", "TarnishedPath", "CC BY-SA 4.0"],
    ["Burger", "Hongreddotbrewhouse", "CC BY-SA 3.0"],
    ["Burrito", "samuelfernandezrivera", "CC0"],
    ["Butter Chicken", "Yuvraj Singh 97", "CC BY-SA 4.0"],
    ["Calzone", "Deryck Chan", "CC BY-SA 4.0"],
    ["Cantaloupe", "USDA photo by Scott Bauer", "Public domain"],
    ["Cao Lau", "Chainwit.", "CC BY 4.0"],
    ["Carbonara", "Javier Somoza", "CC BY-SA 4.0"],
    ["Carrot Cake", "Elitre", "CC BY-SA 4.0"],
    ["Carrots", "Evan-Amos", "Public domain"],
    ["Cassoulet", "BrokenSphere", "CC BY-SA 3.0"],
    ["Causa", "spersper", "CC BY 2.0"],
    ["Cereal", "Unknown photographer/artist", "Public domain"],
    ["Ceviche", "Picanteria karol", "CC BY-SA 4.0"],
    ["Cha Ca", "Phương Huy", "Public domain"],
    ["Chaat", "Rupamdas75", "CC BY-SA 4.0"],
    ["Chai", "Dadhichbittu007", "CC BY-SA 4.0"],
    ["Char Siu", "Simon Shek", "CC BY-SA 3.0"],
    ["Chawanmushi", "Brücke-Osteuropa", "CC0"],
    ["Chebakia", "Indif", "CC BY-SA 3.0"],
    ["Cheese", "Dorina Andress (edited by Neutrality)", "CC BY-SA 3.0"],
    ["Cheeseburger", "Renee Comet", "Public domain"],
    ["Cheesecake", "zingyyellow", "CC BY 2.0"],
    ["Cherries", "spurekar", "CC BY 2.0"],
    ["Chicharron", "Missvain", "CC BY 4.0"],
    ["Chicken", "Evan Swigart", "CC BY 2.0"],
    ["Chicken Fried Steak", "LeeMNichols", "CC BY-SA 4.0"],
    ["Chicken Noodle Soup", "Hoyabird8", "CC BY-SA 3.0"],
    ["Chicken Nuggets", "James Palinsad", "CC BY-SA 2.0"],
    ["Chicken Tikka Masala", "Michael Hays", "CC BY 2.0"],
    ["Chicken Wings", "Clotee Pridgen Allochuku", "CC BY 2.0"],
    ["Chilaquiles", "Chris Woodrich", "CC BY-SA 4.0"],
    ["Chili", "Carstor", "CC BY-SA 2.5"],
    ["Chocolate", "Lynnereal", "CC BY-SA 4.0"],
    ["Chocolate Cake", "Tracy Hunter", "CC BY 2.0"],
    ["Chole Bhature", "Dheerajk88", "CC BY-SA 4.0"],
    ["Chow Mein", "Peachyeung316", "CC BY-SA 4.0"],
    ["Churros", "Joy", "CC BY 2.0"],
    ["Cinnamon Roll", "Kritzolina", "CC BY-SA 4.0"],
    ["Clam Chowder", "Jon Sullivan", "Public domain"],
    ["Cobb Salad", "Jodimichelle", "CC BY-SA 2.0"],
    ["Coconut", "Shameelnurani313", "CC BY-SA 4.0"],
    ["Coffee", "Bex Walton", "CC BY 2.0"],
    ["Coleslaw", "Anagoria", "CC BY 3.0"],
    ["Com Tam", "Christopher Crouzet", "CC BY-SA 4.0"],
    ["Congee", "Daiju Azuma", "CC BY-SA 2.5"],
    ["Cookies", "brainloc on sxc.hu (Bob Smith)", "CC BY 2.5"],
    ["Coq au Vin", "Beck from East Midlands, United Kingdon", "CC BY 2.0"],
    ["Corn Dog", "Ocdp", "CC0"],
    ["Corn on the Cob", "Jonathunder", "CC BY-SA 3.0"],
    ["Cornish Pasty", "David Johnson", "CC BY-SA 3.0"],
    ["Cotton Candy", "FocalPoint", "CC BY-SA 3.0"],
    ["Couscous", "Lmmima", "CC BY-SA 4.0"],
    ["Coxinha", "Romerito Pontes", "CC BY 2.0"],
    ["Crab", "cyclonebill from Copenhagen, Denmark", "CC BY-SA 2.0"],
    ["Crackers", "Giovanni JL", "CC BY-SA 2.0"],
    ["Creme Brulee", "Takeaway", "CC BY-SA 3.0"],
    ["Crepes", "David Monniaux", "CC BY-SA 3.0"],
    ["Croissant", "Petr Kratochvil", "CC0"],
    ["Croque Monsieur", "Michael Brewer", "CC BY-SA 2.5"],
    ["Croquetas", "Jonathan Pincas", "CC BY 2.0"],
    ["Crème Brûlée", "Takeaway", "CC BY-SA 3.0"],
    ["Cucumber", "MOs810", "CC BY-SA 3.0"],
    ["Cupcake", "Marc-Lautenbacher", "CC BY-SA 4.0"],
    ["Curry", "Francesc Fort", "CC BY-SA 4.0"],
    ["Currywurst", "Ziko van Dijk", "CC BY-SA 4.0"],
    ["Dabo Kolo", "Jongenelen, R.G.L.", "CC BY-SA 4.0"],
    ["Dan Dan Noodles", "Steven G. Johnson", "CC BY-SA 3.0"],
    ["Dim Sum", "LeonardKong", "CC BY 2.0"],
    ["Dolmades", "Violetamyftari", "CC BY-SA 3.0"],
    ["Donut", "Evan-Amos", "Public domain"],
    ["Doro Wat", "stu spivack", "CC BY-SA 2.0"],
    ["Dosa", "Vee Satayamas", "CC BY 2.0"],
    ["Duck", "cyclonebill from Copenhagen, Denmark", "CC BY-SA 2.0"],
    ["Duck Confit", "Roboppy", "Public domain"],
    ["Dumplings", "Honmustak Chooica", "CC BY-SA 4.0"],
    ["Egg Rolls", "", "Public domain"],
    ["Elote", "Jonathunder", "CC BY-SA 3.0"],
    ["Enchiladas", "Jon Sullivan", "Public domain"],
    ["Escargot", "Restaurante Granero", "Public domain"],
    ["Espresso", "Lemone", "CC BY-SA 4.0"],
    ["Esquites", "Panochahumedalegend", "CC BY-SA 4.0"],
    ["Eton Mess", "Exx8", "CC0"],
    ["Fabada", "Juan J. Martínez", "CC BY-SA 2.0"],
    ["Fajitas", "Crisco 1492", "CC BY-SA 4.0"],
    ["Falafel", "Popo le Chien", "CC BY-SA 3.0"],
    ["Farofa", "Carioca", "CC BY-SA 3.0"],
    ["Fattoush", "Arousing Appetites", "CC BY-SA 3.0"],
    ["Feijoada", "Adrião", "CC BY 3.0"],
    ["Fettuccine Alfredo", "Meliciousm", "CC BY-SA 4.0"],
    ["Fir Fir", "Temesgen Woldezion (edited by Merhawie Woldezion)", "CC BY-SA 2.5"],
    ["Fish and Chips", "Matthias Meckel", "CC BY-SA 4.0"],
    ["Flan", "Popo le Chien", "CC BY-SA 3.0"],
    ["Focaccia", "Fred Benenson", "CC BY-SA 4.0"],
    ["French Fries", "StockSnap", "CC0"],
    ["French Toast", "Jonathunder", "CC BY-SA 3.0"],
    ["Fried Chicken", "Evan-Amos", "CC0"],
    ["Fried Rice", "Vyacheslav Argenberg", "CC BY 4.0"],
    ["Full English Breakfast", "Joadl", "CC BY-SA 3.0 at"],
    ["Gambas al Ajillo", "Krista", "CC BY 2.0"],
    ["Garlic Bread", "Popo le Chien", "CC BY-SA 3.0"],
    ["Gazpacho", "Haydn Blackey", "CC BY-SA 2.0"],
    ["Genfo", "Stefan Alfons Tzeggai", "CC BY-SA 3.0"],
    ["Gimbap", "changupn", "CC0"],
    ["Gnocchi", "Paoletta S.", "CC BY 2.0"],
    ["Goi Cuon", "pelican from Tokyo, Japan", "CC BY-SA 2.0"],
    ["Gored Gored", "Thomson200", "CC0"],
    ["Granola", "Arnold Gatilao", "CC BY 2.0"],
    ["Grapes", "Vyacheslav Argenberg", "CC BY 4.0"],
    ["Green Beans", "16:9clue", "CC BY 2.0"],
    ["Green Curry", "Takeaway", "CC BY-SA 3.0"],
    ["Grilled Cheese", "Willis Lam", "CC BY-SA 2.0"],
    ["Guacamole", "Nikodem Nijaki", "CC BY-SA 3.0"],
    ["Gyro", "Antonio Fajardo i López", "CC BY-SA 3.0"],
    ["Halo-Halo", "Herbertkikoy", "CC BY-SA 4.0"],
    ["Harcha", "Lucyin", "CC BY-SA 4.0"],
    ["Harira", "Kattusa24", "Public domain"],
    ["Hash Browns", "jeffreyw", "CC BY 2.0"],
    ["Himbasha", "Temesgen Woldezion (edited by Merhawie Woldezion)", "CC BY-SA 2.5"],
    ["Honey", "Scott Bauer, USDA ARS", "Public domain"],
    ["Horiatiki Salad", "Jpatokal", "CC BY-SA 4.0"],
    ["Hot Chocolate", "UggBoy♥UggGirl", "CC BY 2.0"],
    ["Hot Dog", "Czar, original photographed by Renee Comet", "Public domain"],
    ["Hot Pot", "Praneeth Thalla", "CC BY-SA 4.0"],
    ["Hu Tieu", "Dianne Flor Reyno", "CC BY 2.0"],
    ["Hummus", "Beyrouthhh", "CC BY 3.0"],
    ["Ice Cream", "Nicolas Ettlin", "CC BY-SA 4.0"],
    ["Iced Tea", "Melissa Doroquez", "CC BY-SA 2.0"],
    ["Idli", "Soumya dey", "CC BY-SA 3.0"],
    ["Injera", "Artem.G", "CC BY-SA 4.0"],
    ["Jam", "毒島みるく", "CC0"],
    ["Jamon Iberico", "Cantabrucu", "CC0"],
    ["Japchae", "korea.net", "CC BY-SA 2.0"],
    ["Jello", "Famartin", "CC BY-SA 4.0"],
    ["Jjajangmyeon", "국립국어원", "CC BY-SA 2.0 kr"],
    ["Kafta", "Fabienkhan", "CC BY-SA 2.5"],
    ["Kare-Kare", "GwennVienn", "CC BY-SA 4.0"],
    ["Kasespatzle", "1971markus", "CC BY-SA 4.0"],
    ["Katsu Curry", "Kyu3a", "CC BY-SA 4.0"],
    ["Kebab", "Lesya Dolyk", "CC BY-SA 2.0"],
    ["Key Lime Pie", "Louiemantia", "CC BY-SA 4.0"],
    ["Khao Soi", "Chainwit.", "CC BY-SA 4.0"],
    ["Kibbeh", "Bazel", "CC BY-SA 3.0"],
    ["Kimchi", "Johannes Barre", "CC BY-SA 3.0"],
    ["Kimchi Jjigae", "한국농수산식품유통공사", "KOGL Type 1"],
    ["Kitfo", "Milo.G", "CC BY-SA 4.0"],
    ["Kiwi", "Luc Viatour", "CC BY-SA 2.5"],
    ["Kleftiko", "Lord Mountbatten", "CC BY-SA 3.0"],
    ["Knafeh", "elif ayse", "CC BY 2.0"],
    ["Kocho", "Minarate", "CC BY-SA 4.0"],
    ["Kung Pao Chicken", "Steven G. Johnson", "CC BY-SA 3.0"],
    ["Lamb", "Haydn Blackey", "CC BY-SA 4.0"],
    ["Larb", "Jpatokal", "CC BY-SA 4.0"],
    ["Lasagna", "jules / stonesoup", "CC BY 2.0"],
    ["Leberkase", "Rainer Z...", "CC BY-SA 3.0"],
    ["Lechon", "Tamorlan", "CC BY 3.0"],
    ["Lemon", "Evan-Amos", "Public domain"],
    ["Lemonade", "HarshLight", "CC BY 2.0"],
    ["Lime", "Evan-Amos", "CC0"],
    ["Lobster", "thefoodplace.co.uk", "CC BY 2.0"],
    ["Lollipop", "Naturpuur", "CC BY-SA 4.0"],
    ["Lomo Saltado", "Chasqui (Luis Tamayo)", "CC BY-SA 2.0"],
    ["Lumpia", "Midori", "CC BY-SA 3.0"],
    ["Mac and Cheese", "Texasfoodgawker", "CC BY-SA 4.0"],
    ["Macaron", "Michelle Naherny", "CC BY-SA 4.0"],
    ["Macaroni and Cheese", "Texasfoodgawker", "CC BY-SA 4.0"],
    ["Manakish", "Elie.ghob", "CC BY-SA 4.0"],
    ["Mandu", "Raven9722", "CC0"],
    ["Mango", "Ivar Leidus", "CC BY-SA 4.0"],
    ["Mango Sticky Rice", "Dennis Wong", "CC BY 2.0"],
    ["Mapo Tofu", "ZhengZhou", "CC BY-SA 4.0"],
    ["Marshmallow", "John Morgan", "CC BY 2.0"],
    ["Mashed Potatoes", "sousvideguy", "CC BY 2.0"],
    ["Massaman Curry", "Takeaway", "CC BY-SA 3.0"],
    ["Matcha", "Evanhoever", "CC BY-SA 4.0"],
    ["Maultaschen", "FloSch", "CC BY-SA 3.0"],
    ["Meatballs", "ralphhogaboom", "CC BY-SA 2.0"],
    ["Meatloaf", "Renee Comet", "Public domain"],
    ["Mechoui", "Andre Piquet", "CC BY 3.0"],
    ["Mi Quang", "Christopher Crouzet", "CC BY-SA 4.0"],
    ["Milk", "NIAID", "CC BY 2.0"],
    ["Milkshake", "Renee Comet", "Public domain"],
    ["Minestrone", "Daniel Ziegener", "CC BY-SA 2.0"],
    ["Miso Soup", "Ocdp", "CC0"],
    ["Mochi", "Lyzzy", "CC BY 2.5"],
    ["Mole Poblano", "AlejandroLinaresGarcia", "CC BY-SA 4.0"],
    ["Moqueca", "BR", "CC BY-SA 4.0"],
    ["Moussaka", "Robert Kindermann aka RobertK", "CC BY-SA 2.5"],
    ["Mozzarella Sticks", "Kim Scarborough", "CC BY-SA 2.0"],
    ["Msemen", "إيان", "CC BY-SA 4.0"],
    ["Muffin", "Sander van der Wel", "CC BY-SA 2.0"],
    ["Mujadara", "Bazel", "CC BY-SA 3.0"],
    ["Mushrooms", "George Chernilevsky", "Public domain"],
    ["Naan", "snowpea&bokchoi", "CC BY 2.0"],
    ["Nachos", "chee.hong from Kuala Lumpur, Malaysia", "CC BY 2.0"],
    ["Oatmeal", "Renee Comet", "Public domain"],
    ["Okonomiyaki", "ume-y", "CC BY 2.0"],
    ["Olives", "A,Ocram", "CC BY-SA 3.0"],
    ["Omelette", "Guilhem Vellut", "CC BY 2.0"],
    ["Onigiri", "脇山航", "CC BY-SA 4.0"],
    ["Onion", "Colin", "CC BY-SA 3.0"],
    ["Onion Rings", "Jonathunder", "CC BY-SA 3.0"],
    ["Orange", "Ivar Leidus", "CC BY-SA 4.0"],
    ["Orange Chicken", "Evan Joshua Swigart (TheCulinaryGeek)", "CC BY 2.0"],
    ["Orange Juice", "rawpixel.com", "CC0"],
    ["Osso Buco", "Mogens Engelund", "CC BY-SA 3.0"],
    ["Pad Kra Pao", "Iudexvivorum", "CC0"],
    ["Pad See Ew", "stu spivack", "CC BY-SA 2.0"],
    ["Pad Thai", "Takeaway", "CC BY-SA 3.0"],
    ["Paella", "Jan Harenburg", "CC BY-SA 4.0"],
    ["Palak Paneer", "Lopanayak", "CC BY-SA 4.0"],
    ["Pancakes", "Mae Mu", "CC0"],
    ["Pancit", "pulaw", "CC BY 2.0"],
    ["Panini", "Andy Li", "CC0"],
    ["Panna Cotta", "hiro", "CC BY-SA 2.0"],
    ["Pao de Queijo", "Murilo manzini", "CC BY-SA 4.0"],
    ["Papa a la Huancaina", "Feralbt", "CC BY 3.0"],
    ["Pasta", "David Adam Kess", "CC BY-SA 4.0"],
    ["Pastel", "BuenosAiresPhotographer", "CC BY-SA 2.0"],
    ["Pastitsio", "Sam Bailey", "CC BY-SA 4.0"],
    ["Patatas Bravas", "Krista", "CC BY 2.0"],
    ["Peach", "Evan-Amos", "CC0"],
    ["Peanut Butter", "Famartin", "CC BY-SA 4.0"],
    ["Peanuts", "Sanjay Acharya", "CC BY-SA 4.0"],
    ["Pear", "Forest Starr and Kim Starr", "CC BY 2.0"],
    ["Pecan Pie", "Joe Hakim", "CC BY 2.0"],
    ["Peking Duck", "City Foodsters", "CC BY 2.0"],
    ["Pesto Pasta", "Paul Goyette", "CC BY-SA 2.0"],
    ["Philly Cheesesteak", "jeffreyw", "CC BY 2.0"],
    ["Pho", "SerraKnightz", "CC BY 4.0"],
    ["Picanha", "", "Public domain"],
    ["Picarones", "Antox00", "CC BY-SA 3.0"],
    ["Pickles", "Shisma", "CC BY 4.0"],
    ["Pineapple", "David Monniaux", "CC BY-SA 3.0"],
    ["Pisto", "Boca Dorada", "CC BY-SA 2.0"],
    ["Pita", "Azure Dragon of the East", "CC BY-SA 3.0"],
    ["Pizza", "igorovsyannykov", "CC0"],
    ["Plum", "Ivar Leidus", "CC BY-SA 4.0"],
    ["Poke", "Aquateamhungerforce", "CC BY-SA 4.0"],
    ["Pollo a la Brasa", "Dtarazona", "CC BY-SA 3.0"],
    ["Pomegranate", "Augustus Binu: flickr", "CC BY-SA 3.0"],
    ["Popcorn", "Alex Munsell alexmunsell", "CC0"],
    ["Popsicle", "Ruth Hartnup", "CC BY 2.0"],
    ["Pork", "Thogru", "CC BY-SA 3.0"],
    ["Potato Chips", "Evan-Amos", "Public domain"],
    ["Potato Salad", "SajjadF", "CC BY-SA 3.0"],
    ["Pozole", "T.Tseng", "CC BY 2.0"],
    ["Pretzel", "Sundar1", "CC BY-SA 3.0"],
    ["Pudding", "Famartin", "CC BY-SA 4.0"],
    ["Pulled Pork", "Thogru", "CC BY-SA 3.0"],
    ["Pulpo a la Gallega", "Freecat (José Antonio Gil Martínez)", "CC BY 2.0"],
    ["Pumpkin Pie", "Evan-Amos", "CC BY-SA 3.0"],
    ["Quesadilla", "Nsaum75", "CC BY-SA 3.0"],
    ["Quiche Lorraine", "Donna Alvita", "CC BY-SA 4.0"],
    ["Quindim", "Leonardo \"Leguas\" Carvalho", "CC BY-SA 2.5"],
    ["Ramen", "Quercus acuta", "CC BY-SA 4.0"],
    ["Raspberries", "Pixel 2013", "CC0"],
    ["Ratatouille", "Jack145945", "CC0"],
    ["Ravioli", "cyclonebill", "CC BY-SA 2.0"],
    ["Red Velvet Cake", "Hennem08", "CC BY-SA 3.0"],
    ["Rfissa", "Mokhtaroo", "CC BY-SA 3.0"],
    ["Ribs", "Gunawan Kartapranata", "CC BY-SA 3.0"],
    ["Rice", "Ocdp", "CC0"],
    ["Risotto", "Luca Nebuloni", "CC BY 2.0"],
    ["Rocoto Relleno", "Idan Robbins", "CC BY-SA 4.0"],
    ["Rogan Josh", "Spice Eats", "CC BY 3.0"],
    ["Rouladen", "Tamorlan", "CC BY-SA 2.5"],
    ["Salad", "Prayitno", "CC BY 2.0"],
    ["Salmon", "Vee Satayamas", "CC BY 2.0"],
    ["Salmorejo", "P.Lechien", "CC0"],
    ["Salsa", "Popo le Chien", "CC BY-SA 3.0"],
    ["Saltimbocca", "Arnaud 25", "CC BY-SA 4.0"],
    ["Samgyeopsal", "jinsoo jang", "CC0"],
    ["Samosa", "Moheen Reeyad", "CC BY-SA 4.0"],
    ["Sandwich", "Jami430", "CC BY-SA 4.0"],
    ["Satay", "Gunawan Kartapranata", "CC BY-SA 4.0"],
    ["Sauerbraten", "Dr. Bernd Gross", "CC BY-SA 4.0"],
    ["Sausage", "Gerbis", "CC BY-SA 3.0"],
    ["Schwarzwalder Kirschtorte", "Mikelo", "CC BY-SA 2.0"],
    ["Scone", "Dave souza", "CC BY-SA 2.5"],
    ["Scotch Egg", "Unhindered by Talent", "CC BY-SA 2.0"],
    ["Scrambled Eggs", "Takeaway", "CC BY-SA 3.0"],
    ["Sfiha", "Bazel", "Public domain"],
    ["Shawarma", "Vis M", "CC BY-SA 4.0"],
    ["Shepherd's Pie", "Oxfordian Kissuth", "CC BY-SA 3.0"],
    ["Shiro", "Temesgen Woldezion (edited by Merhawie Woldezion)", "CC BY-SA 2.5"],
    ["Shrimp", "rovingI", "CC BY 2.0"],
    ["Sinigang", "Jessartcam", "CC BY-SA 4.0"],
    ["Sisig", "Joy L. Cruz", "CC BY-SA 4.0"],
    ["Sloppy Joe", "Buck Blues", "CC BY 2.0"],
    ["Smoothie", "rawpixel.com", "CC0"],
    ["Soba", "FotoosVanRobin", "CC BY-SA 2.0"],
    ["Soda", "Simon Cousins", "CC BY 2.0"],
    ["Som Tam", "Takeaway", "CC BY-SA 3.0"],
    ["Soup", "Petar Milošević", "CC BY-SA 4.0"],
    ["Souvlaki", "EntaXoyas", "CC BY-SA 3.0"],
    ["Spaghetti", "Elga Cappellari", "CC BY-SA 2.0"],
    ["Spanakopita", "Alpha", "CC BY-SA 2.0"],
    ["Spatzle", "Kobako", "CC BY-SA 2.5"],
    ["Spring Rolls", "Donna Benjamin", "CC BY-SA 2.0"],
    ["Sticky Toffee Pudding", "Sarah Stierch", "CC BY 2.0"],
    ["Stollen", "Gürgi", "Public domain"],
    ["Strawberry", "Ivar Leidus", "CC BY-SA 4.0"],
    ["Sub Sandwich", "jeffreyw", "CC BY 2.0"],
    ["Sundubu Jjigae", "행복한 초록개구리", "CC BY 4.0"],
    ["Sushi", "chidorian from Japan", "CC BY-SA 2.0"],
    ["Sweet Potato", "Llez", "CC BY-SA 3.0"],
    ["Sweet and Sour Pork", "ProjectManhattan", "CC BY-SA 3.0"],
    ["Tabbouleh", "Miansari66", "CC0"],
    ["Tacos", "Larry Miller", "CC BY-SA 2.0"],
    ["Tacos al Pastor", "Matt Saunders", "CC BY-SA 3.0"],
    ["Tacu Tacu", "Suedehead from Buenos Aires, Argentina", "CC BY-SA 2.0"],
    ["Tagine", "BBouchra00", "CC BY-SA 4.0"],
    ["Taho", "Kguirnela", "CC BY 2.5"],
    ["Takoyaki", "加茂川の民", "CC0"],
    ["Tamales", "Nsaum75", "CC BY-SA 3.0"],
    ["Tandoori Chicken", "kspoddar", "CC BY-SA 2.0"],
    ["Taramasalata", "Robert Kindermann", "CC BY-SA 2.5"],
    ["Tea", "AntanO", "CC BY-SA 4.0"],
    ["Tempura", "Yaco*", "CC BY 2.0"],
    ["Tihlo", "Rod Waddington", "CC BY-SA 2.0"],
    ["Tinola", "Anne Molina", "CC BY-SA 4.0"],
    ["Tiradito", "Manuel González Olaechea", "CC BY 3.0"],
    ["Tiramisu", "Raffaele Diomede", "CC BY 2.0"],
    ["Tlayuda", "Bobak Ha'Eri", "CC BY-SA 2.5"],
    ["Toad in the Hole", "Robert Gibert", "Public domain"],
    ["Toast", "Rainer Z...", "CC BY-SA 3.0"],
    ["Tofu", "DryPot", "CC BY-SA 3.0"],
    ["Tom Kha Gai", "Evan Joshua Swigart (TheCulinaryGeek)", "CC BY 2.0"],
    ["Tom Yum", "Takeaway", "CC BY-SA 3.0"],
    ["Tomato", "Softeis", "CC BY-SA 3.0"],
    ["Tomato Soup", "Ella Olsson", "CC BY 2.0"],
    ["Tonkatsu", "ＫｏＺ", "CC BY-SA 4.0"],
    ["Torta", "Tamorlan", "CC BY 3.0"],
    ["Tortilla Espanola", "Kent Wang", "CC BY-SA 2.0"],
    ["Tteokbokki", "Popo le Chien", "CC0"],
    ["Tuna", "eric molina", "CC BY 2.0"],
    ["Turkey", "Patrick Fitzgerald", "CC BY 2.0"],
    ["Tzatziki", "Rainer Zenz", "CC BY-SA 3.0"],
    ["Udon", "加茂川の民", "CC0"],
    ["Vada Pav", "Rutvi Mistry", "CC BY-SA 4.0"],
    ["Vatapa", "Elingunnur", "CC BY 3.0"],
    ["Veggie Burger", "Roee Shpernik", "CC BY-SA 4.0"],
    ["Vindaloo", "Alpha from Melbourne, Australia", "CC BY-SA 2.0"],
    ["Vitello Tonnato", "jules", "CC BY 2.0"],
    ["Waffles", "Parkerman & Christie", "CC BY 2.0"],
    ["Watermelon", "Kwameghana", "CC BY-SA 4.0"],
    ["Wiener Schnitzel", "Kobako", "CC BY-SA 2.5"],
    ["Wonton Soup", "Sumit Surai", "CC BY-SA 4.0"],
    ["Wontons", "Sumit Surai", "CC BY-SA 4.0"],
    ["Xiao Long Bao", "Peachyeung316", "CC BY-SA 4.0"],
    ["Yakitori", "竹麦魚(Searobin)", "CC BY-SA 3.0"],
    ["Yangnyeom Chicken", "Jirangmoon", "CC BY-SA 4.0"],
    ["Yogurt", "Rainer Zenz", "CC BY-SA 3.0"],
    ["Yorkshire Pudding", "Sam Greenhalgh", "CC BY 2.0"],
    ["Youvetsi", "Robert Kindermann", "CC BY-SA 2.5"],
    ["Zaalouk", "Tamorlan", "CC BY-SA 3.0"],
    ["Zhajiangmian", "Archon6812", "CC BY-SA 3.0"],
  ];
})();
