// GENERATED by tools/fetch-objects.js — do not edit by hand.
// Maps a word from the Objects category to its Wikipedia lead photo as a finished
// URL. Each trailing comment is the article it came from.
(function () {
  window.MASQ_OBJECTS = {
    "Alarm Clock": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/2010-07-20_Black_windup_alarm_clock_face.jpg/500px-2010-07-20_Black_windup_alarm_clock_face.jpg",  // Alarm clock
    "Anchor": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Kotwica_SS_Pozna%C5%84.JPG/500px-Kotwica_SS_Pozna%C5%84.JPG",  // Anchor
    "Apron": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Woodworking_apron.webp/500px-Woodworking_apron.webp.png",  // Woodworking apron.webp
    "Axe": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Felling_axe.jpg/500px-Felling_axe.jpg",  // Axe
    "Backpack": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Rucksack1.jpg/500px-Rucksack1.jpg",  // Backpack
    "Bag": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Bolsas-de-asa-plana-interior-bolsapubli.jpg/500px-Bolsas-de-asa-plana-interior-bolsapubli.jpg",  // Bag
    "Bandage": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/HK_Plaster_Strips_1.JPG/500px-HK_Plaster_Strips_1.JPG",  // HK Plaster Strips 1.JPG
    "Baseball": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Baseball.jpg/500px-Baseball.jpg",  // Baseball.jpg
    "Basket": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Baskets_in_Haikou_03.jpg/500px-Baskets_in_Haikou_03.jpg",  // Basket
    "Basketball": "https://upload.wikimedia.org/wikipedia/commons/7/7a/Basketball.png",  // Basketball (ball)
    "Bathtub": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Clawfoot_bathtub.jpg/500px-Clawfoot_bathtub.jpg",  // Bathtub
    "Battery": "https://upload.wikimedia.org/wikipedia/commons/3/3b/Batteries.jpg",  // Electric battery
    "Bed": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/2008-04-12_Freilichtmuseum_Detmold_%2811%29.jpg/500px-2008-04-12_Freilichtmuseum_Detmold_%2811%29.jpg",  // Bed
    "Bell": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Small_Bell.png/500px-Small_Bell.png",  // Small Bell.png
    "Belt": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Germany_Belt-and-Buckle-02.jpg/500px-Germany_Belt-and-Buckle-02.jpg",  // Belt (clothing)
    "Bench": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/City_of_London_Cemetery_Memorial_Gardens_memorial_bench_seat_03.jpg/500px-City_of_London_Cemetery_Memorial_Gardens_memorial_bench_seat_03.jpg",  // City of London Cemetery Memorial Gardens memorial bench seat 03.jpg
    "Bicycle": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Left_side_of_Flying_Pigeon.jpg/500px-Left_side_of_Flying_Pigeon.jpg",  // Bicycle
    "Binder": "https://upload.wikimedia.org/wikipedia/commons/d/d9/Lever_arch_file.jpg",  // Ring binder
    "Binoculars": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Binocular_with_8x_magnification_and_42_mm_lens_diameter.jpg/500px-Binocular_with_8x_magnification_and_42_mm_lens_diameter.jpg",  // Binoculars
    "Blanket": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Baby_blanket.jpg/500px-Baby_blanket.jpg",  // Baby blanket.jpg
    "Blender": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Vitamix_Blender.jpg/500px-Vitamix_Blender.jpg",  // Blender
    "Board Game": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/US_Navy_110713-N-NT881-124_Personnel_Specialist_2nd_Class_James_Vail%2C_left%2C_and_Boatswain%27s_Mate_2nd_Class_Nathaniel_Eaton_play_board_games_with_ch.jpg/500px-US_Navy_110713-N-NT881-124_Personnel_Specialist_2nd_Class_James_Vail%2C_left%2C_and_Boatswain%27s_Mate_2nd_Class_Nathaniel_Eaton_play_board_games_with_ch.jpg",  // Board game
    "Bolt": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Bolt-with-nut.jpg/500px-Bolt-with-nut.jpg",  // Bolt (fastener)
    "Book": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Gutenberg_Bible%2C_Lenox_Copy%2C_New_York_Public_Library%2C_2009._Pic_01.jpg/500px-Gutenberg_Bible%2C_Lenox_Copy%2C_New_York_Public_Library%2C_2009._Pic_01.jpg",  // Book
    "Bookshelf": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Interior_of_Biblioth%C3%A8que_Mazarine_003.JPG/500px-Interior_of_Biblioth%C3%A8que_Mazarine_003.JPG",  // Bookcase
    "Boots": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Cliff_Climbers_Combat_boot_Shoes_Blast.png/500px-Cliff_Climbers_Combat_boot_Shoes_Blast.png",  // Boot
    "Bottle": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Bouteille.jpg/500px-Bouteille.jpg",  // Bottle
    "Bowl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/China%2C_Jiangxi_province%2C_Jingdezhen%2C_Ming_dynasty_%281368-1644%29%2C_Xuande_mark_-_Bowl_with_Decoration_of_the_%22Three_Friends%22_-_1953.631_-_Cleveland_Museum_of_Art.tif/lossy-page1-500px-thumbnail.tif.jpg",  // Bowl
    "Box": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/L%C3%A5da_-_Livrustkammaren_-_107142.tif/lossy-page1-500px-L%C3%A5da_-_Livrustkammaren_-_107142.tif.jpg",  // Box
    "Bracelet": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Gold_charm_bracelet.JPG/500px-Gold_charm_bracelet.JPG",  // Bracelet
    "Broom": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/BroomsforSale.jpg/500px-BroomsforSale.jpg",  // Broom
    "Bucket": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Gotland-Bottarve_Museumshof_07.jpg/500px-Gotland-Bottarve_Museumshof_07.jpg",  // Bucket
    "Button": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Reserveknapper_til_Hans%27_uniform.jpg/500px-Reserveknapper_til_Hans%27_uniform.jpg",  // Button
    "Cabinet": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Barberini_Cabinet_MET_DP106703.jpg/500px-Barberini_Cabinet_MET_DP106703.jpg",  // Cabinetry
    "Calculator": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Casio_calculator_JS-20WK_in_201901_002.jpg/500px-Casio_calculator_JS-20WK_in_201901_002.jpg",  // Calculator
    "Calendar": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Kalender_Indonesia.jpg/500px-Kalender_Indonesia.jpg",  // Calendar
    "Camera": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/LEI0440_Leica_IIIf_chrom_-_Sn._580566_1951-52-M39_Blitzsynchron_front_view-6531_hf-.jpg/500px-LEI0440_Leica_IIIf_chrom_-_Sn._580566_1951-52-M39_Blitzsynchron_front_view-6531_hf-.jpg",  // Camera
    "Can Opener": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Kitchen-Modern-Can-Opener.jpg/500px-Kitchen-Modern-Can-Opener.jpg",  // Can opener
    "Candle": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/LA2_Skultuna_kontorsljusstake.jpg/500px-LA2_Skultuna_kontorsljusstake.jpg",  // Candle
    "Chain": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Broad_chain_closeup.jpg/500px-Broad_chain_closeup.jpg",  // Chain
    "Chair": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Set_of_fourteen_side_chairs_MET_DP110780.jpg/500px-Set_of_fourteen_side_chairs_MET_DP110780.jpg",  // Chair
    "Chalk": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Sidewalk_chalk.jpg/500px-Sidewalk_chalk.jpg",  // Sidewalk chalk
    "Chandelier": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Versailles_Ch%C3%A2teau_de_Versailles_Innen_Grande_Galerie_05.jpg/500px-Versailles_Ch%C3%A2teau_de_Versailles_Innen_Grande_Galerie_05.jpg",  // Chandelier
    "Charger": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Car_Battery_Charger.jpg/500px-Car_Battery_Charger.jpg",  // Battery charger
    "Chess Set": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Chess_board_with_chess_set_in_opening_position_2012_PD_04.jpg/500px-Chess_board_with_chess_set_in_opening_position_2012_PD_04.jpg",  // Chess set
    "Chopsticks": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Many-chopsticks.jpg/500px-Many-chopsticks.jpg",  // Chopsticks
    "Clipboard": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Wood-clipboard.jpg/500px-Wood-clipboard.jpg",  // Clipboard
    "Clock": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Pendulum_clock_by_Jacob_Kock%2C_antique_furniture_photography%2C_IMG_0931_edit.jpg/500px-Pendulum_clock_by_Jacob_Kock%2C_antique_furniture_photography%2C_IMG_0931_edit.jpg",  // Clock
    "Clothes Iron": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Teal_and_white_electric_steam_iron_-_side_view.jpg/500px-Teal_and_white_electric_steam_iron_-_side_view.jpg",  // Clothes iron
    "Coat": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Mens_Coats_1872_Fashion_Plate.jpg/500px-Mens_Coats_1872_Fashion_Plate.jpg",  // Overcoat
    "Coffee Maker": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Moka_Express_sideview.png/500px-Moka_Express_sideview.png",  // Coffeemaker
    "Coin": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Kiloware.JPG/500px-Kiloware.JPG",  // Coin
    "Comb": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Plastic_comb%2C_2015-06-07.jpg/500px-Plastic_comb%2C_2015-06-07.jpg",  // Comb
    "Compass": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/2016_Busola.JPG/500px-2016_Busola.JPG",  // Compass
    "Computer": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Desktop_computer_system_diagram_%28English%29.svg/500px-Desktop_computer_system_diagram_%28English%29.svg.png",  // Desktop computer
    "Computer Mouse": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/3-Tasten-Maus_Microsoft.jpg/500px-3-Tasten-Maus_Microsoft.jpg",  // Computer mouse
    "Couch": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/2009-05-16_Main_office_lobby_at_Hampton_Forest_Apartments.jpg/500px-2009-05-16_Main_office_lobby_at_Hampton_Forest_Apartments.jpg",  // Couch
    "Crayon": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Crayones_cera.jpg/500px-Crayones_cera.jpg",  // Crayon
    "Credit Card": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Credit-cards.jpg/500px-Credit-cards.jpg",  // Credit card
    "Crown": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Saint_Edward%27s_Crown.jpg/500px-Saint_Edward%27s_Crown.jpg",  // Crown
    "Cup": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Cup_and_Saucer_LACMA_47.35.6a-b_%281_of_3%29.jpg/500px-Cup_and_Saucer_LACMA_47.35.6a-b_%281_of_3%29.jpg",  // Cup
    "Curtain": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Gordijnen_aan_venster.JPG/500px-Gordijnen_aan_venster.JPG",  // Curtain
    "Cutting Board": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Chopping_Board.jpg/500px-Chopping_Board.jpg",  // Cutting board
    "Desk": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Bureau_table_MET_DP108643.jpg/500px-Bureau_table_MET_DP108643.jpg",  // Desk
    "Dice": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/6sided_dice_%28cropped%29.jpg/500px-6sided_dice_%28cropped%29.jpg",  // Dice
    "Dictionary": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Woerterbuchstapel_Langenscheidt.jpg/500px-Woerterbuchstapel_Langenscheidt.jpg",  // Dictionary
    "Doll": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Poup%C3%A9e_c_1870.jpg/500px-Poup%C3%A9e_c_1870.jpg",  // Doll
    "Door": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/23_1-2-Fuji_Reala_pushed_2_stops_%285826165749%29.jpg/500px-23_1-2-Fuji_Reala_pushed_2_stops_%285826165749%29.jpg",  // 23 1-2-Fuji Reala pushed 2 stops (5826165749).jpg
    "Doorbell": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Chetham%27s_Library_2015_28.jpg/500px-Chetham%27s_Library_2015_28.jpg",  // Doorbell
    "Dress": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Afternoon_ensemble_MET_63.212a-b_CP4.jpg/500px-Afternoon_ensemble_MET_63.212a-b_CP4.jpg",  // Dress
    "Dresser": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Luikse_Commode%2C_KBS-FRB_01.jpg/500px-Luikse_Commode%2C_KBS-FRB_01.jpg",  // Chest of drawers
    "Drill": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Drill_scheme.svg/500px-Drill_scheme.svg.png",  // Drill
    "Drone": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/MQ-9_Reaper_UAV_%28cropped%29.jpg/500px-MQ-9_Reaper_UAV_%28cropped%29.jpg",  // Unmanned aerial vehicle
    "Drum": "https://upload.wikimedia.org/wikipedia/commons/2/2a/DrumMozartRegiment.jpg",  // Drum
    "Earbuds": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/B%26O_A8.JPG/500px-B%26O_A8.JPG",  // B&O A8.JPG
    "Earrings": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Pair_of_Earrings%2C_600s_AD%2C_Early_Byzantine%2C_gold%2C_pearls%2C_glass%2C_and_emeralds_-_Cleveland_Museum_of_Art_-_DSC08327.JPG/500px-Pair_of_Earrings%2C_600s_AD%2C_Early_Byzantine%2C_gold%2C_pearls%2C_glass%2C_and_emeralds_-_Cleveland_Museum_of_Art_-_DSC08327.JPG",  // Pair of Earrings, 600s AD, Early Byzantine, gold, pearls, glass, and emeralds - Cleveland Museum of Art - DSC08327.JPG
    "Envelope": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Envelope_-_Boonville_Address-000.jpg/500px-Envelope_-_Boonville_Address-000.jpg",  // Envelope
    "Eraser": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Office-pink-erasers.jpg/500px-Office-pink-erasers.jpg",  // Eraser
    "Fan": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Hatari_18_inch_fan.jpg/500px-Hatari_18_inch_fan.jpg",  // Fan (machine)
    "Feather": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/GuineaFeather.jpg/500px-GuineaFeather.jpg",  // GuineaFeather.jpg
    "Fence": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Westtown.jpg/500px-Westtown.jpg",  // Fence
    "Fire Extinguisher": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Wheeled_fire_extinguisher.jpg/500px-Wheeled_fire_extinguisher.jpg",  // Fire extinguisher
    "Fireplace": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Open_fireplace_with_icon.jpg/500px-Open_fireplace_with_icon.jpg",  // Fireplace
    "First Aid Kit": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/British_Red_Cross_First_Aid_Kits.jpg/500px-British_Red_Cross_First_Aid_Kits.jpg",  // First aid kit
    "Fishing Rod": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Fishing_Rods.jpg/500px-Fishing_Rods.jpg",  // Fishing rod
    "Flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/United_Nations_Flags_-_cropped.jpg/500px-United_Nations_Flags_-_cropped.jpg",  // Flag
    "Flashlight": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/LED_Flashlights.jpg/500px-LED_Flashlights.jpg",  // Flashlight
    "Flute": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Fl%C3%BBte_traversi%C3%A8re.png/500px-Fl%C3%BBte_traversi%C3%A8re.png",  // Western concert flute
    "Folder": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Yellow_folder.JPG/500px-Yellow_folder.JPG",  // File folder
    "Fork": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Assorted_forks.jpg/500px-Assorted_forks.jpg",  // Fork
    "Frisbee": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Frisbee_090719.jpg/500px-Frisbee_090719.jpg",  // Frisbee
    "Frying Pan": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Pfanne_%28Edelstahl%29.jpg/500px-Pfanne_%28Edelstahl%29.jpg",  // Frying pan
    "Game Controller": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/SNES-Controller-in-Hand.jpg/500px-SNES-Controller-in-Hand.jpg",  // Game controller
    "Gate": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Gate_of_the_BCR_Headquarters_Building_%28Bucharest%2C_Romania%29.jpg/500px-Gate_of_the_BCR_Headquarters_Building_%28Bucharest%2C_Romania%29.jpg",  // Gate
    "Gift": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Prezenty_EXP_096_%28ubt%29.JPG/500px-Prezenty_EXP_096_%28ubt%29.JPG",  // Gift
    "Glasses": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/2023_Okulary_korekcyjne.jpg/500px-2023_Okulary_korekcyjne.jpg",  // Glasses
    "Globe": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/The_Great_Globe%2C_Guyot_Hall%2C_Princeton_University.jpg/500px-The_Great_Globe%2C_Guyot_Hall%2C_Princeton_University.jpg",  // Globe
    "Gloves": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Centre_de_Documentaci%C3%B3_Museu_T%C3%A8xtil_de_Terrassa-_Reserves-_Teixits-_Guants002.JPG/500px-Centre_de_Documentaci%C3%B3_Museu_T%C3%A8xtil_de_Terrassa-_Reserves-_Teixits-_Guants002.JPG",  // Glove
    "Glue": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/AdhesivesForHouseUse004.jpg/500px-AdhesivesForHouseUse004.jpg",  // Adhesive
    "Guitar": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/GuitareClassique5.png/500px-GuitareClassique5.png",  // Guitar
    "Hair Dryer": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Braun_hair_dryer.jpg/500px-Braun_hair_dryer.jpg",  // Hair dryer
    "Hairbrush": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Conair-brush.jpg/500px-Conair-brush.jpg",  // Conair-brush.jpg
    "Hammer": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/OHM_-_Streithammer.jpg/500px-OHM_-_Streithammer.jpg",  // Hammer
    "Hat": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/A_fedora_hat%2C_made_by_Borsalino.jpg/500px-A_fedora_hat%2C_made_by_Borsalino.jpg",  // Fedora
    "Headphones": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/S%C5%82uchawki_referencyjne_K-701_firmy_AKG.jpg/500px-S%C5%82uchawki_referencyjne_K-701_firmy_AKG.jpg",  // Headphones
    "Helmet": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/A_Wide_Variety_Of_Helmets.png/500px-A_Wide_Variety_Of_Helmets.png",  // Helmet
    "Highlighter": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Yellow_Green_Orange_fluorescent_marker_on_white_background_%285417788017%29.jpg/500px-Yellow_Green_Orange_fluorescent_marker_on_white_background_%285417788017%29.jpg",  // Yellow Green Orange fluorescent marker on white background (5417788017).jpg
    "Hoodie": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Marvin_Jones_2019_%28cropped%29.jpg/500px-Marvin_Jones_2019_%28cropped%29.jpg",  // Hoodie
    "Hose": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Druckschlauch_Schmutzwasserkreiselpumpe.jpg/500px-Druckschlauch_Schmutzwasserkreiselpumpe.jpg",  // Hose
    "Jacket": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Jacket2-1.jpg/500px-Jacket2-1.jpg",  // Jacket
    "Jar": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Jar_of_yeast_extract.jpg/500px-Jar_of_yeast_extract.jpg",  // Jar
    "Jeans": "https://upload.wikimedia.org/wikipedia/commons/5/5a/Jeans.jpg",  // Jeans
    "Jump Rope": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Ghanaian_kid_%28skipping_rope%29_06_%28cropped%29.jpg/500px-Ghanaian_kid_%28skipping_rope%29_06_%28cropped%29.jpg",  // Skipping rope
    "Kettle": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Bernadotte_Wasserkessel.jpg/500px-Bernadotte_Wasserkessel.jpg",  // Kettle
    "Key": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Solex_99_30_padlock_with_keys_%28DSCF2659%29.jpg/500px-Solex_99_30_padlock_with_keys_%28DSCF2659%29.jpg",  // Lock and key
    "Keyboard": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Typing_example.ogv/330px--Typing_example.ogv.jpg",  // Computer keyboard
    "Kite": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Kitesflying.jpg/500px-Kitesflying.jpg",  // Kite
    "Knife": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Damascus_Bowie.jpg/500px-Damascus_Bowie.jpg",  // Knife
    "Ladder": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Ladder.webp/500px-Ladder.webp.png",  // Ladder
    "Ladle": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/A_copper_ladle.JPG/500px-A_copper_ladle.JPG",  // A copper ladle.JPG
    "Lamp": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Lampshades.jpg/500px-Lampshades.jpg",  // Lampshade
    "Lantern": "https://upload.wikimedia.org/wikipedia/commons/6/68/CNW_brakeman%27s_kerosene_lantern.JPG",  // Lantern
    "Laptop": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Lenovo_G500s_laptop-2905.jpg/500px-Lenovo_G500s_laptop-2905.jpg",  // Lenovo G500s laptop-2905.jpg
    "Lawn Mower": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Lawn_Mowing_DVIDS119604.jpg/500px-Lawn_Mowing_DVIDS119604.jpg",  // Lawn mower
    "Lighter": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/White_lighter_with_flame.JPG/500px-White_lighter_with_flame.JPG",  // Lighter
    "Lock": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Padlock_kl%C3%B3dka_ubt.JPG/500px-Padlock_kl%C3%B3dka_ubt.JPG",  // Padlock
    "Magazine": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Harper%27s_January.png/500px-Harper%27s_January.png",  // Magazine
    "Magnet": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/VFPt_horseshoe-magnet.svg/500px-VFPt_horseshoe-magnet.svg.png",  // Horseshoe magnet
    "Magnifying Glass": "https://upload.wikimedia.org/wikipedia/commons/c/c6/Mag_glass_request.jpg",  // Magnifying glass
    "Mailbox": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Green_letterbox_by_Martin_Vorel.jpeg/500px-Green_letterbox_by_Martin_Vorel.jpeg",  // Green letterbox by Martin Vorel.jpeg
    "Map": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/World_Map_1689.JPG/500px-World_Map_1689.JPG",  // Map
    "Marker": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Felt_Tip.jpg/500px-Felt_Tip.jpg",  // Marker pen
    "Matches": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Friction_d%27une_allumette.jpg/500px-Friction_d%27une_allumette.jpg",  // Match
    "Mattress": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Shifman_Mattress_Set.JPG/500px-Shifman_Mattress_Set.JPG",  // Mattress
    "Medal": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Portrait_medal_of_Cecilia_Gonzaga_%28obverse%29%3B_Innocence_and_a_Unicorn_in_a_Moonlit_Landscape_%28reverse%29_MET_DP-1241-015_%28cropped%29.jpg/500px-Portrait_medal_of_Cecilia_Gonzaga_%28obverse%29%3B_Innocence_and_a_Unicorn_in_a_Moonlit_Landscape_%28reverse%29_MET_DP-1241-015_%28cropped%29.jpg",  // Medal
    "Microphone": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Shure_mikrofon_55S.jpg/500px-Shure_mikrofon_55S.jpg",  // Microphone
    "Microwave": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Panasonic_NN-SD69LS_20220410.jpg/500px-Panasonic_NN-SD69LS_20220410.jpg",  // Microwave oven
    "Mirror": "https://upload.wikimedia.org/wikipedia/commons/5/52/Mirror.jpg",  // Mirror
    "Mittens": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Southern_Sami_Mittens_Norway.JPG/500px-Southern_Sami_Mittens_Norway.JPG",  // Mitten
    "Monitor": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/MonitorLCDlcd.svg/500px-MonitorLCDlcd.svg.png",  // Computer monitor
    "Mug": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Mug_of_Tea.JPG/500px-Mug_of_Tea.JPG",  // Mug
    "Nail": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Clou_127.jpg/500px-Clou_127.jpg",  // Nail (fastener)
    "Napkin": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Napkin_ring.jpg/500px-Napkin_ring.jpg",  // Napkin
    "Necklace": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Dasaneh_girls.JPG/500px-Dasaneh_girls.JPG",  // Necklace
    "Newspaper": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/NYTimes-Page1-11-11-1918.jpg/500px-NYTimes-Page1-11-11-1918.jpg",  // Newspaper
    "Nightstand": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Nightstand_2184073576.jpg/500px-Nightstand_2184073576.jpg",  // Nightstand
    "Notebook": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Notebooks.jpg/500px-Notebooks.jpg",  // Notebook
    "Oven": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Four_%C3%A0_c%C3%A9ramique_-_Japan_Aur%C3%A9a_-_2011-0403-_P1070446.JPG/500px-Four_%C3%A0_c%C3%A9ramique_-_Japan_Aur%C3%A9a_-_2011-0403-_P1070446.JPG",  // Oven
    "Painting": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/500px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg",  // Painting
    "Pants": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Trousers-colourisolated.jpg/500px-Trousers-colourisolated.jpg",  // Trousers
    "Paperclip": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Wanzijia.jpg/500px-Wanzijia.jpg",  // Paper clip
    "Passport": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Passports-assorted.jpg/500px-Passports-assorted.jpg",  // Passport
    "Pen": "https://upload.wikimedia.org/wikipedia/commons/a/ae/Carandache_Ecridor.jpg",  // Pen
    "Pencil": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Pencils_hb.jpg/500px-Pencils_hb.jpg",  // Pencil
    "Pencil Sharpener": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Sharpener_with_Pencil.jpg/500px-Sharpener_with_Pencil.jpg",  // Pencil sharpener
    "Perfume": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Bottles_of_Eau_de_Toilette.jpg/500px-Bottles_of_Eau_de_Toilette.jpg",  // Eau de toilette
    "Phone": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Wikipedia_homepage_on_a_large_Android_phone%2C_2015-04-16.jpg/500px-Wikipedia_homepage_on_a_large_Android_phone%2C_2015-04-16.jpg",  // Smartphone
    "Piano": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Steinway_Vienna_002.JPG/500px-Steinway_Vienna_002.JPG",  // Piano
    "Picture Frame": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Carved_frame_01_%2827133614537%29.jpg/500px-Carved_frame_01_%2827133614537%29.jpg",  // Picture frame
    "Pillow": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Pillows_on_a_hotel_bed.jpg/500px-Pillows_on_a_hotel_bed.jpg",  // Pillow
    "Plate": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Botanical_plate_with_spray_of_fruiting_Indian_Bean_Tree_MET_DP-1687-038_%28cropped%29.jpg/500px-Botanical_plate_with_spray_of_fruiting_Indian_Bean_Tree_MET_DP-1687-038_%28cropped%29.jpg",  // Plate (dishware)
    "Playing Cards": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/AcetoFive.JPG/500px-AcetoFive.JPG",  // Playing card
    "Pliers": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Tool-pliers.jpg/500px-Tool-pliers.jpg",  // Tool-pliers.jpg
    "Pot": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/AMC_pot.jpg/500px-AMC_pot.jpg",  // AMC pot.jpg
    "Printer": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/HP_Laserjet_5_DN_1.jpg/500px-HP_Laserjet_5_DN_1.jpg",  // Printer (computing)
    "Projector": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/IFA_2012_IMG_5767.JPG/500px-IFA_2012_IMG_5767.JPG",  // Projector
    "Purse": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Rachel%27s_New_Purse.jpg/500px-Rachel%27s_New_Purse.jpg",  // Rachel's New Purse.jpg
    "Puzzle": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Set_of_various_puzzles.jpg/500px-Set_of_various_puzzles.jpg",  // Puzzle
    "Radio": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Icom_IC-R7000_radio_receiver.jpg/500px-Icom_IC-R7000_radio_receiver.jpg",  // Radio receiver
    "Rake": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Wooden_rake.jpg/500px-Wooden_rake.jpg",  // Wooden rake.jpg
    "Razor": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Quattro_Titanium_Energy.jpg/500px-Quattro_Titanium_Energy.jpg",  // Razor
    "Refrigerator": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Open_refrigerator_with_food_at_night.jpg/500px-Open_refrigerator_with_food_at_night.jpg",  // Refrigerator
    "Remote Control": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Nuon-N2000-Remote-Control.jpg/500px-Nuon-N2000-Remote-Control.jpg",  // Remote control
    "Ring": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Ring_Ruby.jpg/500px-Ring_Ruby.jpg",  // Ring (jewellery)
    "Rolling Pin": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Chapaticooking.jpg/500px-Chapaticooking.jpg",  // Rolling pin
    "Rope": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Cordage_en_chanvre.jpg/500px-Cordage_en_chanvre.jpg",  // Rope
    "Router": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/ASR9006.jpg/500px-ASR9006.jpg",  // Router (computing)
    "Rubber Band": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Rubber_bands.jpg/500px-Rubber_bands.jpg",  // Rubber band
    "Rug": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Wollteppich_1.jpg/500px-Wollteppich_1.jpg",  // Carpet
    "Ruler": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Diverse%C2%B7Ma%C3%9Fst%C3%A4be%2C15.365.jpg/500px-Diverse%C2%B7Ma%C3%9Fst%C3%A4be%2C15.365.jpg",  // Ruler
    "Sandals": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Birki%27s_sandals.JPG/500px-Birki%27s_sandals.JPG",  // Birki's sandals.JPG
    "Saw": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Pily_rozplatnice.jpg/500px-Pily_rozplatnice.jpg",  // Saw
    "Scarf": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/100%25_Kaschmir_Wolle_vonk_kaschmirprodukte.de.jpg/500px-100%25_Kaschmir_Wolle_vonk_kaschmirprodukte.de.jpg",  // Scarf
    "Scissors": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Standard_household_scissors.jpg/500px-Standard_household_scissors.jpg",  // Scissors
    "Screw": "https://upload.wikimedia.org/wikipedia/commons/4/4c/Screws.jpg",  // Screw
    "Screwdriver": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Screw_Driver_display.jpg/500px-Screw_Driver_display.jpg",  // Screwdriver
    "Sewing Machine": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Singer_29_D_62_n%C3%A4hmaschine.jpg/500px-Singer_29_D_62_n%C3%A4hmaschine.jpg",  // Singer 29 D 62 nähmaschine.jpg
    "Shampoo": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Mild_shampoo.jpg/500px-Mild_shampoo.jpg",  // Mild shampoo.jpg
    "Shelf": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Atifells_de_cuina_andalusins%2C_Museu_Arqueol%C3%B2gic_Municipal_d%27Alcoi.JPG/500px-Atifells_de_cuina_andalusins%2C_Museu_Arqueol%C3%B2gic_Municipal_d%27Alcoi.JPG",  // Shelf (storage)
    "Shirt": "https://upload.wikimedia.org/wikipedia/commons/0/01/Charvet_shirt.jpg",  // Shirt
    "Shoes": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Skor_fr%C3%A5n_1700-_till_1960-talet_-_Nordiska_Museet_-_NMA.0056302.jpg/500px-Skor_fr%C3%A5n_1700-_till_1960-talet_-_Nordiska_Museet_-_NMA.0056302.jpg",  // Shoe
    "Shovel": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Grain_shovels%2C_Eling_Tide_Mill.jpg/500px-Grain_shovels%2C_Eling_Tide_Mill.jpg",  // Grain shovels, Eling Tide Mill.jpg
    "Shower": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/IMG_Duschender.jpg/500px-IMG_Duschender.jpg",  // Shower
    "Sink": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Luxury_sink.jpg/500px-Luxury_sink.jpg",  // Sink
    "Skateboard": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Hainerberg_Skate_Park_Now_Open_%286317086%29.jpg/500px-Hainerberg_Skate_Park_Now_Open_%286317086%29.jpg",  // Skateboard
    "Skirt": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Skirt.jpg/500px-Skirt.jpg",  // Skirt
    "Skis": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Carving-ski_1.jpg/500px-Carving-ski_1.jpg",  // Carving-ski 1.jpg
    "Sled": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Volunteer_Mushing_on_Wonder_Lake_%287065286379%29.jpg/500px-Volunteer_Mushing_on_Wonder_Lake_%287065286379%29.jpg",  // Sled
    "Sleeping Bag": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Israel_2_021_Sleeping_Rucksack-Tourist.jpg/500px-Israel_2_021_Sleeping_Rucksack-Tourist.jpg",  // Sleeping bag
    "Slippers": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Slippers.jpg/500px-Slippers.jpg",  // Slipper
    "Soap": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Handmade_soap_cropped_and_simplified.jpg/500px-Handmade_soap_cropped_and_simplified.jpg",  // Soap
    "Soccer Ball": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Adidas_Trionda_ball.jpg/500px-Adidas_Trionda_ball.jpg",  // Ball (association football)
    "Socks": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/HandKnittedWhiteLaceSock.jpg/500px-HandKnittedWhiteLaceSock.jpg",  // Sock
    "Spatula": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Fishslice1.jpg/500px-Fishslice1.jpg",  // Fishslice1.jpg
    "Speaker": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Logitech-usb-speakers.jpg/500px-Logitech-usb-speakers.jpg",  // Computer speakers
    "Sponge": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/%C3%89ponge_type_3_%281%29.jpg/500px-%C3%89ponge_type_3_%281%29.jpg",  // Sponge (tool)
    "Spoon": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Soup_Spoon.jpg/500px-Soup_Spoon.jpg",  // Spoon
    "Staircase": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Skylight%2C_chandelier_and_stairs%2C_Ashmolean_Museum%2C_Oxford.jpg/500px-Skylight%2C_chandelier_and_stairs%2C_Ashmolean_Museum%2C_Oxford.jpg",  // Staircase
    "Stamp": "https://upload.wikimedia.org/wikipedia/commons/b/b6/Nicaragua1_1913.jpg",  // Postage stamp
    "Stapler": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/2017_Zszywacz_biurowy.jpg/500px-2017_Zszywacz_biurowy.jpg",  // Stapler
    "Sticky Note": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Drawing_of_a_Post-It_Note_on_Post-It_Note.jpg/500px-Drawing_of_a_Post-It_Note_on_Post-It_Note.jpg",  // Drawing of a Post-It Note on Post-It Note.jpg
    "Stool": "https://upload.wikimedia.org/wikipedia/commons/5/56/TabouretAFDB.jpg",  // Stool (seat)
    "Stove": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Iron_stove.jpg/500px-Iron_stove.jpg",  // Kitchen stove
    "Straw": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Eight_drinking_straws_%284273846588%29.jpg/500px-Eight_drinking_straws_%284273846588%29.jpg",  // Drinking straw
    "Suitcase": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Suitcase1.jpg/500px-Suitcase1.jpg",  // Suitcase
    "Sunglasses": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Allef_Vinicius_2016-10-20_%28Unsplash%29_%28cropped%29.jpg/500px-Allef_Vinicius_2016-10-20_%28Unsplash%29_%28cropped%29.jpg",  // Sunglasses
    "Surfboard": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/WaikikiSurfboards.JPG/500px-WaikikiSurfboards.JPG",  // Surfboard
    "Sweater": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Selburose-sweater.jpg/500px-Selburose-sweater.jpg",  // Sweater
    "Swing": "https://upload.wikimedia.org/wikipedia/commons/a/a9/MoSchaukel.jpg",  // Swing (seat)
    "Table": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Beautiful_Baroque_gilded_table_from_the_Cinquantenaire_Museum_%28Bruxelles%2C_Belgium%29.jpg/500px-Beautiful_Baroque_gilded_table_from_the_Cinquantenaire_Museum_%28Bruxelles%2C_Belgium%29.jpg",  // Table (furniture)
    "Tablet": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/IPad_Mini_6_-_1.jpg/500px-IPad_Mini_6_-_1.jpg",  // Tablet computer
    "Tape": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Adhesive_tapes_clear.JPG/500px-Adhesive_tapes_clear.JPG",  // Adhesive tape
    "Tape Measure": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Tape_Measure_25%27_Klein_Tools.jpg/500px-Tape_Measure_25%27_Klein_Tools.jpg",  // Tape measure
    "Teapot": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Black_tea_pot_cropped.jpg/500px-Black_tea_pot_cropped.jpg",  // Teapot
    "Teddy Bear": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Teddy_bear_early_1900s_-_Smithsonian_Museum_of_Natural_History.jpg/500px-Teddy_bear_early_1900s_-_Smithsonian_Museum_of_Natural_History.jpg",  // Teddy bear
    "Telescope": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/100inchHooker.jpg/500px-100inchHooker.jpg",  // Telescope
    "Television": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Cptvdisplay.jpg/500px-Cptvdisplay.jpg",  // Television
    "Tennis Racket": "https://upload.wikimedia.org/wikipedia/commons/d/d2/Squash-racquet-and-ball.jpg",  // Racket (sports equipment)
    "Tent": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Tent_at_High_Shelf_Camp_cropped.jpg/500px-Tent_at_High_Shelf_Camp_cropped.jpg",  // Tent
    "Thermometer": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Mercury_Thermometer.jpg/500px-Mercury_Thermometer.jpg",  // Thermometer
    "Thermos": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Thermos.JPG/500px-Thermos.JPG",  // Vacuum flask
    "Ticket": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Azkals_versus_Maldives_Ticket.jpg/500px-Azkals_versus_Maldives_Ticket.jpg",  // Azkals versus Maldives Ticket.jpg
    "Tie": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Memphis_tie_1A.JPG/500px-Memphis_tie_1A.JPG",  // Necktie
    "Tissue": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/A_tissue_box.jpg/500px-A_tissue_box.jpg",  // A tissue box.jpg
    "Toaster": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Consumer_Reports_-_Hamilton_Beach_Digital_toaster.tiff/lossless-page1-500px-Consumer_Reports_-_Hamilton_Beach_Digital_toaster.tiff.png",  // Toaster
    "Toilet": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Toilet_photo.jpg/500px-Toilet_photo.jpg",  // Toilet
    "Toilet Paper": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Toiletpapier_%28Gobran111%29.jpg/500px-Toiletpapier_%28Gobran111%29.jpg",  // Toilet paper
    "Tongs": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Kitchen-tongs.png/500px-Kitchen-tongs.png",  // Tongs
    "Toolbox": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/%22site_toolbox_Armorgard_TuffBank_London_construction_site_20_November_2019.jpg%22.jpg/500px-%22site_toolbox_Armorgard_TuffBank_London_construction_site_20_November_2019.jpg%22.jpg",  // Toolbox
    "Toothbrush": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Toothbrush_20050716_004.jpg/500px-Toothbrush_20050716_004.jpg",  // Toothbrush
    "Toothpaste": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Toothpasteonbrush.jpg/500px-Toothpasteonbrush.jpg",  // Toothpaste
    "Towel": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Zusammengelegte_Handt%C3%BCcher.jpg/500px-Zusammengelegte_Handt%C3%BCcher.jpg",  // Towel
    "Trash Can": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Waste_container_in_Japan.jpg/500px-Waste_container_in_Japan.jpg",  // Waste container
    "Trophy": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Benin%2C_Championnats_nationaux_de_scrabble_2019%2C_troph%C3%A9es.jpg/500px-Benin%2C_Championnats_nationaux_de_scrabble_2019%2C_troph%C3%A9es.jpg",  // Benin, Championnats nationaux de scrabble 2019, trophées.jpg
    "Trumpet": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Yamaha_Trumpet_YTR-8335LA_crop.jpg/500px-Yamaha_Trumpet_YTR-8335LA_crop.jpg",  // Trumpet
    "USB Drive": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/SanDisk-Cruzer-USB-4GB-ThumbDrive.jpg/500px-SanDisk-Cruzer-USB-4GB-ThumbDrive.jpg",  // USB flash drive
    "Umbrella": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/M0354_000727-005_1.jpg/500px-M0354_000727-005_1.jpg",  // Umbrella
    "Vacuum": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Numatic_Henry_vacuum_cleaner_%283308986870%29_%28cropped%29.jpg/500px-Numatic_Henry_vacuum_cleaner_%283308986870%29_%28cropped%29.jpg",  // Vacuum cleaner
    "Vase": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Asian_vase.jpg/500px-Asian_vase.jpg",  // Asian vase.jpg
    "Violin": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Violin_VL100.png/500px-Violin_VL100.png",  // Violin
    "Wallet": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/WalletMpegMan.jpg/500px-WalletMpegMan.jpg",  // Wallet
    "Wardrobe": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Chifforobe.jpg/500px-Chifforobe.jpg",  // Chifforobe
    "Washing Machine": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/LG_%EB%93%9C%EB%9F%BC%EC%84%B8%ED%83%81%EA%B8%B0%EC%99%80_%EC%8B%9D%EA%B8%B0%EC%84%B8%EC%B2%99%EA%B8%B0%2C_%EC%98%81%EA%B5%AD%EC%84%9C_%EB%AC%BC%EC%82%AC%EC%9A%A9_%ED%9A%A8%EC%9C%A8_%EC%B5%9C%EC%9A%B0%EC%88%98_%EC%A0%9C%ED%92%88_%EC%88%98%EC%83%81.jpg/500px-LG_%EB%93%9C%EB%9F%BC%EC%84%B8%ED%83%81%EA%B8%B0%EC%99%80_%EC%8B%9D%EA%B8%B0%EC%84%B8%EC%B2%99%EA%B8%B0%2C_%EC%98%81%EA%B5%AD%EC%84%9C_%EB%AC%BC%EC%82%AC%EC%9A%A9_%ED%9A%A8%EC%9C%A8_%EC%B5%9C%EC%9A%B0%EC%88%98_%EC%A0%9C%ED%92%88_%EC%88%98%EC%83%81.jpg",  // Washing machine
    "Watch": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Casio_OCEANUS_OCW-S1350PC-1AJR_01.JPG/500px-Casio_OCEANUS_OCW-S1350PC-1AJR_01.JPG",  // Watch
    "Wheelbarrow": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/2008-07-15_Construction_wheelbarrow_at_Duke.jpg/500px-2008-07-15_Construction_wheelbarrow_at_Duke.jpg",  // Wheelbarrow
    "Whisk": "https://upload.wikimedia.org/wikipedia/commons/8/85/Schneebesen1.JPG",  // Whisk
    "Whistle": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Pea_Whistle.jpg/500px-Pea_Whistle.jpg",  // Whistle
    "Whiteboard": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/NCTR_Intern_Claire_Boyle_%2815558843862%29.jpg/500px-NCTR_Intern_Claire_Boyle_%2815558843862%29.jpg",  // Whiteboard
    "Window": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Atua_Kosua_shrine4.jpg/500px-Atua_Kosua_shrine4.jpg",  // Window
    "Wrench": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Gedore_No._7_combination_wrenches_6%E2%80%9319_mm.jpg/500px-Gedore_No._7_combination_wrenches_6%E2%80%9319_mm.jpg",  // Wrench
    "Yo-yo": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Yo-Yo-Plastic-Toy-Green.jpg/500px-Yo-Yo-Plastic-Toy-Green.jpg",  // Yo-yo
    "Zipper": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Coil_plastic_and_metal_zippers.jpg/500px-Coil_plastic_and_metal_zippers.jpg",  // Zipper
  };

  // Photographer and licence for each photo above, read by the Credits screen. An
  // empty name is a public-domain photo with no author on record.
  window.MASQ_OBJECT_CREDITS = [
    ["Alarm Clock", "Sun Ladder", "CC BY-SA 3.0"],
    ["Anchor", "Radomil", "CC BY-SA 3.0"],
    ["Apron", "FREERANGE - Burst", "CC0"],
    ["Axe", "タクナワン", "CC BY-SA 3.0"],
    ["Backpack", "de:Benutzer:sjr", "CC BY-SA 3.0"],
    ["Bag", "Bolsapubli", "CC BY-SA 3.0"],
    ["Bandage", "Saumparksda", "CC BY-SA 3.0"],
    ["Baseball", "Tage Olsin", "CC BY-SA 2.0"],
    ["Basket", "Anna Frodesiak", "CC0"],
    ["Basketball", "Reisio", "Public domain"],
    ["Bathtub", "Yannick Trottier (ytrottier)", "CC BY-SA 3.0"],
    ["Battery", "en:Brianiac", "Public domain"],
    ["Bed", "R-E-AL", "CC BY-SA 3.0"],
    ["Bell", "Kapoios2026", "CC0"],
    ["Belt", "CEphoto, Uwe Aranas", "CC BY-SA 3.0"],
    ["Bench", "Acabashi", "CC BY-SA 4.0"],
    ["Bicycle", "齐健 from Peking, People's Republic of China", "CC BY 2.0"],
    ["Binder", "Pavel Krok.", "CC BY-SA 2.5"],
    ["Binoculars", "Andreas Klehr", "CC BY-SA 4.0"],
    ["Blanket", "Durova", "CC BY-SA 3.0"],
    ["Blender", "Didriks", "CC BY 2.0"],
    ["Board Game", "U.S. Navy photo by Chief Mass Communication Specialist Steve Carlson", "Public domain"],
    ["Bolt", "Pavel Krok", "CC BY-SA 2.5"],
    ["Book", "NYC Wanderer (Kevin Eng)", "CC BY-SA 2.0"],
    ["Bookshelf", "Moonik", "CC BY-SA 3.0"],
    ["Boots", "Cliff Climbers", "CC BY-SA 2.5"],
    ["Bottle", "Aurélien Mole", "CC BY-SA 3.0"],
    ["Bowl", "", "CC0"],
    ["Box", "Unknown author", "Public domain"],
    ["Bracelet", "Mabsal", "Public domain"],
    ["Broom", "Edal Anton Lefterov", "CC BY-SA 3.0"],
    ["Bucket", "Wolfgang Sauber", "CC BY-SA 3.0"],
    ["Button", "Europeana staff photographer", "Public domain"],
    ["Cabinet", "Francesco Del Tuppo", "CC0"],
    ["Calculator", "Mc681", "CC BY-SA 4.0"],
    ["Calendar", "Rantemario", "CC BY-SA 4.0"],
    ["Camera", "Kameraprojekt Graz 2015", "CC BY-SA 4.0"],
    ["Can Opener", "Evan-Amos", "Public domain"],
    ["Candle", "LA2", "CC BY-SA 3.0"],
    ["Chain", "Toni Lozano", "CC BY 2.0"],
    ["Chair", "Thomas Chippendale", "CC0"],
    ["Chalk", "Nakaner", "CC BY-SA 4.0"],
    ["Chandelier", "Zairon", "CC BY-SA 4.0"],
    ["Charger", "Tatu Kosonen", "CC BY-SA 4.0"],
    ["Chess Set", "Bin im Garten", "CC BY-SA 3.0"],
    ["Chopsticks", "FiveRings", "CC BY-SA 3.0"],
    ["Clipboard", "Evan-amos", "Public domain"],
    ["Clock", "Christoph Braun", "CC0"],
    ["Clothes Iron", "Sokolikmawwer0", "CC BY-SA 3.0"],
    ["Coat", "Unknown author", "Public domain"],
    ["Coffee Maker", "Hans Chr. R. (edited by Saibo)", "CC BY-SA 3.0"],
    ["Coin", "Michael Sander", "CC BY-SA 4.0"],
    ["Comb", "Crisco 1492", "CC BY-SA 4.0"],
    ["Compass", "Jacek Halicki", "CC BY-SA 4.0"],
    ["Computer", "kjarrett", "CC BY 2.0"],
    ["Computer Mouse", "Darkone", "CC BY-SA 2.5"],
    ["Couch", "Ildar Sagdejev (Specious)", "CC BY-SA 4.0"],
    ["Crayon", "Jorge Barrios", "Public domain"],
    ["Credit Card", "Lotus Head", "CC BY-SA 2.5"],
    ["Crown", "Firebrace", "Public domain"],
    ["Cup", "Vincennes Porcelain (France, circa 1739–1756), Francois Binet (France, active 1750-1775, born 1731)", "Public domain"],
    ["Curtain", "Nieuw~commonswiki", "CC BY-SA 3.0"],
    ["Cutting Board", "Donovan Govan.", "CC BY-SA 3.0"],
    ["Desk", "John Townsend", "CC0"],
    ["Dice", "Diacritica", "CC BY-SA 3.0"],
    ["Dictionary", "Langenscheidt", "CC BY-SA 4.0"],
    ["Doll", "Andreas Praefcke", "Public domain"],
    ["Door", "DARREN ST0NE", "CC BY-SA 2.0"],
    ["Doorbell", "Photograph by Mike Peel (www.mikepeel.net).", "CC BY-SA 4.0"],
    ["Dress", "Metropolitan Museum of Art", "CC0"],
    ["Dresser", "Unknown author", "CC BY-SA 4.0"],
    ["Drill", "Włodzimierz Wysocki", "CC BY-SA 3.0"],
    ["Drone", "Lt. Col. Leslie Pratt", "Public domain"],
    ["Drum", "NPS", "Public domain"],
    ["Earbuds", "Kansai explorer", "CC BY 3.0"],
    ["Earrings", "Daderot", "CC0"],
    ["Envelope", "", "Public domain"],
    ["Eraser", "Evan-Amos", "Public domain"],
    ["Fan", "Peachyo", "CC BY-SA 4.0"],
    ["Feather", "Ben pcc", "Public domain"],
    ["Fence", "", "Public domain"],
    ["Fire Extinguisher", "z22", "CC BY-SA 3.0"],
    ["Fireplace", "Klaus Mueller", "CC BY-SA 2.0 de"],
    ["First Aid Kit", "Owain Davies", "CC BY-SA 3.0"],
    ["Fishing Rod", "Alabama Extension", "CC0"],
    ["Flag", "Tom Page", "CC BY-SA 2.0"],
    ["Flashlight", "Brownse10", "CC BY-SA 4.0"],
    ["Flute", "Tubamirum", "CC BY-SA 4.0"],
    ["Folder", "Jin Zan", "CC BY-SA 3.0"],
    ["Fork", "Mark A. Taff", "CC BY-SA 3.0 us"],
    ["Frisbee", "Petey21", "Public domain"],
    ["Frying Pan", "", "Public domain"],
    ["Game Controller", "Evan-Amos", "Public domain"],
    ["Gate", "Neoclassicism Enthusiast", "CC BY-SA 4.0"],
    ["Gift", "Tomasz Sienicki", "CC BY 4.0"],
    ["Glasses", "Jacek Halicki", "CC BY-SA 4.0"],
    ["Globe", "David Keddie", "CC BY-SA 4.0"],
    ["Gloves", "Kippelboy", "CC BY-SA 3.0"],
    ["Glue", "Babi Hijau", "Public domain"],
    ["Guitar", "Martin Möller Talk", "CC BY-SA 2.0 de"],
    ["Hair Dryer", "Lewis Ronald", "CC BY-SA 3.0"],
    ["Hairbrush", "Evan-Amos", "Public domain"],
    ["Hammer", "Wolfgang Sauber", "CC BY-SA 3.0"],
    ["Hat", "Kjetil Ree", "CC BY 2.5"],
    ["Headphones", "muzyczny.pl", "CC BY-SA 4.0"],
    ["Helmet", "Brandenads", "CC BY-SA 4.0"],
    ["Highlighter", "photosteve101", "CC BY 2.0"],
    ["Hoodie", "AlexanderJonesi", "CC BY-SA 2.0"],
    ["Hose", "Thiemo Schuff", "CC BY-SA 3.0"],
    ["Jacket", "Dudesleeper / Talk", "CC BY-SA 3.0"],
    ["Jar", "SKopp", "CC BY-SA 3.0"],
    ["Jeans", "uploaded by Juanmak", "Public domain"],
    ["Jump Rope", "Pambelle12", "CC BY-SA 4.0"],
    ["Kettle", "Holger Ellgaard", "CC BY-SA 3.0"],
    ["Key", "Trougnouf", "CC BY 4.0"],
    ["Keyboard", "NotFromUtrecht", "CC BY-SA 3.0"],
    ["Kite", "Jon Sullivan", "Public domain"],
    ["Knife", "Carter Cutlery", "CC BY 3.0"],
    ["Ladder", "Wikideas1", "CC0"],
    ["Ladle", "Thamizhpparithi Maari", "CC BY-SA 3.0"],
    ["Lamp", "John Hubbard", "CC BY-SA 3.0"],
    ["Lantern", "Sean Lamb", "CC BY-SA 2.0"],
    ["Laptop", "Raimond Spekking", "CC BY-SA 4.0"],
    ["Lawn Mower", "Staff Sgt. Brian Jopek", "Public domain"],
    ["Lighter", "Kimmo Palosaari", "Public domain"],
    ["Lock", "Tomasz Sienicki", "CC BY-SA 3.0"],
    ["Magazine", "Edward Penfield", "Public domain"],
    ["Magnet", "Geek3", "CC BY-SA 4.0"],
    ["Magnifying Glass", "WolfenSilva", "CC BY-SA 3.0"],
    ["Mailbox", "Martin Vorel", "Public Domain"],
    ["Map", "Gerard van Schagen", "Public domain"],
    ["Marker", "Prosthetic Head", "CC BY-SA 4.0"],
    ["Matches", "Yann SEGALEN", "CC BY-SA 4.0"],
    ["Mattress", "Yahquinn", "CC BY-SA 3.0"],
    ["Medal", "Pisanello", "CC0"],
    ["Microphone", "Holger.Ellgaard", "CC BY-SA 3.0"],
    ["Microwave", "Mrbeastmodeallday", "CC BY-SA 4.0"],
    ["Mirror", "Cgs", "CC BY-SA 3.0"],
    ["Mittens", "Thorguds", "CC BY-SA 3.0"],
    ["Monitor", "Михајло Анђелковић (edited by Mielon)", "CC BY-SA 3.0"],
    ["Mug", "Factorylad", "Public domain"],
    ["Nail", "Christophe.Finot", "CC BY-SA 3.0"],
    ["Napkin", "Neeta Lind", "CC BY 2.0"],
    ["Necklace", "Lourdeschr", "CC BY-SA 4.0"],
    ["Newspaper", "Charles Ransom Miller", "Public domain"],
    ["Nightstand", "Allie (edited by Herrick)", "CC BY-SA 2.0"],
    ["Notebook", "L.Marie", "CC BY 2.0"],
    ["Oven", "Esby", "CC BY-SA 3.0"],
    ["Painting", "Leonardo da Vinci", "Public domain"],
    ["Pants", "Ed Yourdon derivative work: Themightyquill", "CC BY-SA 2.0"],
    ["Paperclip", "Hawyih", "Public domain"],
    ["Passport", "Normadic, Quistnix, बिजय पोख्रेल, and the PRC Government (as indicated in the file for the PRC passport)", "CC BY-SA 4.0"],
    ["Pen", "Vadim Zhuravlev", "Public domain"],
    ["Pencil", "Dmgerman", "CC BY 3.0"],
    ["Pencil Sharpener", "Alexander Klink", "CC BY 3.0"],
    ["Perfume", "Shack", "CC BY-SA 4.0"],
    ["Phone", "Sage Ross", "CC BY-SA 4.0"],
    ["Piano", "Gryffindor", "CC BY-SA 3.0"],
    ["Picture Frame", "Tim Evanson", "CC BY-SA 2.0"],
    ["Pillow", "Amin", "CC BY-SA 4.0"],
    ["Plate", "Chelsea porcelain factory", "CC0"],
    ["Playing Cards", "Ron Maijen", "CC BY-SA 3.0"],
    ["Pliers", "Evan-Amos", "Public domain"],
    ["Pot", "Grap", "CC BY-SA 3.0"],
    ["Printer", "Thiemo Schuff", "CC BY-SA 3.0 de"],
    ["Projector", "Michael Movchin", "CC BY-SA 3.0"],
    ["Purse", "Tom Harpel", "CC BY 2.0"],
    ["Puzzle", "Lpele", "CC BY-SA 4.0"],
    ["Radio", "Mspecht", "CC BY-SA 3.0"],
    ["Rake", "Chmee2", "CC BY-SA 3.0"],
    ["Razor", "Marcus Wengenroth", "CC BY-SA 3.0"],
    ["Refrigerator", "W.carter", "CC BY-SA 4.0"],
    ["Remote Control", "Evan-Amos", "Public domain"],
    ["Ring", "ネックレス (A necklace)", "CC BY-SA 4.0"],
    ["Rolling Pin", "Alena", "CC BY 2.0"],
    ["Rope", "Ji-Elle", "CC BY-SA 3.0"],
    ["Router", "Redfox hq.", "CC BY 3.0"],
    ["Rubber Band", "FML", "CC BY-SA 2.5"],
    ["Rug", "Ryj", "Public domain"],
    ["Ruler", "Geof", "CC BY-SA 3.0"],
    ["Sandals", "Jpogi", "Public domain"],
    ["Saw", "Mnemosine", "Public domain"],
    ["Scarf", "Deepakkr18", "CC BY-SA 4.0"],
    ["Scissors", "Doggerelblogger", "CC BY-SA 4.0"],
    ["Screw", "Brianiac", "Public domain"],
    ["Screwdriver", "Fcb981", "CC BY 2.5"],
    ["Sewing Machine", "Alf van Beem", "CC0"],
    ["Shampoo", "Kulmalukko", "CC BY 3.0"],
    ["Shelf", "Joanbanjo", "CC BY-SA 3.0"],
    ["Shirt", "Author of the photograph unknown.", "CC BY-SA 3.0"],
    ["Shoes", "Birgit Brånvall", "CC BY 3.0 no"],
    ["Shovel", "Richard Avery", "CC BY-SA 4.0"],
    ["Shower", "Mitumial", "CC0"],
    ["Sink", "Amin", "CC BY-SA 4.0"],
    ["Skateboard", "U.S. Army USAGW by Lisa Bishop", "Public domain"],
    ["Skirt", "David Ring", "CC0"],
    ["Skis", "Kunstpiste (edited by Bobek)", "CC BY 3.0"],
    ["Sled", "Denali National Park and Preserve", "Public domain"],
    ["Sleeping Bag", "Daniel Maleck Lewy", "CC BY-SA 3.0"],
    ["Slippers", "PiccoloNamek", "CC BY-SA 3.0"],
    ["Soap", "Malene Thyssen, simplified by HLHJ", "CC BY 2.5"],
    ["Soccer Ball", "OhanaUnited Talk page", "CC BY-SA 4.0"],
    ["Socks", "Loggie-log", "Public domain"],
    ["Spatula", "FreeDigitalPhotos.net", "CC BY-SA 3.0"],
    ["Speaker", "Evan-Amos", "Public domain"],
    ["Sponge", "Lionel Allorge", "CC BY-SA 3.0"],
    ["Spoon", "Donovan Govan.", "CC BY-SA 3.0"],
    ["Staircase", "Gts-tg", "CC BY-SA 4.0"],
    ["Stamp", "Nicagura Post Office. Stamp artist unknown, work more than 70 years old.", "Public domain"],
    ["Stapler", "Jacek Halicki", "CC BY-SA 4.0"],
    ["Sticky Note", "Bladner32", "CC BY-SA 4.0"],
    ["Stool", "Besceh31", "CC BY-SA 2.5"],
    ["Stove", "Hardyplants", "CC BY 3.0"],
    ["Straw", "Horia Varlan", "CC BY 2.0"],
    ["Suitcase", "JEXP", "CC BY-SA 3.0"],
    ["Sunglasses", "Allef Vinicius seteales", "CC0"],
    ["Surfboard", "MercolaOverMerck", "CC BY-SA 3.0"],
    ["Sweater", "Nils R. Barth", "Public domain"],
    ["Swing", "MoSchle", "CC0"],
    ["Table", "Neoclassicism Enthusiast", "CC BY-SA 4.0"],
    ["Tablet", "Kyu3a", "CC BY-SA 4.0"],
    ["Tape", "BarberJP", "Public domain"],
    ["Tape Measure", "Klein Tools", "CC BY-SA 4.0"],
    ["Teapot", "Mendhak", "CC BY-SA 2.0"],
    ["Teddy Bear", "Smithsonian Museum of Natural History", "CC BY-SA 2.0"],
    ["Telescope", "Andrew Dunn", "CC BY-SA 2.0"],
    ["Television", "Wags05", "Public domain"],
    ["Tennis Racket", "", "Public domain"],
    ["Tent", "JJ Harrison", "CC BY-SA 3.0"],
    ["Thermometer", "Anonimski", "CC BY-SA 3.0"],
    ["Thermos", "Denae Bedard", "CC BY-SA 3.0"],
    ["Ticket", "RoyKabanlit", "Public domain"],
    ["Tie", "Affärside", "CC BY-SA 4.0"],
    ["Tissue", "Captain MarcusL", "CC BY-SA 4.0"],
    ["Toaster", "Consumer Reports", "CC BY-SA 4.0"],
    ["Toilet", "Amin", "CC BY-SA 4.0"],
    ["Toilet Paper", "Brandon Blinkenberg", "CC BY 2.5"],
    ["Tongs", "Sac86738", "Public domain"],
    ["Toolbox", "5Diraptor", "CC BY-SA 4.0"],
    ["Toothbrush", "Jonas Bergsten", "Public domain"],
    ["Toothpaste", "Thegreenj", "CC BY-SA 3.0"],
    ["Towel", "Mattes", "Public domain"],
    ["Trash Can", "Hyeonyoung Lee 21", "CC BY-SA 4.0"],
    ["Trophy", "Homo Anchorus", "CC BY-SA 4.0"],
    ["Trumpet", "Yamaha Corporation", "CC BY-SA 4.0"],
    ["USB Drive", "Evan-Amos", "Public domain"],
    ["Umbrella", "MONNIN Jacques", "CC BY-SA 3.0"],
    ["Vacuum", "Tnarik Innael", "CC BY-SA 2.0"],
    ["Vase", "Wallyworld76", "CC BY-SA 3.0"],
    ["Violin", "Just plain Bill", "CC0"],
    ["Wallet", "TheArmadillo.", "CC BY-SA 3.0"],
    ["Wardrobe", "Ewlyahoocom", "CC BY-SA 3.0"],
    ["Washing Machine", "LG전자", "CC BY 2.0"],
    ["Watch", "Kansai explorer", "CC BY-SA 3.0"],
    ["Wheelbarrow", "Ildar Sagdejev (Specious)", "CC BY-SA 4.0"],
    ["Whisk", "Peng", "CC BY-SA 3.0"],
    ["Whistle", "Zephyris", "CC BY-SA 3.0"],
    ["Whiteboard", "The U.S. Food and Drug Administration", "Public domain"],
    ["Window", "Shahadusadik", "CC BY-SA 4.0"],
    ["Wrench", "Lucasbosch", "CC BY-SA 3.0"],
    ["Yo-yo", "Evan-Amos", "Public domain"],
    ["Zipper", "Woodbine9", "CC BY-SA 4.0"],
  ];
})();
