// Masq role data: the role catalogs (Locations, Biomes, Cuisines, Movie/TV Genres, Music
// Genres) and a matching fake-role catalog for each, on window.MASQ_LOCATIONS_DATA. The
// word-only catalogs and their jester hints live in src/data_words.js.
//
// Real catalogs, then the fake-role catalogs that shadow them, then anything parked. Keys
// and their lists are sorted alphabetically throughout.
(function () {
  var biomeCatalog = {
    'Alpine Mountains': ['Bighorn Sheep', 'Condor', 'Eagle', 'Ibex', 'Marmot', 'Mountain Goat', 'Snow Leopard', 'Yak'],
    'Antarctic Ice Sheet (Frozen Ocean)': ['Albatross', 'Antarctic Krill', 'Beluga Whale', 'Emperor Penguin', 'Leopard Seal', 'Orca', 'Seal', 'Snow Petrel'],
    'Arctic Tundra': ['Arctic Fox', 'Arctic Hare', 'Lemming', 'Musk Ox', 'Polar Bear', 'Reindeer', 'Snowy Owl', 'Walrus'],
    'Australian Outback': ['Dingo', 'Emu', 'Kangaroo', 'Koala', 'Platypus', 'Tasmanian Devil', 'Thorny Devil', 'Wombat'],
    'Beach': ['Hermit Crab', 'Mussel', 'Pelican', 'Sand Dollar', 'Sandpiper', 'Sea Lion', 'Seagull', 'Starfish'],
    'Cave System': ['Bat', 'Blind Fish', 'Cricket', 'Salamander', 'Silverfish', 'Spider', 'Swiftlet', 'Troglodyte Beetle'],
    'Chaparral (Shrubland)': ['Bobcat', 'California Quail', 'Gecko', 'Jackrabbit', 'Kangaroo Rat', 'Mule Deer', 'Roadrunner', 'Tarantula'],
    'Coral Reef': ['Clownfish', 'Manta Ray', 'Moray Eel', 'Octopus', 'Parrotfish', 'Reef Shark', 'Sea Turtle', 'Seahorse'],
    'Deep Ocean': ['Anglerfish', 'Deep Sea Jellyfish', 'Dumbo Octopus', 'Fangtooth Fish', 'Giant Squid', 'Gulper Eel', 'Sperm Whale', 'Vampire Squid'],
    'Desert': ['Camel', 'Fennec Fox', 'Gila Monster', 'Meerkat', 'Rattlesnake', 'Sand Cat', 'Scorpion', 'Vulture'],
    'Freshwater River': ['Beaver', 'Catfish', 'Heron', 'Hippopotamus', 'Otter', 'Piranha', 'River Dolphin', 'Salmon'],
    'House': ['Cat', 'Dog', 'Goldfish', 'Hamster', 'Parakeet', 'Rabbit', 'Snake', 'Turtle'],
    'Jurassic Park': ['Ankylosaurus', 'Brachiosaurus', 'Pterodactyl', 'Spinosaurus', 'Stegosaurus', 'Triceratops', 'Tyrannosaurus Rex', 'Velociraptor'],
    'Mangrove Forest': ['Bengal Tiger', 'Cuckoo', 'Fiddler Crab', 'Frog', 'Mudskipper', 'Proboscis Monkey', 'Saltwater Crocodile', 'Tarsier'],
    'Prairie': ['Antelope', 'Badger', 'Bison', 'Coyote', 'Ferret', 'Meadowlark', 'Prairie Dog', 'Red-Tailed Hawk'],
    'Savanna': ['Cheetah', 'Elephant', 'Giraffe', 'Hyena', 'Lion', 'Rhino', 'Wildebeest', 'Zebra'],
    'Swamp': ['Alligator', 'Bullfrog', 'Crayfish', 'Egret', 'Muskrat', 'Snapping Turtle', 'Toad', 'Water Moccasin'],
    'Taiga (Boreal Forest)': ['Gray Owl', 'Gray Wolf', 'Grizzly Bear', 'Lynx', 'Moose', 'Red Squirrel', 'Snowshoe Hare', 'Wolverine'],
    'Temperate Forest': ['Black Bear', 'Deer', 'Owl', 'Porcupine', 'Red Fox', 'Squirrel', 'Wild Boar', 'Woodpecker'],
    'Tropical Rainforest': ['Anaconda', 'Gorilla', 'Harpy Eagle', 'Howler Monkey', 'Jaguar', 'Poison Dart Frog', 'Sloth', 'Toucan'],
    'Urban Environment (City)': ['Cockroach', 'Opossum', 'Pigeon', 'Raccoon', 'Rat', 'Skunk', 'Sparrow', 'Stray Cat'],
    'Volcanic Island': ['Fire Salamander', 'Galápagos Iguana', 'Hawaiian Hoary Bat', 'Lava Lizard', 'Peregrine Falcon', 'Vampire Ground Finch', 'Volcanic Mouse', 'Volcano Rabbit'],
  };

  // Dish names are deaccented, like the artists in musicGenreCatalog: the lists sort
  // plainly and nothing depends on the font having the glyph.
  var cuisineCatalog = {
    'American': ['BLT', 'Buffalo Wings', 'Cheeseburger', 'Chicken Fried Steak', 'Clam Chowder', 'Cobb Salad', 'Corn Dog', 'Grilled Cheese', 'Mac and Cheese', 'Meatloaf', 'Pecan Pie', 'Pulled Pork'],
    'Brazilian': ['Acai Bowl', 'Acaraje', 'Brigadeiro', 'Coxinha', 'Farofa', 'Feijoada', 'Moqueca', 'Pao de Queijo', 'Pastel', 'Picanha', 'Quindim', 'Vatapa'],
    'British': ['Bangers and Mash', 'Beef Wellington', 'Black Pudding', 'Cornish Pasty', 'Eton Mess', 'Fish and Chips', 'Full English Breakfast', 'Scotch Egg', "Shepherd's Pie", 'Sticky Toffee Pudding', 'Toad in the Hole', 'Yorkshire Pudding'],
    'Chinese': ['Char Siu', 'Congee', 'Dan Dan Noodles', 'Dim Sum', 'Hot Pot', 'Kung Pao Chicken', 'Mapo Tofu', 'Peking Duck', 'Sweet and Sour Pork', 'Wonton Soup', 'Xiao Long Bao', 'Zhajiangmian'],
    'Ethiopian': ['Beyaynetu', 'Dabo Kolo', 'Doro Wat', 'Fir Fir', 'Genfo', 'Gored Gored', 'Himbasha', 'Injera', 'Kitfo', 'Kocho', 'Shiro', 'Tihlo'],
    'Filipino': ['Adobo', 'Bibingka', 'Bicol Express', 'Halo-Halo', 'Kare-Kare', 'Lechon', 'Lumpia', 'Pancit', 'Sinigang', 'Sisig', 'Taho', 'Tinola'],
    'French': ['Baguette', 'Bouillabaisse', 'Cassoulet', 'Coq au Vin', 'Creme Brulee', 'Croissant', 'Croque Monsieur', 'Duck Confit', 'Escargot', 'Macaron', 'Quiche Lorraine', 'Ratatouille'],
    'German': ['Bratwurst', 'Currywurst', 'Kasespatzle', 'Leberkase', 'Maultaschen', 'Pretzel', 'Rouladen', 'Sauerbraten', 'Schwarzwalder Kirschtorte', 'Spatzle', 'Stollen', 'Wiener Schnitzel'],
    'Greek': ['Baklava', 'Dolmades', 'Gyro', 'Horiatiki Salad', 'Kleftiko', 'Moussaka', 'Pastitsio', 'Souvlaki', 'Spanakopita', 'Taramasalata', 'Tzatziki', 'Youvetsi'],
    'Indian': ['Biryani', 'Butter Chicken', 'Chaat', 'Chole Bhature', 'Dosa', 'Idli', 'Palak Paneer', 'Rogan Josh', 'Samosa', 'Tandoori Chicken', 'Vada Pav', 'Vindaloo'],
    'Italian': ['Bruschetta', 'Carbonara', 'Focaccia', 'Gnocchi', 'Lasagna', 'Minestrone', 'Osso Buco', 'Panna Cotta', 'Risotto', 'Saltimbocca', 'Tiramisu', 'Vitello Tonnato'],
    'Japanese': ['Chawanmushi', 'Katsu Curry', 'Miso Soup', 'Okonomiyaki', 'Onigiri', 'Ramen', 'Soba', 'Sushi', 'Takoyaki', 'Tempura', 'Tonkatsu', 'Yakitori'],
    'Korean': ['Banchan', 'Bibimbap', 'Bulgogi', 'Gimbap', 'Japchae', 'Jjajangmyeon', 'Kimchi Jjigae', 'Mandu', 'Samgyeopsal', 'Sundubu Jjigae', 'Tteokbokki', 'Yangnyeom Chicken'],
    'Lebanese': ['Baba Ghanoush', 'Falafel', 'Fattoush', 'Hummus', 'Kafta', 'Kibbeh', 'Knafeh', 'Manakish', 'Mujadara', 'Sfiha', 'Shawarma', 'Tabbouleh'],
    'Mexican': ['Birria', 'Chilaquiles', 'Enchiladas', 'Esquites', 'Guacamole', 'Mole Poblano', 'Pozole', 'Quesadilla', 'Tacos al Pastor', 'Tamales', 'Tlayuda', 'Torta'],
    'Moroccan': ['Baghrir', 'Bastilla', 'Briouat', 'Chebakia', 'Couscous', 'Harcha', 'Harira', 'Mechoui', 'Msemen', 'Rfissa', 'Tagine', 'Zaalouk'],
    'Peruvian': ['Aji de Gallina', 'Anticuchos', 'Causa', 'Ceviche', 'Chicharron', 'Lomo Saltado', 'Papa a la Huancaina', 'Picarones', 'Pollo a la Brasa', 'Rocoto Relleno', 'Tacu Tacu', 'Tiradito'],
    'Spanish': ['Churros', 'Croquetas', 'Fabada', 'Gambas al Ajillo', 'Gazpacho', 'Jamon Iberico', 'Paella', 'Patatas Bravas', 'Pisto', 'Pulpo a la Gallega', 'Salmorejo', 'Tortilla Espanola'],
    'Thai': ['Green Curry', 'Khao Soi', 'Larb', 'Mango Sticky Rice', 'Massaman Curry', 'Pad Kra Pao', 'Pad See Ew', 'Pad Thai', 'Satay', 'Som Tam', 'Tom Kha Gai', 'Tom Yum'],
    'Vietnamese': ['Banh Mi', 'Banh Xeo', 'Bun Bo Hue', 'Bun Cha', 'Bun Rieu', 'Cao Lau', 'Cha Ca', 'Com Tam', 'Goi Cuon', 'Hu Tieu', 'Mi Quang', 'Pho'],
  };

  var locationCatalog = {
    'Airplane': ['Air Marshal', 'Bartender', 'Crying Baby', 'Flight Attendant', 'Flight Engineer', 'Passenger', 'Pilot', 'Stowaway'],
    'Airport': ['Crew Member', 'Customs Officer', 'Gate Agent', 'Passenger', 'Pilot', 'Ramp Agent', 'Security Officer', 'Tourist'],
    'Bank': ['Account Holder', 'Armored Car Driver', 'Auditor', 'Branch Manager', 'Loan Officer', 'Robber', 'Security Guard', 'Teller'],
    'Beach': ['Ice Cream Vendor', 'Lifeguard', 'Photographer', 'Sandcastle Builder', 'Sunbather', 'Surfer', 'Tourist', 'Volleyball Player'],
    'Campground': ['Bear', 'Biker', 'Camper', 'Campfire Cook', 'Eagle Scout', 'Hiker', 'Park Ranger', 'Wildlife Photographer'],
    'Casino': ['Bartender', 'Bouncer', 'Cardsharp', 'Dealer', 'Drunkard', 'Gambler', 'Head of Security', 'Pit Boss'],
    'Circus Tent': ['Acrobat', 'Animal Tamer', 'Circus-Goer', 'Clown', 'Juggler', 'Knife Thrower', 'Magician', 'Ringmaster'],
    'Convenience Store': ['Alcoholic', 'Cashier', 'Delivery Driver', 'Food Roller Operator', 'Late Night Customer', 'Manager', 'Regular', 'Shoplifter'],
    'Corporate Party': ['Accountant', 'Administrative Assistant', 'CEO', 'Courier', 'Emcee', 'Intern', 'Manager', 'Party Crasher'],
    'Cruise Ship': ['Attendant', 'Bartender', 'Captain', 'Cook', 'Musician', 'Passenger', 'Radio Operator', 'Stowaway'],
    'Crusader Army': ['Archer', 'Bishop', 'Captive', 'Knight', 'Monk', 'Saracen', 'Servant', 'Squire'],
    'Day Spa': ['Beautician', 'Customer', 'Dermatologist', 'Makeup Specialist', 'Masseur', 'Nail Specialist', 'Receptionist', 'Stylist'],
    'Elementary School': ['Janitor', 'Librarian', 'Lunch Lady', 'Nurse', 'Principal', 'Student', 'Substitute Teacher', 'Teacher'],
    'Embassy': ['Ambassador', 'Bureaucrat', 'Diplomat', 'Interpreter', 'Refugee', 'Secretary', 'Security Guard', 'Tourist'],
    'Fast Food Restaurant': ['Cashier', 'Customer', 'Delivery Driver', 'Disgruntled Teenager Working Their First Job', 'Drive-Thru Worker', 'Fry Cook', 'Health Inspector', 'Manager'],
    'Fire Station': ['Arson Investigator', 'Captain', 'Dispatcher', 'Firefighter', 'Paramedic', 'Rescue Dog', 'Rookie', 'Station Cook'],
    'Gym': ['Athlete', 'Front Desk Worker', "New Year's Resolution Member", 'Personal Trainer', 'Runner', 'Swimmer', 'Weightlifter', 'Yoga Instructor'],
    'Hospital': ['EMT', 'Janitor', 'Nurse', 'Paramedic', 'Patient', 'Receptionist', 'Surgeon', 'Therapist'],
    'Hotel': ['Bellhop', 'Concierge', 'Front Desk Clerk', 'Guest', 'Housekeeper', 'Manager', 'Room Service Worker', 'Valet Parking Attendant'],
    'Military Base': ['Colonel', 'Deserter', 'Drill Instructor', 'Drone Operator', 'Medic', 'Non-Commissioned Officer', 'Private', 'Sentry'],
    'Movie Studio': ['Actor', 'Cameraman', 'Costume Designer', 'Director', 'Extra', 'Producer', 'Sound Engineer', 'Stuntman'],
    'Movie Theater': ['Concession Worker', 'Couple', 'Film Critic', 'Manager', 'Projectionist', 'Teenager', 'Ticket Seller', 'Usher'],
    'Night Club': ['Bartender', 'Bottle Service Waitress', 'Bouncer', 'Dancer', 'DJ', 'Model', 'Pick-Up Artist', 'Regular'],
    'Pirate Ship': ['Cabin Boy', 'Cook', 'First Mate', 'Gunner', 'Parrot', 'Seaman', 'Shackled Prisoner', 'Swashbuckling Captain'],
    'Polar Station': ['Biologist', 'Expedition Leader', 'Geoscientist', 'Hydrologist', 'Medic', 'Meteorologist', 'Photographer', 'Radio Operator'],
    'Police Station': ['Attorney', 'Cop', 'Detective', 'Forensic Scientist', 'Journalist', 'Lieutenant', 'Patrol Officer', 'Suspect'],
    'Restaurant': ['Annoying Karen', 'Dishwasher', 'Food Critic', 'Head Chef', 'Host', 'Manager', 'Sommelier', 'Waiter'],
    'Service Station': ['Biker', 'Car Washer', 'Driver', 'Electrical Technician', 'Manager', 'Service Receptionist', 'Tire Technician', 'Tow Truck Driver'],
    'Space Station': ['Aerospace Engineer', 'Alien', 'Astronaut', 'Doctor', 'Mission Commander', 'Pilot', 'Research Engineer', 'Wealthy Tourist'],
    'Sports Stadium': ['Coach', 'Commentator', 'Concession Worker', 'Mascot', 'Player', 'Referee', 'Security Guard', 'Superfan'],
    'Submarine': ['Commander', 'Cook', 'Electrical Officer', 'Navigator', 'New Recruit', 'Radio Operator', 'Sailor', 'Sonar Operator'],
    'Supermarket': ['Butcher', 'Cart Wrangler', 'Cashier', 'Custodian', 'Delivery Man', 'Manager', 'Shopper', 'Stock Worker'],
    'Theatre': ['Actor', 'Audience Member', 'Coatroom Attendant', 'Director', 'Prompter', 'Stage Hand', 'Understudy', 'Usher'],
    'Theme Park / Amusement Park': ['Character Performer', 'Clown', 'Food Vendor', 'Kid', 'Merchandise Vendor', 'Parent', 'Ride Operator', 'Visitor'],
    'Train': ['Backpacker', 'Conductor', 'Dining Car Cook', 'Passenger', 'Passenger Car Attendant', 'Stoker', 'Ticket Taker', 'Vendor'],
    'University': ['Campus Security', 'Dean', 'Frat Member', 'Freshman', 'Graduate Student', 'Professor', 'Resident Advisor', 'Tour Guide'],
    'Zoo': ['Caretaker', 'General Manager', 'Guide', 'Janitor', 'Vendor', 'Veterinarian', 'Visitor', 'Zookeeper'],
  };

  var movieTvCatalog = {
    'Action': ['Bad Boys', 'Die Hard', 'Fast and Furious', 'John Wick', 'Kill Bill', 'Lethal Weapon', 'Mission Impossible', 'Rambo', 'Speed', 'Taken', 'Terminator', 'The Bourne Identity', 'Top Gun', 'Transformers'],
    'Adventure': ['Indiana Jones', 'Jumanji: Welcome to the Jungle', 'Jurassic Park', 'Life of Pi', 'Lost', 'National Treasure', 'Pirates of the Caribbean', 'The Goonies', 'The Jungle Book', 'The Mandalorian', 'The Mummy'],
    'Aliens': ['A Quiet Place', 'Alien', 'Arrival', 'Close Encounters of the Third Kind', 'District 9', 'Edge of Tomorrow', 'Independence Day', 'Men in Black', 'Nope', 'Predator', 'Prometheus', 'Signs', 'Starship Troopers', 'The X-Files', 'War of the Worlds'],
    'Animated': ['Coco', 'Despicable Me', 'Finding Nemo', 'Frozen', 'How to Train Your Dragon', 'Inside Out', 'Kung Fu Panda', 'Moana', 'Monsters, Inc.', 'Ratatouille', 'Shrek', 'The Lion King', 'Toy Story', 'Up', 'Zootopia'],
    'Anime': ['Attack on Titan', 'Cowboy Bebop', 'Death Note', 'Demon Slayer', 'Dragon Ball Z', 'Fullmetal Alchemist: Brotherhood', "Howl's Moving Castle", 'Jujutsu Kaisen', 'My Hero Academia', 'My Neighbor Totoro', 'Naruto', 'One Piece', 'Pokémon', 'Princess Mononoke', 'Spirited Away'],
    'Biopic / Docudrama': ['127 Hours', 'A Beautiful Mind', 'Apollo 13', 'Argo', 'Bohemian Rhapsody', 'Captain Phillips', 'Chernobyl', 'Elvis', 'Oppenheimer', "Schindler's List", 'Straight Outta Compton', 'The Social Network', 'The Theory of Everything', 'The Wolf of Wall Street', 'Walk the Line'],
    'Body Horror': ['An American Werewolf in London', 'Annihilation', 'Death Becomes Her', 'Hannibal', "Jennifer's Body", 'The Fly', 'The Substance', 'The Thing'],
    'Christmas': ['A Christmas Carol', 'A Christmas Story', 'Elf', 'Home Alone', 'How the Grinch Stole Christmas', "It's a Wonderful Life", 'Jingle All the Way', 'Klaus', 'Miracle on 34th Street', 'The Nightmare Before Christmas', 'The Polar Express', 'The Santa Clause'],
    'Comedy': ['Airplane!', 'Anchorman', 'Borat', 'Bridesmaids', 'Dumb and Dumber', 'Friends', 'Ghostbusters', 'Mean Girls', 'Napoleon Dynamite', 'Parks and Recreation', 'Step Brothers', 'Superbad', 'The Hangover', 'The Office', 'Tropic Thunder'],
    'Cop': ['21 Jump Street', 'Beverly Hills Cop', 'Brooklyn Nine-Nine', 'End of Watch', 'Hot Fuzz', 'Rush Hour', 'The Other Guys', 'Training Day'],
    'Courtroom Drama': ['12 Angry Men', 'A Few Good Men', 'A Time to Kill', 'Erin Brockovich', 'Law & Order', 'Legally Blonde', 'My Cousin Vinny', 'Philadelphia', 'Suits', 'The Lincoln Lawyer'],
    'Crime': ['American Gangster', 'Breaking Bad', 'Casino', 'GoodFellas', 'Heat', 'Narcos', 'Ozark', 'Peaky Blinders', 'Pulp Fiction', 'Reservoir Dogs', 'Scarface', 'The Departed', 'The Godfather', 'The Sopranos', 'The Wire'],
    'Cyberpunk': ['Alita: Battle Angel', 'Blade Runner', 'Ex Machina', 'Ghost in the Shell', 'Mr. Robot', 'Ready Player One', 'RoboCop', 'The Matrix', 'Total Recall', 'Tron'],
    'Disaster': ['2012', 'Armageddon', 'Contagion', "Dante's Peak", 'Deep Impact', 'San Andreas', 'The Day After Tomorrow', 'The Perfect Storm', 'Twister'],
    'Dystopian': ['1984', 'Black Mirror', 'Children of Men', 'Divergent', 'Minority Report', 'Severance', 'Snowpiercer', "The Handmaid's Tale", 'The Hunger Games', 'The Maze Runner', 'V for Vendetta'],
    'Fantasy': ['Aladdin', 'Beauty and the Beast', 'Coraline', 'Game of Thrones', 'Harry Potter', 'Maleficent', "Pan's Labyrinth", 'Percy Jackson', 'The Chronicles of Narnia', 'The Hobbit', 'The Lord of the Rings', 'The Princess Bride', 'The Witcher', 'The Wizard of Oz', 'Willow'],
    'Found Footage': ['Chronicle', 'Cloverfield', 'Paranormal Activity', '[REC]', 'Searching', 'The Blair Witch Project', 'The Visit', 'Unfriended'],
    'Heist': ['Baby Driver', 'Inside Man', 'Lupin', 'Money Heist', 'Now You See Me', "Ocean's Eleven", 'Point Break', 'The Italian Job', 'The Sting', 'The Town'],
    'Historical Epic': ['300', 'Ben-Hur', 'Braveheart', 'Gladiator', 'Kingdom of Heaven', 'Lawrence of Arabia', 'Shogun', 'Spartacus', 'The Last Samurai', 'Troy', 'Vikings'],
    'Horror': ['American Horror Story', 'Get Out', 'Hereditary', 'Insidious', 'It', 'Midsommar', 'Poltergeist', 'Sinister', 'The Babadook', 'The Conjuring', 'The Exorcist', 'The Haunting of Hill House', 'The Ring', 'The Shining', 'Us'],
    'Monster': ['Anaconda', 'Cocaine Bear', 'Godzilla', 'Godzilla Minus One', 'Jaws', 'Jurassic World', 'King Kong', 'Kong: Skull Island', 'Pacific Rim', 'Stranger Things', 'The Meg', 'Tremors'],
    'Musical': ['Chicago', 'Glee', 'Grease', 'Hairspray', 'Hamilton', 'La La Land', 'Les Misérables', 'Mamma Mia!', 'Moulin Rouge!', 'The Greatest Showman', 'The Sound of Music', 'West Side Story', 'Wicked'],
    'Mystery / Whodunit': ['Chinatown', 'Clue', 'Death on the Nile', 'Glass Onion', 'Knives Out', 'Murder on the Orient Express', 'Only Murders in the Building', 'Rear Window', 'Sherlock Holmes', 'The Usual Suspects', 'True Detective'],
    'Post-Apocalyptic': ['Bird Box', 'Fallout', 'I Am Legend', 'Mad Max: Fury Road', 'Silo', 'The Book of Eli', 'The Last of Us', 'The Road', 'WALL-E', 'Waterworld'],
    'Prison': ['American History X', 'Con Air', 'Cool Hand Luke', 'Escape from Alcatraz', 'Holes', 'Orange Is the New Black', 'Prison Break', 'The Great Escape', 'The Green Mile', 'The Shawshank Redemption'],
    'Psychological Thriller': ['Black Swan', 'Fight Club', 'Gone Girl', 'Memento', 'Mindhunter', 'Oldboy', 'Prisoners', 'Requiem for a Dream', 'Shutter Island', 'Split', 'The Sixth Sense', 'You'],
    'Romance': ['(500) Days of Summer', '10 Things I Hate About You', 'Bridgerton', 'Clueless', 'Crazy Rich Asians', 'Easy A', 'Love Actually', 'Pretty Woman', 'Pride and Prejudice', 'Sex Education', 'The Notebook', 'The Summer I Turned Pretty', 'Titanic', "To All the Boys I've Loved Before", 'Twilight'],
    'Sci-Fi / Space Opera': ['2001: A Space Odyssey', 'Avatar', 'Doctor Who', 'Dune', 'E.T.', 'Guardians of the Galaxy', 'Inception', 'Interstellar', 'Star Trek', 'Star Wars', 'The Expanse', 'The Fifth Element'],
    'Slasher': ['A Nightmare on Elm Street', 'Candyman', "Child's Play", 'Friday the 13th', 'Halloween', 'Happy Death Day', 'I Know What You Did Last Summer', 'Scream', 'The Cabin in the Woods', 'The Texas Chainsaw Massacre', 'X'],
    'Sports': ['Coach Carter', 'Creed', 'Friday Night Lights', 'Happy Gilmore', 'Million Dollar Baby', 'Miracle', 'Moneyball', 'Remember the Titans', 'Rocky', 'Space Jam', 'Ted Lasso', 'The Blind Side', 'The Sandlot'],
    'Spy': ['Atomic Blonde', 'Austin Powers', 'Bridge of Spies', 'Casino Royale', 'Killing Eve', 'Kingsman', 'Salt', 'Skyfall', 'The Americans', 'True Lies'],
    'Superhero': ['Black Panther', 'Captain America', 'Daredevil', 'Deadpool', 'Invincible', 'Iron Man', 'Logan', 'Spider-Man', 'Superman', 'The Avengers', 'The Batman', 'The Boys', 'The Dark Knight', 'The Incredibles', 'Wonder Woman'],
    'Survival': ['Alive', 'Cast Away', 'Everest', 'Gravity', 'Into the Wild', 'The Grey', 'The Impossible', 'The Martian', 'The Revenant', 'Yellowjackets'],
    'Teen Drama': ['13 Reasons Why', 'Booksmart', 'Dead Poets Society', 'Euphoria', 'Lady Bird', 'Love, Simon', 'Moonlight', 'Riverdale', 'The Breakfast Club', 'The Edge of Seventeen', 'The Holdovers', 'The Perks of Being a Wallflower'],
    'Thriller': ['A Simple Favor', 'Big Little Lies', 'Misery', 'Nightcrawler', 'Panic Room', 'Parasite', 'Se7en', 'The Girl on the Train', 'The Silence of the Lambs', 'Zodiac'],
    'Time Travel': ['12 Monkeys', 'About Time', 'Back to the Future', "Bill & Ted's Excellent Adventure", 'Dark', 'Groundhog Day', 'Loki', 'Looper', 'Palm Springs', 'Source Code', 'Tenet', 'X-Men: Days of Future Past'],
    'War': ['1917', 'American Sniper', 'Apocalypse Now', 'Band of Brothers', 'Black Hawk Down', 'Dunkirk', 'Full Metal Jacket', 'Hacksaw Ridge', 'Inglourious Basterds', 'Pearl Harbor', 'Platoon', 'Saving Private Ryan', 'The Pacific'],
    'Western': ['3:10 to Yuma', 'Butch Cassidy and the Sundance Kid', 'Deadwood', 'Django Unchained', 'No Country for Old Men', 'Once Upon a Time in the West', 'The Good, the Bad and the Ugly', 'The Magnificent Seven', 'Tombstone', 'True Grit', 'Unforgiven', 'Yellowstone'],
    'Zombie': ['28 Days Later', 'All of Us Are Dead', 'Army of the Dead', 'Dawn of the Dead', 'Night of the Living Dead', 'Resident Evil', 'Shaun of the Dead', 'The Walking Dead', 'Train to Busan', 'Warm Bodies', 'World War Z', 'Zombieland'],
  };

  var museCatalog = {
    'Showbiz': ['Sunburn', 'Muscle Museum', 'Fillip', 'Falling Down', 'Cave', 'Showbiz', 'Unintended', 'Uno', 'Sober', 'Escape', 'Overdue', "Hate This & I'll Love You", 'Spiral Static'],
    'Origin of Symmetry': ['New Born', 'Bliss', 'Space Dementia', 'Hyper Music', 'Plug In Baby', 'Citizen Erased', 'Micro Cuts', 'Screenager', 'Darkshines', 'Feeling Good', 'Megalomania', 'Futurism'],
    'Absolution': ['Apocalypse Please', 'Time Is Running Out', 'Sing for Absolution', 'Stockholm Syndrome', 'Falling Away with You', 'Hysteria', 'Blackout', 'Butterflies & Hurricanes', 'The Small Print', 'Fury', 'Endlessly', 'Thoughts of a Dying Atheist', 'Ruled by Secrecy'],
    'Black Holes and Revelations': ['Take a Bow', 'Starlight', 'Supermassive Black Hole', 'Map of the Problematique', "Soldier's Poem", 'Invincible', 'Assassin', 'Exo-Politics', 'City of Delusion', 'Hoodoo', 'Knights of Cydonia', 'Glorious'],
    'The Resistance': ['Uprising', 'Resistance', 'Undisclosed Desires', 'United States of Eurasia', 'Guiding Light', 'Unnatural Selection', 'MK Ultra', 'I Belong to You', 'Exogenesis: Symphony Part 1 (Overture)', 'Exogenesis: Symphony Part 2 (Cross-Pollination)', 'Exogenesis: Symphony Part 3 (Redemption)'],
    'The 2nd Law': ['Supremacy', 'Madness', 'Panic Station', 'Survival', 'Follow Me', 'Animals', 'Explorers', 'Big Freeze', 'Save Me', 'Liquid State', 'The 2nd Law: Unsustainable', 'The 2nd Law: Isolated System'],
    'Drones': ['Dead Inside', 'Psycho', 'Mercy', 'Reapers', 'The Handler', 'Defector', 'Revolt', 'Aftermath', 'The Globalist', 'Drones'],
    'Simulation Theory': ['Algorithm', 'The Dark Side', 'Pressure', 'Propaganda', 'Break It to Me', 'Something Human', 'Thought Contagion', 'Get Up and Fight', 'Blockades', 'Dig Down', 'The Void'],
    'Will of the People': ['Will of the People', 'Compliance', 'Liberation', "Won't Stand Down", 'Ghosts (How Can I Move On)', "You Make Me Feel Like It's Halloween", 'Kill or Be Killed', 'Verona', 'Euphoria', 'We Are Fucking Fucked'],
    'The Wow! Signal': ['The Dark Forest', 'Nightshift Superstar', 'Shimmering Scars', 'Cryogen', 'Be With You', 'Hexagons', 'The Sickness In You & I', 'Unravelling', 'Hush', 'Space Debris'],
    'B-Sides': ['Con-Science', 'Do We Need This?', 'Coma', 'Host', 'Twin', 'Agitated', 'Jimmy Kane', 'Yes Please', 'Ashamed', 'Nishe', 'Forced In', 'Shine', 'Please Please Please Let Me Get What I Want', 'Piano Thing', 'Hyper Chondriac Music', 'The Gallery', 'Map of Your Head', 'Nature_1', 'Shrinking Universe', 'Recess', 'Dead Star', 'In Your World', 'The Groove', 'Eternally Missed', 'Easily', 'Crying Shame'],
  };

  var musicGenreCatalog = {
    'Alternative Rock': ['Coldplay (Yellow)', 'Gorillaz (Feel Good Inc)', 'Imagine Dragons (Radioactive)', 'Kings of Leon (Sex on Fire)', 'Linkin Park (In the End)', 'Muse (Supermassive Black Hole)', 'Oasis (Wonderwall)', 'R.E.M. (Losing My Religion)', 'Radiohead (Creep)', 'Red Hot Chili Peppers (Californication)', 'Smashing Pumpkins (1979)', 'The Black Keys (Lonely Boy)', 'Third Eye Blind (Semi-Charmed Life)', 'Twenty One Pilots (Stressed Out)', "Weezer (Say It Ain't So)"],
    'Bedroom Pop': ['beabadoobee (the perfect pair)', 'Cigarettes After Sex (Apocalypse)', 'Clairo (Sofia)', 'Djo (End of Beginning)', 'Dominic Fike (3 Nights)', 'Faye Webster (Kingston)', 'girl in red (we fell in love in october)', 'Joji (Glimpse of Us)', 'Mac DeMarco (Chamber of Reflection)', 'Malcolm Todd (Earrings)', 'Rex Orange County (Best Friend)', 'Steve Lacy (Dark Red)', 'The Marias (No One Noticed)', 'TV Girl (Lovers Rock)', 'Wallows (Are You Bored Yet?)'],
    'Blues': ['Albert King (Born Under a Bad Sign)', 'B.B. King (The Thrill Is Gone)', "Buddy Guy (Damn Right, I've Got the Blues)", 'Eric Clapton (Layla)', 'Etta James (At Last)', "Howlin' Wolf (Smokestack Lightning)", 'John Lee Hooker (Boom Boom)', 'Muddy Waters (Hoochie Coochie Man)', 'Robert Johnson (Cross Road Blues)', 'Stevie Ray Vaughan (Pride and Joy)'],
    'Classical': ['Bach (Air on the G String)', 'Beethoven (Fur Elise)', 'Brahms (Lullaby)', 'Chopin (Nocturne in E-flat Major)', 'Debussy (Clair de Lune)', 'Erik Satie (Gymnopedie No. 1)', 'Grieg (In the Hall of the Mountain King)', 'Handel (Hallelujah Chorus)', 'Mozart (Eine kleine Nachtmusik)', 'Pachelbel (Canon in D)', 'Ravel (Bolero)', 'Strauss (The Blue Danube)', 'Tchaikovsky (Swan Lake)', 'Vivaldi (The Four Seasons)', 'Wagner (Ride of the Valkyries)'],
    'Country': ["Blake Shelton (God's Country)", 'Carrie Underwood (Before He Cheats)', 'Chris Stapleton (Tennessee Whiskey)', 'Dolly Parton (Jolene)', 'Garth Brooks (Friends in Low Places)', 'Johnny Cash (Hurt)', 'Kenny Chesney (No Shoes, No Shirt, No Problems)', 'Luke Combs (When It Rains It Pours)', 'Miranda Lambert (The House That Built Me)', 'Morgan Wallen (Last Night)', 'Shania Twain (Man! I Feel Like a Woman!)', 'Tim McGraw (Humble and Kind)', 'Toby Keith (Red Solo Cup)', 'Willie Nelson (On the Road Again)', 'Zach Bryan (Something in the Orange)'],
    'Disco': ['ABBA (Dancing Queen)', 'Anita Ward (Ring My Bell)', "Bee Gees (Stayin' Alive)", 'Boney M. (Rasputin)', 'Chic (Le Freak)', 'Donna Summer (Hot Stuff)', 'Earth Wind & Fire (September)', 'Gloria Gaynor (I Will Survive)', 'KC and the Sunshine Band (Get Down Tonight)', 'Kool & The Gang (Celebration)', 'Sister Sledge (We Are Family)', 'The Trammps (Disco Inferno)', 'The Village People (Y.M.C.A.)'],
    'EDM': ['Alan Walker (Faded)', 'Avicii (Wake Me Up)', 'Calvin Harris (One Kiss)', 'Daft Punk (One More Time)', "David Guetta (I'm Good)", 'deadmau5 (Strobe)', 'Diplo (Lean On)', "Kygo (It Ain't Me)", 'Marshmello (Happier)', 'Martin Garrix (In the Name of Love)', 'Skrillex (Where Are U Now)', "Swedish House Mafia (Don't You Worry Child)", 'The Chainsmokers (Closer)', 'Tiesto (The Business)', 'Zedd (The Middle)'],
    'Emo / Pop Punk': ['All Time Low (Dear Maria, Count Me In)', 'Dashboard Confessional (Hands Down)', 'Fall Out Boy (Centuries)', 'Good Charlotte (The Anthem)', 'Jimmy Eat World (The Middle)', 'My Chemical Romance (Teenagers)', 'Panic! At The Disco (High Hopes)', 'Paramore (Still into You)', "Simple Plan (I'm Just a Kid)", 'Sum 41 (In Too Deep)', 'Taking Back Sunday (MakeDamnSure)', 'The Used (The Taste of Ink)', 'Yellowcard (Ocean Avenue)'],
    'Folk': ["Bob Dylan (Blowin' in the Wind)", 'Cat Stevens (Wild World)', 'Fleet Foxes (White Winter Hymnal)', 'James Taylor (Fire and Rain)', 'Joan Baez (Diamonds & Rust)', 'Joni Mitchell (Big Yellow Taxi)', 'Mumford & Sons (Little Lion Man)', 'Neil Young (Heart of Gold)', 'Simon and Garfunkel (The Sound of Silence)', 'Sufjan Stevens (Mystery of Love)', 'The Lumineers (Ho Hey)', 'Woody Guthrie (This Land Is Your Land)'],
    'Gospel': ['CeCe Winans (Alabaster Box)', 'Donnie McClurkin (We Fall Down)', 'Fred Hammond (No Weapon)', 'Kirk Franklin (Stomp)', 'Mahalia Jackson (Take My Hand, Precious Lord)', 'Marvin Sapp (Never Would Have Made It)', 'Tamela Mann (Take Me to the King)', 'Tasha Cobbs (Break Every Chain)', 'The Clark Sisters (You Brought the Sunshine)', 'Yolanda Adams (Open My Heart)'],
    'Grunge': ['Alice in Chains (Man in the Box)', 'Bush (Glycerine)', 'Hole (Celebrity Skin)', "Mudhoney (Touch Me I'm Sick)", 'Nirvana (Smells Like Teen Spirit)', 'Pearl Jam (Even Flow)', 'Screaming Trees (Nearly Lost You)', 'Soundgarden (Black Hole Sun)', 'Stone Temple Pilots (Plush)', 'Temple of the Dog (Hunger Strike)'],
    'Heavy Metal': ['Avenged Sevenfold (Bat Country)', 'Black Sabbath (Paranoid)', 'Disturbed (Down with the Sickness)', 'Iron Maiden (The Trooper)', 'Judas Priest (Breaking the Law)', 'Korn (Freak on a Leash)', 'Megadeth (Symphony of Destruction)', 'Metallica (Enter Sandman)', 'Motorhead (Ace of Spades)', 'Ozzy Osbourne (Crazy Train)', 'Pantera (Walk)', 'Rammstein (Du Hast)', 'Slayer (Raining Blood)', 'Slipknot (Duality)', 'System Of A Down (Chop Suey!)'],
    'Hip Hop': ['2Pac (California Love)', '50 Cent (In Da Club)', 'Cardi B (I Like It)', 'Drake (One Dance)', 'Eminem (Without Me)', 'J. Cole (No Role Modelz)', 'Jay-Z (Empire State of Mind)', 'Kanye West (Heartless)', 'Kendrick Lamar (All The Stars)', 'Lil Wayne (Love Me)', 'Nicki Minaj (Starships)', 'Post Malone (rockstar)', "Snoop Dogg (Drop It Like It's Hot)", 'The Notorious B.I.G. (Juicy)', 'Travis Scott (goosebumps)'],
    'Indie / Alternative': ['Alt-J (Breezeblocks)', 'Arcade Fire (Wake Up)', 'Arctic Monkeys (I Wanna Be Yours)', 'Bon Iver (Skinny Love)', 'Cage The Elephant (Cigarette Daydreams)', 'Florence + The Machine (Dog Days Are Over)', 'Foster The People (Pumped Up Kicks)', 'Glass Animals (Heat Waves)', 'Hozier (Take Me to Church)', 'Lana Del Rey (Summertime Sadness)', 'MGMT (Kids)', 'Tame Impala (The Less I Know The Better)', 'The 1975 (Somebody Else)', 'The Neighbourhood (Sweater Weather)', 'Vampire Weekend (A-Punk)'],
    'J-Pop / J-Rock': ['Ado (New Genesis)', 'Creepy Nuts (Bling-Bang-Bang-Born)', 'Hikaru Utada (First Love)', 'Kenshi Yonezu (KICK BACK)', 'King Gnu (Hakujitsu)', 'LiSA (Gurenge)', 'Official HIGE DANdism (Pretender)', 'One OK Rock (Wherever You Are)', 'RADWIMPS (Zenzenzense)', 'YOASOBI (Idol)'],
    'Jazz': ['Billie Holiday (Strange Fruit)', 'Charlie Parker (Ornithology)', 'Chet Baker (My Funny Valentine)', 'Dave Brubeck (Take Five)', 'Dizzy Gillespie (A Night in Tunisia)', 'Duke Ellington (Take the A Train)', 'Ella Fitzgerald (Dream a Little Dream of Me)', 'Frank Sinatra (Fly Me to the Moon)', 'Glenn Miller (In the Mood)', 'Herbie Hancock (Cantaloupe Island)', 'John Coltrane (My Favorite Things)', 'Louis Armstrong (What a Wonderful World)', 'Miles Davis (So What)', 'Nina Simone (Feeling Good)', 'Thelonious Monk (Round Midnight)'],
    'K-Pop': ['aespa (Next Level)', 'BIGBANG (Fantastic Baby)', 'BLACKPINK (How You Like That)', 'BTS (Dynamite)', 'EXO (Growl)', "Girls' Generation (Gee)", 'ITZY (WANNABE)', 'IVE (LOVE DIVE)', 'NewJeans (Super Shy)', 'PSY (Gangnam Style)', 'Red Velvet (Psycho)', 'SEVENTEEN (Very Nice)', "Stray Kids (God's Menu)", 'TWICE (TT)', 'TXT (Sugar Rush Ride)'],
    'Latin': ['Camila Cabello (Havana)', 'Carlos Santana (Smooth)', 'Celia Cruz (La Vida Es Un Carnaval)', 'Enrique Iglesias (Bailando)', 'Gloria Estefan (Conga)', 'Juanes (La Camisa Negra)', 'Los Lobos (La Bamba)', 'Luis Fonsi (Despacito)', 'Maluma (Hawai)', 'Marc Anthony (Vivir Mi Vida)', 'Peso Pluma (Ella Baila Sola)', "Ricky Martin (Livin' la Vida Loca)", 'Rosalia (DESPECHA)', 'Selena (Como La Flor)', "Shakira (Hips Don't Lie)"],
    'Pop': ['Adele (Rolling in the Deep)', 'Ariana Grande (7 rings)', 'Billie Eilish (BIRDS OF A FEATHER)', 'Bruno Mars (Locked out of Heaven)', 'Doja Cat (Say So)', 'Dua Lipa (Levitating)', 'Ed Sheeran (Shape of You)', 'Harry Styles (As It Was)', 'Justin Bieber (Love Yourself)', 'Katy Perry (Dark Horse)', 'Lady Gaga (Bad Romance)', 'Michael Jackson (Billie Jean)', 'Olivia Rodrigo (drivers license)', 'Sabrina Carpenter (Espresso)', 'Taylor Swift (Cruel Summer)'],
    'Post-Punk Revival': ['Bloc Party (Banquet)', 'Editors (Munich)', 'Franz Ferdinand (Take Me Out)', 'Interpol (Evil)', 'Kaiser Chiefs (Ruby)', 'The Killers (Mr. Brightside)', "The Libertines (Can't Stand Me Now)", 'The Strokes (The Adults Are Talking)', 'The White Stripes (Seven Nation Army)', 'Yeah Yeah Yeahs (Maps)'],
    'Punk Rock': ['Bad Religion (21st Century Digital Boy)', 'blink-182 (All The Small Things)', 'Dead Kennedys (Holiday in Cambodia)', 'Green Day (Basket Case)', 'Iggy Pop (Lust for Life)', 'Misfits (Last Caress)', 'NOFX (Linoleum)', 'Rancid (Time Bomb)', 'Sex Pistols (Anarchy in the U.K.)', 'The Clash (Should I Stay or Should I Go)', "The Offspring (You're Gonna Go Far, Kid)", 'The Ramones (Blitzkrieg Bop)'],
    'R&B': ["Alicia Keys (If I Ain't Got You)", 'Beyonce (Halo)', 'Boyz II Men (End of the Road)', 'Chris Brown (Under The Influence)', 'Daniel Caesar (Best Part)', "Destiny's Child (Say My Name)", 'Frank Ocean (Pink + White)', 'John Legend (All of Me)', 'Miguel (Sure Thing)', 'Rihanna (Umbrella)', 'SZA (Kill Bill)', 'The Weeknd (Blinding Lights)', 'TLC (No Scrubs)', 'Usher (Yeah!)', 'Whitney Houston (I Wanna Dance with Somebody)'],
    'Reggaeton': ['Anuel AA (China)', 'Bad Bunny (DAKITI)', 'Daddy Yankee (Con Calma)', 'Don Omar (Danza Kuduro)', 'Farruko (Pepas)', 'Feid (LUNA)', 'J Balvin (LA CANCION)', 'Karol G (Si Antes Te Hubiera Conocido)', 'Nicky Jam (X)', 'Ozuna (Hey Mor)', 'Rauw Alejandro (Todo De Ti)', 'Wisin y Yandel (Rakata)', 'Zion & Lennox (Otra Vez)'],
    'Rock': ['AC/DC (Highway to Hell)', 'Aerosmith (Dream On)', "Bon Jovi (Livin' On A Prayer)", 'David Bowie (Heroes)', 'Eagles (Hotel California)', 'Fleetwood Mac (Dreams)', 'Foo Fighters (Everlong)', "Guns N' Roses (Sweet Child O' Mine)", "Journey (Don't Stop Believin')", 'Led Zeppelin (Stairway to Heaven)', 'Pink Floyd (Wish You Were Here)', 'Queen (Bohemian Rhapsody)', 'The Beatles (Here Comes The Sun)', 'The Rolling Stones (Paint It, Black)', "The Who (Baba O'Riley)"],
    'Soul / Motown': ["Al Green (Let's Stay Together)", 'Aretha Franklin (Respect)', 'Ben E. King (Stand by Me)', "Bill Withers (Ain't No Sunshine)", "Diana Ross (I'm Coming Out)", 'James Brown (I Feel Good)', "Marvin Gaye (Ain't No Mountain High Enough)", "Otis Redding (Sittin' On the Dock of the Bay)", 'Ray Charles (Georgia on My Mind)', 'Sam Cooke (A Change Is Gonna Come)', 'Smokey Robinson (The Tracks of My Tears)', 'Stevie Wonder (Superstition)', 'The Jackson 5 (I Want You Back)', "The Supremes (You Can't Hurry Love)", 'The Temptations (My Girl)'],
  };

  var fakeBiomeRoleCatalog = {
    'Alpine Mountains': ['Antelope', 'Gila Monster', 'Water Moccasin'],
    'Antarctic Ice Sheet (Frozen Ocean)': ['Bullfrog', 'Cheetah', 'Spider'],
    'Arctic Tundra': ['Hermit Crab', 'Jaguar', 'Toucan'],
    'Australian Outback': ['Moose', 'Piranha', 'Reindeer'],
    'Beach': ['Bat', 'Prairie Dog', 'Snow Leopard'],
    'Cave System': ['Heron', 'Koala', 'Vampire Squid'],
    'Chaparral (Shrubland)': ['Catfish', 'Moray Eel', 'Zebra'],
    'Coral Reef': ['Marmot', 'Snow Petrel', 'Volcanic Mouse'],
    'Deep Ocean': ['Bullfrog', 'Hippopotamus', 'Otter'],
    'Desert': ['Bat', 'Beaver', 'Kangaroo Rat'],
    'Freshwater River': ['Condor', 'Emu', 'Mountain Goat'],
    'House': ['Anaconda', 'Meerkat', 'Pelican'],
    'Jurassic Park': ['Camel', 'Koala', 'Octopus'],
    'Mangrove Forest': ['Beaver', 'Clownfish', 'Squirrel'],
    'Prairie': ['Antarctic Krill', 'Hawaiian Hoary Bat', 'Rat'],
    'Savanna': ['Fire Salamander', 'Harpy Eagle', 'Leopard Seal'],
    'Swamp': ['Poison Dart Frog', 'Troglodyte Beetle', 'Walrus'],
    'Taiga (Boreal Forest)': ['Red-Tailed Hawk', 'Stray Cat', 'Water Moccasin'],
    'Temperate Forest': ['Beaver', 'Bison', 'Troglodyte Beetle'],
    'Tropical Rainforest': ['Cockroach', 'Reindeer', 'Troglodyte Beetle'],
    'Urban Environment (City)': ['Beaver', 'Deep Sea Jellyfish', 'Manta Ray'],
    'Volcanic Island': ['Harpy Eagle', 'Sparrow', 'Zebra'],
  };

  // Each fake is a real dish from another cuisine: near enough to read as a genuine card,
  // far enough that anything true about it gives the jester away.
  var fakeCuisineRoleCatalog = {
    'American': ['Kibbeh', 'Okonomiyaki', 'Tagine'],
    'Brazilian': ['Bangers and Mash', 'Kimchi Jjigae', 'Spatzle'],
    'British': ['Ceviche', 'Mapo Tofu', 'Tteokbokki'],
    'Chinese': ['Bouillabaisse', 'Cornish Pasty', 'Injera'],
    'Ethiopian': ['Croque Monsieur', 'Takoyaki', 'Tortilla Espanola'],
    'Filipino': ['Beef Wellington', 'Harira', 'Pecan Pie'],
    'French': ['Bibimbap', 'Pad Thai', 'Vada Pav'],
    'German': ['Anticuchos', 'Goi Cuon', 'Moqueca'],
    'Greek': ['Corn Dog', 'Doro Wat', 'Xiao Long Bao'],
    'Indian': ['Cassoulet', 'Feijoada', 'Yorkshire Pudding'],
    'Italian': ['Adobo', 'Kitfo', 'Pozole'],
    'Japanese': ['Baba Ghanoush', 'Chilaquiles', "Shepherd's Pie"],
    'Korean': ['Escargot', 'Lomo Saltado', 'Maultaschen'],
    'Lebanese': ['Bun Cha', 'Clam Chowder', 'Quindim'],
    'Mexican': ['Congee', 'Eton Mess', 'Yakitori'],
    'Moroccan': ['Bulgogi', 'Gnocchi', 'Pho'],
    'Peruvian': ['Fish and Chips', 'Samosa', 'Sauerbraten'],
    'Spanish': ['Genfo', 'Kare-Kare', 'Tom Yum'],
    'Thai': ['Cobb Salad', 'Osso Buco', 'Rfissa'],
    'Vietnamese': ['Baklava', 'Currywurst', 'Papa a la Huancaina'],
  };

  var fakeLocationRoleCatalog = {
    'Airplane': ['Lifeguard', 'Nail Specialist', 'Security Officer'],
    'Airport': ['Bellhop', 'Coach', 'Shackled Prisoner'],
    'Bank': ['Dancer', 'Film Critic', 'Pick-Up Artist'],
    'Beach': ['Astronaut', 'Housekeeper', 'Librarian'],
    'Campground': ['Concierge', 'Security Guard', 'Usher'],
    'Casino': ['Dancer', 'Drive-Thru Worker', 'Manager'],
    'Circus Tent': ['Actor', 'Biologist', 'Geoscientist'],
    'Convenience Store': ['Backpacker', 'Campus Security', 'Dean'],
    'Corporate Party': ['Cameraman', 'Campus Security', 'Flight Attendant'],
    'Cruise Ship': ['Administrative Assistant', 'Usher', 'Zookeeper'],
    'Crusader Army': ['Cabin Boy', 'Dispatcher', 'Teller'],
    'Day Spa': ['Detective', 'Visitor', 'Zookeeper'],
    'Elementary School': ['Auditor', 'Cardsharp', 'Cashier'],
    'Embassy': ['Ice Cream Vendor', 'Masseur', 'Wildlife Photographer'],
    'Fast Food Restaurant': ['Interpreter', 'Journalist', 'Magician'],
    'Fire Station': ['Bartender', 'Coach', 'Radio Operator'],
    'Gym': ['Archer', 'Auditor', 'Cardsharp'],
    'Hospital': ['Archer', 'Delivery Man', 'Stage Hand'],
    'Hotel': ['CEO', "New Year's Resolution Member", 'Sunbather'],
    'Military Base': ['Audience Member', 'Musician', 'Zookeeper'],
    'Movie Studio': ['Astronaut', 'Attendant', 'Receptionist'],
    'Movie Theater': ['Coatroom Attendant', 'Cop', 'Teller'],
    'Night Club': ['Cashier', 'Sommelier', 'Vendor'],
    'Pirate Ship': ['Campus Security', 'Dancer', 'Personal Trainer'],
    'Polar Station': ['Prompter', 'Waiter', 'Wealthy Tourist'],
    'Police Station': ['Audience Member', 'Non-Commissioned Officer', 'Shoplifter'],
    'Restaurant': ['First Mate', 'Pick-Up Artist', 'Usher'],
    'Service Station': ['Bartender', 'Ringmaster', 'Weightlifter'],
    'Space Station': ['Disgruntled Teenager Working Their First Job', 'Ice Cream Vendor', 'Janitor'],
    'Sports Stadium': ['Acrobat', 'Ambassador', 'Parrot'],
    'Submarine': ['Butcher', 'Flight Engineer', 'Tourist'],
    'Supermarket': ['Runner', 'Service Receptionist', 'Usher'],
    'Theatre': ['Auditor', 'Shopper', 'Yoga Instructor'],
    'Theme Park / Amusement Park': ['Campus Security', 'Captive', 'Sommelier'],
    'Train': ['Bottle Service Waitress', 'Circus-Goer', 'Guest'],
    'University': ['Bartender', 'Pilot', 'Tourist'],
    'Zoo': ['Delivery Driver', 'Front Desk Clerk', 'Pick-Up Artist'],
  };

  var fakeMovieTvRoleCatalog = {
    'Action': ['(500) Days of Summer', 'Grease', 'Sherlock Holmes'],
    'Adventure': ['A Simple Favor', "Howl's Moving Castle", 'Stranger Things'],
    'Aliens': ['Atomic Blonde', 'Killing Eve', 'The Departed'],
    'Animated': ['Black Panther', 'Love Actually', 'The Holdovers'],
    'Anime': ["Child's Play", 'Moonlight', 'The Perks of Being a Wallflower'],
    'Biopic / Docudrama': ['Death Note', 'Only Murders in the Building', 'The Summer I Turned Pretty'],
    'Body Horror': ['Edge of Tomorrow', 'Predator', 'Tremors'],
    'Christmas': ['Get Out', 'San Andreas', 'West Side Story'],
    'Comedy': ['2001: A Space Odyssey', 'Holes', 'Space Jam'],
    'Cop': ['All of Us Are Dead', 'Iron Man', 'The Americans'],
    'Courtroom Drama': ['Band of Brothers', 'Kung Fu Panda', 'The Good, the Bad and the Ugly'],
    'Crime': ['Bridgerton', 'Men in Black', 'The Mandalorian'],
    'Cyberpunk': ['Coach Carter', 'Napoleon Dynamite', 'The Road'],
    'Disaster': ['Despicable Me', 'Panic Room', 'The Wire'],
    'Dystopian': ['Fallout', 'Pulp Fiction', 'Twister'],
    'Fantasy': ['GoodFellas', 'Sex Education', 'Zombieland'],
    'Found Footage': ['A Beautiful Mind', 'Hot Fuzz', 'Split'],
    'Heist': ['Anchorman', "Jennifer's Body", 'The Breakfast Club'],
    'Historical Epic': ['Black Hawk Down', 'Loki', 'The Hangover'],
    'Horror': ['Chernobyl', 'Moana', 'The Other Guys'],
    'Monster': ['Creed', 'Oldboy', 'The Substance'],
    'Musical': ['Dumb and Dumber', 'Poltergeist', 'Train to Busan'],
    'Mystery / Whodunit': ['Frozen', 'RoboCop', 'War of the Worlds'],
    'Post-Apocalyptic': ['12 Monkeys', 'Hacksaw Ridge', 'Shogun'],
    'Prison': ['Airplane!', 'Inside Out', 'Superman'],
    'Psychological Thriller': ['Austin Powers', 'Kingdom of Heaven', 'The Fifth Element'],
    'Romance': ['Brooklyn Nine-Nine', 'Men in Black', 'The Last Samurai'],
    'Sci-Fi / Space Opera': ['Clue', 'My Neighbor Totoro', 'The Ring'],
    'Slasher': ['Death Note', 'Palm Springs', 'The Visit'],
    'Sports': ['Escape from Alcatraz', 'Prometheus', 'Twilight'],
    'Spy': ['Glass Onion', 'Scarface', 'Wonder Woman'],
    'Superhero': ['A Christmas Story', 'I Am Legend', 'Star Wars'],
    'Survival': ['American Horror Story', 'Jaws', 'The Avengers'],
    'Teen Drama': ['Ben-Hur', 'Les Misérables', 'The Grey'],
    'Thriller': ['Butch Cassidy and the Sundance Kid', 'Men in Black', 'The Mandalorian'],
    'Time Travel': ['Cowboy Bebop', 'Now You See Me', 'The Social Network'],
    'War': ['Dune', 'Poltergeist', 'Toy Story'],
    'Western': ['Friday Night Lights', 'Remember the Titans', 'V for Vendetta'],
    'Zombie': ['10 Things I Hate About You', 'Guardians of the Galaxy', 'Shrek'],
  };

  var fakeMuseRoleCatalog = {};
  Object.keys(museCatalog).forEach(function (album) {
    fakeMuseRoleCatalog[album] = Object.keys(museCatalog)
      .filter(function (other) { return other !== album; })
      .reduce(function (songs, other) { return songs.concat(museCatalog[other]); }, []);
  });

  var fakeMusicGenreRoleCatalog = {
    'Alternative Rock': ['Bush (Glycerine)', 'Interpol (Evil)', 'Tame Impala (The Less I Know The Better)'],
    'Bedroom Pop': ['Johnny Cash (Hurt)', 'Metallica (Enter Sandman)', 'Mozart (Eine kleine Nachtmusik)'],
    'Blues': ["Al Green (Let's Stay Together)", 'Chet Baker (My Funny Valentine)', 'Johnny Cash (Hurt)'],
    'Classical': ['Duke Ellington (Take the A Train)', 'Mahalia Jackson (Take My Hand, Precious Lord)', 'Nina Simone (Feeling Good)'],
    'Country': ["Bob Dylan (Blowin' in the Wind)", 'Etta James (At Last)', 'Stevie Ray Vaughan (Pride and Joy)'],
    'Disco': ['Calvin Harris (One Kiss)', "Diana Ross (I'm Coming Out)", 'Usher (Yeah!)'],
    'EDM': ["Bee Gees (Stayin' Alive)", 'Sabrina Carpenter (Espresso)', 'The Weeknd (Blinding Lights)'],
    'Emo / Pop Punk': ['Green Day (Basket Case)', 'Linkin Park (In the End)', "The Offspring (You're Gonna Go Far, Kid)"],
    'Folk': ['Chris Stapleton (Tennessee Whiskey)', 'Dolly Parton (Jolene)', 'Robert Johnson (Cross Road Blues)'],
    'Gospel': ['Aretha Franklin (Respect)', 'B.B. King (The Thrill Is Gone)', 'Sam Cooke (A Change Is Gonna Come)'],
    'Grunge': ['Foo Fighters (Everlong)', 'Pantera (Walk)', 'Radiohead (Creep)'],
    'Heavy Metal': ['AC/DC (Highway to Hell)', 'Alice in Chains (Man in the Box)', "Guns N' Roses (Sweet Child O' Mine)"],
    'Hip Hop': ['Bad Bunny (DAKITI)', 'Frank Ocean (Pink + White)', 'SZA (Kill Bill)'],
    'Indie / Alternative': ['Billie Eilish (BIRDS OF A FEATHER)', 'Coldplay (Yellow)', 'The Killers (Mr. Brightside)'],
    'J-Pop / J-Rock': ['Aretha Franklin (Respect)', 'Dolly Parton (Jolene)', 'Sex Pistols (Anarchy in the U.K.)'],
    'Jazz': ['Bach (Air on the G String)', 'Muddy Waters (Hoochie Coochie Man)', 'Stevie Wonder (Superstition)'],
    'K-Pop': ['Ariana Grande (7 rings)', 'Marshmello (Happier)', 'Rihanna (Umbrella)'],
    'Latin': ['Bruno Mars (Locked out of Heaven)', 'J Balvin (LA CANCION)', 'Nicky Jam (X)'],
    'Pop': ['Beyonce (Halo)', 'BTS (Dynamite)', 'The Chainsmokers (Closer)'],
    'Post-Punk Revival': ['Arctic Monkeys (I Wanna Be Yours)', 'Oasis (Wonderwall)', 'The Clash (Should I Stay or Should I Go)'],
    'Punk Rock': ['Fall Out Boy (Centuries)', 'Nirvana (Smells Like Teen Spirit)', 'System Of A Down (Chop Suey!)'],
    'R&B': ['Drake (One Dance)', "Marvin Gaye (Ain't No Mountain High Enough)", 'Taylor Swift (Cruel Summer)'],
    'Reggaeton': ['Kendrick Lamar (All The Stars)', 'Maluma (Hawai)', "Shakira (Hips Don't Lie)"],
    'Rock': ['Iron Maiden (The Trooper)', 'Pearl Jam (Even Flow)', 'Red Hot Chili Peppers (Californication)'],
    'Soul / Motown': ["Alicia Keys (If I Ain't Got You)", 'Ella Fitzgerald (Dream a Little Dream of Me)', 'Kirk Franklin (Stomp)'],
  };

  window.MASQ_LOCATIONS_DATA = {
    'biomeCatalog': biomeCatalog,
    'cuisineCatalog': cuisineCatalog,
    'locationCatalog': locationCatalog,
    'movieTvCatalog': movieTvCatalog,
    'museCatalog': museCatalog,
    'musicGenreCatalog': musicGenreCatalog,
    'fakeBiomeRoleCatalog': fakeBiomeRoleCatalog,
    'fakeCuisineRoleCatalog': fakeCuisineRoleCatalog,
    'fakeLocationRoleCatalog': fakeLocationRoleCatalog,
    'fakeMovieTvRoleCatalog': fakeMovieTvRoleCatalog,
    'fakeMuseRoleCatalog': fakeMuseRoleCatalog,
    'fakeMusicGenreRoleCatalog': fakeMusicGenreRoleCatalog,
  };
})();
