// Masq Word Mode data: the word-only catalogs, and the jester hints that go
// with them. Plain script, exposed on window.MASQ_WORDS.
//
// Split out of src/data_roles.js, which holds the role catalogs. These two belong
// together and to nothing else: a word-only category has no roles, so none of
// the fake-role machinery next door applies to it, and the hints are keyed by
// the very categories listed here.
(function () {
  var wordOnlyCatalog = {
    'Animals': [
      'Ant', 'Antelope', 'Axolotl', 'Baboon', 'Badger', 'Bat', 'Bear', 'Beaver', 'Bee', 'Beetle',
      'Buffalo', 'Butterfly', 'Camel', 'Cat', 'Caterpillar', 'Catfish', 'Chameleon', 'Cheetah', 'Chicken', 'Chimpanzee',
      'Chipmunk', 'Clownfish', 'Cobra', 'Cockroach', 'Cow', 'Coyote', 'Crab', 'Crocodile', 'Crow', 'Deer',
      'Dog', 'Dolphin', 'Donkey', 'Dragonfly', 'Duck', 'Eagle', 'Eel', 'Elephant', 'Emu', 'Falcon',
      'Ferret', 'Firefly', 'Flamingo', 'Fly', 'Fox', 'Frog', 'Gecko', 'Giraffe', 'Goat', 'Goldfish',
      'Goose', 'Gorilla', 'Grasshopper', 'Guinea Pig', 'Hamster', 'Hawk', 'Hedgehog', 'Hippo', 'Horse', 'Hummingbird',
      'Hyena', 'Iguana', 'Jaguar', 'Jellyfish', 'Kangaroo', 'Koala', 'Komodo Dragon', 'Ladybug', 'Lemur', 'Leopard',
      'Lion', 'Lizard', 'Llama', 'Lobster', 'Manatee', 'Meerkat', 'Mole', 'Monkey', 'Moose', 'Mosquito',
      'Mouse', 'Narwhal', 'Octopus', 'Orangutan', 'Orca', 'Ostrich', 'Otter', 'Owl', 'Oyster', 'Panda',
      'Parrot', 'Peacock', 'Pelican', 'Penguin', 'Pig', 'Pigeon', 'Platypus', 'Polar Bear', 'Porcupine', 'Pufferfish',
      'Puffin', 'Python', 'Rabbit', 'Raccoon', 'Rattlesnake', 'Red Panda', 'Rhino', 'Robin', 'Rooster', 'Salamander',
      'Salmon', 'Scorpion', 'Sea Urchin', 'Seagull', 'Seahorse', 'Seal', 'Shark', 'Sheep', 'Shrimp', 'Skunk',
      'Sloth', 'Snail', 'Snake', 'Sparrow', 'Spider', 'Squid', 'Squirrel', 'Starfish', 'Stingray', 'Stork',
      'Swan', 'Swordfish', 'Termite', 'Tiger', 'Toucan', 'Turkey', 'Turtle', 'Vulture', 'Walrus', 'Warthog',
      'Wasp', 'Whale', 'Wildebeest', 'Wolf', 'Wombat', 'Woodpecker', 'Worm', 'Zebra'],
    'Food/Drinks': [
      'Almonds', 'Apple', 'Apple Pie', 'Avocado', 'Bacon', 'Bagel', 'Baguette', 'Baked Potato', 'Banana',
      'Banana Bread', 'Banh Mi', 'Beef', 'Beef Stew', 'Biryani', 'Biscuit', 'BLT', 'Blueberries',
      'Boba Milk Tea', 'Bread', 'Broccoli', 'Brownie', 'Burger', 'Burrito', 'Calzone', 'Cantaloupe',
      'Carbonara', 'Carrot Cake', 'Carrots', 'Cereal', 'Chai', 'Cheese', 'Cheesecake', 'Cherries', 'Chicken',
      'Chicken Noodle Soup', 'Chicken Nuggets', 'Chicken Tikka Masala', 'Chicken Wings', 'Chili', 'Chocolate',
      'Chocolate Cake', 'Chow Mein', 'Churros', 'Cinnamon Roll', 'Clam Chowder', 'Coconut', 'Coffee',
      'Coleslaw', 'Cookies', 'Corn Dog', 'Corn on the Cob', 'Cotton Candy', 'Crab', 'Crackers',
      'Crème Brûlée', 'Crepes', 'Croissant', 'Cucumber', 'Cupcake', 'Curry', 'Dim Sum', 'Donut', 'Duck',
      'Dumplings', 'Egg Rolls', 'Elote', 'Enchiladas', 'Espresso', 'Fajitas', 'Falafel', 'Fettuccine Alfredo',
      'Fish and Chips', 'Flan', 'French Fries', 'French Toast', 'Fried Chicken', 'Fried Rice', 'Garlic Bread',
      'Gnocchi', 'Granola', 'Grapes', 'Green Beans', 'Grilled Cheese', 'Guacamole', 'Gyro', 'Hash Browns',
      'Honey', 'Hot Chocolate', 'Hot Dog', 'Hot Pot', 'Hummus', 'Ice Cream', 'Iced Tea', 'Jam', 'Jello',
      'Kebab', 'Key Lime Pie', 'Kimchi', 'Kiwi', 'Lamb', 'Lasagna', 'Lemon', 'Lemonade', 'Lime', 'Lobster',
      'Lollipop', 'Macaron', 'Macaroni and Cheese', 'Mango', 'Marshmallow', 'Mashed Potatoes', 'Matcha',
      'Meatballs', 'Meatloaf', 'Milk', 'Milkshake', 'Mochi', 'Mozzarella Sticks', 'Muffin', 'Mushrooms',
      'Naan', 'Nachos', 'Oatmeal', 'Olives', 'Omelette', 'Onigiri', 'Onion', 'Onion Rings', 'Orange',
      'Orange Chicken', 'Orange Juice', 'Pad Thai', 'Pancakes', 'Panini', 'Pasta', 'Peach', 'Peanut Butter',
      'Peanuts', 'Pear', 'Pesto Pasta', 'Philly Cheesesteak', 'Pho', 'Pickles', 'Pineapple', 'Pita', 'Pizza',
      'Plum', 'Poke', 'Pomegranate', 'Popcorn', 'Popsicle', 'Pork', 'Potato Chips', 'Potato Salad', 'Pretzel',
      'Pudding', 'Pumpkin Pie', 'Quesadilla', 'Ramen', 'Raspberries', 'Ravioli', 'Red Velvet Cake', 'Ribs',
      'Rice', 'Salad', 'Salmon', 'Salsa', 'Samosa', 'Sandwich', 'Sausage', 'Scone', 'Scrambled Eggs',
      'Shawarma', "Shepherd's Pie", 'Shrimp', 'Sloppy Joe', 'Smoothie', 'Soda', 'Soup', 'Spaghetti',
      'Spring Rolls', 'Strawberry', 'Sub Sandwich', 'Sushi', 'Sweet Potato', 'Tacos', 'Tamales', 'Tea',
      'Tiramisu', 'Toast', 'Tofu', 'Tomato', 'Tomato Soup', 'Tuna', 'Turkey', 'Udon', 'Veggie Burger',
      'Waffles', 'Watermelon', 'Wontons', 'Xiao Long Bao', 'Yogurt'],
    'Movies/TV': [
      '(500) Days of Summer', '10 Things I Hate About You', '101 Dalmatians', '12 Angry Men', '12 Years a Slave', '127 Hours', '13 Going on 30', '13 Reasons Why', '1917', '1984',
      '2001: A Space Odyssey', '2012', '21 Jump Street', '28 Days Later', '300', '8 Mile', 'A Beautiful Mind', "A Bug's Life", 'A Christmas Carol', 'A Christmas Story',
      'A Clockwork Orange', 'A Few Good Men', 'A Minecraft Movie', 'A Nightmare on Elm Street', 'A Quiet Place', 'A Silent Voice', 'A Star Is Born', 'About Time', 'Airplane!', 'Aladdin',
      'Alice in Wonderland', 'Alien', 'Alita: Battle Angel', 'All of Us Are Dead', 'American Beauty', 'American Gangster', 'American History X', 'American Horror Story', 'American Psycho', 'American Sniper',
      'An American Werewolf in London', 'Anaconda', 'Anchorman', 'Annabelle', 'Annihilation', 'Anora', 'Ant-Man', 'Anyone But You', 'Apocalypse Now', 'Apollo 13',
      'Argo', 'Armageddon', 'Army of the Dead', 'Arrival', 'Assassination Classroom', 'Attack on Titan', 'Austin Powers', 'Avatar', 'Avatar: The Last Airbender', 'Baby Driver',
      'Back to the Future', 'Backrooms', 'Bad Boys', 'Bambi', 'Band of Brothers', 'Barbarian', 'Barbie', 'Batman Begins', 'Beauty and the Beast', 'Beetlejuice',
      'Better Call Saul', 'Beverly Hills Cop', 'Big Hero 6', "Bill & Ted's Excellent Adventure", 'Bird Box', 'Birdman', 'Black Hawk Down', 'Black Mirror', 'Black Panther', 'Black Swan',
      'Black Widow', 'Blade Runner', 'Bleach', 'Bohemian Rhapsody', 'Booksmart', 'Borat', 'Brave', 'Braveheart', 'Breaking Bad', 'Bridesmaids',
      'Bridgerton', 'Brokeback Mountain', 'Brooklyn Nine-Nine', 'Bullet Train', 'Call Me by Your Name', 'Candyman', 'Captain America', 'Captain Marvel', 'Captain Phillips', 'Carrie',
      'Cars', 'Casino', 'Casino Royale', 'Cast Away', 'Catch Me If You Can', 'Chainsaw Man', 'Challengers', 'Charlie and the Chocolate Factory', 'Chernobyl', 'Chicago',
      "Child's Play", 'Children of Men', 'Chinatown', 'Chronicle', 'Cinderella', 'Cloverfield', 'Clue', 'Clueless', 'Coach Carter', 'Cocaine Bear',
      'Coco', 'Code Geass', 'Contagion', 'Coraline', 'Corpse Bride', 'Cowboy Bebop', 'Crazy Rich Asians', 'Crazy, Stupid, Love.', 'Creed', 'Daredevil',
      'Dark', 'Dawn of the Dead', 'Dead Poets Society', 'Deadpool', 'Death Note', 'Death on the Nile', 'Demon Slayer', 'Despicable Me', 'Dexter', 'Die Hard',
      'District 9', 'Divergent', 'Django Unchained', 'Doctor Strange', 'Doctor Who', 'Donnie Darko', "Don't Look Up", "Don't Worry Darling", 'Dr. Stone', 'Dragon Ball Z',
      'Drive', 'Dumb and Dumber', 'Dune', 'Dunkirk', 'E.T.', 'Easy A', 'Edge of Tomorrow', 'Edward Scissorhands', 'Elf', 'Elvis',
      'Emily in Paris', 'Encanto', 'Erased', 'Eternal Sunshine of the Spotless Mind', 'Euphoria', 'Everything Everywhere All at Once', 'Ex Machina', 'F1', 'Fallout', 'Family Guy',
      'Fantastic Mr. Fox', 'Fargo', 'Fast and Furious', "Ferris Bueller's Day Off", 'Fight Club', 'Final Destination', 'Finding Nemo', "Five Nights at Freddy's", 'Ford v Ferrari', 'Forrest Gump',
      'Frankenstein', 'Friday Night Lights', 'Friday the 13th', 'Friends', 'Frozen', 'Full Metal Jacket', 'Fullmetal Alchemist: Brotherhood', 'Game of Thrones', 'Get Out', 'Ghost in the Shell',
      'Ghostbusters', 'Gladiator', 'Glass Onion', 'Glee', 'Godzilla', 'Godzilla Minus One', 'Gone Girl', 'Good Will Hunting', 'GoodFellas', 'Gossip Girl',
      'Grave of the Fireflies', 'Gravity', 'Grease', 'Green Book', "Grey's Anatomy", 'Groundhog Day', 'Guardians of the Galaxy', 'Hacksaw Ridge', 'Haikyuu!!', 'Hairspray',
      'Halloween', 'Hamilton', 'Hannibal', 'Happy Death Day', 'Happy Gilmore', 'Harry Potter', 'Heat', 'Her', 'Hereditary', 'High School Musical',
      'Holes', 'Home Alone', 'House', 'How I Met Your Mother', 'How the Grinch Stole Christmas', 'How to Lose a Guy in 10 Days', 'How to Train Your Dragon', "Howl's Moving Castle", 'Hunter x Hunter', 'I Am Legend',
      'I Know What You Did Last Summer', 'I, Robot', 'I, Tonya', 'Ice Age', 'Inception', 'Independence Day', 'Indiana Jones', 'Inglourious Basterds', 'Inside Out', 'Insidious',
      'Interstellar', 'Into the Wild', 'Invincible', 'Iron Man', 'It', "It's a Wonderful Life", "It's Always Sunny in Philadelphia", 'Jaws', "Jennifer's Body", 'John Wick',
      "JoJo's Bizarre Adventure", 'Joker', 'Jujutsu Kaisen', 'Jumanji: Welcome to the Jungle', 'Juno', 'Jurassic Park', 'Jurassic World', 'Kill Bill', 'Killers of the Flower Moon', 'King Kong',
      'Kingdom of Heaven', 'Kingsman', 'Knives Out', 'Kong: Skull Island', 'KPop Demon Hunters', 'Kung Fu Panda', 'La La Land', 'Lady Bird', 'Law & Order', 'Lawrence of Arabia',
      'Legally Blonde', 'Les Misérables', 'Lethal Weapon', 'Life of Pi', 'Lilo & Stitch', 'Little Miss Sunshine', 'Little Women', 'Logan', 'Loki', 'Looper',
      'Lost', 'Love Actually', 'Love, Simon', 'M3GAN', 'Mad Max: Fury Road', 'Mad Men', 'Madagascar', 'Maleficent', 'Mamma Mia!', 'Marriage Story',
      'Matilda', 'Me Before You', 'Mean Girls', 'Memento', 'Men in Black', 'Michael', 'Midsommar', 'Million Dollar Baby', 'Mindhunter', 'Minority Report',
      'Miracle on 34th Street', 'Misery', 'Mission Impossible', 'Moana', 'Mob Psycho 100', 'Modern Family', 'Money Heist', 'Moneyball', 'Monsters, Inc.', 'Moonlight',
      'Moulin Rouge!', 'Mr. & Mrs. Smith', 'Mr. Robot', 'Mulan', 'Murder on the Orient Express', 'My Hero Academia', 'My Neighbor Totoro', 'Napoleon Dynamite', 'Narcos', 'Naruto',
      'National Treasure', 'Neon Genesis Evangelion', 'Night of the Living Dead', 'Nightcrawler', 'No Country for Old Men', 'No Hard Feelings', 'Nope', 'Nosferatu', 'Notting Hill', 'Now You See Me',
      'Obsession', "Ocean's Eleven", 'Oldboy', 'Once Upon a Time in Hollywood', 'One Piece', 'One Punch Man', 'Oppenheimer', 'Orange Is the New Black', 'Ozark', 'Pacific Rim',
      "Pan's Labyrinth", 'Paranormal Activity', 'Parasite', 'Parks and Recreation', 'Pearl Harbor', 'Percy Jackson', 'Pet Sematary', 'Peter Pan', 'Philadelphia', 'Pirates of the Caribbean',
      'Pitch Perfect', 'Planet of the Apes', 'Pokémon', 'Poltergeist', 'Ponyo', 'Poor Things', 'Predator', 'Pretty Little Liars', 'Pretty Woman', 'Pride & Prejudice',
      'Princess Mononoke', 'Prison Break', 'Prisoners', 'Project Hail Mary', 'Psycho', 'Pulp Fiction', 'Rambo', 'Ratatouille', 'Ready or Not', 'Ready Player One',
      '[REC]', 'Remember the Titans', 'Requiem for a Dream', 'Reservoir Dogs', 'Re:Zero', 'Rick and Morty', 'Riverdale', 'RoboCop', 'Rocketman', 'Rocky',
      'Rush Hour', 'Saltburn', 'San Andreas', 'Saving Private Ryan', 'Saw', 'Scarface', "Schindler's List", 'Scott Pilgrim vs. the World', 'Scream', 'Se7en',
      'Searching', 'Seinfeld', 'Severance', 'Sex and the City', 'Sex Education', 'Shaun of the Dead', 'Sherlock Holmes', 'Shogun', 'Shrek', 'Shutter Island',
      'Sicario', 'Signs', 'Silo', 'Sing', 'Sinister', 'Sinners', 'Skyfall', 'Slumdog Millionaire', 'Smile', 'Snow White and the Seven Dwarfs',
      'Snowpiercer', 'Sonic the Hedgehog', 'Soul', 'South Park', 'Space Jam', 'Spartacus', 'Speed', 'Spider-Man', 'Spirited Away', 'Split',
      'SpongeBob SquarePants', 'Squid Game', 'Stand by Me', 'Star Trek', 'Star Wars', 'Steins;Gate', 'Step Brothers', 'Straight Outta Compton', 'Stranger Things', 'Suits',
      'Superbad', 'Superman', 'Supernatural', 'Sword Art Online', 'Taken', 'Talk to Me', 'Tangled', 'Taxi Driver', 'Ted Lasso', 'Teen Wolf',
      'Tenet', 'Terminator', 'The Avengers', 'The Batman', 'The Big Bang Theory', 'The Big Lebowski', 'The Big Short', 'The Black Phone', 'The Blair Witch Project', 'The Blind Side',
      'The Bourne Identity', 'The Boys', 'The Breakfast Club', 'The Cabin in the Woods', 'The Chronicles of Narnia', 'The Conjuring', 'The Crown', 'The Dark Knight', 'The Day After Tomorrow', 'The Departed',
      'The Devil Wears Prada', 'The Drama', 'The Edge of Seventeen', 'The Equalizer', 'The Exorcist', 'The Expanse', 'The Fantastic 4', 'The Fault in Our Stars', 'The Fly', 'The Girl on the Train',
      'The Girl with the Dragon Tattoo', 'The Godfather', 'The Good, the Bad and the Ugly', 'The Goonies', 'The Grand Budapest Hotel', 'The Great Escape', 'The Great Gatsby', 'The Greatest Showman', 'The Green Mile', 'The Grudge',
      "The Handmaid's Tale", 'The Hangover', 'The Haunting of Hill House', 'The Help', 'The Hobbit', 'The Holdovers', 'The Hunger Games', 'The Incredibles', 'The Italian Job', 'The Jungle Book',
      'The Karate Kid', 'The Last of Us', 'The Last Samurai', 'The Lego Movie', 'The Lincoln Lawyer', 'The Lion King', 'The Little Mermaid', 'The Lord of the Rings', 'The Mandalorian', 'The Martian',
      'The Mask', 'The Matrix', 'The Maze Runner', 'The Meg', 'The Menu', 'The Mummy', 'The Nightmare Before Christmas', 'The Notebook', 'The Odyssey', 'The Office',
      'The Other Guys', 'The Perfect Storm', 'The Perks of Being a Wallflower', 'The Phantom of the Opera', 'The Pianist', 'The Polar Express', 'The Prestige', 'The Prince of Egypt', 'The Princess Bride', 'The Promised Neverland',
      'The Purge', 'The Revenant', 'The Ring', 'The Road', 'The Sandlot', 'The Santa Clause', 'The Seven Deadly Sins', 'The Shawshank Redemption', 'The Shining', 'The Silence of the Lambs',
      'The Simpsons', 'The Sixth Sense', 'The Social Network', 'The Sopranos', 'The Sound of Music', 'The Substance', 'The Suicide Squad', 'The Summer I Turned Pretty', 'The Super Mario Bros. Movie', 'The Texas Chainsaw Massacre',
      'The Theory of Everything', 'The Thing', 'The Truman Show', 'The Twilight Zone', 'The Usual Suspects', 'The Vampire Diaries', 'The Walking Dead', 'The Whale', 'The Wild Robot', 'The Wire',
      'The Witcher', 'The Wizard of Oz', 'The Wolf of Wall Street', 'The X-Files', 'There Will Be Blood', 'Thunderbolts*', 'Titanic', "To All the Boys I've Loved Before", 'Tokyo Ghoul', 'Top Gun',
      'Toradora!', 'Total Recall', 'Toy Story', 'Train to Busan', 'Training Day', 'Transformers', 'Tremors', 'Trolls', 'Tron', 'Tropic Thunder',
      'Troy', 'True Detective', 'Twilight', 'Twister', 'Uncut Gems', 'Unfriended', 'Up', 'Us', 'V for Vendetta', 'Vikings',
      'Violet Evergarden', 'Walk the Line', 'WALL-E', 'War of the Worlds', 'Weapons', 'Wednesday', 'West Side Story', 'When Harry Met Sally...', 'Whiplash', 'White Chicks',
      'Wicked', 'Wonder Woman', 'Wonka', 'World War Z', 'Wreck-It Ralph', 'Wuthering Heights', 'X', 'X-Men', 'Yellowjackets', 'Yellowstone',
      'You', 'Your Lie in April', 'Your Name', 'Zero Dark Thirty', 'Zodiac', 'Zombieland', 'Zoolander', 'Zootopia'],
    'Numbers': [
      '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
      '10', '11', '12', '13', '14', '15', '16', '17', '18', '19',
      '20', '21', '22', '23', '24', '25', '26', '27', '28', '29',
      '30', '31', '32', '33', '34', '35', '36', '37', '38', '39',
      '40', '41', '42', '43', '44', '45', '46', '47', '48', '49',
      '50', '51', '52', '53', '54', '55', '56', '57', '58', '59',
      '60', '61', '62', '63', '64', '65', '66', '67', '68', '69',
      '70', '71', '72', '73', '74', '75', '76', '77', '78', '79',
      '80', '81', '82', '83', '84', '85', '86', '87', '88', '89',
      '90', '91', '92', '93', '94', '95', '96', '97', '98', '99',
      '100', '200', '500', '1000'],
    'Objects': [
      'Alarm Clock', 'Anchor', 'Apron', 'Axe', 'Backpack', 'Bag', 'Bandage', 'Baseball', 'Basket', 'Basketball',
      'Bathtub', 'Battery', 'Bed', 'Bell', 'Belt', 'Bench', 'Bicycle', 'Binder', 'Binoculars', 'Blanket',
      'Blender', 'Board Game', 'Bolt', 'Book', 'Bookshelf', 'Boots', 'Bottle', 'Bowl', 'Box', 'Bracelet',
      'Broom', 'Bucket', 'Button', 'Cabinet', 'Calculator', 'Calendar', 'Camera', 'Can Opener', 'Candle', 'Chain',
      'Chair', 'Chalk', 'Chandelier', 'Charger', 'Chess Set', 'Chopsticks', 'Clipboard', 'Clock', 'Clothes Iron', 'Coat',
      'Coffee Maker', 'Coin', 'Comb', 'Compass', 'Computer', 'Computer Mouse', 'Couch', 'Crayon', 'Credit Card', 'Crown',
      'Cup', 'Curtain', 'Cutting Board', 'Desk', 'Dice', 'Dictionary', 'Doll', 'Door', 'Doorbell', 'Dress',
      'Dresser', 'Drill', 'Drone', 'Drum', 'Earbuds', 'Earrings', 'Envelope', 'Eraser', 'Fan', 'Feather',
      'Fence', 'Fire Extinguisher', 'Fireplace', 'First Aid Kit', 'Fishing Rod', 'Flag', 'Flashlight', 'Flute', 'Folder', 'Fork',
      'Frisbee', 'Frying Pan', 'Game Controller', 'Gate', 'Gift', 'Glasses', 'Globe', 'Gloves', 'Glue', 'Guitar',
      'Hair Dryer', 'Hairbrush', 'Hammer', 'Hat', 'Headphones', 'Helmet', 'Highlighter', 'Hoodie', 'Hose', 'Jacket',
      'Jar', 'Jeans', 'Jump Rope', 'Kettle', 'Key', 'Keyboard', 'Kite', 'Knife', 'Ladder', 'Ladle',
      'Lamp', 'Lantern', 'Laptop', 'Lawn Mower', 'Lighter', 'Lock', 'Magazine', 'Magnet', 'Magnifying Glass', 'Mailbox',
      'Map', 'Marker', 'Matches', 'Mattress', 'Medal', 'Microphone', 'Microwave', 'Mirror', 'Mittens', 'Monitor',
      'Mug', 'Nail', 'Napkin', 'Necklace', 'Newspaper', 'Nightstand', 'Notebook', 'Oven', 'Painting', 'Pants',
      'Paperclip', 'Passport', 'Pen', 'Pencil', 'Pencil Sharpener', 'Perfume', 'Phone', 'Piano', 'Picture Frame', 'Pillow',
      'Plate', 'Playing Cards', 'Pliers', 'Pot', 'Printer', 'Projector', 'Purse', 'Puzzle', 'Radio', 'Rake',
      'Razor', 'Refrigerator', 'Remote Control', 'Ring', 'Rolling Pin', 'Rope', 'Router', 'Rubber Band', 'Rug', 'Ruler',
      'Sandals', 'Saw', 'Scarf', 'Scissors', 'Screw', 'Screwdriver', 'Sewing Machine', 'Shampoo', 'Shelf', 'Shirt',
      'Shoes', 'Shovel', 'Shower', 'Sink', 'Skateboard', 'Skirt', 'Skis', 'Sled', 'Sleeping Bag', 'Slippers',
      'Soap', 'Soccer Ball', 'Socks', 'Spatula', 'Speaker', 'Sponge', 'Spoon', 'Staircase', 'Stamp', 'Stapler',
      'Sticky Note', 'Stool', 'Stove', 'Straw', 'Suitcase', 'Sunglasses', 'Surfboard', 'Sweater', 'Swing', 'Table',
      'Tablet', 'Tape', 'Tape Measure', 'Teapot', 'Teddy Bear', 'Telescope', 'Television', 'Tennis Racket', 'Tent', 'Thermometer',
      'Thermos', 'Ticket', 'Tie', 'Tissue', 'Toaster', 'Toilet', 'Toilet Paper', 'Tongs', 'Toolbox', 'Toothbrush',
      'Toothpaste', 'Towel', 'Trash Can', 'Trophy', 'Trumpet', 'Umbrella', 'USB Drive', 'Vacuum', 'Vase', 'Violin',
      'Wallet', 'Wardrobe', 'Washing Machine', 'Watch', 'Wheelbarrow', 'Whisk', 'Whistle', 'Whiteboard', 'Window', 'Wrench',
      'Yo-yo', 'Zipper'],
  };

  // Jester hints, for the word-only categories. A Word Mode jester is handed the
  // round word's category and nothing else, which leaves them guessing at a pool
  // of two hundred — so with Jester Hints on, one of the round word's three is
  // drawn at random and printed on their card. One hint per round, not one per
  // jester: two jesters comparing notes would otherwise hold the whole answer.
  //
  // Keyed by category first, then by word. Seven words live in both Food/Drinks
  // and Animals — Chicken, Crab, Duck, Lobster, Salmon, Shrimp, Turkey — and a
  // flat map would hand an Animals round the food's hints, telling a jester the
  // chicken was 'Roasted' for 'Dinner'.
  //
  // Everything but Movies/TV, where a title is its own clue. A word with no
  // hints deals no hint, which is what Movies/TV and every custom category do.
  var wordHintCatalog = {
    'Animals': {
      'Ant': ['Tiny', 'Marching', 'Bug'],
      'Antelope': ['Slender', 'Leaping', 'Savanna'],
      'Axolotl': ['Pink', 'Smiling', 'Water'],
      'Baboon': ['Furry', 'Loud', 'Savanna'],
      'Badger': ['Striped', 'Digging', 'Forest'],
      'Bat': ['Winged', 'Nocturnal', 'Cave'],
      'Bear': ['Huge', 'Growling', 'Forest'],
      'Beaver': ['Toothy', 'Building', 'River'],
      'Bee': ['Tiny', 'Buzzing', 'Bug'],
      'Beetle': ['Shiny', 'Crawling', 'Bug'],
      'Buffalo': ['Massive', 'Charging', 'Plains'],
      'Butterfly': ['Colorful', 'Fluttering', 'Bug'],
      'Camel': ['Humped', 'Plodding', 'Desert'],
      'Cat': ['Furry', 'Purring', 'Pet'],
      'Caterpillar': ['Squishy', 'Crawling', 'Bug'],
      'Catfish': ['Whiskered', 'Bottom-dwelling', 'River'],
      'Chameleon': ['Scaly', 'Color-changing', 'Reptile'],
      'Cheetah': ['Spotted', 'Sprinting', 'Savanna'],
      'Chicken': ['Feathered', 'Clucking', 'Farm'],
      'Chimpanzee': ['Furry', 'Clever', 'Jungle'],
      'Chipmunk': ['Tiny', 'Scurrying', 'Forest'],
      'Clownfish': ['Orange', 'Darting', 'Ocean'],
      'Cobra': ['Hooded', 'Venomous', 'Reptile'],
      'Cockroach': ['Small', 'Scuttling', 'Bug'],
      'Cow': ['Heavy', 'Grazing', 'Farm'],
      'Coyote': ['Scruffy', 'Howling', 'Desert'],
      'Crab': ['Armored', 'Sideways', 'Beach'],
      'Crocodile': ['Toothy', 'Lurking', 'Swamp'],
      'Crow': ['Black', 'Clever', 'Bird'],
      'Deer': ['Antlered', 'Bounding', 'Forest'],
      'Dog': ['Furry', 'Loyal', 'Pet'],
      'Dolphin': ['Sleek', 'Leaping', 'Ocean'],
      'Donkey': ['Sturdy', 'Braying', 'Farm'],
      'Dragonfly': ['Winged', 'Hovering', 'Bug'],
      'Duck': ['Feathered', 'Paddling', 'Pond'],
      'Eagle': ['Winged', 'Soaring', 'Bird'],
      'Eel': ['Long', 'Slithering', 'Ocean'],
      'Elephant': ['Massive', 'Trumpeting', 'Savanna'],
      'Emu': ['Tall', 'Running', 'Bird'],
      'Falcon': ['Sharp', 'Diving', 'Bird'],
      'Ferret': ['Slinky', 'Playful', 'Pet'],
      'Firefly': ['Tiny', 'Glowing', 'Bug'],
      'Flamingo': ['Pink', 'Wading', 'Bird'],
      'Fly': ['Tiny', 'Buzzing', 'Bug'],
      'Fox': ['Red', 'Sneaky', 'Forest'],
      'Frog': ['Slimy', 'Hopping', 'Pond'],
      'Gecko': ['Small', 'Climbing', 'Reptile'],
      'Giraffe': ['Tall', 'Grazing', 'Savanna'],
      'Goat': ['Horned', 'Climbing', 'Farm'],
      'Goldfish': ['Orange', 'Swimming', 'Pet'],
      'Goose': ['Feathered', 'Honking', 'Pond'],
      'Gorilla': ['Massive', 'Strong', 'Jungle'],
      'Grasshopper': ['Green', 'Jumping', 'Bug'],
      'Guinea Pig': ['Round', 'Squeaking', 'Pet'],
      'Hamster': ['Tiny', 'Hoarding', 'Pet'],
      'Hawk': ['Sharp', 'Circling', 'Bird'],
      'Hedgehog': ['Spiky', 'Curling', 'Forest'],
      'Hippo': ['Massive', 'Wallowing', 'River'],
      'Horse': ['Large', 'Galloping', 'Farm'],
      'Hummingbird': ['Tiny', 'Hovering', 'Bird'],
      'Hyena': ['Scruffy', 'Cackling', 'Savanna'],
      'Iguana': ['Scaly', 'Basking', 'Reptile'],
      'Jaguar': ['Spotted', 'Prowling', 'Jungle'],
      'Jellyfish': ['Translucent', 'Drifting', 'Ocean'],
      'Kangaroo': ['Pouched', 'Hopping', 'Outback'],
      'Koala': ['Fuzzy', 'Sleepy', 'Treetop'],
      'Komodo Dragon': ['Huge', 'Lumbering', 'Reptile'],
      'Ladybug': ['Spotted', 'Crawling', 'Bug'],
      'Lemur': ['Ringed', 'Leaping', 'Jungle'],
      'Leopard': ['Spotted', 'Stalking', 'Savanna'],
      'Lion': ['Maned', 'Roaring', 'Savanna'],
      'Lizard': ['Scaly', 'Scurrying', 'Reptile'],
      'Llama': ['Fluffy', 'Spitting', 'Mountain'],
      'Lobster': ['Armored', 'Clawed', 'Ocean'],
      'Manatee': ['Round', 'Drifting', 'Ocean'],
      'Meerkat': ['Small', 'Standing', 'Desert'],
      'Mole': ['Small', 'Burrowing', 'Underground'],
      'Monkey': ['Furry', 'Swinging', 'Jungle'],
      'Moose': ['Antlered', 'Towering', 'Forest'],
      'Mosquito': ['Tiny', 'Biting', 'Bug'],
      'Mouse': ['Tiny', 'Scurrying', 'Indoors'],
      'Narwhal': ['Tusked', 'Diving', 'Arctic'],
      'Octopus': ['Rubbery', 'Sprawling', 'Ocean'],
      'Orangutan': ['Orange', 'Climbing', 'Jungle'],
      'Orca': ['Massive', 'Breaching', 'Ocean'],
      'Ostrich': ['Tall', 'Running', 'Bird'],
      'Otter': ['Sleek', 'Playful', 'River'],
      'Owl': ['Feathered', 'Nocturnal', 'Bird'],
      'Oyster': ['Shelled', 'Still', 'Ocean'],
      'Panda': ['Chubby', 'Munching', 'Bamboo'],
      'Parrot': ['Colorful', 'Talking', 'Bird'],
      'Peacock': ['Colorful', 'Strutting', 'Bird'],
      'Pelican': ['Beaked', 'Scooping', 'Bird'],
      'Penguin': ['Tuxedoed', 'Waddling', 'Arctic'],
      'Pig': ['Pink', 'Rooting', 'Farm'],
      'Pigeon': ['Gray', 'Strutting', 'City'],
      'Platypus': ['Odd', 'Paddling', 'River'],
      'Polar Bear': ['Massive', 'Prowling', 'Arctic'],
      'Porcupine': ['Spiky', 'Waddling', 'Forest'],
      'Pufferfish': ['Round', 'Inflating', 'Ocean'],
      'Puffin': ['Small', 'Diving', 'Bird'],
      'Python': ['Long', 'Squeezing', 'Reptile'],
      'Rabbit': ['Fluffy', 'Hopping', 'Pet'],
      'Raccoon': ['Masked', 'Sneaky', 'City'],
      'Rattlesnake': ['Coiled', 'Venomous', 'Desert'],
      'Red Panda': ['Fluffy', 'Climbing', 'Bamboo'],
      'Rhino': ['Horned', 'Charging', 'Savanna'],
      'Robin': ['Small', 'Chirping', 'Bird'],
      'Rooster': ['Feathered', 'Crowing', 'Farm'],
      'Salamander': ['Slimy', 'Creeping', 'Pond'],
      'Salmon': ['Silver', 'Swimming', 'River'],
      'Scorpion': ['Armored', 'Stinging', 'Desert'],
      'Sea Urchin': ['Spiky', 'Still', 'Ocean'],
      'Seagull': ['White', 'Squawking', 'Beach'],
      'Seahorse': ['Tiny', 'Drifting', 'Ocean'],
      'Seal': ['Sleek', 'Barking', 'Beach'],
      'Shark': ['Toothy', 'Circling', 'Ocean'],
      'Sheep': ['Woolly', 'Grazing', 'Farm'],
      'Shrimp': ['Tiny', 'Darting', 'Ocean'],
      'Skunk': ['Striped', 'Smelly', 'Forest'],
      'Sloth': ['Shaggy', 'Slow', 'Treetop'],
      'Snail': ['Shelled', 'Slow', 'Garden'],
      'Snake': ['Long', 'Slithering', 'Reptile'],
      'Sparrow': ['Tiny', 'Chirping', 'Bird'],
      'Spider': ['Eight-legged', 'Spinning', 'Bug'],
      'Squid': ['Rubbery', 'Darting', 'Ocean'],
      'Squirrel': ['Bushy', 'Climbing', 'Park'],
      'Starfish': ['Five-armed', 'Still', 'Beach'],
      'Stingray': ['Flat', 'Gliding', 'Ocean'],
      'Stork': ['Tall', 'Wading', 'Bird'],
      'Swan': ['White', 'Gliding', 'Pond'],
      'Swordfish': ['Pointed', 'Fast', 'Ocean'],
      'Termite': ['Tiny', 'Chewing', 'Bug'],
      'Tiger': ['Striped', 'Prowling', 'Jungle'],
      'Toucan': ['Colorful', 'Perching', 'Bird'],
      'Turkey': ['Feathered', 'Gobbling', 'Farm'],
      'Turtle': ['Shelled', 'Slow', 'Reptile'],
      'Vulture': ['Bald', 'Circling', 'Bird'],
      'Walrus': ['Tusked', 'Blubbery', 'Arctic'],
      'Warthog': ['Tusked', 'Trotting', 'Savanna'],
      'Wasp': ['Striped', 'Stinging', 'Bug'],
      'Whale': ['Massive', 'Spouting', 'Ocean'],
      'Wildebeest': ['Horned', 'Stampeding', 'Savanna'],
      'Wolf': ['Furry', 'Howling', 'Forest'],
      'Wombat': ['Stocky', 'Burrowing', 'Outback'],
      'Woodpecker': ['Sharp', 'Drumming', 'Bird'],
      'Worm': ['Slimy', 'Wriggling', 'Garden'],
      'Zebra': ['Striped', 'Galloping', 'Savanna'],
    },
    'Food/Drinks': {
      'Almonds': ['Crunchy', 'Small', 'Snack'],
      'Apple': ['Crunchy', 'Raw', 'Snack'],
      'Apple Pie': ['Sweet', 'Baked', 'Dessert'],
      'Avocado': ['Creamy', 'Green', 'Brunch'],
      'Bacon': ['Crispy', 'Salty', 'Breakfast'],
      'Bagel': ['Chewy', 'Round', 'Breakfast'],
      'Baguette': ['Crisp', 'Long', 'Side'],
      'Baked Potato': ['Baked', 'Fluffy', 'Side'],
      'Banana': ['Soft', 'Yellow', 'Snack'],
      'Banana Bread': ['Moist', 'Baked', 'Snack'],
      'Banh Mi': ['Crisp', 'Tangy', 'Lunch'],
      'Beef': ['Savory', 'Grilled', 'Dinner'],
      'Beef Stew': ['Hearty', 'Saucy', 'Comfort'],
      'Biryani': ['Spiced', 'Rice', 'Dinner'],
      'Biscuit': ['Flaky', 'Baked', 'Breakfast'],
      'BLT': ['Layered', 'Toasted', 'Lunch'],
      'Blueberries': ['Small', 'Sweet', 'Snack'],
      'Boba Milk Tea': ['Cold', 'Sweet', 'Drink'],
      'Bread': ['Soft', 'Baked', 'Simple'],
      'Broccoli': ['Green', 'Steamed', 'Side'],
      'Brownie': ['Fudgy', 'Baked', 'Dessert'],
      'Burger': ['Grilled', 'Stacked', 'Lunch'],
      'Burrito': ['Wrapped', 'Heavy', 'Lunch'],
      'Calzone': ['Cheesy', 'Baked', 'Dinner'],
      'Cantaloupe': ['Juicy', 'Soft', 'Snack'],
      'Carbonara': ['Creamy', 'Savory', 'Dinner'],
      'Carrot Cake': ['Moist', 'Spiced', 'Dessert'],
      'Carrots': ['Crunchy', 'Raw', 'Side'],
      'Cereal': ['Crunchy', 'Cold', 'Breakfast'],
      'Chai': ['Warm', 'Spiced', 'Drink'],
      'Cheese': ['Creamy', 'Sliced', 'Snack'],
      'Cheesecake': ['Creamy', 'Baked', 'Dessert'],
      'Cherries': ['Juicy', 'Small', 'Snack'],
      'Chicken': ['Savory', 'Roasted', 'Dinner'],
      'Chicken Noodle Soup': ['Warm', 'Noodle', 'Comfort'],
      'Chicken Nuggets': ['Fried', 'Bite-sized', 'Snack'],
      'Chicken Tikka Masala': ['Spiced', 'Saucy', 'Dinner'],
      'Chicken Wings': ['Fried', 'Saucy', 'Party'],
      'Chili': ['Hearty', 'Spiced', 'Comfort'],
      'Chocolate': ['Sweet', 'Melty', 'Snack'],
      'Chocolate Cake': ['Moist', 'Layered', 'Dessert'],
      'Chow Mein': ['Savory', 'Noodle', 'Dinner'],
      'Churros': ['Fried', 'Sweet', 'Dessert'],
      'Cinnamon Roll': ['Sweet', 'Sticky', 'Breakfast'],
      'Clam Chowder': ['Creamy', 'Warm', 'Comfort'],
      'Coconut': ['Chewy', 'Tropical', 'Snack'],
      'Coffee': ['Hot', 'Bitter', 'Morning'],
      'Coleslaw': ['Crunchy', 'Cold', 'Side'],
      'Cookies': ['Chewy', 'Baked', 'Snack'],
      'Corn Dog': ['Fried', 'Skewered', 'Party'],
      'Corn on the Cob': ['Grilled', 'Buttery', 'Side'],
      'Cotton Candy': ['Sweet', 'Light', 'Party'],
      'Crab': ['Rich', 'Boiled', 'Dinner'],
      'Crackers': ['Crunchy', 'Simple', 'Snack'],
      'Crème Brûlée': ['Creamy', 'Rich', 'Dessert'],
      'Crepes': ['Soft', 'Sweet', 'Brunch'],
      'Croissant': ['Flaky', 'Baked', 'Breakfast'],
      'Cucumber': ['Fresh', 'Cold', 'Side'],
      'Cupcake': ['Sweet', 'Frosted', 'Dessert'],
      'Curry': ['Spiced', 'Saucy', 'Dinner'],
      'Dim Sum': ['Steamed', 'Bite-sized', 'Brunch'],
      'Donut': ['Sweet', 'Fried', 'Breakfast'],
      'Duck': ['Rich', 'Roasted', 'Dinner'],
      'Dumplings': ['Steamed', 'Filled', 'Snack'],
      'Egg Rolls': ['Crispy', 'Wrapped', 'Snack'],
      'Elote': ['Grilled', 'Cheesy', 'Side'],
      'Enchiladas': ['Saucy', 'Baked', 'Dinner'],
      'Espresso': ['Hot', 'Bitter', 'Drink'],
      'Fajitas': ['Sizzling', 'Savory', 'Dinner'],
      'Falafel': ['Fried', 'Crispy', 'Lunch'],
      'Fettuccine Alfredo': ['Creamy', 'Saucy', 'Dinner'],
      'Fish and Chips': ['Crispy', 'Fried', 'Dinner'],
      'Flan': ['Creamy', 'Sweet', 'Dessert'],
      'French Fries': ['Crispy', 'Salty', 'Side'],
      'French Toast': ['Sweet', 'Fried', 'Breakfast'],
      'Fried Chicken': ['Crispy', 'Fried', 'Dinner'],
      'Fried Rice': ['Savory', 'Fried', 'Dinner'],
      'Garlic Bread': ['Warm', 'Baked', 'Side'],
      'Gnocchi': ['Soft', 'Boiled', 'Dinner'],
      'Granola': ['Crunchy', 'Sweet', 'Breakfast'],
      'Grapes': ['Juicy', 'Sweet', 'Snack'],
      'Green Beans': ['Fresh', 'Green', 'Side'],
      'Grilled Cheese': ['Melty', 'Grilled', 'Lunch'],
      'Guacamole': ['Creamy', 'Green', 'Snack'],
      'Gyro': ['Wrapped', 'Saucy', 'Lunch'],
      'Hash Browns': ['Crispy', 'Fried', 'Breakfast'],
      'Honey': ['Sweet', 'Sticky', 'Sweetener'],
      'Hot Chocolate': ['Warm', 'Sweet', 'Drink'],
      'Hot Dog': ['Grilled', 'Saucy', 'Lunch'],
      'Hot Pot': ['Warm', 'Savory', 'Dinner'],
      'Hummus': ['Creamy', 'Savory', 'Snack'],
      'Ice Cream': ['Cold', 'Sweet', 'Dessert'],
      'Iced Tea': ['Cold', 'Simple', 'Drink'],
      'Jam': ['Sweet', 'Sticky', 'Spread'],
      'Jello': ['Wobbly', 'Cold', 'Dessert'],
      'Kebab': ['Grilled', 'Skewered', 'Dinner'],
      'Key Lime Pie': ['Tart', 'Creamy', 'Dessert'],
      'Kimchi': ['Tangy', 'Spiced', 'Side'],
      'Kiwi': ['Tart', 'Green', 'Snack'],
      'Lamb': ['Rich', 'Roasted', 'Dinner'],
      'Lasagna': ['Layered', 'Baked', 'Dinner'],
      'Lemon': ['Tart', 'Raw', 'Simple'],
      'Lemonade': ['Cold', 'Tart', 'Drink'],
      'Lime': ['Tart', 'Green', 'Simple'],
      'Lobster': ['Rich', 'Boiled', 'Dinner'],
      'Lollipop': ['Sweet', 'Handheld', 'Snack'],
      'Macaron': ['Chewy', 'Bite-sized', 'Dessert'],
      'Macaroni and Cheese': ['Creamy', 'Baked', 'Comfort'],
      'Mango': ['Juicy', 'Sweet', 'Snack'],
      'Marshmallow': ['Soft', 'Sweet', 'Snack'],
      'Mashed Potatoes': ['Creamy', 'Whipped', 'Side'],
      'Matcha': ['Green', 'Warm', 'Drink'],
      'Meatballs': ['Savory', 'Saucy', 'Dinner'],
      'Meatloaf': ['Savory', 'Baked', 'Comfort'],
      'Milk': ['Cold', 'Simple', 'Drink'],
      'Milkshake': ['Cold', 'Sweet', 'Drink'],
      'Mochi': ['Chewy', 'Sweet', 'Dessert'],
      'Mozzarella Sticks': ['Melty', 'Fried', 'Party'],
      'Muffin': ['Sweet', 'Baked', 'Breakfast'],
      'Mushrooms': ['Savory', 'Soft', 'Side'],
      'Naan': ['Soft', 'Warm', 'Side'],
      'Nachos': ['Crunchy', 'Cheesy', 'Party'],
      'Oatmeal': ['Warm', 'Soft', 'Breakfast'],
      'Olives': ['Salty', 'Bite-sized', 'Snack'],
      'Omelette': ['Fluffy', 'Savory', 'Breakfast'],
      'Onigiri': ['Simple', 'Handheld', 'Snack'],
      'Onion': ['Sharp', 'Raw', 'Simple'],
      'Onion Rings': ['Crispy', 'Fried', 'Side'],
      'Orange': ['Juicy', 'Tart', 'Snack'],
      'Orange Chicken': ['Sweet', 'Fried', 'Dinner'],
      'Orange Juice': ['Cold', 'Tart', 'Drink'],
      'Pad Thai': ['Savory', 'Noodle', 'Dinner'],
      'Pancakes': ['Fluffy', 'Sweet', 'Breakfast'],
      'Panini': ['Grilled', 'Layered', 'Lunch'],
      'Pasta': ['Boiled', 'Saucy', 'Dinner'],
      'Peach': ['Juicy', 'Soft', 'Snack'],
      'Peanut Butter': ['Creamy', 'Sticky', 'Spread'],
      'Peanuts': ['Crunchy', 'Salty', 'Snack'],
      'Pear': ['Soft', 'Sweet', 'Snack'],
      'Pesto Pasta': ['Green', 'Savory', 'Dinner'],
      'Philly Cheesesteak': ['Cheesy', 'Savory', 'Lunch'],
      'Pho': ['Warm', 'Savory', 'Dinner'],
      'Pickles': ['Tangy', 'Cold', 'Side'],
      'Pineapple': ['Juicy', 'Tart', 'Snack'],
      'Pita': ['Soft', 'Simple', 'Side'],
      'Pizza': ['Cheesy', 'Baked', 'Party'],
      'Plum': ['Juicy', 'Soft', 'Snack'],
      'Poke': ['Cold', 'Fresh', 'Lunch'],
      'Pomegranate': ['Tart', 'Small', 'Snack'],
      'Popcorn': ['Crunchy', 'Salty', 'Snack'],
      'Popsicle': ['Cold', 'Sweet', 'Snack'],
      'Pork': ['Savory', 'Roasted', 'Dinner'],
      'Potato Chips': ['Crunchy', 'Salty', 'Snack'],
      'Potato Salad': ['Creamy', 'Cold', 'Side'],
      'Pretzel': ['Salty', 'Chewy', 'Snack'],
      'Pudding': ['Creamy', 'Soft', 'Dessert'],
      'Pumpkin Pie': ['Spiced', 'Baked', 'Dessert'],
      'Quesadilla': ['Cheesy', 'Grilled', 'Lunch'],
      'Ramen': ['Warm', 'Savory', 'Comfort'],
      'Raspberries': ['Tart', 'Small', 'Snack'],
      'Ravioli': ['Soft', 'Saucy', 'Dinner'],
      'Red Velvet Cake': ['Moist', 'Frosted', 'Dessert'],
      'Ribs': ['Saucy', 'Grilled', 'Dinner'],
      'Rice': ['Simple', 'Boiled', 'Side'],
      'Salad': ['Fresh', 'Cold', 'Lunch'],
      'Salmon': ['Savory', 'Grilled', 'Dinner'],
      'Salsa': ['Chunky', 'Tangy', 'Dip'],
      'Samosa': ['Crispy', 'Filled', 'Snack'],
      'Sandwich': ['Layered', 'Handheld', 'Lunch'],
      'Sausage': ['Savory', 'Grilled', 'Breakfast'],
      'Scone': ['Baked', 'Simple', 'Breakfast'],
      'Scrambled Eggs': ['Soft', 'Fluffy', 'Breakfast'],
      'Shawarma': ['Savory', 'Wrapped', 'Lunch'],
      "Shepherd's Pie": ['Hearty', 'Baked', 'Comfort'],
      'Shrimp': ['Savory', 'Bite-sized', 'Dinner'],
      'Sloppy Joe': ['Saucy', 'Handheld', 'Comfort'],
      'Smoothie': ['Cold', 'Sweet', 'Drink'],
      'Soda': ['Cold', 'Sweet', 'Drink'],
      'Soup': ['Warm', 'Savory', 'Comfort'],
      'Spaghetti': ['Long', 'Saucy', 'Dinner'],
      'Spring Rolls': ['Crisp', 'Wrapped', 'Snack'],
      'Strawberry': ['Juicy', 'Sweet', 'Snack'],
      'Sub Sandwich': ['Layered', 'Long', 'Lunch'],
      'Sushi': ['Cold', 'Savory', 'Bite-sized'],
      'Sweet Potato': ['Soft', 'Sweet', 'Side'],
      'Tacos': ['Handheld', 'Savory', 'Lunch'],
      'Tamales': ['Steamed', 'Filled', 'Comfort'],
      'Tea': ['Warm', 'Simple', 'Drink'],
      'Tiramisu': ['Sweet', 'Creamy', 'Dessert'],
      'Toast': ['Crispy', 'Simple', 'Breakfast'],
      'Tofu': ['Soft', 'Simple', 'Savory'],
      'Tomato': ['Juicy', 'Raw', 'Simple'],
      'Tomato Soup': ['Warm', 'Simple', 'Comfort'],
      'Tuna': ['Savory', 'Simple', 'Lunch'],
      'Turkey': ['Savory', 'Roasted', 'Dinner'],
      'Udon': ['Soft', 'Warm', 'Comfort'],
      'Veggie Burger': ['Grilled', 'Stacked', 'Lunch'],
      'Waffles': ['Sweet', 'Crispy', 'Breakfast'],
      'Watermelon': ['Juicy', 'Sweet', 'Snack'],
      'Wontons': ['Soft', 'Filled', 'Bite-sized'],
      'Xiao Long Bao': ['Steamed', 'Filled', 'Bite-sized'],
      'Yogurt': ['Creamy', 'Cold', 'Breakfast'],
    },
    'Objects': {
      'Alarm Clock': ['Plastic', 'Small', 'Bedroom'],
      'Anchor': ['Metal', 'Heavy', 'Outdoors'],
      'Apron': ['Fabric', 'Flat', 'Kitchen'],
      'Axe': ['Metal', 'Sharp', 'Outdoors'],
      'Backpack': ['Fabric', 'Roomy', 'Travel'],
      'Bag': ['Fabric', 'Foldable', 'Everyday'],
      'Bandage': ['Fabric', 'Thin', 'Medical'],
      'Baseball': ['Leather', 'Round', 'Sports'],
      'Basket': ['Woven', 'Hollow', 'Storage'],
      'Basketball': ['Rubber', 'Round', 'Sports'],
      'Bathtub': ['Ceramic', 'Large', 'Bathroom'],
      'Battery': ['Metal', 'Small', 'Electronics'],
      'Bed': ['Soft', 'Large', 'Bedroom'],
      'Bell': ['Metal', 'Hollow', 'Noisy'],
      'Belt': ['Leather', 'Long', 'Wearable'],
      'Bench': ['Wooden', 'Long', 'Outdoors'],
      'Bicycle': ['Metal', 'Large', 'Outdoors'],
      'Binder': ['Plastic', 'Flat', 'Office'],
      'Binoculars': ['Plastic', 'Handheld', 'Outdoors'],
      'Blanket': ['Soft', 'Flat', 'Bedroom'],
      'Blender': ['Plastic', 'Loud', 'Kitchen'],
      'Board Game': ['Cardboard', 'Flat', 'Toy'],
      'Bolt': ['Metal', 'Tiny', 'Tools'],
      'Book': ['Paper', 'Flat', 'Reading'],
      'Bookshelf': ['Wooden', 'Tall', 'Living Room'],
      'Boots': ['Leather', 'Sturdy', 'Wearable'],
      'Bottle': ['Plastic', 'Hollow', 'Kitchen'],
      'Bowl': ['Ceramic', 'Round', 'Kitchen'],
      'Box': ['Cardboard', 'Boxy', 'Storage'],
      'Bracelet': ['Metal', 'Tiny', 'Wearable'],
      'Broom': ['Bristly', 'Long', 'Cleaning'],
      'Bucket': ['Plastic', 'Hollow', 'Cleaning'],
      'Button': ['Plastic', 'Tiny', 'Wearable'],
      'Cabinet': ['Wooden', 'Large', 'Kitchen'],
      'Calculator': ['Plastic', 'Small', 'Office'],
      'Calendar': ['Paper', 'Flat', 'Office'],
      'Camera': ['Plastic', 'Handheld', 'Electronics'],
      'Can Opener': ['Metal', 'Handheld', 'Kitchen'],
      'Candle': ['Waxy', 'Small', 'Decor'],
      'Chain': ['Metal', 'Long', 'Tools'],
      'Chair': ['Wooden', 'Sturdy', 'Furniture'],
      'Chalk': ['Dusty', 'Small', 'School'],
      'Chandelier': ['Glass', 'Hanging', 'Decor'],
      'Charger': ['Plastic', 'Long', 'Electronics'],
      'Chess Set': ['Wooden', 'Small', 'Toy'],
      'Chopsticks': ['Wooden', 'Thin', 'Kitchen'],
      'Clipboard': ['Plastic', 'Flat', 'Office'],
      'Clock': ['Plastic', 'Round', 'Decor'],
      'Clothes Iron': ['Metal', 'Hot', 'Laundry'],
      'Coat': ['Fabric', 'Bulky', 'Wearable'],
      'Coffee Maker': ['Plastic', 'Bulky', 'Kitchen'],
      'Coin': ['Metal', 'Tiny', 'Money'],
      'Comb': ['Plastic', 'Flat', 'Bathroom'],
      'Compass': ['Metal', 'Small', 'Outdoors'],
      'Computer': ['Plastic', 'Bulky', 'Electronics'],
      'Computer Mouse': ['Plastic', 'Handheld', 'Electronics'],
      'Couch': ['Soft', 'Large', 'Living Room'],
      'Crayon': ['Waxy', 'Small', 'School'],
      'Credit Card': ['Plastic', 'Flat', 'Money'],
      'Crown': ['Metal', 'Shiny', 'Wearable'],
      'Cup': ['Ceramic', 'Hollow', 'Kitchen'],
      'Curtain': ['Fabric', 'Hanging', 'Decor'],
      'Cutting Board': ['Wooden', 'Flat', 'Kitchen'],
      'Desk': ['Wooden', 'Large', 'Office'],
      'Dice': ['Plastic', 'Tiny', 'Toy'],
      'Dictionary': ['Paper', 'Heavy', 'Reading'],
      'Doll': ['Plastic', 'Small', 'Toy'],
      'Door': ['Wooden', 'Tall', 'Household'],
      'Doorbell': ['Plastic', 'Tiny', 'Noisy'],
      'Dress': ['Fabric', 'Flowing', 'Wearable'],
      'Dresser': ['Wooden', 'Bulky', 'Bedroom'],
      'Drill': ['Metal', 'Loud', 'Tools'],
      'Drone': ['Plastic', 'Flying', 'Electronics'],
      'Drum': ['Hollow', 'Loud', 'Music'],
      'Earbuds': ['Plastic', 'Tiny', 'Electronics'],
      'Earrings': ['Metal', 'Tiny', 'Wearable'],
      'Envelope': ['Paper', 'Flat', 'Mail'],
      'Eraser': ['Rubber', 'Small', 'School'],
      'Fan': ['Plastic', 'Spinning', 'Cooling'],
      'Feather': ['Soft', 'Light', 'Nature'],
      'Fence': ['Wooden', 'Long', 'Outdoors'],
      'Fire Extinguisher': ['Metal', 'Heavy', 'Safety'],
      'Fireplace': ['Stone', 'Hot', 'Living Room'],
      'First Aid Kit': ['Plastic', 'Small', 'Safety'],
      'Fishing Rod': ['Thin', 'Long', 'Outdoors'],
      'Flag': ['Fabric', 'Flapping', 'Outdoors'],
      'Flashlight': ['Plastic', 'Handheld', 'Camping'],
      'Flute': ['Metal', 'Long', 'Music'],
      'Folder': ['Paper', 'Flat', 'Office'],
      'Fork': ['Metal', 'Pointed', 'Kitchen'],
      'Frisbee': ['Plastic', 'Flat', 'Sports'],
      'Frying Pan': ['Metal', 'Round', 'Kitchen'],
      'Game Controller': ['Plastic', 'Handheld', 'Electronics'],
      'Gate': ['Metal', 'Tall', 'Outdoors'],
      'Gift': ['Wrapped', 'Boxy', 'Party'],
      'Glasses': ['Glass', 'Light', 'Wearable'],
      'Globe': ['Plastic', 'Round', 'School'],
      'Gloves': ['Fabric', 'Snug', 'Wearable'],
      'Glue': ['Sticky', 'Small', 'School'],
      'Guitar': ['Wooden', 'Stringed', 'Music'],
      'Hair Dryer': ['Plastic', 'Loud', 'Bathroom'],
      'Hairbrush': ['Bristly', 'Handheld', 'Bathroom'],
      'Hammer': ['Metal', 'Heavy', 'Tools'],
      'Hat': ['Fabric', 'Round', 'Wearable'],
      'Headphones': ['Plastic', 'Bulky', 'Electronics'],
      'Helmet': ['Hard', 'Round', 'Safety'],
      'Highlighter': ['Plastic', 'Bright', 'Office'],
      'Hoodie': ['Soft', 'Bulky', 'Wearable'],
      'Hose': ['Rubber', 'Long', 'Garden'],
      'Jacket': ['Fabric', 'Bulky', 'Wearable'],
      'Jar': ['Glass', 'Hollow', 'Kitchen'],
      'Jeans': ['Denim', 'Sturdy', 'Wearable'],
      'Jump Rope': ['Plastic', 'Long', 'Sports'],
      'Kettle': ['Metal', 'Hot', 'Kitchen'],
      'Key': ['Metal', 'Tiny', 'Everyday'],
      'Keyboard': ['Plastic', 'Flat', 'Electronics'],
      'Kite': ['Fabric', 'Flying', 'Outdoors'],
      'Knife': ['Metal', 'Sharp', 'Kitchen'],
      'Ladder': ['Metal', 'Tall', 'Tools'],
      'Ladle': ['Metal', 'Curved', 'Kitchen'],
      'Lamp': ['Bright', 'Tall', 'Living Room'],
      'Lantern': ['Metal', 'Glowing', 'Camping'],
      'Laptop': ['Plastic', 'Flat', 'Electronics'],
      'Lawn Mower': ['Metal', 'Loud', 'Garden'],
      'Lighter': ['Plastic', 'Tiny', 'Fire'],
      'Lock': ['Metal', 'Small', 'Security'],
      'Magazine': ['Paper', 'Flat', 'Reading'],
      'Magnet': ['Metal', 'Small', 'Sticky'],
      'Magnifying Glass': ['Glass', 'Handheld', 'Reading'],
      'Mailbox': ['Metal', 'Hollow', 'Mail'],
      'Map': ['Paper', 'Flat', 'Travel'],
      'Marker': ['Plastic', 'Small', 'School'],
      'Matches': ['Wooden', 'Tiny', 'Fire'],
      'Mattress': ['Soft', 'Large', 'Bedroom'],
      'Medal': ['Metal', 'Shiny', 'Sports'],
      'Microphone': ['Metal', 'Handheld', 'Music'],
      'Microwave': ['Metal', 'Boxy', 'Kitchen'],
      'Mirror': ['Glass', 'Flat', 'Bathroom'],
      'Mittens': ['Soft', 'Snug', 'Wearable'],
      'Monitor': ['Glass', 'Flat', 'Electronics'],
      'Mug': ['Ceramic', 'Hollow', 'Kitchen'],
      'Nail': ['Metal', 'Pointed', 'Tools'],
      'Napkin': ['Paper', 'Flat', 'Kitchen'],
      'Necklace': ['Metal', 'Hanging', 'Wearable'],
      'Newspaper': ['Paper', 'Thin', 'Reading'],
      'Nightstand': ['Wooden', 'Small', 'Bedroom'],
      'Notebook': ['Paper', 'Flat', 'School'],
      'Oven': ['Metal', 'Hot', 'Kitchen'],
      'Painting': ['Framed', 'Flat', 'Decor'],
      'Pants': ['Fabric', 'Long', 'Wearable'],
      'Paperclip': ['Metal', 'Tiny', 'Office'],
      'Passport': ['Paper', 'Small', 'Travel'],
      'Pen': ['Plastic', 'Thin', 'Office'],
      'Pencil': ['Wooden', 'Thin', 'School'],
      'Pencil Sharpener': ['Plastic', 'Tiny', 'School'],
      'Perfume': ['Glass', 'Small', 'Bathroom'],
      'Phone': ['Glass', 'Handheld', 'Electronics'],
      'Piano': ['Wooden', 'Heavy', 'Music'],
      'Picture Frame': ['Wooden', 'Flat', 'Decor'],
      'Pillow': ['Soft', 'Squishy', 'Bedroom'],
      'Plate': ['Ceramic', 'Flat', 'Kitchen'],
      'Playing Cards': ['Paper', 'Flat', 'Toy'],
      'Pliers': ['Metal', 'Handheld', 'Tools'],
      'Pot': ['Metal', 'Hollow', 'Kitchen'],
      'Printer': ['Plastic', 'Bulky', 'Office'],
      'Projector': ['Plastic', 'Bright', 'Electronics'],
      'Purse': ['Leather', 'Small', 'Everyday'],
      'Puzzle': ['Cardboard', 'Flat', 'Toy'],
      'Radio': ['Plastic', 'Boxy', 'Electronics'],
      'Rake': ['Metal', 'Long', 'Garden'],
      'Razor': ['Metal', 'Sharp', 'Bathroom'],
      'Refrigerator': ['Metal', 'Cold', 'Kitchen'],
      'Remote Control': ['Plastic', 'Handheld', 'Living Room'],
      'Ring': ['Metal', 'Tiny', 'Wearable'],
      'Rolling Pin': ['Wooden', 'Long', 'Kitchen'],
      'Rope': ['Fibrous', 'Long', 'Outdoors'],
      'Router': ['Plastic', 'Small', 'Electronics'],
      'Rubber Band': ['Rubber', 'Stretchy', 'Office'],
      'Rug': ['Fabric', 'Flat', 'Living Room'],
      'Ruler': ['Plastic', 'Straight', 'School'],
      'Sandals': ['Rubber', 'Flat', 'Wearable'],
      'Saw': ['Metal', 'Sharp', 'Tools'],
      'Scarf': ['Soft', 'Long', 'Wearable'],
      'Scissors': ['Metal', 'Sharp', 'Office'],
      'Screw': ['Metal', 'Tiny', 'Tools'],
      'Screwdriver': ['Metal', 'Handheld', 'Tools'],
      'Sewing Machine': ['Metal', 'Loud', 'Crafts'],
      'Shampoo': ['Slippery', 'Bottled', 'Bathroom'],
      'Shelf': ['Wooden', 'Flat', 'Storage'],
      'Shirt': ['Fabric', 'Light', 'Wearable'],
      'Shoes': ['Leather', 'Sturdy', 'Wearable'],
      'Shovel': ['Metal', 'Long', 'Garden'],
      'Shower': ['Wet', 'Tall', 'Bathroom'],
      'Sink': ['Ceramic', 'Hollow', 'Bathroom'],
      'Skateboard': ['Wooden', 'Flat', 'Sports'],
      'Skirt': ['Fabric', 'Flowing', 'Wearable'],
      'Skis': ['Thin', 'Long', 'Sports'],
      'Sled': ['Plastic', 'Flat', 'Winter'],
      'Sleeping Bag': ['Soft', 'Bulky', 'Camping'],
      'Slippers': ['Soft', 'Snug', 'Wearable'],
      'Soap': ['Slippery', 'Small', 'Bathroom'],
      'Soccer Ball': ['Leather', 'Round', 'Sports'],
      'Socks': ['Soft', 'Snug', 'Wearable'],
      'Spatula': ['Plastic', 'Flat', 'Kitchen'],
      'Speaker': ['Plastic', 'Loud', 'Electronics'],
      'Sponge': ['Squishy', 'Small', 'Cleaning'],
      'Spoon': ['Metal', 'Curved', 'Kitchen'],
      'Staircase': ['Wooden', 'Tall', 'Household'],
      'Stamp': ['Paper', 'Tiny', 'Mail'],
      'Stapler': ['Metal', 'Small', 'Office'],
      'Sticky Note': ['Paper', 'Tiny', 'Office'],
      'Stool': ['Wooden', 'Small', 'Furniture'],
      'Stove': ['Metal', 'Hot', 'Kitchen'],
      'Straw': ['Plastic', 'Thin', 'Kitchen'],
      'Suitcase': ['Hard', 'Boxy', 'Travel'],
      'Sunglasses': ['Dark', 'Light', 'Wearable'],
      'Surfboard': ['Smooth', 'Long', 'Sports'],
      'Sweater': ['Soft', 'Bulky', 'Wearable'],
      'Swing': ['Hanging', 'Sturdy', 'Playground'],
      'Table': ['Wooden', 'Flat', 'Furniture'],
      'Tablet': ['Glass', 'Flat', 'Electronics'],
      'Tape': ['Sticky', 'Thin', 'Office'],
      'Tape Measure': ['Metal', 'Long', 'Tools'],
      'Teapot': ['Ceramic', 'Hollow', 'Kitchen'],
      'Teddy Bear': ['Soft', 'Squishy', 'Toy'],
      'Telescope': ['Metal', 'Long', 'Stargazing'],
      'Television': ['Glass', 'Flat', 'Living Room'],
      'Tennis Racket': ['Stringed', 'Handheld', 'Sports'],
      'Tent': ['Fabric', 'Roomy', 'Camping'],
      'Thermometer': ['Glass', 'Thin', 'Medical'],
      'Thermos': ['Metal', 'Hollow', 'Travel'],
      'Ticket': ['Paper', 'Tiny', 'Travel'],
      'Tie': ['Fabric', 'Long', 'Wearable'],
      'Tissue': ['Paper', 'Soft', 'Household'],
      'Toaster': ['Metal', 'Hot', 'Kitchen'],
      'Toilet': ['Ceramic', 'Bulky', 'Bathroom'],
      'Toilet Paper': ['Paper', 'Soft', 'Bathroom'],
      'Tongs': ['Metal', 'Handheld', 'Kitchen'],
      'Toolbox': ['Metal', 'Boxy', 'Storage'],
      'Toothbrush': ['Bristly', 'Small', 'Bathroom'],
      'Toothpaste': ['Minty', 'Small', 'Bathroom'],
      'Towel': ['Soft', 'Flat', 'Bathroom'],
      'Trash Can': ['Plastic', 'Hollow', 'Cleaning'],
      'Trophy': ['Shiny', 'Tall', 'Sports'],
      'Trumpet': ['Metal', 'Shiny', 'Music'],
      'Umbrella': ['Fabric', 'Curved', 'Rainy'],
      'USB Drive': ['Plastic', 'Tiny', 'Electronics'],
      'Vacuum': ['Plastic', 'Loud', 'Cleaning'],
      'Vase': ['Glass', 'Hollow', 'Decor'],
      'Violin': ['Wooden', 'Stringed', 'Music'],
      'Wallet': ['Leather', 'Small', 'Everyday'],
      'Wardrobe': ['Wooden', 'Tall', 'Bedroom'],
      'Washing Machine': ['Metal', 'Loud', 'Laundry'],
      'Watch': ['Metal', 'Tiny', 'Wearable'],
      'Wheelbarrow': ['Metal', 'Bulky', 'Garden'],
      'Whisk': ['Metal', 'Curved', 'Kitchen'],
      'Whistle': ['Metal', 'Tiny', 'Noisy'],
      'Whiteboard': ['Smooth', 'Flat', 'Office'],
      'Window': ['Glass', 'Flat', 'Household'],
      'Wrench': ['Metal', 'Handheld', 'Tools'],
      'Yo-yo': ['Plastic', 'Round', 'Toy'],
      'Zipper': ['Metal', 'Thin', 'Wearable'],
    },
  };
  window.MASQ_WORDS = {
    'wordOnlyCatalog': wordOnlyCatalog,
    'wordHintCatalog': wordHintCatalog,
  };
})();
