// Masq Word Mode data: the word-only catalogs, and the jester hints that go
// with them. Plain script, exposed on window.MASQ_WORDS.
//
// Split out of src/data_roles.js, which holds the role catalogs. These two belong
// together and to nothing else: a word-only category has no roles, so none of
// the fake-role machinery next door applies to it, and the hints are keyed by
// the very categories listed here.
(function () {
  var wordOnlyCatalog = {
    'Animals': [
      'Alpaca', 'Ant', 'Antelope', 'Baboon', 'Bat', 'Bear', 'Beaver', 'Bee', 'Bison', 'Buffalo',
      'Butterfly', 'Camel', 'Chameleon', 'Cheetah', 'Chicken', 'Chimpanzee', 'Cow', 'Crab', 'Crocodile', 'Deer',
      'Dolphin', 'Donkey', 'Duck', 'Eagle', 'Elephant', 'Elk', 'Falcon', 'Flamingo', 'Fox', 'Frog',
      'Gazelle', 'Giraffe', 'Goat', 'Gorilla', 'Guinea Pig', 'Hamster', 'Hawk', 'Hedgehog', 'Hippo', 'Horse',
      'Hyena', 'Jaguar', 'Jellyfish', 'Kangaroo', 'Koala', 'Lemur', 'Leopard', 'Lion', 'Lizard', 'Llama',
      'Lobster', 'Meerkat', 'Moose', 'Mouse', 'Octopus', 'Orangutan', 'Orca', 'Otter', 'Owl', 'Panda',
      'Panther', 'Parrot', 'Peacock', 'Penguin', 'Pig', 'Platypus', 'Polar Bear', 'Rabbit', 'Raccoon', 'Rat',
      'Red Panda', 'Rhino', 'Scorpion', 'Seal', 'Shark', 'Sheep', 'Shrimp', 'Skunk', 'Sloth', 'Snail',
      'Snake', 'Spider', 'Squirrel', 'Starfish', 'Stingray', 'Swan', 'Tiger', 'Toad', 'Tortoise', 'Toucan',
      'Turkey', 'Turtle', 'Vulture', 'Walrus', 'Warthog', 'Whale', 'Wildebeest', 'Wolf', 'Wombat', 'Zebra'],
    'Food': [
      'Almonds', 'Apple', 'Apple Pie', 'Avocado', 'Bacon', 'Bagel', 'Baguette', 'Baked Potato', 'Banana',
      'Banana Bread', 'Banh Mi', 'Beef', 'Beef Stew', 'Biryani', 'Biscuit', 'BLT', 'Blueberries',
      'Boba Milk Tea', 'Bread', 'Broccoli', 'Brownie', 'Burger', 'Burrito', 'Calzone', 'Cantaloupe',
      'Carbonara', 'Carrot Cake', 'Carrots', 'Cereal', 'Chai', 'Cheese', 'Cheesecake', 'Cherries', 'Chicken',
      'Chicken Noodle Soup', 'Chicken Nuggets', 'Chicken Tikka Masala', 'Chicken Wings', 'Chili', 'Chocolate',
      'Chocolate Cake', 'Chow Mein', 'Churros', 'Cinnamon Roll', 'Clam Chowder', 'Coconut', 'Coffee',
      'Coleslaw', 'Cookies', 'Corn Dog', 'Corn on the Cob', 'Cotton Candy', 'Crab', 'Crackers',
      'Crème Brûlée', 'Crepes', 'Croissant', 'Cucumber', 'Cupcake', 'Curry', 'Dim Sum', 'Donut', 'Duck',
      'Dumplings', 'Egg Rolls', 'Elote', 'Enchiladas', 'Espresso', 'Fajitas', 'Falafel', 'Fettuccine Alfredo',
      'Fish and Chips', 'Flan', 'French Fries', 'French Toast', 'Fried Chicken', 'Fried Rice', 'Garlic Bread',
      'Gnocchi', 'Granola', 'Grapes', 'Green Beans', 'Grilled Cheese', 'Guacamole', 'Gyro', 'Hash Browns',
      'Honey', 'Hot Chocolate', 'Hot Dog', 'Hot Pot', 'Hummus', 'Ice Cream', 'Iced Tea', 'Jam', 'Jello',
      'Kebab', 'Key Lime Pie', 'Kimchi', 'Kiwi', 'Lamb', 'Lasagna', 'Lemon', 'Lemonade', 'Lime', 'Lobster',
      'Lollipop', 'Macaron', 'Macaroni and Cheese', 'Mango', 'Marshmallow', 'Mashed Potatoes', 'Matcha',
      'Meatballs', 'Meatloaf', 'Milk', 'Milkshake', 'Mochi', 'Mozzarella Sticks', 'Muffin', 'Mushrooms',
      'Naan', 'Nachos', 'Oatmeal', 'Olives', 'Omelette', 'Onigiri', 'Onion', 'Onion Rings', 'Orange',
      'Orange Chicken', 'Orange Juice', 'Pad Thai', 'Pancakes', 'Panini', 'Pasta', 'Peach', 'Peanut Butter',
      'Peanuts', 'Pear', 'Pesto Pasta', 'Philly Cheesesteak', 'Pho', 'Pickles', 'Pineapple', 'Pita', 'Pizza',
      'Plum', 'Poke', 'Pomegranate', 'Popcorn', 'Popsicle', 'Pork', 'Potato Chips', 'Potato Salad', 'Pretzel',
      'Pudding', 'Pumpkin Pie', 'Quesadilla', 'Ramen', 'Raspberries', 'Ravioli', 'Red Velvet Cake', 'Ribs',
      'Rice', 'Salad', 'Salmon', 'Salsa', 'Samosa', 'Sandwich', 'Sausage', 'Scone', 'Scrambled Eggs',
      'Shawarma', "Shepherd's Pie", 'Shrimp', 'Sloppy Joe', 'Smoothie', 'Soda', 'Soup', 'Spaghetti',
      'Spring Rolls', 'Strawberry', 'Sub Sandwich', 'Sushi', 'Sweet Potato', 'Tacos', 'Tamales', 'Tea',
      'Tiramisu', 'Toast', 'Tofu', 'Tomato', 'Tomato Soup', 'Tuna', 'Turkey', 'Udon', 'Veggie Burger',
      'Waffles', 'Watermelon', 'Wontons', 'Xiao Long Bao', 'Yogurt'],
    'Movies/TV': [
      '(500) Days of Summer', '10 Things I Hate About You', '12 Angry Men', '12 Monkeys', '127 Hours', '13 Reasons Why', '1917', '1984', '2001: A Space Odyssey', '2012',
      '21 Jump Street', '28 Days Later', '3:10 to Yuma', '300', 'A Beautiful Mind', 'A Christmas Carol', 'A Christmas Story', 'A Few Good Men', 'A Nightmare on Elm Street', 'A Quiet Place',
      'A Simple Favor', 'A Time to Kill', 'About Time', 'Airplane!', 'Aladdin', 'Alien', 'Alita: Battle Angel', 'Alive', 'All of Us Are Dead', 'American Gangster',
      'American History X', 'American Horror Story', 'American Sniper', 'An American Werewolf in London', 'Anaconda', 'Anchorman', 'Annihilation', 'Apocalypse Now', 'Apollo 13', 'Argo',
      'Armageddon', 'Army of the Dead', 'Arrival', 'Atomic Blonde', 'Attack on Titan', 'Austin Powers', 'Avatar', 'Baby Driver', 'Back to the Future', 'Bad Boys',
      'Band of Brothers', 'Beauty and the Beast', 'Ben-Hur', 'Beverly Hills Cop', 'Big Little Lies', "Bill & Ted's Excellent Adventure", 'Bird Box', 'Black Hawk Down', 'Black Mirror', 'Black Panther',
      'Black Swan', 'Blade Runner', 'Bohemian Rhapsody', 'Booksmart', 'Borat', 'Braveheart', 'Breaking Bad', 'Bridesmaids', 'Bridge of Spies', 'Bridgerton',
      'Brooklyn Nine-Nine', 'Butch Cassidy and the Sundance Kid', 'Candyman', 'Captain America', 'Captain Phillips', 'Casino', 'Casino Royale', 'Cast Away', 'Chernobyl', 'Chicago',
      "Child's Play", 'Children of Men', 'Chinatown', 'Chronicle', 'Close Encounters of the Third Kind', 'Cloverfield', 'Clue', 'Clueless', 'Coach Carter', 'Cocaine Bear',
      'Coco', 'Con Air', 'Contagion', 'Cool Hand Luke', 'Coraline', 'Cowboy Bebop', 'Crazy Rich Asians', 'Creed', "Dante's Peak", 'Daredevil',
      'Dark', 'Dawn of the Dead', 'Dead Poets Society', 'Deadpool', 'Deadwood', 'Death Becomes Her', 'Death Note', 'Death on the Nile', 'Deep Impact', 'Demon Slayer',
      'Despicable Me', 'Die Hard', 'District 9', 'Divergent', 'Django Unchained', 'Doctor Who', 'Dragon Ball Z', 'Dumb and Dumber', 'Dune', 'Dunkirk',
      'E.T.', 'Easy A', 'Edge of Tomorrow', 'Elf', 'Elvis', 'End of Watch', 'Erin Brockovich', 'Escape from Alcatraz', 'Euphoria', 'Everest',
      'Ex Machina', 'Fallout', 'Fast and Furious', 'Fight Club', 'Finding Nemo', 'Friday Night Lights', 'Friday the 13th', 'Friends', 'Frozen', 'Full Metal Jacket',
      'Fullmetal Alchemist: Brotherhood', 'Game of Thrones', 'Get Out', 'Ghost in the Shell', 'Ghostbusters', 'Gladiator', 'Glass Onion', 'Glee', 'Godzilla', 'Godzilla Minus One',
      'Gone Girl', 'Goodfellas', 'Gravity', 'Grease', 'Groundhog Day', 'Guardians of the Galaxy', 'Hacksaw Ridge', 'Hairspray', 'Halloween', 'Hamilton',
      'Hannibal', 'Happy Death Day', 'Happy Gilmore', 'Harry Potter', 'Heat', 'Hereditary', 'Holes', 'Home Alone', 'Hot Fuzz', 'How the Grinch Stole Christmas',
      'How to Train Your Dragon', "Howl's Moving Castle", 'I Am Legend', 'I Know What You Did Last Summer', 'Inception', 'Independence Day', 'Indiana Jones', 'Inglourious Basterds', 'Inside Man', 'Inside Out',
      'Insidious', 'Interstellar', 'Into the Wild', 'Invincible', 'Iron Man', 'It', "It's a Wonderful Life", 'Jaws', "Jennifer's Body", 'Jingle All the Way',
      'John Wick', 'Jujutsu Kaisen', 'Jumanji: Welcome to the Jungle', 'Jurassic Park', 'Jurassic World', 'Kill Bill', 'Killing Eve', 'King Kong', 'Kingdom of Heaven', 'Kingsman',
      'Klaus', 'Knives Out', 'Kong: Skull Island', 'Kung Fu Panda', 'La La Land', 'Lady Bird', 'Law & Order', 'Lawrence of Arabia', 'Legally Blonde', 'Les Miserables',
      'Lethal Weapon', 'Life of Pi', 'Logan', 'Loki', 'Looper', 'Lost', 'Love Actually', 'Love, Simon', 'Lupin', 'Mad Max: Fury Road',
      'Maleficent', 'Mamma Mia', 'Mean Girls', 'Memento', 'Men in Black', 'Midsommar', 'Million Dollar Baby', 'Mindhunter', 'Minority Report', 'Miracle',
      'Miracle on 34th Street', 'Misery', 'Mission Impossible', 'Moana', 'Money Heist', 'Moneyball', 'Monsters, Inc.', 'Moonlight', 'Moulin Rouge', 'Mr. Robot',
      'Murder on the Orient Express', 'My Cousin Vinny', 'My Hero Academia', 'My Neighbor Totoro', 'Napoleon Dynamite', 'Narcos', 'Naruto', 'National Treasure', 'Night of the Living Dead', 'Nightcrawler',
      'No Country for Old Men', 'Nope', 'Now You See Me', "Ocean's Eleven", 'Oldboy', 'Once Upon a Time in the West', 'One Piece', 'Only Murders in the Building', 'Oppenheimer', 'Orange Is the New Black',
      'Ozark', 'Pacific Rim', 'Palm Springs', "Pan's Labyrinth", 'Panic Room', 'Paranormal Activity', 'Parasite', 'Parks and Recreation', 'Peaky Blinders', 'Pearl Harbor',
      'Percy Jackson', 'Philadelphia', 'Pirates of the Caribbean', 'Platoon', 'Point Break', 'Pokemon', 'Poltergeist', 'Predator', 'Pretty Woman', 'Pride and Prejudice',
      'Princess Mononoke', 'Prison Break', 'Prisoners', 'Prometheus', 'Pulp Fiction', 'Rambo', 'Ratatouille', 'Ready Player One', 'Rear Window', 'REC',
      'Remember the Titans', 'Requiem for a Dream', 'Reservoir Dogs', 'Resident Evil', 'Riverdale', 'RoboCop', 'Rocky', 'Rush Hour', 'Salt', 'San Andreas',
      'Saving Private Ryan', 'Scarface', "Schindler's List", 'Scream', 'Se7en', 'Searching', 'Severance', 'Sex Education', 'Shaun of the Dead', 'Sherlock Holmes',
      'Shogun', 'Shrek', 'Shutter Island', 'Signs', 'Silo', 'Sinister', 'Skyfall', 'Snowpiercer', 'Source Code', 'Space Jam',
      'Spartacus', 'Speed', 'Spider-Man', 'Spirited Away', 'Split', 'Star Trek', 'Star Wars', 'Starship Troopers', 'Step Brothers', 'Straight Outta Compton',
      'Stranger Things', 'Suits', 'Superbad', 'Superman', 'Taken', 'Ted Lasso', 'Tenet', 'Terminator', 'The Americans', 'The Avengers',
      'The Babadook', 'The Batman', 'The Blair Witch Project', 'The Blind Side', 'The Book of Eli', 'The Bourne Identity', 'The Boys', 'The Breakfast Club', 'The Cabin in the Woods', 'The Chronicles of Narnia',
      'The Conjuring', 'The Dark Knight', 'The Day After Tomorrow', 'The Departed', 'The Edge of Seventeen', 'The Exorcist', 'The Expanse', 'The Fifth Element', 'The Fly', 'The Girl on the Train',
      'The Godfather', 'The Good, the Bad and the Ugly', 'The Goonies', 'The Great Escape', 'The Greatest Showman', 'The Green Mile', 'The Grey', "The Handmaid's Tale", 'The Hangover', 'The Haunting of Hill House',
      'The Hobbit', 'The Holdovers', 'The Hunger Games', 'The Impossible', 'The Incredibles', 'The Italian Job', 'The Jungle Book', 'The Last of Us', 'The Last Samurai', 'The Lincoln Lawyer',
      'The Lion King', 'The Lord of the Rings', 'The Magnificent Seven', 'The Mandalorian', 'The Martian', 'The Matrix', 'The Maze Runner', 'The Meg', 'The Mummy', 'The Nightmare Before Christmas',
      'The Notebook', 'The Office', 'The Other Guys', 'The Pacific', 'The Perfect Storm', 'The Perks of Being a Wallflower', 'The Polar Express', 'The Princess Bride', 'The Revenant', 'The Ring',
      'The Road', 'The Sandlot', 'The Santa Clause', 'The Shawshank Redemption', 'The Shining', 'The Silence of the Lambs', 'The Sixth Sense', 'The Social Network', 'The Sopranos', 'The Sound of Music',
      'The Sting', 'The Substance', 'The Summer I Turned Pretty', 'The Texas Chainsaw Massacre', 'The Theory of Everything', 'The Thing', 'The Town', 'The Usual Suspects', 'The Visit', 'The Walking Dead',
      'The Wire', 'The Witcher', 'The Wizard of Oz', 'The Wolf of Wall Street', 'The X-Files', 'Titanic', "To All the Boys I've Loved Before", 'Tombstone', 'Top Gun', 'Total Recall',
      'Toy Story', 'Train to Busan', 'Training Day', 'Transformers', 'Tremors', 'Tron', 'Tropic Thunder', 'Troy', 'True Detective', 'True Grit',
      'True Lies', 'Twilight', 'Twister', 'Unforgiven', 'Unfriended', 'Up', 'Us', 'V for Vendetta', 'Vikings', 'Walk the Line',
      'WALL-E', 'War of the Worlds', 'Warm Bodies', 'Waterworld', 'West Side Story', 'Wicked', 'Willow', 'Wonder Woman', 'World War Z', 'X',
      'X-Men: Days of Future Past', 'Yellowjackets', 'Yellowstone', 'You', 'Zodiac', 'Zombieland', 'Zootopia'],
    'Objects': [
      'Backpack', 'Bag', 'Basket', 'Battery', 'Bed', 'Belt', 'Binoculars', 'Blanket', 'Book', 'Bookshelf',
      'Bottle', 'Bowl', 'Box', 'Bracelet', 'Broom', 'Bucket', 'Calculator', 'Camera', 'Candle', 'Chain',
      'Chair', 'Charger', 'Clock', 'Comb', 'Compass', 'Computer', 'Couch', 'Cup', 'Curtain', 'Desk',
      'Door', 'Envelope', 'Eraser', 'Fan', 'Flashlight', 'Fork', 'Globe', 'Gloves', 'Guitar', 'Hammer',
      'Hat', 'Headphones', 'Jar', 'Key', 'Keyboard', 'Knife', 'Ladder', 'Lamp', 'Laptop', 'Lock',
      'Map', 'Microphone', 'Mirror', 'Mouse', 'Mug', 'Nail', 'Necklace', 'Newspaper', 'Notebook', 'Painting',
      'Passport', 'Pen', 'Pencil', 'Phone', 'Picture Frame', 'Pillow', 'Plate', 'Refrigerator', 'Remote Control', 'Ring',
      'Rope', 'Rug', 'Ruler', 'Scarf', 'Scissors', 'Screw', 'Screwdriver', 'Shoes', 'Soap', 'Socks',
      'Speaker', 'Sponge', 'Spoon', 'Stamp', 'Stove', 'Suitcase', 'Sunglasses', 'Table', 'Telescope', 'Television',
      'Toaster', 'Toothbrush', 'Towel', 'Umbrella', 'Vacuum', 'Vase', 'Wallet', 'Watch', 'Window', 'Wrench'],
  };

  // Jester hints, for the word-only categories. A Word Mode jester is handed the
  // round word's category and nothing else, which leaves them guessing at a pool
  // of two hundred — so with Jester Hints on, one of the round word's three is
  // drawn at random and printed on their card. One hint per round, not one per
  // jester: two jesters comparing notes would otherwise hold the whole answer.
  //
  // Keyed by category first, then by word. Six words live in both Food and
  // Animals — Chicken, Crab, Duck, Lobster, Shrimp, Turkey — and a flat map
  // would hand an Animals round the food's hints, telling a jester the chicken
  // was 'Roasted' for 'Dinner'.
  //
  // Food only for now. A word with no hints deals no hint, which is what every
  // other category and every custom one does today.
  var wordHintCatalog = {
    'Food': {
      'Almonds': ['Crunchy', 'Small', 'Snack'],
      'Apple': ['Crunchy', 'Raw', 'Snack'],
      'Apple Pie': ['Sweet', 'Baked', 'Dessert'],
      'Avocado': ['Creamy', 'Green', 'Brunch'],
      'Bacon': ['Crispy', 'Salty', 'Breakfast'],
      'Bagel': ['Chewy', 'Round', 'Breakfast'],
      'Baguette': ['Crisp', 'Long', 'Side'],
      'Baked Potato': ['Baked', 'Fluffy', 'Side'],
      'Banana': ['Soft', 'Yellow', 'Snack'],
      'Banana Bread': ['Moist', 'Baked', 'Snack'],
      'Banh Mi': ['Crisp', 'Tangy', 'Lunch'],
      'Beef': ['Savory', 'Grilled', 'Dinner'],
      'Beef Stew': ['Hearty', 'Saucy', 'Comfort'],
      'Biryani': ['Spiced', 'Rice', 'Dinner'],
      'Biscuit': ['Flaky', 'Baked', 'Breakfast'],
      'BLT': ['Layered', 'Toasted', 'Lunch'],
      'Blueberries': ['Small', 'Sweet', 'Snack'],
      'Boba Milk Tea': ['Cold', 'Sweet', 'Drink'],
      'Bread': ['Soft', 'Baked', 'Simple'],
      'Broccoli': ['Green', 'Steamed', 'Side'],
      'Brownie': ['Fudgy', 'Baked', 'Dessert'],
      'Burger': ['Grilled', 'Stacked', 'Lunch'],
      'Burrito': ['Wrapped', 'Heavy', 'Lunch'],
      'Calzone': ['Cheesy', 'Baked', 'Dinner'],
      'Cantaloupe': ['Juicy', 'Soft', 'Snack'],
      'Carbonara': ['Creamy', 'Savory', 'Dinner'],
      'Carrot Cake': ['Moist', 'Spiced', 'Dessert'],
      'Carrots': ['Crunchy', 'Raw', 'Side'],
      'Cereal': ['Crunchy', 'Cold', 'Breakfast'],
      'Chai': ['Warm', 'Spiced', 'Drink'],
      'Cheese': ['Creamy', 'Sliced', 'Snack'],
      'Cheesecake': ['Creamy', 'Baked', 'Dessert'],
      'Cherries': ['Juicy', 'Small', 'Snack'],
      'Chicken': ['Savory', 'Roasted', 'Dinner'],
      'Chicken Noodle Soup': ['Warm', 'Noodle', 'Comfort'],
      'Chicken Nuggets': ['Fried', 'Bite-sized', 'Snack'],
      'Chicken Tikka Masala': ['Spiced', 'Saucy', 'Dinner'],
      'Chicken Wings': ['Fried', 'Saucy', 'Party'],
      'Chili': ['Hearty', 'Spiced', 'Comfort'],
      'Chocolate': ['Sweet', 'Melty', 'Snack'],
      'Chocolate Cake': ['Moist', 'Layered', 'Dessert'],
      'Chow Mein': ['Savory', 'Noodle', 'Dinner'],
      'Churros': ['Fried', 'Sweet', 'Dessert'],
      'Cinnamon Roll': ['Sweet', 'Sticky', 'Breakfast'],
      'Clam Chowder': ['Creamy', 'Warm', 'Comfort'],
      'Coconut': ['Chewy', 'Tropical', 'Snack'],
      'Coffee': ['Hot', 'Bitter', 'Morning'],
      'Coleslaw': ['Crunchy', 'Cold', 'Side'],
      'Cookies': ['Chewy', 'Baked', 'Snack'],
      'Corn Dog': ['Fried', 'Skewered', 'Party'],
      'Corn on the Cob': ['Grilled', 'Buttery', 'Side'],
      'Cotton Candy': ['Sweet', 'Light', 'Party'],
      'Crab': ['Rich', 'Boiled', 'Dinner'],
      'Crackers': ['Crunchy', 'Simple', 'Snack'],
      'Crème Brûlée': ['Creamy', 'Rich', 'Dessert'],
      'Crepes': ['Soft', 'Sweet', 'Brunch'],
      'Croissant': ['Flaky', 'Baked', 'Breakfast'],
      'Cucumber': ['Fresh', 'Cold', 'Side'],
      'Cupcake': ['Sweet', 'Frosted', 'Dessert'],
      'Curry': ['Spiced', 'Saucy', 'Dinner'],
      'Dim Sum': ['Steamed', 'Bite-sized', 'Brunch'],
      'Donut': ['Sweet', 'Fried', 'Breakfast'],
      'Duck': ['Rich', 'Roasted', 'Dinner'],
      'Dumplings': ['Steamed', 'Filled', 'Snack'],
      'Egg Rolls': ['Crispy', 'Wrapped', 'Snack'],
      'Elote': ['Grilled', 'Cheesy', 'Side'],
      'Enchiladas': ['Saucy', 'Baked', 'Dinner'],
      'Espresso': ['Hot', 'Bitter', 'Drink'],
      'Fajitas': ['Sizzling', 'Savory', 'Dinner'],
      'Falafel': ['Fried', 'Crispy', 'Lunch'],
      'Fettuccine Alfredo': ['Creamy', 'Saucy', 'Dinner'],
      'Fish and Chips': ['Crispy', 'Fried', 'Dinner'],
      'Flan': ['Creamy', 'Sweet', 'Dessert'],
      'French Fries': ['Crispy', 'Salty', 'Side'],
      'French Toast': ['Sweet', 'Fried', 'Breakfast'],
      'Fried Chicken': ['Crispy', 'Fried', 'Dinner'],
      'Fried Rice': ['Savory', 'Fried', 'Dinner'],
      'Garlic Bread': ['Warm', 'Baked', 'Side'],
      'Gnocchi': ['Soft', 'Boiled', 'Dinner'],
      'Granola': ['Crunchy', 'Sweet', 'Breakfast'],
      'Grapes': ['Juicy', 'Sweet', 'Snack'],
      'Green Beans': ['Fresh', 'Green', 'Side'],
      'Grilled Cheese': ['Melty', 'Grilled', 'Lunch'],
      'Guacamole': ['Creamy', 'Green', 'Snack'],
      'Gyro': ['Wrapped', 'Saucy', 'Lunch'],
      'Hash Browns': ['Crispy', 'Fried', 'Breakfast'],
      'Honey': ['Sweet', 'Sticky', 'Sweetener'],
      'Hot Chocolate': ['Warm', 'Sweet', 'Drink'],
      'Hot Dog': ['Grilled', 'Saucy', 'Lunch'],
      'Hot Pot': ['Warm', 'Savory', 'Dinner'],
      'Hummus': ['Creamy', 'Savory', 'Snack'],
      'Ice Cream': ['Cold', 'Sweet', 'Dessert'],
      'Iced Tea': ['Cold', 'Simple', 'Drink'],
      'Jam': ['Sweet', 'Sticky', 'Spread'],
      'Jello': ['Wobbly', 'Cold', 'Dessert'],
      'Kebab': ['Grilled', 'Skewered', 'Dinner'],
      'Key Lime Pie': ['Tart', 'Creamy', 'Dessert'],
      'Kimchi': ['Tangy', 'Spiced', 'Side'],
      'Kiwi': ['Tart', 'Green', 'Snack'],
      'Lamb': ['Rich', 'Roasted', 'Dinner'],
      'Lasagna': ['Layered', 'Baked', 'Dinner'],
      'Lemon': ['Tart', 'Raw', 'Simple'],
      'Lemonade': ['Cold', 'Tart', 'Drink'],
      'Lime': ['Tart', 'Green', 'Simple'],
      'Lobster': ['Rich', 'Boiled', 'Dinner'],
      'Lollipop': ['Sweet', 'Handheld', 'Snack'],
      'Macaron': ['Chewy', 'Bite-sized', 'Dessert'],
      'Macaroni and Cheese': ['Creamy', 'Baked', 'Comfort'],
      'Mango': ['Juicy', 'Sweet', 'Snack'],
      'Marshmallow': ['Soft', 'Sweet', 'Snack'],
      'Mashed Potatoes': ['Creamy', 'Whipped', 'Side'],
      'Matcha': ['Green', 'Warm', 'Drink'],
      'Meatballs': ['Savory', 'Saucy', 'Dinner'],
      'Meatloaf': ['Savory', 'Baked', 'Comfort'],
      'Milk': ['Cold', 'Simple', 'Drink'],
      'Milkshake': ['Cold', 'Sweet', 'Drink'],
      'Mochi': ['Chewy', 'Sweet', 'Dessert'],
      'Mozzarella Sticks': ['Melty', 'Fried', 'Party'],
      'Muffin': ['Sweet', 'Baked', 'Breakfast'],
      'Mushrooms': ['Savory', 'Soft', 'Side'],
      'Naan': ['Soft', 'Warm', 'Side'],
      'Nachos': ['Crunchy', 'Cheesy', 'Party'],
      'Oatmeal': ['Warm', 'Soft', 'Breakfast'],
      'Olives': ['Salty', 'Bite-sized', 'Snack'],
      'Omelette': ['Fluffy', 'Savory', 'Breakfast'],
      'Onigiri': ['Simple', 'Handheld', 'Snack'],
      'Onion': ['Sharp', 'Raw', 'Simple'],
      'Onion Rings': ['Crispy', 'Fried', 'Side'],
      'Orange': ['Juicy', 'Tart', 'Snack'],
      'Orange Chicken': ['Sweet', 'Fried', 'Dinner'],
      'Orange Juice': ['Cold', 'Tart', 'Drink'],
      'Pad Thai': ['Savory', 'Noodle', 'Dinner'],
      'Pancakes': ['Fluffy', 'Sweet', 'Breakfast'],
      'Panini': ['Grilled', 'Layered', 'Lunch'],
      'Pasta': ['Boiled', 'Saucy', 'Dinner'],
      'Peach': ['Juicy', 'Soft', 'Snack'],
      'Peanut Butter': ['Creamy', 'Sticky', 'Spread'],
      'Peanuts': ['Crunchy', 'Salty', 'Snack'],
      'Pear': ['Soft', 'Sweet', 'Snack'],
      'Pesto Pasta': ['Green', 'Savory', 'Dinner'],
      'Philly Cheesesteak': ['Cheesy', 'Savory', 'Lunch'],
      'Pho': ['Warm', 'Savory', 'Dinner'],
      'Pickles': ['Tangy', 'Cold', 'Side'],
      'Pineapple': ['Juicy', 'Tart', 'Snack'],
      'Pita': ['Soft', 'Simple', 'Side'],
      'Pizza': ['Cheesy', 'Baked', 'Party'],
      'Plum': ['Juicy', 'Soft', 'Snack'],
      'Poke': ['Cold', 'Fresh', 'Lunch'],
      'Pomegranate': ['Tart', 'Small', 'Snack'],
      'Popcorn': ['Crunchy', 'Salty', 'Snack'],
      'Popsicle': ['Cold', 'Sweet', 'Snack'],
      'Pork': ['Savory', 'Roasted', 'Dinner'],
      'Potato Chips': ['Crunchy', 'Salty', 'Snack'],
      'Potato Salad': ['Creamy', 'Cold', 'Side'],
      'Pretzel': ['Salty', 'Chewy', 'Snack'],
      'Pudding': ['Creamy', 'Soft', 'Dessert'],
      'Pumpkin Pie': ['Spiced', 'Baked', 'Dessert'],
      'Quesadilla': ['Cheesy', 'Grilled', 'Lunch'],
      'Ramen': ['Warm', 'Savory', 'Comfort'],
      'Raspberries': ['Tart', 'Small', 'Snack'],
      'Ravioli': ['Soft', 'Saucy', 'Dinner'],
      'Red Velvet Cake': ['Moist', 'Frosted', 'Dessert'],
      'Ribs': ['Saucy', 'Grilled', 'Dinner'],
      'Rice': ['Simple', 'Boiled', 'Side'],
      'Salad': ['Fresh', 'Cold', 'Lunch'],
      'Salmon': ['Savory', 'Grilled', 'Dinner'],
      'Salsa': ['Chunky', 'Tangy', 'Dip'],
      'Samosa': ['Crispy', 'Filled', 'Snack'],
      'Sandwich': ['Layered', 'Handheld', 'Lunch'],
      'Sausage': ['Savory', 'Grilled', 'Breakfast'],
      'Scone': ['Baked', 'Simple', 'Breakfast'],
      'Scrambled Eggs': ['Soft', 'Fluffy', 'Breakfast'],
      'Shawarma': ['Savory', 'Wrapped', 'Lunch'],
      "Shepherd's Pie": ['Hearty', 'Baked', 'Comfort'],
      'Shrimp': ['Savory', 'Bite-sized', 'Dinner'],
      'Sloppy Joe': ['Saucy', 'Handheld', 'Comfort'],
      'Smoothie': ['Cold', 'Sweet', 'Drink'],
      'Soda': ['Cold', 'Sweet', 'Drink'],
      'Soup': ['Warm', 'Savory', 'Comfort'],
      'Spaghetti': ['Long', 'Saucy', 'Dinner'],
      'Spring Rolls': ['Crisp', 'Wrapped', 'Snack'],
      'Strawberry': ['Juicy', 'Sweet', 'Snack'],
      'Sub Sandwich': ['Layered', 'Long', 'Lunch'],
      'Sushi': ['Cold', 'Savory', 'Bite-sized'],
      'Sweet Potato': ['Soft', 'Sweet', 'Side'],
      'Tacos': ['Handheld', 'Savory', 'Lunch'],
      'Tamales': ['Steamed', 'Filled', 'Comfort'],
      'Tea': ['Warm', 'Simple', 'Drink'],
      'Tiramisu': ['Sweet', 'Creamy', 'Dessert'],
      'Toast': ['Crispy', 'Simple', 'Breakfast'],
      'Tofu': ['Soft', 'Simple', 'Savory'],
      'Tomato': ['Juicy', 'Raw', 'Simple'],
      'Tomato Soup': ['Warm', 'Simple', 'Comfort'],
      'Tuna': ['Savory', 'Simple', 'Lunch'],
      'Turkey': ['Savory', 'Roasted', 'Dinner'],
      'Udon': ['Soft', 'Warm', 'Comfort'],
      'Veggie Burger': ['Grilled', 'Stacked', 'Lunch'],
      'Waffles': ['Sweet', 'Crispy', 'Breakfast'],
      'Watermelon': ['Juicy', 'Sweet', 'Snack'],
      'Wontons': ['Soft', 'Filled', 'Bite-sized'],
      'Xiao Long Bao': ['Steamed', 'Filled', 'Bite-sized'],
      'Yogurt': ['Creamy', 'Cold', 'Breakfast'],
    },
  };
  window.MASQ_WORDS = {
    'wordOnlyCatalog': wordOnlyCatalog,
    'wordHintCatalog': wordHintCatalog,
  };
})();
