// Masq word/role data: the role catalogs (Locations, Biomes, Movie/TV Genres,
// Music Genres), a matching fake-role catalog for each, and the word-only
// catalogs. Plain script, exposed on window.MASQ_LOCATIONS_DATA.
//
// Real catalogs come first, then the fake-role catalogs that shadow them, then
// anything parked. Within each catalog, keys and their role/word lists are
// sorted alphabetically.
(function () {
  var biomeCatalog = {
    'Alpine Mountains': ['Bighorn Sheep', 'Condor', 'Eagle', 'Ibex', 'Marmot', 'Mountain Goat', 'Snow Leopard', 'Yak'],
    'Antarctic Ice Sheet (Frozen Ocean)': ['Albatross', 'Antarctic Krill', 'Beluga Whale', 'Emperor Penguin', 'Leopard Seal', 'Orca', 'Seal', 'Snow Petrel'],
    'Arctic Tundra': ['Arctic Fox', 'Arctic Hare', 'Lemming', 'Musk Ox', 'Polar Bear', 'Reindeer', 'Snowy Owl', 'Walrus'],
    'Australian Outback': ['Dingo', 'Emu', 'Kangaroo', 'Koala', 'Platypus', 'Tasmanian Devil', 'Thorny Devil', 'Wombat'],
    'Beach': ['Hermit Crab', 'Mussel', 'Pelican', 'Sand Dollar', 'Sandpiper', 'Sea Lion', 'Seagull', 'Starfish'],
    'Cave System': ['Bat', 'Blind Fish', 'Cricket', 'Rat', 'Salamander', 'Silverfish', 'Spider', 'Troglodyte Beetle'],
    'Chaparral (Shrubland)': ['Bobcat', 'California Quail', 'Coyote', 'Gecko', 'Jackrabbit', 'Kangaroo Rat', 'Rattlesnake', 'Roadrunner'],
    'Coral Reef': ['Clownfish', 'Manta Ray', 'Moray Eel', 'Octopus', 'Parrotfish', 'Reef Shark', 'Sea Turtle', 'Seahorse'],
    'Deep Ocean': ['Anglerfish', 'Deep Sea Jellyfish', 'Dumbo Octopus', 'Fangtooth Fish', 'Giant Squid', 'Gulper Eel', 'Sperm Whale', 'Vampire Squid'],
    'Desert': ['Camel', 'Fennec Fox', 'Gila Monster', 'Meerkat', 'Rattlesnake', 'Sand Cat', 'Scorpion', 'Vulture'],
    'Freshwater River': ['Beaver', 'Catfish', 'Heron', 'Hippopotamus', 'Otter', 'Piranha', 'River Dolphin', 'Salmon'],
    'House': ['Cat', 'Dog', 'Goldfish', 'Rabbit', 'Rat', 'Snake', 'Spider', 'Turtle'],
    'Jurassic Park': ['Ankylosaurus', 'Brachiosaurus', 'Pterodactyl', 'Spinosaurus', 'Stegosaurus', 'Triceratops', 'Tyrannosaurus Rex', 'Velociraptor'],
    'Mangrove Forest': ['Bengal Tiger', 'Cuckoo', 'Fiddler Crab', 'Frog', 'Mudskipper', 'Proboscis Monkey', 'Saltwater Crocodile', 'Tarsier'],
    'Prairie': ['Antelope', 'Badger', 'Bison', 'Coyote', 'Ferret', 'Prairie Dog', 'Rattlesnake', 'Red-Tailed Hawk'],
    'Savanna': ['Cheetah', 'Elephant', 'Giraffe', 'Hyena', 'Lion', 'Rhino', 'Wildebeest', 'Zebra'],
    'Swamp': ['Alligator', 'Beaver', 'Bullfrog', 'Heron', 'River Otter', 'Snapping Turtle', 'Toad', 'Water Moccasin'],
    'Taiga (Boreal Forest)': ['Black Bear', 'Gray Owl', 'Gray Wolf', 'Lynx', 'Moose', 'Red Squirrel', 'Snowshoe Hare', 'Wolverine'],
    'Temperate Forest': ['Black Bear', 'Deer', 'Owl', 'Raccoon', 'Red Fox', 'Squirrel', 'Wild Boar', 'Woodpecker'],
    'Tropical Rainforest': ['Anaconda', 'Gorilla', 'Harpy Eagle', 'Howler Monkey', 'Jaguar', 'Poison Dart Frog', 'Sloth', 'Toucan'],
    'Urban Environment (City)': ['Cockroach', 'Opossum', 'Pigeon', 'Raccoon', 'Rat', 'Sparrow', 'Squirrel', 'Stray Cat'],
    'Volcanic Island': ['Fire Salamander', 'Galápagos Iguana', 'Hawaiian Hoary Bat', 'Lava Lizard', 'Peregrine Falcon', 'Vampire Ground Finch', 'Volcanic Mouse', 'Volcano Rabbit'],
  };

  var locationCatalog = {
    'Airplane': ['Air Marshal', 'Bartender', 'Crying Baby', 'Flight Attendant', 'Flight Engineer', 'Passenger', 'Pilot', 'Stowaway'],
    'Airport': ['Crew Member', 'Customs Officer', 'Gate Agent', 'Passenger', 'Pilot', 'Ramp Agent', 'Security Officer', 'Tourist'],
    'Bank': ['Account Holder', 'Armored Car Driver', 'Auditor', 'Branch Manager', 'Loan Officer', 'Robber', 'Security Guard', 'Teller'],
    'Beach': ['Ice Cream Vendor', 'Lifeguard', 'Photographer', 'Sandcastle Builder', 'Sunbather', 'Surfer', 'Tourist', 'Volleyball Player'],
    'Campground': ['Bear', 'Biker', 'Camper', 'Campfire Cook', 'Eagle Scout', 'Hiker', 'Park Ranger', 'Wildlife Photographer'],
    'Casino': ['Bartender', 'Bouncer', 'Cardsharp', 'Dealer', 'Drunkard', 'Gambler', 'Head of Security', 'Pit Boss'],
    'Circus Tent': ['Acrobat', 'Animal Tamer', 'Circus-Goer', 'Clown', 'Juggler', 'Knife Thrower', 'Magician', 'Ringmaster'],
    'Convenience Store': ['Alcoholic', 'Cashier', 'Delivery Driver', 'Food Roller Operator', 'Late Night Customer', 'Manager', 'Regular', 'Shoplifter'],
    'Corporate Party': ['Accountant', 'Administrative Assistant', 'CEO', 'Courier', 'Emcee', 'Intern', 'Manager', 'Party Crasher'],
    'Cruise Ship': ['Attendant', 'Bartender', 'Captain', 'Cook', 'Musician', 'Passenger', 'Radio Operator', 'Stowaway'],
    'Crusader Army': ['Archer', 'Bishop', 'Captive', 'Knight', 'Monk', 'Saracen', 'Servant', 'Squire'],
    'Day Spa': ['Beautician', 'Customer', 'Dermatologist', 'Makeup Specialist', 'Masseur', 'Nail Specialist', 'Receptionist', 'Stylist'],
    'Elementary School': ['Janitor', 'Librarian', 'Lunch Lady', 'Nurse', 'Principal', 'Student', 'Substitute Teacher', 'Teacher'],
    'Embassy': ['Ambassador', 'Bureaucrat', 'Diplomat', 'Interpreter', 'Refugee', 'Secretary', 'Security Guard', 'Tourist'],
    'Fast Food Restaurant': ['Cashier', 'Customer', 'Delivery Driver', 'Disgruntled Teenager Working Their First Job', 'Drive-Thru Worker', 'Fry Cook', 'Health Inspector', 'Manager'],
    'Fire Station': ['Arson Investigator', 'Captain', 'Dispatcher', 'Firefighter', 'Paramedic', 'Rescue Dog', 'Rookie', 'Station Cook'],
    'Gym': ['Athlete', 'Front Desk Worker', "New Year's Resolution Member", 'Personal Trainer', 'Runner', 'Swimmer', 'Weightlifter', 'Yoga Instructor'],
    'Hospital': ['EMT', 'Janitor', 'Nurse', 'Paramedic', 'Patient', 'Receptionist', 'Surgeon', 'Therapist'],
    'Hotel': ['Bellhop', 'Concierge', 'Front Desk Clerk', 'Guest', 'Housekeeper', 'Manager', 'Room Service Worker', 'Valet Parking Attendant'],
    'Military Base': ['Colonel', 'Deserter', 'Drill Instructor', 'Drone Operator', 'Medic', 'Non-Commissioned Officer', 'Private', 'Sentry'],
    'Movie Studio': ['Actor', 'Cameraman', 'Costume Designer', 'Director', 'Extra', 'Producer', 'Sound Engineer', 'Stuntman'],
    'Movie Theater': ['Concession Worker', 'Couple', 'Film Critic', 'Manager', 'Projectionist', 'Teenager', 'Ticket Seller', 'Usher'],
    'Night Club': ['Bartender', 'Bottle Service Waitress', 'Bouncer', 'Dancer', 'DJ', 'Model', 'Pick-Up Artist', 'Regular'],
    'Pirate Ship': ['Cabin Boy', 'Cook', 'First Mate', 'Gunner', 'Parrot', 'Seaman', 'Shackled Prisoner', 'Swashbuckling Captain'],
    'Polar Station': ['Biologist', 'Expedition Leader', 'Geoscientist', 'Hydrologist', 'Medic', 'Meteorologist', 'Photographer', 'Radio Operator'],
    'Police Station': ['Attorney', 'Cop', 'Detective', 'Forensic Scientist', 'Journalist', 'Lieutenant', 'Patrol Officer', 'Suspect'],
    'Restaurant': ['Annoying Karen', 'Dishwasher', 'Food Critic', 'Head Chef', 'Host', 'Manager', 'Sommelier', 'Waiter'],
    'Service Station': ['Biker', 'Car Washer', 'Driver', 'Electrical Technician', 'Manager', 'Service Receptionist', 'Tire Technician', 'Tow Truck Driver'],
    'Space Station': ['Aerospace Engineer', 'Alien', 'Astronaut', 'Doctor', 'Mission Commander', 'Pilot', 'Research Engineer', 'Wealthy Tourist'],
    'Sports Stadium': ['Coach', 'Commentator', 'Concession Worker', 'Mascot', 'Player', 'Referee', 'Security Guard', 'Superfan'],
    'Submarine': ['Commander', 'Cook', 'Electrical Officer', 'Navigator', 'New Recruit', 'Radio Operator', 'Sailor', 'Sonar Operator'],
    'Supermarket': ['Butcher', 'Cart Wrangler', 'Cashier', 'Custodian', 'Delivery Man', 'Manager', 'Shopper', 'Stock Worker'],
    'Theatre': ['Actor', 'Audience Member', 'Coatroom Attendant', 'Director', 'Prompter', 'Stage Hand', 'Understudy', 'Usher'],
    'Theme Park / Amusement Park': ['Character Performer', 'Clown', 'Food Vendor', 'Kid', 'Merchandise Vendor', 'Parent', 'Ride Operator', 'Visitor'],
    'Train': ['Backpacker', 'Conductor', 'Dining Car Cook', 'Passenger', 'Passenger Car Attendant', 'Stoker', 'Ticket Taker', 'Vendor'],
    'University': ['Campus Security', 'Dean', 'Frat Member', 'Freshman', 'Graduate Student', 'Professor', 'Resident Advisor', 'Tour Guide'],
    'Zoo': ['Caretaker', 'General Manager', 'Guide', 'Janitor', 'Vendor', 'Veterinarian', 'Visitor', 'Zookeeper'],
  };

  var movieTvCatalog = {
    'Action': ['24', 'Bad Boys', 'Die Hard', 'Fast and Furious', 'Jack Ryan', 'John Wick', 'Lethal Weapon', 'Mad Max', 'Mission Impossible', 'Speed', 'Terminator', 'The Bourne Identity'],
    'Adventure': ['Indiana Jones', 'Into the Wild', 'Jumanji', 'Jurassic Park', 'Life of Pi', 'Lost', 'National Treasure', 'Pirates of the Caribbean', 'The Goonies', 'The Jungle Book', 'The Mandalorian', 'The Mummy'],
    'Alien Invasion': ['A Quiet Place', 'Arrival', 'Battle: Los Angeles', 'District 9', 'Edge of Tomorrow', 'Falling Skies', 'Independence Day', 'Signs', 'Skyline', 'The Day the Earth Stood Still', 'The X-Files', 'War of the Worlds'],
    'Animated': ['Arcane', 'Avatar: The Last Airbender', 'Coco', 'Despicable Me', 'Finding Nemo', 'Frozen', 'Moana', 'Ninjago', 'Shrek', 'The Lion King', 'Toy Story', 'Up'],
    'Anime': ['Attack on Titan', 'Cowboy Bebop', 'Death Note', 'Demon Slayer', 'Dragon Ball Z', 'Fullmetal Alchemist: Brotherhood', 'My Hero Academia', 'My Neighbor Totoro', 'Naruto', 'One Piece', 'Princess Mononoke', 'Spirited Away'],
    'Biopic': ['A Beautiful Mind', 'Bohemian Rhapsody', 'Elvis', 'Oppenheimer', 'Ray', 'Rocketman', 'Straight Outta Compton', 'The Crown', 'The Social Network', 'The Theory of Everything', 'The Wolf of Wall Street', 'Walk the Line'],
    'Body Horror': ['Alien', 'An American Werewolf in London', 'Hannibal', 'Slither', 'Society', 'The Fly', 'The Substance', 'The Thing', 'Titane', 'Tusk', 'Videodrome'],
    'Christmas': ['A Christmas Carol', 'A Christmas Story', 'Elf', 'How the Grinch Stole Christmas', "It's a Wonderful Life", 'Jingle All the Way', 'Miracle on 34th Street', 'The Nightmare Before Christmas', 'The Polar Express', 'The Santa Clause'],
    'Comedy': ['Anchorman', 'Bridesmaids', 'Dumb and Dumber', 'Friends', 'Ghostbusters', 'Home Alone', 'Mean Girls', 'Step Brothers', 'Superbad', 'The Hangover', 'The Office', 'Tropic Thunder'],
    'Cop': ['21 Bridges', '21 Jump Street', 'Beverly Hills Cop', 'Brooklyn Nine-Nine', 'Hot Fuzz', 'Men in Black', 'Ride Along', 'Rush Hour', 'The Heat', 'The Other Guys', 'Training Day', 'White Collar'],
    'Courtroom Drama': ['12 Angry Men', 'A Few Good Men', 'A Time to Kill', 'Erin Brockovich', 'Law & Order', 'Legally Blonde', 'Marshall', 'My Cousin Vinny', 'Philadelphia', 'Suits', 'The Lincoln Lawyer', 'The Verdict'],
    'Crime': ['American Gangster', 'Breaking Bad', 'Casino', 'Goodfellas', 'Heat', 'Ozark', 'Peaky Blinders', 'Pulp Fiction', 'Scarface', 'The Departed', 'The Godfather', 'The Wire'],
    'Cyberpunk': ['Alita: Battle Angel', 'Altered Carbon', 'Blade Runner', 'Elysium', 'Ex Machina', 'Ghost in the Shell', 'Mr. Robot', 'Ready Player One', 'RoboCop', 'The Matrix', 'Total Recall', 'Tron'],
    'Disaster': ['2012', 'Armageddon', 'Contagion', "Dante's Peak", 'Deep Impact', 'Geostorm', 'San Andreas', 'The Day After Tomorrow', 'The Perfect Storm', 'Twister'],
    'Docudrama': ['127 Hours', 'Apollo 13', 'Argo', 'Band of Brothers', 'Captain Phillips', 'Chernobyl', "Schindler's List", 'Spotlight', 'Sully', 'The Big Short', 'United 93', 'Zero Dark Thirty'],
    'Dystopian': ['Black Mirror', 'Brazil', 'Children of Men', 'Divergent', 'Minority Report', 'Severance', 'Snowpiercer', 'The Giver', "The Handmaid's Tale", 'The Hunger Games', 'The Maze Runner', 'V for Vendetta'],
    'Fantasy': ['Aladdin', 'Beauty and the Beast', 'Game of Thrones', 'Harry Potter', 'Maleficent', 'Stardust', 'The Chronicles of Narnia', 'The Hobbit', 'The Lord of the Rings', 'The Princess Bride', 'The Witcher', 'The Wizard of Oz'],
    'Found Footage': ['As Above So Below', 'Chronicle', 'Cloverfield', 'Host', 'Paranormal Activity', 'Project X', 'REC', 'Searching', 'The Blair Witch Project', 'The Visit', 'Unfriended', 'V/H/S'],
    'Heist': ['Baby Driver', 'Catch Me If You Can', 'Den of Thieves', 'Inside Man', 'Logan Lucky', 'Lupin', 'Money Heist', 'Now You See Me', "Ocean's Eleven", 'Point Break', 'The Italian Job', 'The Town'],
    'Historical Epic': ['300', 'Ben-Hur', 'Braveheart', 'Gladiator', 'Kingdom of Heaven', 'Lawrence of Arabia', 'Rome', 'Shogun', 'Spartacus', 'The Last Samurai', 'Troy', 'Vikings'],
    'Horror': ['A Nightmare on Elm Street', 'American Horror Story', 'Get Out', 'Halloween', 'Hereditary', 'Insidious', 'It', 'Scream', 'The Conjuring', 'The Exorcist', 'The Haunting of Hill House', 'The Shining'],
    'Monster': ['Anaconda', 'Cocaine Bear', 'Godzilla', 'Godzilla Minus One', 'Jurassic World', 'King Kong', 'Kong: Skull Island', 'Pacific Rim', 'Stranger Things', 'The Host', 'The Meg', 'Tremors'],
    'Musical': ['Chicago', 'Glee', 'Grease', 'Hairspray', 'La La Land', 'Les Miserables', 'Mamma Mia', 'Moulin Rouge', 'The Greatest Showman', 'The Sound of Music', 'West Side Story', 'Wicked'],
    'Mystery / Whodunit': ['And Then There Were None', 'Chinatown', 'Clue', 'Death on the Nile', 'Glass Onion', 'Knives Out', 'Murder on the Orient Express', 'Only Murders in the Building', 'Rear Window', 'Sherlock Holmes', 'The Usual Suspects', 'True Detective'],
    'Post-Apocalyptic': ['28 Days Later', 'Bird Box', 'Fallout', 'I Am Legend', 'Mad Max: Fury Road', 'Silo', 'The Book of Eli', 'The Last of Us', 'The Road', 'The Walking Dead', 'WALL-E', 'Waterworld'],
    'Prison': ['American History X', 'Con Air', 'Cool Hand Luke', 'Escape from Alcatraz', 'Holes', 'Orange Is the New Black', 'Papillon', 'Prison Break', 'The Great Escape', 'The Green Mile', 'The Longest Yard', 'The Shawshank Redemption'],
    'Psychological Thriller': ['Black Swan', 'Fight Club', 'Gone Girl', 'Mindhunter', 'Oldboy', 'Prisoners', 'Shutter Island', 'Split', 'The Machinist', 'The Others', 'The Sixth Sense', 'You'],
    'Romance': ['(500) Days of Summer', 'Bridgerton', 'Crazy Rich Asians', 'Love Actually', 'Outlander', 'Pretty Woman', 'Pride and Prejudice', 'Sex Education', 'The Notebook', 'The Summer I Turned Pretty', 'Titanic', 'Twilight'],
    'Sci-Fi / Space Opera': ['Avatar', 'Back to the Future', 'Doctor Who', 'Dune', 'E.T.', 'Guardians of the Galaxy', 'Inception', 'Interstellar', 'Star Trek', 'Star Wars', 'The Expanse', 'The Fifth Element'],
    'Slasher': ['Black Christmas', 'Candyman', "Child's Play", 'Friday the 13th', 'Happy Death Day', 'I Know What You Did Last Summer', 'Pearl', 'Terrifier', 'The Cabin in the Woods', 'The Texas Chainsaw Massacre', 'Us', 'X'],
    'Sports': ['Coach Carter', 'Creed', 'Friday Night Lights', 'Million Dollar Baby', 'Miracle', 'Moneyball', 'Remember the Titans', 'Rocky', 'Space Jam', 'Ted Lasso', 'The Blind Side', 'The Sandlot'],
    'Spy': ['Atomic Blonde', 'Austin Powers', 'Bridge of Spies', 'Casino Royale', 'Killing Eve', 'Kingsman', 'Red Sparrow', 'Salt', 'Skyfall', 'The Americans', 'Tinker Tailor Soldier Spy', 'True Lies'],
    'Superhero': ['Black Panther', 'Daredevil', 'Deadpool', 'Invincible', 'Iron Man', 'Spider-Man', 'Superman', 'The Avengers', 'The Boys', 'The Dark Knight', 'The Incredibles', 'Wonder Woman'],
    'Survival': ['All Is Lost', 'Cast Away', 'Everest', 'Gravity', 'Society of the Snow', 'The Grey', 'The Impossible', 'The Martian', 'The Revenant', 'The Terror', 'Wild', 'Yellowjackets'],
    'Teen Drama': ['10 Things I Hate About You', 'Booksmart', 'Clueless', 'Easy A', 'Euphoria', 'Lady Bird', 'Love, Simon', 'Riverdale', 'The Breakfast Club', 'The Edge of Seventeen', 'The Perks of Being a Wallflower', "To All the Boys I've Loved Before"],
    'Thriller': ['A Simple Favor', 'Big Little Lies', 'Gone Baby Gone', 'Jaws', 'Nightcrawler', 'Parasite', 'Se7en', 'The Girl on the Train', 'The Night Of', 'The Silence of the Lambs', 'Wind River', 'Zodiac'],
    'Time Travel': ['12 Monkeys', 'About Time', "Bill & Ted's Excellent Adventure", 'Dark', 'Frequency', 'Groundhog Day', 'Loki', 'Looper', 'Palm Springs', 'Source Code', 'Tenet', 'X-Men: Days of Future Past'],
    'War': ['1917', 'American Sniper', 'Apocalypse Now', 'Black Hawk Down', 'Dunkirk', 'Full Metal Jacket', 'Generation Kill', 'Hacksaw Ridge', 'Pearl Harbor', 'Platoon', 'Saving Private Ryan', 'The Pacific'],
    'Western': ['3:10 to Yuma', 'Butch Cassidy and the Sundance Kid', 'Deadwood', 'Django Unchained', 'No Country for Old Men', 'Once Upon a Time in the West', 'The Good, the Bad and the Ugly', 'The Magnificent Seven', 'Tombstone', 'True Grit', 'Unforgiven', 'Yellowstone'],
    'Zombie': ['28 Weeks Later', 'All of Us Are Dead', 'Army of the Dead', 'Dawn of the Dead', 'Kingdom', 'Night of the Living Dead', 'Resident Evil', 'Shaun of the Dead', 'Train to Busan', 'Warm Bodies', 'World War Z', 'Zombieland'],
  };

  var musicGenreCatalog = {
    'Alternative Rock': ['Coldplay (Yellow)', 'Gorillaz (Feel Good Inc)', 'Linkin Park (In the End)', 'Muse (Uprising)', 'Oasis (Wonderwall)', 'Radiohead (Creep)', 'Red Hot Chili Peppers (Californication)', 'Smashing Pumpkins (1979)', 'Third Eye Blind (Semi-Charmed Life)', "Weezer (Say It Ain't So)"],
    'Bedroom Pop': ['beabadoobee (the perfect pair)', 'Cigarettes After Sex (Apocalypse)', 'Clairo (Sofia)', 'Faye Webster (Kingston)', 'girl in red (we fell in love in october)', 'Mac DeMarco (Chamber of Reflection)', 'Malcolm Todd (Earrings)', 'Rex Orange County (Best Friend)', 'Steve Lacy (Dark Red)', 'The Marias (No One Noticed)'],
    'Blues': ['Albert King (Born Under a Bad Sign)', 'B.B. King (The Thrill Is Gone)', "Buddy Guy (Damn Right, I've Got the Blues)", 'Eric Clapton (Layla)', 'Etta James (At Last)', "Howlin' Wolf (Smokestack Lightning)", 'John Lee Hooker (Boom Boom)', 'Muddy Waters (Hoochie Coochie Man)', 'Robert Johnson (Cross Road Blues)', 'Stevie Ray Vaughan (Pride and Joy)'],
    'Classical': ['Bach (Air on the G String)', 'Beethoven (Fur Elise)', 'Brahms (Lullaby)', 'Chopin (Nocturne in E-flat Major)', 'Debussy (Clair de Lune)', 'Erik Satie (Gymnopedie No. 1)', 'Grieg (In the Hall of the Mountain King)', 'Mozart (Eine kleine Nachtmusik)', 'Tchaikovsky (Swan Lake)', 'Vivaldi (The Four Seasons)'],
    'Country': ["Blake Shelton (God's Country)", 'Carrie Underwood (Before He Cheats)', 'Chris Stapleton (Tennessee Whiskey)', 'Dolly Parton (Jolene)', 'Johnny Cash (Hurt)', 'Kenny Chesney (No Shoes, No Shirt, No Problems)', 'Luke Combs (When It Rains It Pours)', 'Miranda Lambert (The House That Built Me)', 'Morgan Wallen (Last Night)', 'Zach Bryan (Something in the Orange)'],
    'Disco': ['ABBA (Dancing Queen)', "Bee Gees (Stayin' Alive)", 'Boney M. (Rasputin)', 'Chic (Le Freak)', 'Donna Summer (Hot Stuff)', 'Earth Wind & Fire (September)', 'Gloria Gaynor (I Will Survive)', 'KC and the Sunshine Band (Get Down Tonight)', 'Sister Sledge (We Are Family)', 'The Village People (Y.M.C.A.)'],
    'EDM': ['Avicii (Wake Me Up)', 'Calvin Harris (One Kiss)', "David Guetta (I'm Good)", 'Diplo (Lean On)', "Kygo (It Ain't Me)", 'Marshmello (Happier)', 'Martin Garrix (In the Name of Love)', 'Skrillex (Where Are U Now)', 'The Chainsmokers (Closer)', 'Zedd (The Middle)'],
    'Emo / Pop Punk': ['All Time Low (Dear Maria, Count Me In)', 'Dashboard Confessional (Hands Down)', 'Fall Out Boy (Centuries)', 'Jimmy Eat World (The Middle)', 'My Chemical Romance (Teenagers)', 'Panic! At The Disco (High Hopes)', 'Paramore (Still into You)', "Simple Plan (I'm Just a Kid)", 'Sum 41 (In Too Deep)', 'Taking Back Sunday (MakeDamnSure)'],
    'Folk': ["Bob Dylan (Blowin' in the Wind)", 'Cat Stevens (Wild World)', 'Fleet Foxes (White Winter Hymnal)', 'James Taylor (Fire and Rain)', 'Joan Baez (Diamonds & Rust)', 'Joni Mitchell (Big Yellow Taxi)', 'Neil Young (Heart of Gold)', 'Simon and Garfunkel (The Sound of Silence)', 'Sufjan Stevens (Mystery of Love)', 'Woody Guthrie (This Land Is Your Land)'],
    'Gospel': ['CeCe Winans (Alabaster Box)', 'Donnie McClurkin (We Fall Down)', 'Fred Hammond (No Weapon)', 'Kirk Franklin (Stomp)', 'Mahalia Jackson (Take My Hand, Precious Lord)', 'Marvin Sapp (Never Would Have Made It)', 'Tamela Mann (Take Me to the King)', 'Tasha Cobbs (Break Every Chain)', 'The Clark Sisters (You Brought the Sunshine)', 'Yolanda Adams (Open My Heart)'],
    'Grunge': ['Alice in Chains (Man in the Box)', 'Bush (Glycerine)', 'Hole (Celebrity Skin)', "Mudhoney (Touch Me I'm Sick)", 'Nirvana (Smells Like Teen Spirit)', 'Pearl Jam (Even Flow)', 'Screaming Trees (Nearly Lost You)', 'Soundgarden (Black Hole Sun)', 'Stone Temple Pilots (Plush)', 'Temple of the Dog (Hunger Strike)'],
    'Heavy Metal': ['Black Sabbath (Paranoid)', 'Iron Maiden (The Trooper)', 'Judas Priest (Breaking the Law)', 'Megadeth (Symphony of Destruction)', 'Metallica (Enter Sandman)', 'Pantera (Walk)', 'Rammstein (Du Hast)', 'Slayer (Raining Blood)', 'Slipknot (Duality)', 'System Of A Down (Chop Suey!)'],
    'Hip Hop': ['Cardi B (I Like It)', 'Drake (One Dance)', 'Eminem (Without Me)', 'J. Cole (No Role Modelz)', 'Jay-Z (Empire State of Mind)', 'Kanye West (Heartless)', 'Kendrick Lamar (All The Stars)', 'Lil Wayne (Love Me)', 'Nicki Minaj (Starships)', 'Travis Scott (goosebumps)'],
    'Indie / Alternative': ['Arctic Monkeys (I Wanna Be Yours)', 'Cage The Elephant (Cigarette Daydreams)', 'Cigarettes After Sex (Apocalypse)', 'Florence + The Machine (Dog Days Are Over)', 'Glass Animals (Heat Waves)', 'Lana Del Rey (Summertime Sadness)', 'Mac DeMarco (Chamber of Reflection)', 'Tame Impala (The Less I Know The Better)', 'The 1975 (Somebody Else)', 'Vampire Weekend (A-Punk)'],
    'J-Pop / J-Rock': ['Ado (New Genesis)', 'Creepy Nuts (Bling-Bang-Bang-Born)', 'Hikaru Utada (First Love)', 'Kenshi Yonezu (KICK BACK)', 'King Gnu (Hakujitsu)', 'LiSA (Gurenge)', 'Official HIGE DANdism (Pretender)', 'One OK Rock (Wherever You Are)', 'RADWIMPS (Zenzenzense)', 'YOASOBI (Idol)'],
    'Jazz': ['Billie Holiday (Strange Fruit)', 'Charlie Parker (Ornithology)', 'Chet Baker (My Funny Valentine)', 'Dave Brubeck (Take Five)', 'Duke Ellington (Take the A Train)', 'Ella Fitzgerald (Dream a Little Dream of Me)', 'John Coltrane (My Favorite Things)', 'Louis Armstrong (What a Wonderful World)', 'Miles Davis (So What)', 'Nina Simone (Feeling Good)'],
    'K-Pop': ['aespa (Next Level)', 'BLACKPINK (How You Like That)', 'BTS (Dynamite)', 'EXO (Growl)', 'IVE (LOVE DIVE)', 'NewJeans (Super Shy)', 'SEVENTEEN (Very Nice)', "Stray Kids (God's Menu)", 'TWICE (TT)', 'TXT (Sugar Rush Ride)'],
    'Latin': ['Enrique Iglesias (Bailando)', 'Juanes (La Camisa Negra)', 'Luis Fonsi (Despacito)', 'Maluma (Hawai)', 'Marc Anthony (Vivir Mi Vida)', 'Peso Pluma (Ella Baila Sola)', "Ricky Martin (Livin' la Vida Loca)", 'Rosalia (DESPECHA)', 'Selena (Como La Flor)', "Shakira (Hips Don't Lie)"],
    'Pop': ['Ariana Grande (7 rings)', 'Billie Eilish (BIRDS OF A FEATHER)', 'Bruno Mars (Locked out of Heaven)', 'Ed Sheeran (Shape of You)', 'Harry Styles (As It Was)', 'Justin Bieber (Love Yourself)', 'Katy Perry (Dark Horse)', 'Olivia Rodrigo (drivers license)', 'Sabrina Carpenter (Espresso)', 'Taylor Swift (Cruel Summer)'],
    'Post-Punk Revival': ['Bloc Party (Banquet)', 'Editors (Munich)', 'Franz Ferdinand (Take Me Out)', 'Interpol (Evil)', 'Kaiser Chiefs (Ruby)', 'The Killers (Mr. Brightside)', "The Libertines (Can't Stand Me Now)", 'The Strokes (The Adults Are Talking)', 'The White Stripes (Seven Nation Army)', 'Yeah Yeah Yeahs (Maps)'],
    'Punk Rock': ['Bad Religion (21st Century Digital Boy)', 'blink-182 (All The Small Things)', 'Dead Kennedys (Holiday in Cambodia)', 'Green Day (Basket Case)', 'NOFX (Linoleum)', 'Rancid (Time Bomb)', 'Sex Pistols (Anarchy in the U.K.)', 'The Clash (Should I Stay or Should I Go)', "The Offspring (You're Gonna Go Far, Kid)", 'The Ramones (Blitzkrieg Bop)'],
    'R&B': ["Alicia Keys (If I Ain't Got You)", 'Beyonce (Halo)', 'Boyz II Men (End of the Road)', 'Chris Brown (Under The Influence)', 'Daniel Caesar (Best Part)', 'Frank Ocean (Pink + White)', 'Rihanna (Umbrella)', 'SZA (Kill Bill)', 'The Weeknd (Blinding Lights)', 'Usher (Yeah!)'],
    'Reggaeton': ['Bad Bunny (DAKITI)', 'Daddy Yankee (Con Calma)', 'Don Omar (Danza Kuduro)', 'Feid (LUNA)', 'J Balvin (LA CANCION)', 'Karol G (Si Antes Te Hubiera Conocido)', 'Nicky Jam (X)', 'Ozuna (Hey Mor)', 'Rauw Alejandro (Todo De Ti)', 'Wisin y Yandel (Rakata)'],
    'Rock': ['AC/DC (Highway to Hell)', 'Aerosmith (Dream On)', "Bon Jovi (Livin' On A Prayer)", 'Fleetwood Mac (Dreams)', 'Foo Fighters (Everlong)', "Guns N' Roses (Sweet Child O' Mine)", 'Led Zeppelin (Stairway to Heaven)', 'Queen (Bohemian Rhapsody)', 'The Beatles (Here Comes The Sun)', 'The Rolling Stones (Paint It, Black)'],
    'Soul / Motown': ["Al Green (Let's Stay Together)", 'Aretha Franklin (Respect)', "Diana Ross (I'm Coming Out)", "Marvin Gaye (Ain't No Mountain High Enough)", "Otis Redding (Sittin' On the Dock of the Bay)", 'Sam Cooke (A Change Is Gonna Come)', 'Smokey Robinson (The Tracks of My Tears)', 'Stevie Wonder (Superstition)', 'The Jackson 5 (I Want You Back)', 'The Temptations (My Girl)'],
  };

  var wordOnlyCatalog = {
    'Animals': [
      'Alpaca', 'Ant', 'Antelope', 'Baboon', 'Bat', 'Bear', 'Beaver', 'Bee', 'Bison', 'Buffalo',
      'Butterfly', 'Camel', 'Chameleon', 'Cheetah', 'Chicken', 'Chimpanzee', 'Cow', 'Crab', 'Crocodile', 'Deer',
      'Dolphin', 'Donkey', 'Duck', 'Eagle', 'Elephant', 'Elk', 'Falcon', 'Flamingo', 'Fox', 'Frog',
      'Gazelle', 'Giraffe', 'Goat', 'Gorilla', 'Guinea Pig', 'Hamster', 'Hawk', 'Hedgehog', 'Hippo', 'Horse',
      'Hyena', 'Jaguar', 'Jellyfish', 'Kangaroo', 'Koala', 'Lemur', 'Leopard', 'Lion', 'Lizard', 'Llama',
      'Lobster', 'Meerkat', 'Moose', 'Mouse', 'Octopus', 'Orangutan', 'Orca', 'Otter', 'Owl', 'Panda',
      'Panther', 'Parrot', 'Peacock', 'Penguin', 'Pig', 'Platypus', 'Polar Bear', 'Rabbit', 'Raccoon', 'Rat',
      'Red Panda', 'Rhino', 'Scorpion', 'Seal', 'Shark', 'Sheep', 'Shrimp', 'Skunk', 'Sloth', 'Snail',
      'Snake', 'Spider', 'Squirrel', 'Starfish', 'Stingray', 'Swan', 'Tiger', 'Toad', 'Tortoise', 'Toucan',
      'Turkey', 'Turtle', 'Vulture', 'Walrus', 'Warthog', 'Whale', 'Wildebeest', 'Wolf', 'Wombat', 'Zebra'],
    'Food': [
      'Apple', 'Avocado', 'Bacon', 'Bagel', 'Baked Potato', 'Banana', 'Bao', 'Barbecue', 'Biscuit', 'BLT',
      'Brownie', 'Burger', 'Burrito', 'Cereal', 'Cheese', 'Cheesecake', 'Chicken Wings', 'Chocolate', 'Chocolate Cake', 'Club Sandwich',
      'Coconut', 'Coffee', 'Coleslaw', 'Cookies', 'Corn on the Cob', 'Croissant', 'Cupcake', 'Curry', 'Deviled Eggs', 'Dim Sum',
      'Donut', 'Dumplings', 'Enchiladas', 'Falafel', 'French Fries', 'French Toast', 'Fried Chicken', 'Fried Rice', 'Gnocchi', 'Goulash',
      'Grapes', 'Grilled Cheese', 'Guacamole', 'Gyro', 'Honey', 'Hot Dog', 'Hummus', 'Ice Cream', 'Jelly', 'Kebab',
      'Lasagna', 'Lemonade', 'Macaroni and Cheese', 'Mango', 'Maple Syrup', 'Mashed Potatoes', 'Meatballs', 'Meatloaf', 'Milkshake', 'Muffin',
      'Nachos', 'Oatmeal', 'Omelette', 'Orange', 'Pad Thai', 'Paella', 'Pancakes', 'Pasta', 'Peanut Butter', 'Pho',
      'Pie', 'Pierogi', 'Pineapple', 'Pizza', 'Popcorn', 'Potato Salad', 'Pretzel', 'Quesadilla', 'Ramen', 'Ravioli',
      'Ribs', 'Risotto', 'Salad', 'Salsa', 'Sandwich', 'Scrambled Eggs', 'Shawarma', 'Smoothie', 'Soup', 'Spaghetti',
      'Spring Rolls', 'Steak', 'Strawberry', 'Sushi', 'Sweet Potato', 'Tacos', 'Tiramisu', 'Toast', 'Waffles', 'Watermelon'],
    'Movies': [
      '10 Things I Hate About You', '12 Angry Men', '1917', '2001: A Space Odyssey', 'About Time', 'Aladdin', 'Alien', 'Amélie', 'American Beauty', 'American Psycho',
      'Anatomy of a Fall', 'Anyone But You', 'Avatar', 'Baby Driver', 'Back to the Future', 'Barbie', 'Batman', 'Beautiful Boy', 'Beauty and the Beast', 'Before Sunrise',
      'Black Panther', 'Black Swan', 'Blade Runner', 'Bottoms', 'Bourne', 'Braveheart', 'Brokeback Mountain', 'Call Me by Your Name', 'Casino', 'Cast Away',
      'Catch Me If You Can', 'Cinderella', 'Clueless', 'Coco', 'Conclave', 'Coraline', 'Dead Poets Society', 'Deadpool', 'Despicable Me', 'Die Hard',
      'Django Unchained', 'Don\'t Look Up', 'Donnie Darko', 'Drive', 'E.T.', 'Edward Scissorhands', 'Eternal Sunshine of the Spotless Mind', 'Eyes Wide Shut', 'Fantastic Four', 'Fantastic Mr. Fox',
      'Fast and Furious', 'Fight Club', 'Finding Nemo', 'Forrest Gump', 'Frozen', 'Get Out', 'Ghostbusters', 'Girl, Interrupted', 'Gladiator', 'Glass Onion',
      'Gone Girl', 'Good Will Hunting', 'Goodfellas', 'Gravity', 'Guardians of the Galaxy', 'Hamnet', 'Harry Potter', 'Heat', 'Her', 'Home Alone',
      'How to Train Your Dragon', 'Howl\'s Moving Castle', 'Inception', 'Indiana Jones', 'Inglourious Basterds', 'Inside Out', 'Interstellar', 'Iron Man', 'James Bond', 'Jaws',
      'Jennifer\'s Body', 'John Wick', 'Jojo Rabbit', 'Joker', 'Jumanji', 'Jurassic Park', 'Kill Bill', 'Knives Out', 'KPop Demon Hunters', 'Kung Fu Panda',
      'La La Land', 'Lady Bird', 'Legally Blonde', 'Little Miss Sunshine', 'Little Women', 'Logan', 'Love Actually', 'Mad Max', 'Mamma Mia', 'Memento',
      'Men in Black', 'Mickey 17', 'Midsommar', 'Mission Impossible', 'Moana', 'Monsters, Inc.', 'Moonlight', 'Mulholland Drive', 'My Neighbor Totoro', 'National Treasure',
      'Nightcrawler', 'Nope', 'Nosferatu', 'Ocean\'s Eleven', 'Oldboy', 'Once Upon a Time in Hollywood', 'Oppenheimer', 'Parasite', 'Perfect Blue', 'Pirates of the Caribbean',
      'Poor Things', 'Portrait of a Lady on Fire', 'Pride and Prejudice', 'Princess Mononoke', 'Pulp Fiction', 'Puss in Boots', 'Ratatouille', 'Requiem for a Dream', 'Rocky', 'Saltburn',
      'Saving Private Ryan', 'Saw', 'Scarface', 'Schindler\'s List', 'Scott Pilgrim vs. the World', 'Scream', 'Se7en', 'Shrek', 'Shutter Island', 'Signs',
      'Sinners', 'Sleeping Beauty', 'Snow White', 'Soul', 'Speed', 'Spider-Man', 'Spirited Away', 'Star Trek', 'Star Wars', 'Superbad',
      'Taxi Driver', 'Terminator', 'The Avengers', 'The Breakfast Club', 'The Dark Knight', 'The Departed', 'The Devil Wears Prada', 'The Fabelmans', 'The Godfather', 'The Grand Budapest Hotel',
      'The Green Mile', 'The Hobbit', 'The Holdovers', 'The Hunger Games', 'The Incredibles', 'The Lighthouse', 'The Lion King', 'The Little Mermaid', 'The Lord of the Rings', 'The Martian',
      'The Matrix', 'The Menu', 'The Neverending Story', 'The Nightmare Before Christmas', 'The Notebook', 'The Perks of Being a Wallflower', 'The Prestige', 'The Princess Bride', 'The Shawshank Redemption', 'The Shining',
      'The Silence of the Lambs', 'The Sixth Sense', 'The Social Network', 'The Substance', 'The Truman Show', 'The Virgin Suicides', 'The Wolf of Wall Street', 'Thor: Ragnarok', 'Thunderbolts', 'Titanic',
      'Toy Story', 'Transformers', 'Twilight', 'Uncut Gems', 'Up', 'Us', 'WALL-E', 'Whiplash', 'Wicked', 'Willow',
      'Wonder Woman', 'X-Men', 'Zodiac', 'Zootopia'],
    'Objects': [
      'Backpack', 'Bag', 'Basket', 'Battery', 'Bed', 'Belt', 'Binoculars', 'Blanket', 'Book', 'Bookshelf',
      'Bottle', 'Bowl', 'Box', 'Bracelet', 'Broom', 'Bucket', 'Calculator', 'Camera', 'Candle', 'Chain',
      'Chair', 'Charger', 'Clock', 'Comb', 'Compass', 'Computer', 'Couch', 'Cup', 'Curtain', 'Desk',
      'Door', 'Envelope', 'Eraser', 'Fan', 'Flashlight', 'Fork', 'Globe', 'Gloves', 'Guitar', 'Hammer',
      'Hat', 'Headphones', 'Jar', 'Key', 'Keyboard', 'Knife', 'Ladder', 'Lamp', 'Laptop', 'Lock',
      'Map', 'Microphone', 'Mirror', 'Mouse', 'Mug', 'Nail', 'Necklace', 'Newspaper', 'Notebook', 'Painting',
      'Passport', 'Pen', 'Pencil', 'Phone', 'Picture Frame', 'Pillow', 'Plate', 'Refrigerator', 'Remote Control', 'Ring',
      'Rope', 'Rug', 'Ruler', 'Scarf', 'Scissors', 'Screw', 'Screwdriver', 'Shoes', 'Soap', 'Socks',
      'Speaker', 'Sponge', 'Spoon', 'Stamp', 'Stove', 'Suitcase', 'Sunglasses', 'Table', 'Telescope', 'Television',
      'Toaster', 'Toothbrush', 'Towel', 'Umbrella', 'Vacuum', 'Vase', 'Wallet', 'Watch', 'Window', 'Wrench'],
  };

  var fakeBiomeRoleCatalog = {
    'Alpine Mountains': ['Antelope', 'Gila Monster', 'Water Moccasin'],
    'Antarctic Ice Sheet (Frozen Ocean)': ['Bullfrog', 'Cheetah', 'Spider'],
    'Arctic Tundra': ['Hermit Crab', 'Jaguar', 'Toucan'],
    'Australian Outback': ['Moose', 'Piranha', 'Reindeer'],
    'Beach': ['Bat', 'Prairie Dog', 'Snow Leopard'],
    'Cave System': ['Heron', 'Koala', 'Vampire Squid'],
    'Chaparral (Shrubland)': ['Catfish', 'Moray Eel', 'Zebra'],
    'Coral Reef': ['Marmot', 'Snow Petrel', 'Volcanic Mouse'],
    'Deep Ocean': ['Bullfrog', 'Hippopotamus', 'Otter'],
    'Desert': ['Bat', 'Beaver', 'Kangaroo Rat'],
    'Freshwater River': ['Condor', 'Emu', 'Mountain Goat'],
    'House': ['Anaconda', 'Meerkat', 'Pelican'],
    'Jurassic Park': ['Camel', 'Koala', 'Octopus'],
    'Mangrove Forest': ['Beaver', 'Clownfish', 'Squirrel'],
    'Prairie': ['Antarctic Krill', 'Hawaiian Hoary Bat', 'Rat'],
    'Savanna': ['Fire Salamander', 'Harpy Eagle', 'Leopard Seal'],
    'Swamp': ['Poison Dart Frog', 'Troglodyte Beetle', 'Walrus'],
    'Taiga (Boreal Forest)': ['Red-Tailed Hawk', 'Stray Cat', 'Water Moccasin'],
    'Temperate Forest': ['Beaver', 'Bison', 'Troglodyte Beetle'],
    'Tropical Rainforest': ['Cockroach', 'Reindeer', 'Troglodyte Beetle'],
    'Urban Environment (City)': ['Beaver', 'Deep Sea Jellyfish', 'Manta Ray'],
    'Volcanic Island': ['Harpy Eagle', 'Sparrow', 'Zebra'],
  };

  var fakeLocationRoleCatalog = {
    'Airplane': ['Lifeguard', 'Nail Specialist', 'Security Officer'],
    'Airport': ['Bellhop', 'Coach', 'Shackled Prisoner'],
    'Bank': ['Dancer', 'Film Critic', 'Pick-Up Artist'],
    'Beach': ['Astronaut', 'Housekeeper', 'Librarian'],
    'Campground': ['Concierge', 'Security Guard', 'Usher'],
    'Casino': ['Dancer', 'Drive-Thru Worker', 'Manager'],
    'Circus Tent': ['Actor', 'Biologist', 'Geoscientist'],
    'Convenience Store': ['Backpacker', 'Campus Security', 'Dean'],
    'Corporate Party': ['Cameraman', 'Campus Security', 'Flight Attendant'],
    'Cruise Ship': ['Administrative Assistant', 'Usher', 'Zookeeper'],
    'Crusader Army': ['Cabin Boy', 'Dispatcher', 'Teller'],
    'Day Spa': ['Detective', 'Visitor', 'Zookeeper'],
    'Elementary School': ['Auditor', 'Cardsharp', 'Cashier'],
    'Embassy': ['Ice Cream Vendor', 'Masseur', 'Wildlife Photographer'],
    'Fast Food Restaurant': ['Interpreter', 'Journalist', 'Magician'],
    'Fire Station': ['Bartender', 'Coach', 'Radio Operator'],
    'Gym': ['Archer', 'Auditor', 'Cardsharp'],
    'Hospital': ['Archer', 'Delivery Man', 'Stage Hand'],
    'Hotel': ['CEO', "New Year's Resolution Member", 'Sunbather'],
    'Military Base': ['Audience Member', 'Musician', 'Zookeeper'],
    'Movie Studio': ['Astronaut', 'Attendant', 'Receptionist'],
    'Movie Theater': ['Coatroom Attendant', 'Cop', 'Teller'],
    'Night Club': ['Cashier', 'Sommelier', 'Vendor'],
    'Pirate Ship': ['Campus Security', 'Dancer', 'Personal Trainer'],
    'Polar Station': ['Prompter', 'Waiter', 'Wealthy Tourist'],
    'Police Station': ['Audience Member', 'Non-Commissioned Officer', 'Shoplifter'],
    'Restaurant': ['First Mate', 'Pick-Up Artist', 'Usher'],
    'Service Station': ['Bartender', 'Ringmaster', 'Weightlifter'],
    'Space Station': ['Disgruntled Teenager Working Their First Job', 'Ice Cream Vendor', 'Janitor'],
    'Sports Stadium': ['Acrobat', 'Ambassador', 'Parrot'],
    'Submarine': ['Butcher', 'Flight Engineer', 'Tourist'],
    'Supermarket': ['Runner', 'Service Receptionist', 'Usher'],
    'Theatre': ['Auditor', 'Shopper', 'Yoga Instructor'],
    'Theme Park / Amusement Park': ['Campus Security', 'Captive', 'Sommelier'],
    'Train': ['Bottle Service Waitress', 'Circus-Goer', 'Guest'],
    'University': ['Bartender', 'Pilot', 'Tourist'],
    'Zoo': ['Delivery Driver', 'Front Desk Clerk', 'Pick-Up Artist'],
  };

  var fakeMovieTvRoleCatalog = {
    'Action': ['Coco', 'Mamma Mia', 'The Notebook'],
    'Adventure': ['Breaking Bad', 'Mamma Mia', 'Se7en'],
    'Alien Invasion': ['Legally Blonde', 'Tombstone', 'Toy Story'],
    'Animated': ['Hereditary', 'The Godfather', 'Zero Dark Thirty'],
    'Anime': ['Home Alone', 'Rocky', 'The Crown'],
    'Biopic': ['Jurassic Park', 'Shrek', 'Zombieland'],
    'Body Horror': ['Frozen', 'Mamma Mia', 'The Sandlot'],
    'Christmas': ['Attack on Titan', 'Scarface', 'Se7en'],
    'Comedy': ['Gladiator', 'Saving Private Ryan', 'The Shining'],
    'Cop': ["Schindler's List", 'The Exorcist', 'Titanic'],
    'Courtroom Drama': ['Die Hard', 'Godzilla', 'Grease'],
    'Crime': ['Frozen', 'La La Land', 'Toy Story'],
    'Cyberpunk': ['A Christmas Story', 'Pride and Prejudice', 'Rocky'],
    'Disaster': ['Coco', 'Mean Girls', 'Sherlock Holmes'],
    'Docudrama': ['Ghostbusters', 'Shrek', 'Twilight'],
    'Dystopian': ['Anchorman', 'Mamma Mia', 'The Sandlot'],
    'Fantasy': ['Dunkirk', 'Goodfellas', 'Moneyball'],
    'Found Footage': ['Rocky', 'The Sound of Music', 'Toy Story'],
    'Heist': ['Finding Nemo', 'The Exorcist', 'The Notebook'],
    'Historical Epic': ['Anchorman', 'Paranormal Activity', 'Toy Story'],
    'Horror': ['Mamma Mia', 'Moana', 'Ted Lasso'],
    'Monster': ['12 Angry Men', 'La La Land', 'The Notebook'],
    'Musical': ['Black Hawk Down', 'Se7en', 'The Thing'],
    'Mystery / Whodunit': ['Dune', 'Rocky', 'Shrek'],
    'Post-Apocalyptic': ['Bridgerton', 'Grease', 'Legally Blonde'],
    'Prison': ['Finding Nemo', 'Frozen', 'Mamma Mia'],
    'Psychological Thriller': ['Elf', 'The Sandlot', 'Toy Story'],
    'Romance': ['Full Metal Jacket', 'Halloween', 'Terminator'],
    'Sci-Fi / Space Opera': ['Goodfellas', 'Mean Girls', 'The Notebook'],
    'Slasher': ['Coco', 'La La Land', 'Moneyball'],
    'Sports': ['Blade Runner', 'Pulp Fiction', 'The Exorcist'],
    'Spy': ['Finding Nemo', 'Jaws', 'The Greatest Showman'],
    'Superhero': ['Chernobyl', 'The Notebook', 'Titanic'],
    'Survival': ['Anchorman', 'Grease', 'Mean Girls'],
    'Teen Drama': ['Alien', 'Apocalypse Now', 'The Godfather'],
    'Thriller': ['Elf', 'Mamma Mia', 'Toy Story'],
    'Time Travel': ['Rocky', 'Scream', 'The Notebook'],
    'War': ['Frozen', 'La La Land', 'Mean Girls'],
    'Western': ['Star Wars', 'The Hangover', 'Titanic'],
    'Zombie': ['La La Land', 'Moneyball', 'The Notebook'],
  };

  var fakeMusicGenreRoleCatalog = {
    'Alternative Rock': ['Bush (Glycerine)', 'Interpol (Evil)', 'Tame Impala (The Less I Know The Better)'],
    'Bedroom Pop': ['Johnny Cash (Hurt)', 'Metallica (Enter Sandman)', 'Mozart (Eine kleine Nachtmusik)'],
    'Blues': ["Al Green (Let's Stay Together)", 'Chet Baker (My Funny Valentine)', 'Johnny Cash (Hurt)'],
    'Classical': ['Duke Ellington (Take the A Train)', 'Mahalia Jackson (Take My Hand, Precious Lord)', 'Nina Simone (Feeling Good)'],
    'Country': ["Bob Dylan (Blowin' in the Wind)", 'Etta James (At Last)', 'Stevie Ray Vaughan (Pride and Joy)'],
    'Disco': ['Calvin Harris (One Kiss)', "Diana Ross (I'm Coming Out)", 'Usher (Yeah!)'],
    'EDM': ["Bee Gees (Stayin' Alive)", 'Sabrina Carpenter (Espresso)', 'The Weeknd (Blinding Lights)'],
    'Emo / Pop Punk': ['Green Day (Basket Case)', 'Linkin Park (In the End)', "The Offspring (You're Gonna Go Far, Kid)"],
    'Folk': ['Chris Stapleton (Tennessee Whiskey)', 'Dolly Parton (Jolene)', 'Robert Johnson (Cross Road Blues)'],
    'Gospel': ['Aretha Franklin (Respect)', 'B.B. King (The Thrill Is Gone)', 'Sam Cooke (A Change Is Gonna Come)'],
    'Grunge': ['Foo Fighters (Everlong)', 'Pantera (Walk)', 'Radiohead (Creep)'],
    'Heavy Metal': ['AC/DC (Highway to Hell)', 'Alice in Chains (Man in the Box)', "Guns N' Roses (Sweet Child O' Mine)"],
    'Hip Hop': ['Bad Bunny (DAKITI)', 'Frank Ocean (Pink + White)', 'SZA (Kill Bill)'],
    'Indie / Alternative': ['Billie Eilish (BIRDS OF A FEATHER)', 'Coldplay (Yellow)', 'The Killers (Mr. Brightside)'],
    'J-Pop / J-Rock': ['Aretha Franklin (Respect)', 'Dolly Parton (Jolene)', 'Sex Pistols (Anarchy in the U.K.)'],
    'Jazz': ['Bach (Air on the G String)', 'Muddy Waters (Hoochie Coochie Man)', 'Stevie Wonder (Superstition)'],
    'K-Pop': ['Ariana Grande (7 rings)', 'Marshmello (Happier)', 'Rihanna (Umbrella)'],
    'Latin': ['Bruno Mars (Locked out of Heaven)', 'J Balvin (LA CANCION)', 'Nicky Jam (X)'],
    'Pop': ['Beyonce (Halo)', 'BTS (Dynamite)', 'The Chainsmokers (Closer)'],
    'Post-Punk Revival': ['Arctic Monkeys (I Wanna Be Yours)', 'Oasis (Wonderwall)', 'The Clash (Should I Stay or Should I Go)'],
    'Punk Rock': ['Fall Out Boy (Centuries)', 'Nirvana (Smells Like Teen Spirit)', 'System Of A Down (Chop Suey!)'],
    'R&B': ['Drake (One Dance)', "Marvin Gaye (Ain't No Mountain High Enough)", 'Taylor Swift (Cruel Summer)'],
    'Reggaeton': ['Kendrick Lamar (All The Stars)', 'Maluma (Hawai)', "Shakira (Hips Don't Lie)"],
    'Rock': ['Iron Maiden (The Trooper)', 'Pearl Jam (Even Flow)', 'Red Hot Chili Peppers (Californication)'],
    'Soul / Motown': ["Alicia Keys (If I Ain't Got You)", 'Ella Fitzgerald (Dream a Little Dream of Me)', 'Kirk Franklin (Stomp)'],
  };

  // Historical Eras is parked: the catalog is drafted but the category still
  // needs a lot of reworking before it is fit to play, so it ships commented
  // out and is left off window.MASQ_LOCATIONS_DATA below. app.js drops the
  // category from its lists to match — restore both sides together.

  // var historicalErasCatalog = {
  //   'Age of Exploration': ['Caravel Captain', 'Conquistador', 'Indigenous Interpreter', 'Missionary Priest', 'New World Cartographer', 'Scurvy-Stricken Sailor', 'Ship\'s Navigator', 'Spice Trade Merchant'],
  //   'American Revolution': ['British Redcoat', 'Colonial Town Crier', 'Continental Army Surgeon', 'Founding Father', 'Loyalist Tory', 'Minuteman Militiaman', 'Pamphlet Printer', 'Tea Party Raider'],
  //   'Ancient China (Dynastic Era)': ['Confucian Scholar-Official', 'Court Eunuch', 'Dynastic Emperor', 'Great Wall Laborer', 'Gunpowder Alchemist', 'Imperial Calligrapher', 'Silk Road Merchant', 'Terracotta Army Sculptor'],
  //   'Ancient Egypt': ['Hieroglyph Scribe', 'Mummification Embalmer', 'Nile Flood Surveyor', 'Pharaoh', 'Priest of Ra', 'Pyramid Stonecutter', 'Royal Vizier', 'Tomb Robber'],
  //   'Ancient Greece': ['Athenian Philosopher', 'Homeric Bard', 'Marble Temple Sculptor', 'Olympic Wrestler', 'Oracle of Delphi', 'Spartan Hoplite', 'Tragedy Playwright', 'Trireme Rower'],
  //   'Ancient Rome': ['Aqueduct Engineer', 'Chariot Racer', 'Colosseum Gladiator', 'Forum Senator', 'Legion Centurion', 'Praetorian Guard', 'Toga-Clad Emperor', 'Vestal Virgin'],
  //   'Aztec Empire': ['Chinampa Garden Farmer', 'Eagle Warrior', 'Featherwork Artisan', 'Jaguar Warrior', 'Pochteca Long-Distance Trader', 'Sacrificial Captive', 'Sacrificial Temple Priest', 'Tlatoani Ruler'],
  //   'Cold War Era': ['Berlin Wall Guard', 'CIA Agent', 'Duck-and-Cover Schoolteacher', 'Fallout Shelter Builder', 'Iron Curtain Defector', 'KGB Spy', 'Missile Silo Officer', 'Propaganda Radio Broadcaster'],
  //   'Feudal Japan': ['Daimyo Lord', 'Geisha', 'Katana Swordsmith', 'Masterless Ronin', 'Ninja Assassin', 'Samurai', 'Shogun', 'Zen Temple Monk'],
  //   'Great Depression': ['Boxcar-Hopping Hobo', 'Breadline Regular', 'Dance Marathon Contestant', 'Dust Bowl Farmer', 'Hooverville Resident', 'Soup Kitchen Volunteer', 'Wiped-Out Stockbroker', 'WPA Road Crew Worker'],
  //   'Industrial Revolution': ['Chimney Sweep Boy', 'Coal Miner', 'Factory Foreman', 'Luddite Machine-Breaker', 'Mill Owner', 'Steam Engine Mechanic', 'Steam Locomotive Engineer', 'Textile Mill Child Laborer'],
  //   'Medieval Europe': ['Armored Knight', 'Cathedral Stonemason', 'Court Jester', 'Crusader', 'Feudal King', 'Manor Serf', 'Manuscript-Illuminating Monk', 'Plague Doctor'],
  //   'Prehistoric/Stone Age': ['Bone Flute Carver', 'Cave Painter', 'Clan Elder', 'Fire Keeper', 'Flint Toolmaker', 'Mammoth Hunter', 'Root and Berry Forager', 'Tribal Shaman'],
  //   'Renaissance': ['Flying Machine Inventor', 'Forbidden Anatomist', 'Fresco Painter', 'Heretical Astronomer', 'Humanist Scholar', 'Medici Banker', 'Patron of the Arts', 'Printing Press Operator'],
  //   'Viking Age': ['Berserker', 'Jarl Chieftain', 'Longship Raider', 'Longship Shipwright', 'Rune Carver', 'Shield Maiden', 'Skald Storyteller', 'Völva Seer'],
  //   'Wild West': ['Bounty Hunter', 'Cattle Drive Cowboy', 'Frontier Sheriff', 'Gold Rush Prospector', 'Pony Express Rider', 'Saloon Keeper', 'Stagecoach Driver', 'Train-Robbing Outlaw'],
  //   'World War II': ['Air Raid Warden', 'Bomber Crew Gunner', 'D-Day Paratrooper', 'Enigma Codebreaker', 'French Resistance Fighter', 'Radar Operator', 'Riveting Factory Worker', 'Spitfire Pilot'],
  // };

  // var fakeHistoricalErasRoleCatalog = {
  //   'Age of Exploration': ['Enigma Codebreaker', 'Fresco Painter', 'Pharaoh'],
  //   'American Revolution': ['Cattle Drive Cowboy', 'Great Wall Laborer', 'Oracle of Delphi'],
  //   'Ancient China (Dynastic Era)': ['Gold Rush Prospector', 'Hieroglyph Scribe', 'Zen Temple Monk'],
  //   'Ancient Egypt': ['Crusader', 'Terracotta Army Sculptor', 'Wiped-Out Stockbroker'],
  //   'Ancient Greece': ['Longship Raider', 'Radar Operator', 'Vestal Virgin'],
  //   'Ancient Rome': ['Katana Swordsmith', 'KGB Spy', 'Spartan Hoplite'],
  //   'Aztec Empire': ['Bounty Hunter', 'Conquistador', 'Priest of Ra'],
  //   'Cold War Era': ['Court Jester', 'Enigma Codebreaker', 'Spitfire Pilot'],
  //   'Feudal Japan': ['Armored Knight', 'Confucian Scholar-Official', 'Riveting Factory Worker'],
  //   'Great Depression': ['Coal Miner', 'Riveting Factory Worker', 'Vestal Virgin'],
  //   'Industrial Revolution': ['Gold Rush Prospector', 'Hooverville Resident', 'Ninja Assassin'],
  //   'Medieval Europe': ['Jaguar Warrior', 'Samurai', 'Steam Locomotive Engineer'],
  //   'Prehistoric/Stone Age': ['Pyramid Stonecutter', 'Völva Seer', 'Wiped-Out Stockbroker'],
  //   'Renaissance': ['Cathedral Stonemason', 'Cave Painter', 'New World Cartographer'],
  //   'Viking Age': ['Crusader', 'Legion Centurion', 'Pony Express Rider'],
  //   'Wild West': ['Boxcar-Hopping Hobo', 'Court Eunuch', 'Steam Locomotive Engineer'],
  //   'World War II': ['Berlin Wall Guard', 'Court Jester', 'Dust Bowl Farmer'],
  // };

  window.MASQ_LOCATIONS_DATA = {
    'biomeCatalog': biomeCatalog,
    'locationCatalog': locationCatalog,
    'movieTvCatalog': movieTvCatalog,
    'musicGenreCatalog': musicGenreCatalog,
    'wordOnlyCatalog': wordOnlyCatalog,
    'fakeBiomeRoleCatalog': fakeBiomeRoleCatalog,
    'fakeLocationRoleCatalog': fakeLocationRoleCatalog,
    'fakeMovieTvRoleCatalog': fakeMovieTvRoleCatalog,
    'fakeMusicGenreRoleCatalog': fakeMusicGenreRoleCatalog,
    // 'historicalErasCatalog': historicalErasCatalog,
    // 'fakeHistoricalErasRoleCatalog': fakeHistoricalErasRoleCatalog,
  };
})();
